feat(backup): separate backup settings from default settings
longhorn/longhorn pull request #10097
Opened 2024-12-30 07:52 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#5411, longhorn/longhorn#10089

#### What this PR does / why we need it:

Separate the default backup related settings from default settings into a new yaml file `default-backupstore-setting.yaml`

Introduce a new category `defaultBackupStoreSettings` to control the default backupstore related settings with Helm.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-12-30 09:36 UTC, mantissahz commented
Regression test:
- Settings: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8091/
- Backup Related: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8092/

2024-12-30 13:40 UTC, derekbit commented on chart/templates/default-backupstore-settings.yaml
> +  name: longhorn-default-backupstore-settings
To prevent any confusion, remove `settings`
```suggestion
  name: longhorn-default-backupstore
```

2024-12-30 13:40 UTC, derekbit commented on chart/templates/default-backupstore-settings.yaml
> +  default-backupstore-settings.yaml: |-
```suggestion
  default-backupstore.yaml: |-
```

2024-12-30 13:40 UTC, derekbit commented on chart/values.yaml
> +defaultBackupStoreSettings:
To prevent any confusion, remove `settings`
```suggestion
defaultBackupStore:
```

2024-12-30 13:40 UTC, derekbit commented on chart/values.yaml
> +defaultBackupStoreSettings:
Add a comment for the purpose of defaultBackupStore`

2024-12-30 13:40 UTC, derekbit commented on chart/README.md
> +| defaultBackupStoreSettings.pollInterval | `nil` | Number of seconds that Longhorn waits before checking the default backupstore for new backups. The default value is "300". When the value is "0", p
```suggestion
| defaultBackupStore.backupTarget | `nil` | Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE") |
| defaultBackupStore.backupTargetCredentialSecret | `nil` | Name of the Kubernetes secret associated with the default backup target. |
| defaultBackupStore.pollInterval | `nil` | Number of seconds that Longhorn waits before checking the default backupstore for new backups. The default value is "300". When the value is "0", polling is disabled. |
```

2024-12-30 15:41 UTC, mantissahz commented on chart/templates/default-backupstore-settings.yaml
> +  name: longhorn-default-backupstore-settings
Modified. Thanks.

2024-12-30 15:41 UTC, mantissahz commented on chart/templates/default-backupstore-settings.yaml
> +  default-backupstore-settings.yaml: |-
Modified. Thanks.

2024-12-30 15:41 UTC, mantissahz commented on chart/values.yaml
> +defaultBackupStoreSettings:
Added. Thanks

2024-12-30 15:42 UTC, mantissahz commented on chart/README.md
> +| defaultBackupStoreSettings.pollInterval | `nil` | Number of seconds that Longhorn waits before checking the default backupstore for new backups. The default value is "300". When the value is "0", p
Re-generated. Thanks.

2024-12-31 08:31 UTC, innobead requested changes

2024-12-31 08:31 UTC, innobead commented on chart/templates/default-backupstore.yaml
> +  name: longhorn-default-backupstore
```suggestion
  name: longhorn-default-resource
```

This way, we can add more default resources in the config map instead of creating a new one.

2024-12-31 14:00 UTC, mantissahz commented on chart/README.md
> +| longhornDriver.log.format | string | `"plain"` | Format of longhorn-driver logs. (Options: "plain", "json") |
Reverted. Thanks.

2024-12-31 14:01 UTC, mantissahz commented on chart/templates/default-backupstore.yaml
> +  name: longhorn-default-backupstore
Modified. Thanks.

2024-12-31 14:33 UTC, innobead approved these changes

2024-12-31 14:33 UTC, merged

2025-01-02 03:03 UTC, mantissahz commented
@Mergifyio backport v1.8.x