Add replica eviction support for disks and nodes enhancement document
longhorn/longhorn pull request #1668
Opened 2020-08-05 01:05 UTC by boknowswiki

https://github.com/longhorn/longhorn/issues/298

Signed-off-by: Bo Tao <bo.tao@rancher.com>

2020-08-05 04:00 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +Before, when user wants to evict a disk, user needs to disable the disk first, then delete all the replicas on this disks after the deleted replica has been rebuilt successfully.
Add some detailed descriptions. e.g., `disable scheduling of the disk first, then find out and delete all the replicas on this disks for each volume manually`

2020-08-05 04:04 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### Disk Eviction
Step 2~4 are like the implementation details rather than the user experience.

Similar below.

2020-08-05 04:10 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +6. If there is any error e.g. no space or couldn't find other schedulable disk, the error message will be display on the `Longhorn UI`. And the eviction for the failed volume would be changed to `Dis
How do users find the related errors? In `Dashboard/Event Log`?

2020-08-05 04:17 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +Also disk and node controller can take this `errMessage` field to indicate the eviction for the disk or the node has failed, and updatet the disk and node eviction condition to `Disable`.
1. If the eviction fails, can we put the error in the condition message then somehow show it in UI?
2. Typo `updatet`

2020-08-05 04:37 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +Initially, for every replica created, the default stats is `Disabled`. And if user select a node or disk to evcit, and the replica on that disk will be set to `Enabled`, and this should trigger volum
1. Typo `stats`
2. Put this part together with the `replica eviction state` introduction.
3. It seems we need a new field in `replica.Spec` besides `replica eviction state`.
4. Why using a new field `replica eviction state` rather than adding a condition `Eviction` in `replica.Status`?

2020-08-05 04:41 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### For Disk Eviction
It this manual test or integration test? What's the test skeleton/step? Putting a draft version here is fine.

2020-08-05 04:41 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +## Note [optional]
Remove it if it's unnecessary.

2020-08-07 03:01 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `requestEviction`  `type.Source` field to `Node.Spec` and `Node.Spec.disks`. This is to help tracking the request from user and trigger volume controler.
What is `type.Source` for?

2020-08-07 05:10 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +1. Allow user easily evict the replicas on the selected disks or nodes to other disks or nodes without impact the user defined `Volume.Spec` and keep the same level of fault tolerance.
I think I should say `Volume.Spec.numberOfReplicas` to be more clear. This means we don't change the user defined replica number.

2020-08-07 22:42 UTC, boknowswiki commented
@shuo-wu , after synced with @yasker , we will focus on the `Attached` volume for now, and will revisit the `Detached` volume case after refactoring. So I will start to implement the code as the LEP described.

2020-08-13 00:11 UTC, boknowswiki commented
@shuo-wu I just update this as a RP, please take a look. Thanks.

2020-08-17 04:13 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +3. Add new `ReplicaEvictionRequested` slice of string to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction requested replica.
Add the new field to `volume.status`?

2020-08-17 04:16 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### Integration Test Plan
The description of this part is too vague. And we can add more integration tests. e.g.:
1. Test eviction canceling.
2. Test if the suspending eviction will move on once there is one disk/node suddenly becoming available.

2020-08-17 04:18 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +6. During `ReconcileEngineReplicaState`, based on this map to trigger rebuild for different volumes' replicas. And remove the replicas have been evicted from the map.
Do not need to mention the concrete function name you prepare to modify. And it may be changed during the implementation.

2020-08-17 04:20 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### For Node Eviction
Does this still belong to `Test Plan`?  
Same below.

2020-08-17 04:23 UTC, shuo-wu commented
And it's better to mention how you know the eviction is done in the implementation part. This would help us understand why you introduce those new fields.

2020-08-17 20:54 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +3. Add new `ReplicaEvictionRequested` slice of string to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction requested replica.
Sorry, this should be removed. I will remove it.

2020-08-17 20:57 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### Integration Test Plan
I think for the two test cases you described should be in manual test, not integration test. Since in the integration test, it's hard to predict when to cancel the eviction and what the status may be looked like.

2020-08-17 21:00 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +6. During `ReconcileEngineReplicaState`, based on this map to trigger rebuild for different volumes' replicas. And remove the replicas have been evicted from the map.
Ok, let me update this part.

2020-08-17 21:04 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +3. Add new `ReplicaEvictionRequested` slice of string to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction requested replica.
Will update it to make it more clear.

2020-08-17 21:20 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### For Node Eviction
Yes, let me remove the header, it's confusing.

2020-08-17 21:20 UTC, boknowswiki commented
> And it's better to mention how you know the eviction is done in the implementation part. This would help us understand why you introduce those new fields.

Updated, please take a look. Thanks.

2020-08-17 21:26 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +This enhancement is to simpler and automatically to evict the replicas on the selected disabled disks or nodes to other suitable disks and nodes. Meanwhile keep the same level of fault tolerance duri
`simpler`? You meant `simplify`?

2020-08-17 21:27 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +1. Add `Evict` and `Unevict` buttons for disks and nodes. This is for user to evict or cancel the eviction of the disks or the nodes.
`Evict` and `cancel eviction`. `Unevict` is not commonly used.

2020-08-17 21:28 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `requestEviction` field to `Node.Spec` and `Node.Spec.disks` Spec. This is to help tracking the request from user and trigger volume controler. And this will reconsile with `scheduledRepli
Should be `evictionRequested`, following the naming convention of other fields.

2020-08-17 21:29 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +3. Display can not evict error to `Dashboard` and any other eviction errors to the `Event log`.
Display `fail to evict` error

2020-08-17 21:29 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +For disk replacement or node replacement, the eviction needs to be done successfully in order to guarantee longhorn volume function properly.
`Longhorn`

2020-08-17 21:30 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. User needs to scale up the replica count for the volume which has replica on disabled disks or nodes, and wait for the rebuild complete, then delete the replicas on this disk or node.
In fact the user needs to scale up the replica count, wait for the rebuilding complete, **scale down the replica count**, then delete the replica.

2020-08-17 21:33 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +1. User can selects `Evict` from `Longhorn UI` for disks or nodes. And user has to make sure the selected disks or nodes have been disabled, or select the `Disable` Scheduling at the same time of `Ev
Thinking about that page, it makes sense to present `Evict` as `Request Eviction` status, since it will be submitted as a form. `Evict` is a verb so we need to use the noun to describe the status.

2020-08-17 21:34 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +From an API perspective, the call made to `Evict` and `Unevict` the `Node` or `Disk` eviction should look the same. The logic for handling the new field `Evict` and `Unevict` should to be in the `Nod
Probably do `Eviction requested` and `true` or `false`.

2020-08-17 21:38 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +5. If there is any error e.g. no space or couldn't find other schedulable disk, the error message will be logged in the `Event log`. And the eviction will be suspended until either user cancel the ev
We can add a condition in the node/disk as well, to indicate the reason of the eviction failure. That would be easier for the user, instead of looking into the event log (which can be written to automatically when updating the condition), or the manager log.

2020-08-17 22:04 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +This enhancement is to simpler and automatically to evict the replicas on the selected disabled disks or nodes to other suitable disks and nodes. Meanwhile keep the same level of fault tolerance duri
Yes, will fix.

2020-08-17 22:10 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +1. Add `Evict` and `Unevict` buttons for disks and nodes. This is for user to evict or cancel the eviction of the disks or the nodes.
Will fix.

2020-08-17 22:13 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `requestEviction` field to `Node.Spec` and `Node.Spec.disks` Spec. This is to help tracking the request from user and trigger volume controler. And this will reconsile with `scheduledRepli
This is in the same struct with `AllowScheduling`, so I think `requestEviction` matches the naming. Please let me know if you still think `evictionRequested` is better.

2020-08-17 22:23 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `requestEviction` field to `Node.Spec` and `Node.Spec.disks` Spec. This is to help tracking the request from user and trigger volume controler. And this will reconsile with `scheduledRepli
I see. `AllowScheduling` is named a long time ago, so it doesn't follow the pattern as well. It's still better we can follow the pattern as `noun-verb` from now on.

2020-08-17 22:28 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. User needs to scale up the replica count for the volume which has replica on disabled disks or nodes, and wait for the rebuild complete, then delete the replicas on this disk or node.
Will fix.

2020-08-17 22:34 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +1. User can selects `Evict` from `Longhorn UI` for disks or nodes. And user has to make sure the selected disks or nodes have been disabled, or select the `Disable` Scheduling at the same time of `Ev
Sure, will change the UI button name from `Eviction` to `Request Eviction`. And `Unevict` to `Cancel Eviction`.

2020-08-17 22:36 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +From an API perspective, the call made to `Evict` and `Unevict` the `Node` or `Disk` eviction should look the same. The logic for handling the new field `Evict` and `Unevict` should to be in the `Nod
Yes, this sound better. At beginning, I was thinking of `Eviction`/ `enable` and `disable`. But I think the `Eviction requested`/`true` and `false` sounds better.

2020-08-17 22:40 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `requestEviction` field to `Node.Spec` and `Node.Spec.disks` Spec. This is to help tracking the request from user and trigger volume controler. And this will reconsile with `scheduledRepli
Got it, I will rename it to `evictionRequested`.

2020-08-17 23:36 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +5. If there is any error e.g. no space or couldn't find other schedulable disk, the error message will be logged in the `Event log`. And the eviction will be suspended until either user cancel the ev
Yes, it will be logged in manager log.

2020-08-18 03:11 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### Integration Test Plan
For the 1st case, when the volume replica count is 3, the eviction should get stuck when the soft anti-affinity setting is disabled.
For the 2nd case, you can disable one node scheduling, unset soft anti-affinity, and create a volume with 2 replicas. Then the eviction of the volume will get stuck until you enable the node scheduling.

2020-08-18 06:44 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +5. If there is any error e.g. no space or couldn't find other schedulable disk, the error message will be logged in the `Event log`. And the eviction will be suspended until either user cancel the ev
@yasker  and @shuo-wu , I thought about the design, and I am thinking it's better to let replica controller to listen on the nodes changes, and update the new field `evictionRequested` in `Replica.Spec`. And once volume controller gets the replicas will have this field set, and then trigger replenish replica.

Also about adding a condition in volume. I think we don't need it once we have [this UI redirect replica name to volume page feature](https://github.com/longhorn/longhorn/issues/1697), once in the volume page, if there is any like `Schedule failure` or `Replica rebuild failure`, they will be displayed there.

Please let me know what you think. Thanks.

2020-08-18 18:00 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +5. If there is any error e.g. no space or couldn't find other schedulable disk, the error message will be logged in the `Event log`. And the eviction will be suspended until either user cancel the ev
@boknowswiki Good idea. We should the field in `replica.Status` instead of `spec` though. No controller can change it's own spec.

I am OK with no condition change now too. We can add a condition later if it's needed.

2020-08-18 22:26 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +4. Add new `ReplicaEvictionRequested` slice of string in volume controller as local variable to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction req
Do we still need this after introducing the new field in the replica?

2020-08-18 22:28 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +For both `Replica Node Level Soft Anti-Affinity` has been enabled and disabled, and for the node that volume has been mount or not mount.
Anti-affinity setting and mount or not shouldn't impact this feature, so we don't need to add specific test for them (unless we want to use anti-affinity to simulate scheduling failure).

2020-08-18 22:28 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +Failure Cases:
`Negative case`

2020-08-18 22:29 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +Success Case:
Positive Case

2020-08-18 22:57 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +4. Add new `ReplicaEvictionRequested` slice of string in volume controller as local variable to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction req
Yes, there could be multiple replicas need to be evicted.
With the new field in the replica, this could simplify the logic in volume controller to tell if the replica has been requested eviction.

2020-08-18 23:00 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +For both `Replica Node Level Soft Anti-Affinity` has been enabled and disabled, and for the node that volume has been mount or not mount.
Ok, I see. I was thinking they could be different scenarios for tests. And yes, I was using the anti-affinity to simulate the scheduling failure case. So I mentioned all the cases here for reference.

2020-08-18 23:03 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +4. Add new `ReplicaEvictionRequested` slice of string in volume controller as local variable to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction req
Volume controller has the full list of the replica in the memory, it can just query that.

2020-08-18 23:07 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +4. Add new `ReplicaEvictionRequested` slice of string in volume controller as local variable to collecting eviction replicas. Use this for the eviction creating extra replica or deleting eviction req
Yes, you are right, we can drop this variable as well. Let me update it.

2020-08-18 23:26 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +6. During reconcile the engine replica, based on `Replica.Status.EvictionRequested` of the volume replicas to trigger rebuild for different volumes' replicas. And remove the replicas have been evicte
There is no map now.

2020-08-18 23:26 UTC, yasker commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +This enhancement is to simplify and automatically to evict the replicas on the selected disabled disks or nodes to other suitable disks and nodes. Meanwhile keep the same level of fault tolerance dur
`to simplify and automatically evict .... per user's request.`

2020-08-19 07:36 UTC, shuo-wu requested changes
In general LGTM except for the test part.

2020-08-19 13:55 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +
Fixed.

2020-08-19 13:55 UTC, boknowswiki commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +2. Add new `evictionRequested` field to `Node.Spec`, `Node.Spec.disks` Spec and `Replica.Status`. These will help tracking the request from user and trigger replica controller to update `Replica.Stat
Fixed.

2020-08-20 02:55 UTC, shuo-wu commented on enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
> +#### Integration Test Plan
Here is the integration test example for case 1. Can you check if it's possible?
1. Disable the setting soft anti-affinity
2. Create and attach a 3-replica volume.
3. Do eviction for a random node.
4. Verify there is a scheduling failed replica and the volume is still healthy
5. Verify the evictionRequested field in node/replica.
6. Cancel the eviction.
7. Re-verify the evictionRequested field in node/replica.

2020-08-20 03:29 UTC, shuo-wu approved these changes

2020-08-20 19:56 UTC, boknowswiki commented
> What if the volume get detached during the eviction process?

I think for this case, we can cover it with [detached volume case](https://github.com/longhorn/longhorn/issues/1704), since we need to auto-attach it and do the eviction.

So far I am thinking of the eviction is depends on the volume status, if it's attached, then we can trigger rebuild and once it success, we can remove the replica. If the volume become detached during this eviction time or the volume is detached at the beginning, we need to auto-attach it and do the rebuild and once it success we remove the replica and then auto-detach by the end(need to take a deep look at the code about the auto-detach logic since there could be the case a pod which the volume attached is crashed, and the volume become detached. And after the eviction, we need to keep it attached).

Please let me know if you have other concern @yasker  and @shuo-wu . Thanks.

2020-08-21 00:21 UTC, yasker commented
We haven't implemented the eviction for the detached volume yet so we can leave this part to that.

Otherwise LGTM. We can update the proposal once we start working on the evict detached volume as well.

2020-08-21 00:22 UTC, merged