enhancements: Add LEP 'Preserve replicas after the disks migration'
longhorn/longhorn pull request #1699
Opened 2020-08-18 12:31 UTC by shuo-wu

longhorn/longhorn#1269

2020-08-18 23:02 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +9. Update Node ID for the related replicas in Disk Controller when an existing disk is re-attached to a node.
Not sure if the disk controller should update the node ID of replica, since replica spec is not created by the disk controller. Also, update a node ID for a "running" replica means it needs to be stopped (if the user didn't detach the volume before changing the disk). I feel like the volume controller is the better place to do it.

2020-08-19 21:25 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +     Instead, there is a corruption timeout for the disk. Once the disk is resued/added back before the timeout, the disk won't be deleted.
`Disconnection timeout`. It's not an indication of corruption.

`reused`

2020-08-19 21:25 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +2. Remove the field `NodeID` in `replica.Spec`. Instead, the disk UUID will be stored in `replica.Spec`, and the node ID will be detected only when the replica needs to be started.
`move the nodeid into replica.status.`

2020-08-19 21:27 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +After the enhancement, all volumes will become `Faulted` first after the replacement. Then the auto salvage will reuse the data in the old disks to recover the replicas. As a result, all volumes will
Not all the volumes become faulted.

Also, there is a possibility that managed EKS will drain the node first before replacing it.

There is a difference between the volume attached to the node and the volume has the replica on the node but not attached to it.

2020-08-19 21:31 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +3. scale up, wait for the rebuild, then scale down the volumes (this guarantees the HA)
New replica eviction feature can be used.

User can do:
1. Evict Longhorn replicas.
2. Drain the node

2020-08-19 21:31 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  2. The disk configuration (e.g., reserved space) is always determined by the users. Longhorn won't apply the previous configuration when reusing the old disks.
why? we have the same object.

2020-08-19 21:32 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  1. Add a new option `Clean up the host path during the initialization`. Sometimes users don't need the existing data when they want to reuse the disks.
I prefer to let the user do that. If they don't want to reuse the old replicas, they should wipe the disk.

2020-08-19 21:38 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  2. Add a new field `DetachedAt` in `disk.Status`. This field will be set when the related node is down. And Disk controller will clean up the disk if this field is set and the timeout is passed.
Disk controller shouldn't delete a disk object.

2020-08-19 21:43 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  1. Add a new field `NodeID` in `disk.Spec` and set it when adding the disk to a node.
Needs to be careful here on who is responsible for creating the disk.

If it's the user, the user will need to manually move the disk.

It might be easier if it's the node controller to create/migrate/cleanup the disk. Cleanup needs to be done by someone else if it's disconnected disk though.

Thinking about it, I am not sure if a timeout for the disk removal makes sense. If users don't want the disk, they will set timeout to 0; if they want to keep the disk, that means they are planning to reattach the disk, so removing the disk automatically anytime in the future seems weird. I think it makes better sense if the option is just true/false to keep the disk after the node removal. By default, it will be true since losing data is more worrisome than keeping something that you need to clean up.

2020-08-19 21:43 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  3. During the disk initialization/re-initialization, the UUID will be loaded if the meta file is found, field `DetachedAt` will be unset, and other status fields like `ScheduledReplica` will be det
Use `DisconnectedAt` to differentiate from the volume.

2020-08-20 23:45 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +        1. `Immediate`: Always delete disk immediately when the node is removed. This means the disk migration is not taken into consideration. This will be the default policy.
Why `Immediate` is the default option? This changes the default behavior from now and might result in data loss.

2020-08-20 23:47 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +        2. `Delayed`: Set a long deletion timestamp when the node is gone. When the disks are back later, the deletion timestamp will be unset and the disks will be re-initialized.
Will deletion timestamp be used later? Or it's just a marker for when the disk was disconnected. Sounds like `DisconnectedAt` timestamp is more proper is that's the case.

2020-08-20 23:52 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +           Hence, the **failed replicas should be retained** and **the rebuild will be delayed** before the related disks are completely removed. Then Longhorn can rebuild new replicas based on (the
Good catch. This is a problem not only happens with disk migration. If the replica failed due to a temporary network interruption, rebuild replica immediately is not a good idea too.

We can introduce a setting named e.g. `ReplicaRebuildWaitTime` (in seconds) to delay the rebuild for existing replicas, assuming the network and disk can be mounted back automatically after a few minutes.

2020-08-20 23:53 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +  3. Launch Disk Controller to handle the disk status monitoring and update rather than directly using Node Controller.
`update disk`?

2020-08-20 23:54 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +2. directly attach the disk to the another node
`reattach` or `reconnect`

2020-08-20 23:55 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +2. Directly Detach the disk from the old node, and reattach it to the new node (physically or in cloud vendor).
We can use `connect` instead of `attach` for the disk case, otherwise, it gets easily confused with the volume.

2020-08-20 23:56 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +
Add a case of scaling down the Kubernetes cluster automatically and a case of decommissioning a node.

In theory, as long as the user only scales down less than replica count number of nodes (e.g. 1 or 2 nodes) every time, and wait for the rebuild to complete, the cluster should be fine.

2020-08-20 23:57 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +    2. `Delayed`: Add a grace period for disk deletion. But this will block/delay the replica rebuild.
As I mentioned above, I feel it's better to leave this timeout to the rebuilding of the existing replica feature.

2020-08-20 23:58 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +
Add other two cases here as well.

2020-08-21 00:00 UTC, yasker commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +The soft anti-affinity restriction will be broken after the disk migration.
hmm? why only the soft anti-affinity? how about hard anti-affinity?

2020-08-21 02:41 UTC, shuo-wu commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +        1. `Immediate`: Always delete disk immediately when the node is removed. This means the disk migration is not taken into consideration. This will be the default policy.
This means the disk will be removed only when the node is deleted rather than when the node is down. In order to delete the node, all replicas should be removed by users first. Hence I don't think this policy will cause data loss.

2020-08-21 02:56 UTC, shuo-wu commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +        2. `Delayed`: Set a long deletion timestamp when the node is gone. When the disks are back later, the deletion timestamp will be unset and the disks will be re-initialized.
The deletion timestamp will be set in the node & disk deletion API call. If a field `DisconnectedAt` is used for the deletion delay, the node controller should take care of the actual disk deletion later, which increases the unnecessary complexity.

2020-08-21 02:57 UTC, shuo-wu commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +           Hence, the **failed replicas should be retained** and **the rebuild will be delayed** before the related disks are completely removed. Then Longhorn can rebuild new replicas based on (the
Yeah. Add this setting is definitely a good idea.

2020-08-21 02:59 UTC, shuo-wu commented on enhancements/20200817-preserve-replicas-after-the-disks-migration.md
> +The soft anti-affinity restriction will be broken after the disk migration.
Sorry for the typo. I mean `hard anti-affinity` here.

2020-08-24 03:48 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +    3. When a node is/can be manually removed via the UI, there is no replica using the related disks. It means there is no existing data in the related disks.
We can add a notification for the node deletion or rename the button name to `Remove node and related disks`

2020-08-24 03:56 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +Creating disk related HTTP APIs is required.
It's just HTTP APIs. Since we may require users to delete the disk manually.

2020-08-24 10:31 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +
I am not sure why we need to remove the disk with the node here?  I am trying to reuse the disk on the down node, rather than cleaning up the down node.

2020-08-24 23:48 UTC, yasker commented on enhancements/20200817-identify-disk-reconnection.md
> +
I meant if the user decides the disk will be gone if the node is gone (so no reattachment), we should remove the disk automatically, so the user won't need to do it manually. See https://github.com/longhorn/longhorn/issues/1151

2020-08-25 02:41 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +    2. Update `DiskStatus.State` in Disk Controller: If `DiskSpec.NodeID` is empty or the related node is down, the state will be `DiskStateConnected`. Otherwise, the state is `DiskStateConnected`.
Yes. Thank you for pointing out the typo!

2020-08-25 09:45 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +
1. What if there are (unknown) engines on the down node? Do we need to break the node deletion restriction thoroughly? 
2. We can provide an option/setting to do automatically cleanup (volumes, engines, replicas, disks) for down nodes, but I don't think this is related to this feature. It can be handled in #1151 separately. IMO, the main purpose of this feature is to reuse the existing data on the disk. Adding more complexity is not a good choice.

2020-08-25 09:45 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +
1. What if there are (unknown) engines on the down node? Do we need to break the node deletion restriction thoroughly? 
2. We can provide an option/setting to do automatically cleanup (volumes, engines, replicas, disks) for down nodes, but I don't think this is related to this feature. It can be handled in #1151 separately. IMO, the main purpose of this feature is to reuse the existing data on the disk. Adding more complexity is not a good choice.

2020-08-25 16:15 UTC, yasker commented on enhancements/20200817-identify-disk-reconnection.md
> +
1. The node has been removed from the cluster, there is no way there still be an engine attached to it. I feel detach the volume automatically and don't attach it until the Spec.NodeID changes to any existing nodes.
2. There are two ways of scaling down the cluster, and both are included in the epic issue https://github.com/longhorn/longhorn/issues/1151 (and  https://github.com/longhorn/longhorn/issues/1232 ). The goal of v1.1.0 is to support both cases.

2020-09-18 19:54 UTC, boknowswiki commented on enhancements/20200817-identify-disk-reconnection.md
> +1. Use separate CRD resources to manage disk lifecycle, so that the disks and nodes are decoupled. Then there is a chance to reuse replica data the disks:
```suggestion
1. Use separate CRD resources to manage disk lifecycle, so that the disks and nodes are decoupled. Then there is a chance to reuse replica data  on the disks:
```

2020-09-18 20:00 UTC, boknowswiki commented on enhancements/20200817-identify-disk-reconnection.md
> +    2. We can add an setting `Retain disks during node deletion` to determine if Longhorn needs to clean up disks.
Does this mean user can delete a node from Longhorn, but leave the disks in Longhorn? Could you help me to understand this part? Thanks.

2020-09-18 20:20 UTC, boknowswiki requested changes

2020-09-18 20:20 UTC, boknowswiki commented on enhancements/20200817-identify-disk-reconnection.md
> +7. Verify there is a failed replica. And the node ID of the failed replica is updated to Node2.
Why 'Verify these is a failed replica'? Should there be 3 replicas, and 2 replicas are on Node2 one on the default disk, one on the extra disk which reconnected from Node1 to Node2?

2020-09-19 10:46 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +7. Verify there is a failed replica. And the node ID of the failed replica is updated to Node2.
The main purpose of this test is to verify if Longhorn will update DiskID/NodeID/DataPath for the failed replica after the migration. Since the feature #1304 is not implemented, Longhorn won't reuse the failed replica and the existing data to do the rebuild.

2020-09-21 16:02 UTC, boknowswiki commented on enhancements/20200817-identify-disk-reconnection.md
> +1. Use separate CRD resources to manage disk lifecycle, so that the disks and nodes are decoupled. Then there is a chance to reuse replica data the disks:
What about this part? Is there a missing "on"? The sentence doesn't seem right to me.

2020-09-22 03:26 UTC, shuo-wu commented on enhancements/20200817-identify-disk-reconnection.md
> +1. Use separate CRD resources to manage disk lifecycle, so that the disks and nodes are decoupled. Then there is a chance to reuse replica data the disks:
Oh, sorry. I forgot to push the update commit for the PR.

2020-11-02 19:03 UTC, yasker commented
Let's update this one to the new design.

2020-11-06 12:17 UTC, shuo-wu commented
Close this PR since the new design is totally different from this version.

2020-11-06 12:17 UTC, closed without merging