enhancement: Add LEP 'support Data Locality option to keep a replica local to the engine'
longhorn/longhorn pull request #1705
Opened 2020-08-20 02:32 UTC by PhanLe1010

Issue: longhorn/longhorn#1045

2020-08-20 04:24 UTC, PhanLe1010 commented
I will fix spelling and grammar soon. Please help me to verify the logic first 😁

2020-08-20 05:10 UTC, shuo-wu requested changes
Great investigation and analysis! In general LGTM.

2020-08-20 05:10 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. **Kubernetes Scheduler Framework and Plugins**
It's seems that the main disadvantage of this approach is that users need to specify `spec.schedulerName` in pods' spec?

2020-08-20 05:10 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. **Longhorn's ability to move replica to a new node**
Maybe this part can be put in the `Design` or `Implementation Overview`. And summarising the essence of the design here is enough.

2020-08-20 05:10 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 3 modes for `dataLocality`:
The mode naming `dynamic` and `static` is a little bit confusing.

2020-08-20 08:28 UTC, joshimoo reviewed
@PhanLe1010 good job on the analysis and the write up  👍 

Left some comments.

One Sentence per line please, this helps with the diffs and reviews.
Markdown will format as required :)

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     1. In the `prioritize` phase, the `default scheduler` will score the nodes based on attributes such as the state. Longhorn can register the Http server as a webhook at the end of this phase. The
Since points are additive, we can score non replica nodes with negative scores in our scoring function :)
This way we are more or less in control of the scheduling decisions.

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     The scheduling framework contains 2 cyles: `Scheduling Cycle` and `Binding Cycle`. The `Scheduling Cycle` exposes 7 extension points. Longhorn can implement 2 plugins: one for the `Filter` exten
`filter` implementation is only required for `enforced` data locality
`prioritize` for `best effort` data locality

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 3 modes for `dataLocality`:
Agree how about `best-effort` and `required/enforced/guaranteed` data locality?

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 3 things the user can change for `data locality` setting:
Consider exposing the data locality setting  as a parameter on the Storage Class.
This way the user can create different Storage Classes for different setups, we can also then ship common Storage Classes for different usage scenarios.

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. specify `dataLocality` mode for all volume in the global setting
Not sure if we need a global setting, switching from one mode of data locality to another seems complicated.

In my mind data locality mode is a setting that should be specified when a `volume is created`, same as the access mode. One wouldn't expect to be able to change a RWO to an RWX volume after creation :)

If we do want to support changing this, then the per volume setting is fine otherwise let's consider the storage class approach?
@yasker @shuo-wu @PhanLe1010

2020-08-20 08:28 UTC, joshimoo commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. In `longhorn-soring-plugin`, If `dataLocality: dynamic`, then we give more points for the nodes in the input list which contain existing volume's replica.
Also subtract points for nodes, that don't have a local replica.
Also need to look at the Storage Capacity of the available nodes.

2020-08-21 00:23 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. This enhancement doesn't make any guarantee if the users misconfigure the `data locality` setting. When the users misconfigure the `data locality` setting, the `data-locality` behavior will be und
What does this mean? How can the user misconfigure it?

2020-08-21 00:31 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +**My propose solution** is the combination of the component **Longhorn's ability to move replica to a new node** and **Kubernetes Scheduler Framework and Plugins**
I also don't understand the reason behind picking this approach. Recompile the scheduler is big. Ask the user to change the Pod spec is a big ask.

2020-08-21 00:35 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. `do-nothing`: this is the default setting. Longhorn will not attempt to keep a local replica on the same node as the consuming pod
Just simply `Disabled`.

2020-08-21 00:35 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 3 modes for `dataLocality`:
`best-effort` and `enforced` sounds good.

2020-08-21 00:36 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. need to specify `spec.schedulerName: longhorn-scheduler` in the spec of all pods which use Longhorn volumes.
Ask I mentioned above, it's a big ask.

2020-08-21 00:39 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. specify `dataLocality` mode for all volume in the global setting
The global setting should only function as a default value, like replica count. It shouldn't change any existing volume's setting.

On change volume's setting side, it seems the setting can be changed without much consequence once the volume is detached. Changing the attached volume sounds like another story.

And yes, definitely should be an option per storageclass.

2020-08-21 00:40 UTC, yasker commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +No API changes
There is setting added per global and in volume level, probably both creation and update. So there are API changes and we need to define the API names etc.

2020-08-21 00:55 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. This enhancement doesn't make any guarantee if the users misconfigure the `data locality` setting. When the users misconfigure the `data locality` setting, the `data-locality` behavior will be und
In my proposal solution, user need to specify 2 things for `dataLocality` settings:
1. need to specify `spec.schedulerName: longhorn-scheduler` in the spec of all pods which use Longhorn volumes.
1. need to specify `dataLocality` mode for each volume

By saying the user misconfigures, I mean that user specify specify `dataLocality` mode for each volume (e.g. the setting in storageclass) but forget to  specify `spec.schedulerName: longhorn-scheduler`. In this case, the behavior of Longhorn will be undefined. 

For example, user  set `dataLocality=enforced` mode in storageclass but  forget to  specify `spec.schedulerName: longhorn-scheduler`. In this case Kubernetes does not use `longhorn-scheduler` profile, therefore Longhorn cannot influence the scheduling descision.

2020-08-21 00:57 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. **Longhorn's ability to move replica to a new node**
Thank you! I will fix this

2020-08-21 00:59 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     1. First, in the `filter` phase, the `default scheduler` filters out all the un-schedulable nodes base on the requirements (like CPU, memory, selector, affinity, ..). At the end of the `filter`
> We will need filter in the case where we enforce data locality.
For best effort data locality we shouldn't filter out any nodes and instead only use a custom scoring function in the prioritize call, otherwise we potentially end up with an empty list after the filter call.

Yes, the propose solution is doing this. I will fix the doc to reflect this. 

> Also it's not a new list it's the resulting list (output of filter) that gets passed to the prioritize call.

Will fix this

2020-08-21 00:59 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     1. In the `prioritize` phase, the `default scheduler` will score the nodes based on attributes such as the state. Longhorn can register the Http server as a webhook at the end of this phase. The
I will try this

2020-08-21 01:03 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. **Kubernetes Scheduler Framework and Plugins**
Yes, you are correct! If we want Longhorn to automatically set ` spec.schedulerName:longhorn-scheaduler `, we can implement a `Mutating Admission Controller` as mentioned in this document. StorageOS is doing this. However, there are disadvantages when using a `Mutating Admission Controller` (also mentioned on this doc) which discourage me from using a `Mutating Admission Controller`

2020-08-21 01:04 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     The scheduling framework contains 2 cyles: `Scheduling Cycle` and `Binding Cycle`. The `Scheduling Cycle` exposes 7 extension points. Longhorn can implement 2 plugins: one for the `Filter` exten
Thank you! I will update the document to reflect this.

2020-08-21 01:42 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +**My propose solution** is the combination of the component **Longhorn's ability to move replica to a new node** and **Kubernetes Scheduler Framework and Plugins**
> Recompile the scheduler is big.

So sorry, I was wrong here. I mentioned before that by using `Kubernetes Scheduler Framework`, we will modify the user's default scheduler and there will be only 1 scheduler in the cluster. I was wrong. The proposing solution is actually building a separate custom scheduler using `Kubernetes Scheduler Framework`. We will build 2 custom plugins for `filter` and `scoring` extension points and use `Kubernetes Scheduler Framework` to compile the 2 plugins with all the default plugins. The end result is a custom, performant scheduler without having to fork the core scheduler's code.  The building and compiling happen on our end.  We then can push and image of this scheduler onto DockerHub. Then can deploy the custom scheduler to the user's cluster using a deployment of 1 pod. 

> Ask the user to change the Pod spec is a big ask.

In order to use a custom scheduler, the pod's spec must have `schedulerName` set to a profile name in the custom scheduler. If we don't want users to manually set this field, we can implement a `Mutating Admission Controller` as mentioned in this document.  The `Mutating Admission Controller` will automatically `schedulerName`. StorageOS is doing this. However, there are disadvantages when using a Mutating Admission Controller (also mentioned on this doc) which discourage me from using it.

2020-08-21 01:50 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 3 modes for `dataLocality`:
thank you! I will fix this

2020-08-21 01:51 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. need to specify `spec.schedulerName: longhorn-scheduler` in the spec of all pods which use Longhorn volumes.
Same as https://github.com/longhorn/longhorn/pull/1705/files#r474361317

2020-08-21 01:52 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +No API changes
Thank you!

2020-08-21 01:54 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. In `longhorn-soring-plugin`, If `dataLocality: dynamic`, then we give more points for the nodes in the input list which contain existing volume's replica.
Thank you. I will try to subtract.

Note sure why we need to `look at the Storage Capacity of the available nodes.` We only give more point for the nodes which contains existing replicas. It means that the node already has enough  Storage Capacity. Is it correct?

2020-08-25 23:50 UTC, yasker commented
We need to clean up this LEP to make it qualify as a Longhorn LEP. This document in the current format is more like notes of discussion and brainstorming, rather than a formal design document for a feature.

Here are a few things we can do about this doc:
1. For the LEP itself, limit the topic to migrating the replica to the pod/node. State the scheduling change as a `non-goal` for this part of enhancement, and refer to the issue for details.
2. Summary the discussion and thought process and post them to https://github.com/longhorn/longhorn/issues/1045 instead of a part of LEP.
    1. Remove creating our own scheduler. It's out of the question.
    2. State the pros and cons with the other potential scheduler changes (either webhook or the new scheduling framework).
    3. Potential enhancement of Kubernetes.
    4. Anything else you think useful for understanding the choice.

2020-08-26 00:02 UTC, PhanLe1010 commented
Thanks Sheng! working on this now.

2020-08-26 12:06 UTC, shuo-wu requested changes

2020-08-26 12:06 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. Open the ingress and go to volume API at `v1/volumes`
Ideally, QA will test the case after the UI modification. I don't need to mention this. Same below

2020-08-26 12:06 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +##### Test volume creation with `dataLocality` is unspecified and `DefaultDataLocality` setting as `diable`:
Typo `diable`

2020-08-26 12:06 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. Leave the `DefaultDataLocality` setting as `diable` in Longhorn UI.
Typo `diable`

2020-08-26 12:06 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. create a shell deployment of 1 pod using `ubuntu:xenial` image, and the PVC dynamically created by `disable-longhorn` storage class.
I don't think we need to mention this kind of detail in LEP. Same below

2020-08-26 12:06 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +
Add tests for the volumes created in old versions.

2020-08-26 18:05 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +There are 2 modes for `dataLocality`:
Thank you! Fixed

2020-08-26 18:05 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. Using Rancher to install an L7 ingress pointing to `longhorn-backend` service
Thank you! Fixed

2020-08-26 18:05 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +
Thank you! Added

2020-08-26 18:06 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. Open the ingress and go to volume API at `v1/volumes`
Thank you! Fixed

2020-08-26 18:06 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +##### Test volume creation with `dataLocality` is unspecified and `DefaultDataLocality` setting as `diable`:
Thank you! Fixed

2020-08-26 18:06 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. Leave the `DefaultDataLocality` setting as `diable` in Longhorn UI.
Thank you! Fixed

2020-08-26 18:06 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +1. create a shell deployment of 1 pod using `ubuntu:xenial` image, and the PVC dynamically created by `disable-longhorn` storage class.
Thank you! Fixed

2020-08-26 18:06 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +
Thank you! Added

2020-08-27 04:20 UTC, shuo-wu requested changes

2020-08-27 04:20 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +User can use this enhancement feature to solve problems as described in [Story 1](#story-1) and [Story 2](#story-2)
The experience is more like: Users do something first to enable the feature, then users will see something.
e.g.:
1. Users create a storageclass with `dataLocality: best-effort` set
2. Users launch a statefulset with the storageclass.
3. Users will find that there is always a replica on the node where the pod resides on

2020-08-27 04:20 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +
Use a separate sub-section to clarify which kind of UI modification should be applied.

2020-08-27 17:51 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +User can use this enhancement feature to solve problems as described in [Story 1](#story-1) and [Story 2](#story-2)
Thank you. I fixed it

2020-08-27 17:52 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +
Thank you. Added

2020-08-28 03:18 UTC, shuo-wu requested changes
LGTM except for the typo

2020-08-28 03:18 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     Similar to the replica node redundancy wanring [here](https://github.com/longhorn/longhorn-ui/blob/0a52c1f0bef172d8ececdf4e1e953bfe78c86f29/src/routes/volume/detail/VolumeInfo.js#L47)
typo `wanring `

2020-08-28 21:21 UTC, PhanLe1010 commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     Similar to the replica node redundancy wanring [here](https://github.com/longhorn/longhorn-ui/blob/0a52c1f0bef172d8ececdf4e1e953bfe78c86f29/src/routes/volume/detail/VolumeInfo.js#L47)
Thank you! Fixed. I am sorry for the late response.

2020-08-29 02:57 UTC, shuo-wu commented on enhancements/20200819-keep-a-local-replica-to-engine.md
> +     Similar to the replica node redundancy wanring [here](https://github.com/longhorn/longhorn-ui/blob/0a52c1f0bef172d8ececdf4e1e953bfe78c86f29/src/routes/volume/detail/VolumeInfo.js#L47)
Wait... The typo is still there.

2020-09-08 22:19 UTC, yasker approved these changes

2020-09-08 22:19 UTC, merged