enhancements: Add LEP 'Rebuild replica with existing data'
longhorn/longhorn pull request #1708
Opened 2020-08-21 11:30 UTC by shuo-wu

longhorn/longhorn#1304

2020-08-24 12:32 UTC, shuo-wu commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +    1. Avoid replenishing a new replica objects for degraded volumes if there is a failed replica, and `ReplicaRebuildWaitTime` is not passed since the replica failure.
If Longhorn failed to rebuild the volume with a failed replica due to the network fluctuation, `ReplicaSpec.HealthyAt` is empty but there is data in the directory (`ReplicaSpec.HealthyAt` will be cleaned up during before the rebuild). 
If the directory does not contain any valid data when `ReplicaSpec.HealthyAt` is empty, the rebuild still work fine in theory. 

Hence, it's better not to add this restriction.

2020-08-24 23:49 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +    1. Avoid replenishing a new replica objects for degraded volumes if there is a failed replica, and `ReplicaRebuildWaitTime` is not passed since the replica failure.
Make sense.

2020-08-25 03:44 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +2. Add field `EngineStatus.FailedReplicaRetryCount` to indicate how many times Longhorn tries to reuse a failed replica for the rebuild
`EngineStatus`? How do you know which replica has been retried in this way? I thought the retry is per replica, not per engine/volume.

2020-08-25 04:42 UTC, shuo-wu commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +2. Add field `EngineStatus.FailedReplicaRetryCount` to indicate how many times Longhorn tries to reuse a failed replica for the rebuild
Sorry for the typo. The field should be `FailedReplicaRetryCountMap`. The record will be cleaned up when the replica mode becomes RW in the engine monitor .

Will update the doc for this part

2020-08-25 16:31 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +2. Add field `EngineStatus.FailedReplicaRetryCount` to indicate how many times Longhorn tries to reuse a failed replica for the rebuild
Should we preserve the counter in the replica or engine? It might make more sense in the engine since it's not directly reported by the engine.

2020-08-26 02:01 UTC, shuo-wu commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +2. Add field `EngineStatus.FailedReplicaRetryCount` to indicate how many times Longhorn tries to reuse a failed replica for the rebuild
Do you mean adding a synced map in the engine controller? Then the engine controller main loop and the engine monitor will be responsible for updating it.

2020-08-26 02:30 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +2. Add field `EngineStatus.FailedReplicaRetryCount` to indicate how many times Longhorn tries to reuse a failed replica for the rebuild
Sorry, typo. I meant to say `it might make more sense in the replica`.

2020-10-30 21:21 UTC, yasker requested changes
Minor wording issues, otherwise LGTM.

2020-10-30 21:21 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +    - If the failed replica currently is unavailable but it may be able to be reused later(we call it potential reusable failed replica), Longhorn may need to relay the new replica replenishment so t
`relay`?

2020-10-30 21:21 UTC, yasker commented on enhancements/20200821-rebuild-replica-with-existing-data.md
> +3. Hack into one replica directory and make it immutable.
`make the directory and files read-only`.

2020-11-02 19:01 UTC, yasker commented
Any update?

2020-11-03 17:07 UTC, yasker approved these changes

2020-11-03 17:07 UTC, merged