Add replace revision counter in longhorn engine enhancement document
longhorn/longhorn pull request #1710
Opened 2020-08-22 00:36 UTC by boknowswiki

https://github.com/longhorn/longhorn/issues/508

Signed-off-by: Bo Tao <bo.tao@rancher.com>

2020-08-24 03:43 UTC, shuo-wu requested changes

2020-08-24 03:43 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +Currently Longhorn Replica will update revision counter to the 'revision.counter' file on every write operation, this impacts the performance a lot. And the main purpose of this revision counter is t
We will check the revision counter to prevent inconsistency among replicas each time the engine is started, too:
https://github.com/longhorn/longhorn-engine/blob/17c3e3ea20ea660a025b0b8c14e2c3f6e3f186e8/pkg/controller/control.go#L552

Remember to update the summary and goal with this info, too.

2020-08-24 03:43 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +This enhancement doesn't impact any user experience.
Not sure if we need to mention the performance improvement here.

2020-08-24 03:43 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +1. Add Longhorn Engine Replica new gRPC API like 'ReplicaVolumeHeadStatGet' to get 'volume-head-xxx.img' stat information which includes 'last modified time' and 'block numbers' allocated to this fil
Need to add this kind of gRPC API changes in Section `API changes`

2020-08-24 03:43 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state and 'Automatic salvage' has been enabled, get the candidate replicas for salvage from 'GetCan
1. Need to consider the engine status. IIRC, the engine will be detached and reattached once all replicas become faulted. And the gRPC call cannot be invoked once the engine process is gone.
2. Need to consider the compatibility issue.

2020-08-24 18:12 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +Currently Longhorn Replica will update revision counter to the 'revision.counter' file on every write operation, this impacts the performance a lot. And the main purpose of this revision counter is t
I will update the 'Proposal and Goal'. Do you think we need to add this specific case to the 'Summary'? I think the 'Summary' is more like a high level description. Please let me know. Thanks.

2020-08-24 18:14 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +This enhancement doesn't impact any user experience.
I am not sure either. Let me add it for now and see how @yasker says.

2020-08-24 18:20 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +1. Add Longhorn Engine Replica new gRPC API like 'ReplicaVolumeHeadStatGet' to get 'volume-head-xxx.img' stat information which includes 'last modified time' and 'block numbers' allocated to this fil
Oh, I see. I was thinking the 'API changes' was for the UI. I will update this part.

2020-08-24 20:14 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state and 'Automatic salvage' has been enabled, get the candidate replicas for salvage from 'GetCan
Thanks for pointing this, let me think about the engine status case and sync up with you later.

2020-08-25 03:39 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +Currently Longhorn Replica will update revision counter to the 'revision.counter' file on every write operation, this impacts the performance a lot. And the main purpose of this revision counter is t
No. `Summary` LGTM.

2020-08-25 07:00 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state and 'Automatic salvage' has been enabled, get the candidate replicas for salvage from 'GetCan
You are right about the engine will be detached. So I am thinking to call the replica gRPC to get the stat directly, what do you think this idea?
And for the compatibility issue, I am thinking if we call the new gRPC failed, then we do the original way.
Please let me know what do you think. Thanks.

2020-08-25 17:32 UTC, boknowswiki commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state and 'Automatic salvage' has been enabled, get the candidate replicas for salvage from 'GetCan
After discuss with @yasker , I should stay with the original idea, and to auto-attach the engine during the 'Faulted' state, and then auto-detach it. I will update this part.

2020-08-27 00:03 UTC, yasker commented on enhancements/20200821-add-revision-counter-disable-support.md
> +4. Also during Longhorn Engine starting, be able to connect to all the synced replicas and mark the out of synced replicas as 'ERR' state.
We might want to reconsider if it's possible if we disabled the revision counter.

2020-08-27 00:05 UTC, yasker commented on enhancements/20200821-add-revision-counter-disable-support.md
> +Some user has concern about Longhorn's performance. And with this 'RevisionCounterDisabled' option, Longhorn's performance will be improved a lot. And give user better experience.
Remove `And give user better experience` since it's unclear what is `experience` referring to here.

Also, we can collect some preliminary performance data here.

2020-08-27 00:05 UTC, yasker commented on enhancements/20200821-add-revision-counter-disable-support.md
> +In Longhorn UI 'Setting' 'General', by default 'RevisionCounterDisabled' is 'false', user can set 'RevisionCounterDisabled' to 'true', this will apply to all the new volumes both from Longhoron UI or
Should be applied only to the volumes created by the Longhorn UI. StorageClass has a separate setting for that.

2020-08-27 03:17 UTC, c3y1huang commented on enhancements/20200821-add-revision-counter-disable-support.md
> +####TODO how to make engine to fauled state. One way is to failed to ping monitor, like connection or modifing the replica files.
```suggestion
####TODO how to make engine to a failed state. One way is to failed to ping monitor, like connection or modifying the replica files.
```

2020-08-27 03:17 UTC, c3y1huang commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- If Mixed case, use the head file size for the comparision. And print warning about it.
```suggestion
- If Mixed case, use the head file size for the comparison. And print warning about it.
```

2020-08-27 05:07 UTC, shuo-wu commented on enhancements/20200821-replace-revision-counter-in-longhorn-engine.md
> +This enhancement doesn't impact any user experience.
According to Sheng's comment, we need to collect the performance data here.

2020-08-27 05:12 UTC, shuo-wu requested changes

2020-08-27 05:12 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +With the head file information, Longhorn Engine can still mark the out of synced replica as 'ERR' during the starting time.
Clarify how Longhorn can verify the out-of-date replica via the head file information.

2020-08-27 05:12 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +4. Add new parameter to 'ReplicaCreateProcess' to disable revision counter. And a new gRPC API for engine control to get this setting from replica.
It seems that both instance manager gRPC API and the replica gRPC API need to be updated. Then you may need to clarify how to handle the compatibility issue in this doc.

2020-08-27 17:36 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +Some user has concern about Longhorn's performance. And with this 'RevisionCounterDisabled' option, Longhorn's performance will be improved a lot. And give user better experience.
I will add a 'TODO' in this section, and update this part once we have the data.

2020-08-27 17:36 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +In Longhorn UI 'Setting' 'General', by default 'RevisionCounterDisabled' is 'false', user can set 'RevisionCounterDisabled' to 'true', this will apply to all the new volumes both from Longhoron UI or
Sure, will update this part.

2020-08-27 17:36 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +####TODO how to make engine to fauled state. One way is to failed to ping monitor, like connection or modifing the replica files.
Will fix, thanls.

2020-08-27 17:36 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- If Mixed case, use the head file size for the comparision. And print warning about it.
Will fix, thanks.

2020-08-27 17:37 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +With the head file information, Longhorn Engine can still mark the out of synced replica as 'ERR' during the starting time.
Will add more details there. thanks.

2020-08-27 17:38 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +4. Add new parameter to 'ReplicaCreateProcess' to disable revision counter. And a new gRPC API for engine control to get this setting from replica.
Let me think more detail about it and update it later. May need to sync with you. Thanks.

2020-08-27 18:17 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +With the head file information, Longhorn Engine can still mark the out of synced replica as 'ERR' during the starting time.
@shuo-wu , per discussion with @yasker , so far we haven't think a good way to tell if any replica is out of sync if some of the latest writes are on the same block. We will skip the check for now. Please let me know if you have any good idea about this part. Thanks.

2020-08-31 22:06 UTC, yasker commented on enhancements/20200821-add-revision-counter-disable-support.md
> +1. By default 'RevisionCounterDisabled' is 'false', but Longhorn provides an optional for user to disable it.
It's better to call the setting `DisableRevisionCounter` (like `Disable Scheduling on Cordoned Node`) with the options `true` or `false`, or `RevisionCounter` with the options `enabled`/`disabled`.

2020-08-31 22:26 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +1. By default 'RevisionCounterDisabled' is 'false', but Longhorn provides an optional for user to disable it.
Sure. I will update it to 'DisableRevisionCounter'. Thanks.

2020-09-08 04:54 UTC, shuo-wu requested changes

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +4. Add new parameter to 'ReplicaCreateProcess' to disable revision counter. And a new gRPC API for engine control to get this setting from replica.
I think adding a new field in `replica/ReplicaGetResponse` is enough. We don't need a new separate engine GRPC API for it.

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +2. Once 'RevisionCounterDisabled' is 'true' either from global setting or individual setting, volume controller will set 'Volume.Spec.RevisionCounterDisabled' to true, and 'Replica.Status.RevisionCou
Why not put `RevisionCounterDisabled` in `Replica.Spec`?

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- If Mixed case, engine will not check the synchronation of the replicas. And print warning about it.
What's this?

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +1. The logic details of 'ReplicaList' with 'salvage' to get the most suitable replica for salvage.
Do you mean the command in `longhorn-manager/engineapi`?

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- Based on 'volume-head-xxx.img' last modified time, to get the latest one and any one within 5 second can be put in the candidate replicas for now.
Do you mean the engine process is responsible for figuring out the candidates? When all replica processes become ERROR, how does the engine process get this kind of info?

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +
After skipping the longhorn engine starting check, adding a regression test would be better.
e.g.,
1. Disable the revision counter.
2. Kill the engine process during the data writing.
3. Verify the volume still works fine.
4. Repeat the above test multiple times.

2020-09-08 04:54 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +Revision counter disbled option should return error if only Longhorn Manager got upgraded, not Longhorn Engine.
You mean disabling revision counter for old volumes will error out?

2020-09-08 18:19 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +2. Once 'RevisionCounterDisabled' is 'true' either from global setting or individual setting, volume controller will set 'Volume.Spec.RevisionCounterDisabled' to true, and 'Replica.Status.RevisionCou
Sure, will fix it. Thanks.

2020-09-08 18:21 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- If Mixed case, engine will not check the synchronation of the replicas. And print warning about it.
will clarify this part. Thanks.

2020-09-08 18:22 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +1. The logic details of 'ReplicaList' with 'salvage' to get the most suitable replica for salvage.
After discussion, let me take more look at this part.

2020-09-08 18:23 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +- Based on 'volume-head-xxx.img' last modified time, to get the latest one and any one within 5 second can be put in the candidate replicas for now.
After discussion, will think about this part. Thanks.

2020-09-08 18:23 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +Revision counter disbled option should return error if only Longhorn Manager got upgraded, not Longhorn Engine.
Will update this part for clarification.

2020-09-14 21:01 UTC, boknowswiki commented
@shuo-wu , I have updated this LEP based on our discussion, please help to take a look. Thanks.

2020-09-15 08:35 UTC, shuo-wu requested changes

2020-09-15 08:35 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state, set 'SalvageRequested' in 'InstanceSpec' to 'true' and start engine controller with 'salvage
During the auto salvage, longhorn-manager will still launch replicas first then launch the engine. And as I mentioned in the discussion, we need to consider what if some replicas cannot be launched.

2020-09-15 08:35 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +#### Add New Logic for Salvage
In this part, it's better to follow the salvage workflow to clarify what will happen after the refactoring. And explicitly clarifying which part (`longhorn-engine/controller`, `longhorn-manager/engineapi`, `longhorn-manager/controller`) the modification is applied to will be more easy-to-understand.

2020-09-15 08:35 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +Revision counter disbled option should return error if only Longhorn Manager got upgraded, not Longhorn Engine.
Remember to update this statement. And there is a typo `disbled `

2020-09-15 08:35 UTC, shuo-wu commented on enhancements/20200821-add-revision-counter-disable-support.md
> +#### Salvage replica when revision counter disabled
Mention this test as a regression test.

2020-09-15 16:15 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state, set 'SalvageRequested' in 'InstanceSpec' to 'true' and start engine controller with 'salvage
Yes, we have discussed this, and I think @yasker mentioned replicas couldn't be launched was a separate case which our current design also had this issue. If the replica can not be launched, then engine can not connect to them, they won't be selected as candidate for recovering, right?

2020-09-15 16:27 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +#### Add New Logic for Salvage
Sure, will update.

2020-09-16 16:22 UTC, boknowswiki commented
@shuo-wu , any comments on the last PR? Thanks.

2020-09-17 19:50 UTC, boknowswiki commented on enhancements/20200821-add-revision-counter-disable-support.md
> +3. Update the logic in Volume Controller 'ReconcileVolumeState', when the volume is at 'allFaulted' state, set 'SalvageRequested' in 'InstanceSpec' to 'true' and start engine controller with 'salvage
Hi Shuo, I have tried the steps per our discussion (kill the replica pods, and then delete one replica directory), I don't hit the issue that engine won't be up until all the replicas are up. So I think it's fine. Also I think this feature doesn't change previous behavior. Please let me know what you think. Thanks.

2020-09-18 04:23 UTC, shuo-wu approved these changes

2020-09-21 19:41 UTC, boknowswiki commented
Hi @shuo-wu and @yasker , I just updated this LEP mainly the implementation overview part to add 'Engine.Spec.RevisionCounterDisabled' to engine object, which pass extra flag to engine controller to be aware of revision counter disabled or not. Please take a look and let me know. Thanks.

2020-09-22 03:52 UTC, shuo-wu approved these changes

2020-09-22 21:57 UTC, yasker approved these changes

2020-09-22 21:57 UTC, merged