add enhancement document for the feature `allow recurring backup for detached volumes`
longhorn/longhorn pull request #1851
Opened 2020-10-04 06:31 UTC by PhanLe1010

longhorn/longhorn#1509

2020-10-05 18:31 UTC, yasker requested changes

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Avoid conflict with the data locality feature.
`if the automatically attach happens.`

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Add new global boolean setting `Allow-Recurring-Backup-While-Volume-Detached`
Merge those two sentences.

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +When there is no demand (e.g there is no function calls because there is no users' request), OpeenFaas will scale down the number of function replicas (similar to Pod concept in Kubernetes) to 0.
`OpenFaas`.

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +      set `DataLocality` to `disabled` for the volume.
You cannot change the spec of the volume.

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +      This is necessary so that we can safely detach the volume when finishing the backup.
Disable Volume frontend should automatically disable the data locality.

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +
Reset the option once the test is done.

2020-10-05 18:31 UTC, yasker commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Wait until the recurring backup starts.
Make sure Longhorn automatically attach the volume to a node that doesn't have a replica and doesn't trigger the rebuild.

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Avoid conflict with the data locality feature.
Thank you. Fixed

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Add new global boolean setting `Allow-Recurring-Backup-While-Volume-Detached`
Thank you. Fixed

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +When there is no demand (e.g there is no function calls because there is no users' request), OpeenFaas will scale down the number of function replicas (similar to Pod concept in Kubernetes) to 0.
Thank you. Fixed

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +      set `DataLocality` to `disabled` for the volume.
Thank you. Fixed

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +      This is necessary so that we can safely detach the volume when finishing the backup.
Thank you. Fixed

2020-10-05 20:40 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +
Thank you. Fixed

2020-10-05 20:41 UTC, PhanLe1010 commented on enhancements/20201002-allow-recurring-backup-detached-volumes.md
> +1. Wait until the recurring backup starts.
Thank you. Fixed

2020-10-06 03:20 UTC, yasker approved these changes

2020-10-06 03:21 UTC, merged