Update Helm chart templates for Longhorn v1.1.0
longhorn/longhorn pull request #1907
Opened 2020-10-23 23:42 UTC by PhanLe1010

longhorn/longhorn#1906

2020-10-24 00:36 UTC, yasker requested changes

2020-10-24 00:36 UTC, yasker commented on chart/templates/clusterrole.yaml
> +    - "*"
?

2020-10-24 00:36 UTC, yasker commented on chart/templates/clusterrole.yaml
> +  verbs: ["get", "watch", "list", "delete", "update", "create"]
?

2020-10-24 00:36 UTC, yasker commented on chart/templates/clusterrole.yaml
> +- apiGroups: ["coordination.k8s.io"]
Those are duplicated fields. We should clean them up on the manager's side.

2020-10-24 00:36 UTC, yasker commented on chart/templates/storageclass.yaml
> +  namespace: longhorn-system
Does other yaml used hardcoded namespace as well?

2020-10-24 01:13 UTC, PhanLe1010 commented on chart/templates/clusterrole.yaml
> +    - "*"
I am sorry. Copy error.

2020-10-24 01:14 UTC, PhanLe1010 commented on chart/templates/clusterrole.yaml
> +  verbs: ["get", "watch", "list", "delete", "update", "create"]
This come from longhorn/longhorn-manager repo. Should we keep it the same as in over there?

2020-10-24 01:18 UTC, PhanLe1010 commented on chart/templates/storageclass.yaml
> +  namespace: longhorn-system
Thank you! Fixed

2020-10-24 01:23 UTC, PhanLe1010 commented on chart/templates/clusterrole.yaml
> +- apiGroups: ["coordination.k8s.io"]
Thank you. Fixed

2020-10-24 04:32 UTC, yasker approved these changes

2020-10-24 04:33 UTC, yasker commented
LGTM. Waiting for the other PRs to be ready.

2020-10-26 19:16 UTC, PhanLe1010 commented
Removed the storageclass configmap from `manager` daemonset's volumes  because we will read the configmap directly from Kubernetes API.

2020-10-29 01:42 UTC, merged