enhancement: Add a new enhancement 'disk-reconnection'
longhorn/longhorn pull request #1959
Opened 2020-11-06 12:15 UTC by shuo-wu

#1269

2020-11-06 18:38 UTC, yasker requested changes
LGTM except a few minor issues.

2020-11-06 18:38 UTC, yasker commented on enhancements/20201106-disk-reconnection.md
> +3. Click `Connect Disk` with new the mount point and the new node ID in Longhorn Node page.
`Connect Disk`?

2020-11-06 18:38 UTC, yasker commented on enhancements/20201106-disk-reconnection.md
> +Disk related HTTP APIs are required.
Need to list the changes here.

2020-11-09 12:20 UTC, shuo-wu commented on enhancements/20201106-disk-reconnection.md
> +Disk related HTTP APIs are required.
Sorry for the mistake. This is the leftover of the previous version.

2020-11-09 17:59 UTC, yasker approved these changes

2020-11-09 17:59 UTC, merged