Update README.md
longhorn/longhorn pull request #1982
Opened 2020-11-14 02:55 UTC by wjimenez5271

highlight community events

2020-11-14 03:18 UTC, yasker requested changes
Can you also add your `Signed-off-by` ? See https://github.com/longhorn/longhorn/blob/master/CONTRIBUTING.md#dco-sign-off

2020-11-14 03:18 UTC, yasker commented on README.md
> +**Community Office Hours**!: Hosted by the core maintainers of Longhorn: 2nd Friday of the every month at 09:00 Pacific Time (PT)/12:00 Eastern Time (ET) on Zoom: http://bit.ly/longhorn-community-mee
Can we add the calendar (http://bit.ly/longhorn-events) to it as well? Since it's not easy to remember to join once a month.

2020-11-14 03:19 UTC, yasker commented on README.md
> +**Community Office Hours**!: Hosted by the core maintainers of Longhorn: 2nd Friday of the every month at 09:00 Pacific Time (PT)/12:00 Eastern Time (ET) on Zoom: http://bit.ly/longhorn-community-mee
Also, it's called `Community meeting and office hour`.

2020-11-14 03:48 UTC, wjimenez5271 commented on README.md
> +**Community Office Hours**!: Hosted by the core maintainers of Longhorn: 2nd Friday of the every month at 09:00 Pacific Time (PT)/12:00 Eastern Time (ET) on Zoom: http://bit.ly/longhorn-community-mee
@yasker thanks updated

2020-11-15 23:23 UTC, yasker approved these changes

2020-11-15 23:23 UTC, merged