1670 change registry secret location
longhorn/longhorn pull request #2007
Opened 2020-11-21 06:30 UTC by PhanLe1010

To avoid confusing user, we move the registry secret setting outside of default setting section. Now, user will set registry secret setting in `privateRegistry.registrySecret`

longhorn/longhorn#1670

2020-11-23 22:51 UTC, yasker requested changes

2020-11-23 22:51 UTC, yasker commented on chart/questions.yml
> +  description: "The Kubernetes Secret name"
If we will generate it automatically, we need to call it out.

2020-11-23 22:51 UTC, yasker commented on chart/templates/postupgrade-job.yaml
> +        imagePullPolicy: IfNotPresent
I remember we have related issues regarding the imagepullpolicy of the uninstaller? Should refer it.

2020-11-23 23:32 UTC, PhanLe1010 commented on chart/templates/postupgrade-job.yaml
> +        imagePullPolicy: IfNotPresent
@yasker I couldn't find the related issue. Do you have a link?

2020-11-24 00:01 UTC, yasker commented on chart/templates/postupgrade-job.yaml
> +        imagePullPolicy: IfNotPresent
https://github.com/longhorn/longhorn/issues/1986

2020-11-24 00:08 UTC, PhanLe1010 commented on chart/templates/postupgrade-job.yaml
> +        imagePullPolicy: IfNotPresent
Thank you. I was searching for `uninstall` keyword so I couldn't find the issue.

2020-11-24 00:09 UTC, PhanLe1010 commented on chart/templates/postupgrade-job.yaml
> +        imagePullPolicy: IfNotPresent
Linked

2020-11-24 00:13 UTC, PhanLe1010 commented on chart/questions.yml
> +  description: "The Kubernetes Secret name"
Thank you. Fixed

2020-11-24 01:16 UTC, yasker approved these changes

2020-11-24 01:16 UTC, merged