enhancement: Add a new enhancement 'enable backing file'
longhorn/longhorn pull request #2133
Opened 2020-12-23 13:30 UTC by shuo-wu

#2006

2020-12-24 02:54 UTC, yasker requested changes

2020-12-24 02:54 UTC, yasker commented on enhancements/20201223-enable-backing-file.md
> +    - Considering the disk migration and failed replica reusage features, for each backing file, the related CR is per disk rather than per node. In brief, there will be a CR for each backing file UR
One CR for each file on each disk? There can be tons of CRs then. How about one CR per image? Where the image should be downloaded to can be set in the spec of the CR as a map. The status of the CR can contain the status e.g. `downloaded`/`failed`/`in progress`.

2020-12-24 02:54 UTC, yasker commented on enhancements/20201223-enable-backing-file.md
> +8. Clean up all volumes.
Also try deleting the backing file before restore. Make sure the restore process downloads the backing file again.

2020-12-24 02:54 UTC, yasker commented on enhancements/20201223-enable-backing-file.md
> +No API change is required.
Can user remove backing file directly? We can provide a way to do that before the file reaches `CleanupTimeout`. Since those backing files are likely taking spaces, and it become invisible to the user in the current design. We do need a way to manage this resource.

Also, I am thinking instead of asking for URL everytime when a volume is created, can we ask user to `create/import` backing file, then choose the backing file during the volume creation. Though it will add additional burden to users if they want to restore a volume with backing file - or we can automatically add the backing file from specified URL to the system.

2020-12-24 02:55 UTC, yasker commented
Also, can we change the feature name to `backing image`? it sounds better than `backing file`.

2021-01-20 10:06 UTC, joshimoo commented on enhancements/20201228-enable-backing-image.md
> +    - Field `BackingImageDownloadState` is the key of map `Status.DiskStatusMap`. It can be `downloaded`/`downloading`/`failed`/`terminating`.
should this be value? key I am assuming is the disk/disk.name

2021-01-20 10:06 UTC, joshimoo commented on enhancements/20201228-enable-backing-image.md
> +    - Set a timestamp in backing image`Spec.DiskLastRefAtMap` when the backing image in the disk is used by no replica. Once the timeout `BackingImageCleanupTimeout` is passed, the backing image in t
Do we unset this field if after a while the backing image is used again?

2021-01-20 11:17 UTC, shuo-wu commented on enhancements/20201228-enable-backing-image.md
> +    - Set a timestamp in backing image`Spec.DiskLastRefAtMap` when the backing image in the disk is used by no replica. Once the timeout `BackingImageCleanupTimeout` is passed, the backing image in t
Yeah. The field will be unset in the node controller when there is a replica reusing the backing image in the disk.

2021-01-20 11:18 UTC, shuo-wu commented on enhancements/20201228-enable-backing-image.md
> +    - Field `BackingImageDownloadState` is the key of map `Status.DiskStatusMap`. It can be `downloaded`/`downloading`/`failed`/`terminating`.
Yeah. This is a typo. The key of this map is the disk UUID

2021-02-05 00:53 UTC, yasker commented on enhancements/20201228-enable-backing-image.md
> +
Have we implemented automatic image loading from CSI? If so, we can mention it here.

2021-02-05 00:54 UTC, yasker reviewed
LGTM in general. @joshimoo can you take a look as well?

2021-02-25 22:57 UTC, joshimoo approved these changes
LGTM, added some typos can be ignored.
Go ahead and merge this no need for me to rereview.

2021-02-26 03:57 UTC, merged