Add LEP for feature automatically upgrade engine for volumes
longhorn/longhorn pull request #2172
Opened 2021-01-11 21:03 UTC by PhanLe1010

longhorn/longhorn#2152

2021-01-11 21:03 UTC, PhanLe1010 commented
Please help to review the logic.
I will correct spelling and add test case later.

2021-01-11 22:07 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +  - upgradableFromEngineIMTags: ["v1.0.2", "v1.0.1", "v1.0.0", "v0.8.1", "v0.8.0"]
It seems that hard coding is not a good approach because we will have to modify/build manager code for every Longhorn release. I am thinking about using semantic version comparison to make sure that we only upgrade to newer engine image version and never downgrade.

2021-01-12 05:59 UTC, shuo-wu requested changes

2021-01-12 05:59 UTC, shuo-wu commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. If volume is a DR volume, the volume's robustness must be `healthy`
Notice that Longhorn will directly apply a full restore after upgrading a DR volume. I am not sure if we need to do the automatic live upgrade for DR/restore volumes.

Besides, we need to disable this for expanding volumes.

2021-01-12 05:59 UTC, shuo-wu commented on enhancements/20210111-upgrade-engine-automatically.md
> +  - upgradableFromEngineIMTags: ["v1.0.2", "v1.0.1", "v1.0.0", "v0.8.1", "v0.8.0"]
Why do we need these 2 lists? 
For detached volumes, we can directly do the offline upgrade without compatibility issues.
For attached volumes, if the latest engine image is compatible with the current instance manager an old volume is running on, Longhorn will directly do a live upgrade for it. And we can determine the compatibility by checking the version numbers in `InstanceManagerStatus` and `EngineImageStatus`.

2021-01-13 01:45 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +  - upgradableFromEngineIMTags: ["v1.0.2", "v1.0.1", "v1.0.0", "v0.8.1", "v0.8.0"]
Thank you! That makes sense. I was planned to use the list to prevent downgrading from a higher version to lower version incase something went wrong and user rollback to the previous deployment. However, hard coding is not a good idea. I will use [semantic version comparison](https://github.com/Masterminds/semver) instead

2021-01-14 00:45 UTC, yasker requested changes

2021-01-14 00:45 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +Add a new boolean setting, `Automatically Upgrade Engine When Possible`, so users can turn on/off this feature.
`Automatically Upgrade Engine to Default Version`

2021-01-14 00:45 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +Users only have to scale the workload down and up.
User shouldn't need to scale workload down and up. We will set the spec and it should be upgraded automatically once it's detached.

2021-01-14 08:55 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +Users only have to scale the workload down and up.
Thank you! 

I meant the same. Longhorn will retry upgrade engine when volume is detached (i.e. scale the workload down and up.)

We cannot set the spec because it will upgrade engine immediately.

2021-01-14 08:55 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +Add a new boolean setting, `Automatically Upgrade Engine When Possible`, so users can turn on/off this feature.
Thank you! Fixed

2021-01-14 23:48 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. If volume is a DR volume, the volume's robustness must be `healthy`
> Besides, we need to disable this for expanding volumes.

Thank you. Fixed

> Notice that Longhorn will directly apply a full restore after upgrading a DR volume. I am not sure if we need to do the automatic live upgrade for DR/restore volumes.

I think we should keep every thing up to date

2021-01-15 20:04 UTC, yasker requested changes

2021-01-15 20:04 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +      The current volume's instance manager image is the same as the new default instance manager image.
Does this mean that automatic live upgrade won't work if the instance manage image is upgraded as well? Not sure why it's needed.

2021-01-15 20:04 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +1. We will load balance the upgrading. Make sure not to upgrade too many volumes on the same node at the same time.
It's not called load balance. 

Also, need more details on how will we throttle the automated upgrade process (e.g. is there a customizable parameter or it's hardcoded. Sound like the parameter can be set to 0 to disable the automated engine upgrade process), and what will happen if the engine upgrade failed to complete.

2021-01-15 20:38 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +      The current volume's instance manager image is the same as the new default instance manager image.
Yeah, it is not needed. We didn't do this in the code PR. Updated the LEP

2021-01-15 20:39 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +1. We will load balance the upgrading. Make sure not to upgrade too many volumes on the same node at the same time.
Thank you. Fixed the name and added more details

2021-01-19 23:15 UTC, yasker requested changes

2021-01-19 23:15 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +1. The new default engine image is newer than the current volume's engine image in term of semantic version comparision
As we discussed, don't need version comparsion. As long as API version is compatible, we can do live upgrade. Otherwise we need to do offline upgrade. 

@shuo-wu API version doc is still on you: https://github.com/longhorn/longhorn/issues/1544 :)

2021-01-19 23:15 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +This enhancement is designed to for end users who use office image tags.
Shouldn't be necessary if we don't compare the image tag for version.

2021-01-19 23:15 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +   we just consider it is the same as volume is in upgrading process and skip it.
Should we have a fail-safe to stop auto-upgrade in case too many engine upgrades failed?

2021-01-19 23:15 UTC, yasker commented on enhancements/20210111-upgrade-engine-automatically.md
> +   We define a constant `maxConcurrentEngineUpgradingPerNode` which specifies the maximum number of upgrading engines on a node at a time.
`ConcurrentEngineUpgradePerNodeLimit`. And is this apply to the manual upgrade as well? Otherwise, we should call it `ConcurrentAutomaticEngineUpgradePerNodeLimit`.

2021-01-20 01:13 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +   we just consider it is the same as volume is in upgrading process and skip it.
In case there are many upgrades fails, the `concurrentAutomaticEngineUpgradePerNodeLimit` will server as a gate to stop the additional upgrade

2021-01-20 01:16 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +1. The new default engine image is newer than the current volume's engine image in term of semantic version comparision
Thank you. Fixed

2021-01-20 01:16 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +This enhancement is designed to for end users who use office image tags.
Thank you! Fixed

2021-01-20 01:16 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +   We define a constant `maxConcurrentEngineUpgradingPerNode` which specifies the maximum number of upgrading engines on a node at a time.
Thank you! Fixed

2021-01-20 15:53 UTC, joshimoo commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. Volume is not expanding
If I understood @shuo-wu correctly, this is an exclusion criteria.
So if the volume is attached (one of the cases) but it's expanding we should not do the upgrade.

So maybe something like this:
1. The volume condition is one of the following:
- XXX
- YYY
- ZZZ

2. And not one of the following:
- the volume is expanding

2021-01-21 18:58 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. Volume is not expanding
Sorry, I was not clear on this part. Fixed it to indicate that the volume condition is one of the 2 cases:
```
   1. Volume is in detached state.
   2. Volume is in attached state (live upgrade).
      And The current volume's engine image is compatible with the new default engine image.
      And If volume is a DR volume, the volume's robustness must be `healthy`
      And Volume is not expanding.
```
How do you think?

2021-01-28 03:53 UTC, shuo-wu requested changes

2021-01-28 03:53 UTC, shuo-wu commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. Volume is in attached state (live upgrade).
Add the condition: volume should be `healthy`

2021-01-28 03:53 UTC, shuo-wu commented on enhancements/20210111-upgrade-engine-automatically.md
> +### User Experience In Detail
Do we need to mention that users need to disable this if they want to update the engine image to a specific version for the volumes?

2021-01-28 03:53 UTC, shuo-wu commented on enhancements/20210111-upgrade-engine-automatically.md
> +      And volume is not expanding.
And volume is healthy

2021-01-28 04:05 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +   1. Volume is in attached state (live upgrade).
Thank you. Fixed

2021-01-28 04:05 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +### User Experience In Detail
Thank you. Fixed

2021-01-28 04:05 UTC, PhanLe1010 commented on enhancements/20210111-upgrade-engine-automatically.md
> +      And volume is not expanding.
Thank you. Fixed

2021-01-28 07:06 UTC, shuo-wu approved these changes

2021-01-29 19:37 UTC, yasker approved these changes

2021-01-29 19:37 UTC, merged