Update default share-manager image to v1_20210106
longhorn/longhorn pull request #2173
Opened 2021-01-13 00:56 UTC by joshimoo

We switched from fedora to an ubuntu base image, to support the security
scanner.

longhorn/longhorn#2111

Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

2021-01-13 04:46 UTC, yasker requested changes
Also need to change https://github.com/longhorn/longhorn/blob/master/chart/questions.yml#L68

2021-01-19 16:53 UTC, joshimoo commented
Updated to pr and switched the base to master, so it's available on all future dev builds.

2021-01-19 19:35 UTC, yasker commented
This should be for v1.1.1 branch, otherwise, all the users using master will start using the image immediately.

2021-01-19 21:52 UTC, joshimoo commented
changed to v1.1.1

2021-01-19 22:55 UTC, yasker approved these changes

2021-01-19 22:55 UTC, merged