Add LEP for rwx feature
longhorn/longhorn pull request #2196
Opened 2021-01-19 17:14 UTC by joshimoo

longhorn/longhorn#1470

Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

2021-01-19 23:05 UTC, yasker requested changes

2021-01-19 23:05 UTC, yasker commented on enhancements/20201220-rwx-volume-support.md
> +### NFS ganesha Active Passive Setups
!!! Great find!

2021-01-19 23:05 UTC, yasker commented on enhancements/20201220-rwx-volume-support.md
> +- Volume controller is responsible for creation of share manager crd and synconising share status and endpoint of the volume with the share manager resource.
The implementation detail is too brief... We don't even mention how share manager pod mapping to the volume, and how the failure recovery works.

2021-02-16 18:52 UTC, joshimoo commented on enhancements/20201220-rwx-volume-support.md
> +- Volume controller is responsible for creation of share manager crd and synconising share status and endpoint of the volume with the share manager resource.
Thanks added more details to the implementation section, please let me know if it is to much detail or additional clarification is required.

2021-02-16 21:57 UTC, yasker commented on enhancements/20201220-rwx-volume-support.md
> +- Volume controller is responsible for creation of share manager crd and synconising share status and endpoint of the volume with the share manager resource.
LGTM now.

2021-02-16 21:57 UTC, yasker approved these changes

2021-02-16 21:57 UTC, merged