enhancement: Add a new LEP 'enhanced-cpu-reservation'
longhorn/longhorn pull request #2213
Opened 2021-01-25 12:19 UTC by shuo-wu

#2207

2021-01-25 17:47 UTC, yasker requested changes

2021-01-25 17:47 UTC, yasker commented on enhancements/20210125-enhanced-cpu-reservation.md
> +        - For the existing/upgraded Longhorn cluster, both the old setting value and the new setting values will be set. However, the new settings will be applied only if the old setting value become
`will be crashed unexpectedly?`

How does the upgrade process work exactly?

2021-01-25 17:47 UTC, yasker commented on enhancements/20210125-enhanced-cpu-reservation.md
> +1. Add 2 new settings `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU`.
`Guaranteed Engine Instance Manager CPU` and so on.

Are we going to have a node-specific setting?

What's going to happen if the percentage is too large for certain nodes that have too many CPU reserved workloads? Kubernetes's scheduling will fail.

2021-02-12 00:53 UTC, yasker requested changes
I have some doubts regarding the upgrade path.

2021-02-22 04:55 UTC, shuo-wu commented on enhancements/20210125-enhanced-cpu-reservation.md
> +              2. Find a chance that allows detaching all volumes. If there is no chance to detach all volumes, please modify the new settings or the node fields so that the requested CPUs for the ins
OK. Considering the worker node CPUs may be different, Longhorn can set the new fields of the node spec automatically to the old value of `Guarantee Engine CPU`. Then users don't need to worry about the old setting at all after the upgrade.

2021-02-25 21:35 UTC, yasker approved these changes
LGTM. @joshimoo can you review as well?

2021-02-26 00:32 UTC, joshimoo approved these changes
LGTM, we should consider treating the two values independent of each other instead of validating the sum of both.

2021-02-26 00:32 UTC, joshimoo commented on enhancements/20210125-enhanced-cpu-reservation.md
> +    - Make sure the sum of the 2 setting values should be smaller than 40 (%).
Mentioned this in the PR review https://github.com/longhorn/longhorn-manager/pull/828
Should we treat them independent of each other instead of validating the sum of both?

Thinking about the dedicated storage node setup, where it should be totally valid to request 40% replicas on the storage nodes.

And 40% engine on the workload nodes.

2021-02-26 00:32 UTC, joshimoo commented on enhancements/20210125-enhanced-cpu-reservation.md
> +1. Add 2 new settings `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU`.
Mention that these are in decimal percentages in the range 0 to 40

2021-02-26 00:32 UTC, joshimoo commented on enhancements/20210125-enhanced-cpu-reservation.md
> +Add a new field `EngineManagerCPURequest` and `ReplicaManagerCPURequest` for node objects.
Mention that these are milli values, can be down in the implementation details.

2021-03-08 04:53 UTC, innobead approved these changes
LGTM

2021-03-08 06:23 UTC, merged