Add support for ingressClassName in helm chart
longhorn/longhorn pull request #2258
Opened 2021-02-15 23:59 UTC by Diaoul

This PR adds support for `ingressClassName` on `Ingress` object.

See related [blog post](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)

Fixes #2257

2021-03-25 21:04 UTC, meldafrawi approved these changes
LGTM

2021-03-31 01:54 UTC, innobead requested changes
LGTM, but a minor suggest to fix.

2021-03-31 01:54 UTC, innobead commented on chart/values.yaml
> +  #ingressClassName: nginx-internal
Suggest uncomment the setting but have it empy or nil value instead.

`ingressClassName: ""` or `ingressClassName: ~`

2021-03-31 05:56 UTC, innobead approved these changes
Thanks for the contribution!

The DCO check failed, please help make sure you use signoff for the commit. Thanks.

https://github.com/longhorn/longhorn/pull/2258/checks?check_run_id=2234149369

2021-03-31 07:44 UTC, andyjeffries commented
> Thanks for the contribution!
> 
> @andyjeffries the DCO check failed, please help make sure you use signoff for the commit. Thanks.

Huh? What did I do here?

2021-03-31 07:52 UTC, innobead commented
@Diaoul 

Because the master is used for the stable version only, please help create another PR based on v1.1.1 into v1.1.1 branch instead. Thanks!

2021-03-31 17:09 UTC, Diaoul commented
Should be ok now. Let me know if there is anything else.

2021-04-01 03:46 UTC, innobead approved these changes

2021-04-01 03:47 UTC, merged