Add LEP for live migration feature
longhorn/longhorn pull request #2266
Opened 2021-02-19 23:02 UTC by joshimoo

Longhorn #2127

Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

2021-02-25 21:32 UTC, yasker requested changes
The implementation details part looks good. Though need a better summarization at the beginning.

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +The Summary section is incredibly important for producing high quality user-focused documentation such as release notes or a development roadmap.
?

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- use attach/detach flow to implement migration interactions
The goal is to support the VM live migration. Then we can start talking details a little more.

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- run a migration engine for a volume in RWX access mode that is marked as `migratable`
This is implementation details, not goal.

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- only allow volumes during migration to be mounted in block device mode on a pod
Raw block device mode you meant? or are you referring to `RWO` vs `RWX`?

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- HA support for NFS shared volumes
? Why we want to mention it here?

2021-02-25 21:32 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +We only want to support this for block device mode, since we don't support concurrent writes and having kubernetes mount a filesystem even in read only
So you meant `raw block device` mode. 
```
You can set the value of volumeMode to Block to use a volume as a raw block device.
```
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode

2021-02-26 13:29 UTC, shuo-wu requested changes

2021-02-26 13:29 UTC, shuo-wu commented on enhancements/20210216-volume-live-migration.md
> +https://github.com/longhorn/longhorn-manager/pull/822
Remove this line

2021-02-26 13:29 UTC, shuo-wu commented on enhancements/20210216-volume-live-migration.md
> +- only allow volumes during migration to be mounted in block device mode on a pod
Or `BlockVolume` mode vs `Filesystem` mode?

2021-02-26 13:29 UTC, shuo-wu commented on enhancements/20210216-volume-live-migration.md
> +#### Testing Kubevirt VM live migration
It seems that the test steps and the user experience are mixed up... It's good to tell us how to test this feature with Harvester in detail. But I think it's better to put it in the test part

2021-02-26 13:29 UTC, shuo-wu commented on enhancements/20210216-volume-live-migration.md
> +- volume detach call now expects a `detachInput { hostId: "" }` if `hostId==""` it will be treated as detach from all nodes same behavior as before.
Add more explanations about the changed API `attach` and `detach`. e.g.:

For `attach`,
  1. If a volume is mode `RWO`, ......
  2.If a volume is mode `RWX` (NFS), ......
  3. If a volume is mode `RWX` (Migratable), migration means this attached volume receives a attach request to a different node.

For detach,
  1. If a volume is mode `RWO`, ......
  2.If a volume is mode `RWX` (NFS), ......
  3. If a volume is mode `RWX` (Migratable), migration confirmation means this attached volume receives a detach request that requires detaching from the 1st node. And migration rollback means this attached volume receives a detach request that requires detaching from the 2nd node

2021-02-26 13:29 UTC, shuo-wu commented on enhancements/20210216-volume-live-migration.md
> +#### Volume migration flow
This part maybe not straightforward enough if the reader hasn't reviewed the actual implementation.
Can you check if the following description is better?
1. Users launch a new VM with a new migratable Longhorn volume -> A migratable volume is created then attached to node1. Similar to regular attachment, Longhorn will set `v.spec.nodeID` to `node1` here.
2. Users launch the 2nd VM (pod) with the same Longhorn volume -> 
    1. Kubernetes requests the (attached) volume attaching to node2. Then Longhorn receive the attach call and set `v.spec.migrationNodeID` to `node2` with `v.spec.nodeID = node1`.
    2. Longhorn volume-controller brings up the new engine on node2, with inactive matching replicas (same as live engine upgrade)
    3. Longhorn CSI driver polls for the existence of the second engine on node2 before acknowledging attachment success.
3. Once the migration (actually the 2nd attachment succeeded/failed), the following detach decides whether migration is completed successfully, or a migration rollback is desired:
    1.  If succeeded:...
    2. If failed:....
4. Longhorn volume controller then cleans up the second engine and switches the active replicas to be the current engine ones.

2021-03-01 17:41 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +#### Testing Kubevirt VM live migration
The only user of this feature should be Harvester, there is to many things that can go wrong if it's used outside of that context.

2021-03-01 17:53 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +- HA support for NFS shared volumes
changed to
### Non-goals
- using multiple engines for faster volume failover

2021-03-01 17:54 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +We only want to support this for block device mode, since we don't support concurrent writes and having kubernetes mount a filesystem even in read only
Changed to
We only support this for a volume while it is used with `volumeMode=BLOCK`

2021-03-01 17:54 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +- only allow volumes during migration to be mounted in block device mode on a pod
changed to
### Goals
- support harvester VM live migration

2021-03-01 17:54 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +- run a migration engine for a volume in RWX access mode that is marked as `migratable`
removed

2021-03-01 17:55 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +- use attach/detach flow to implement migration interactions
done

2021-03-01 17:55 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +The Summary section is incredibly important for producing high quality user-focused documentation such as release notes or a development roadmap.
replaced with:
To enable Harvester to utilize Kubevirts live migration support, we need to allow for volume live migration,
so that a Kubevirt triggered migration will lead to a volume migration from the old node to the new node.

2021-03-01 17:56 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +- volume detach call now expects a `detachInput { hostId: "" }` if `hostId==""` it will be treated as detach from all nodes same behavior as before.
Implementation detail, that is subject to change down the line.
Not sure if it makes sense to include that detail in a document that will not be updated.

2021-03-01 18:27 UTC, joshimoo commented on enhancements/20210216-volume-live-migration.md
> +#### Volume migration flow
thanks, included this form of a description.

2021-03-01 19:11 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- only allow volumes during migration to be mounted in block device mode on a pod
`Support Harvester VM live migration`.

2021-03-01 19:12 UTC, yasker commented on enhancements/20210216-volume-live-migration.md
> +- HA support for NFS shared volumes
`using multiple engines for faster volume failover for other scenarios than live migration`.

2021-03-02 03:05 UTC, joshimoo commented
updated the LEP to adress review feedback.

2021-03-02 03:08 UTC, yasker approved these changes
LGTM. @shuo-wu ?

2021-03-02 06:08 UTC, shuo-wu approved these changes

2021-03-02 06:10 UTC, shuo-wu commented
vv `Merging is blocked` vv

2021-03-02 16:25 UTC, merged