chart: Update chart for the enhanced backing image feature
longhorn/longhorn pull request #2443
Opened 2021-04-05 11:56 UTC by shuo-wu

Longhorn #2295

2021-04-05 12:04 UTC, shuo-wu commented
Will update this PR when a tag like `v20210405` is created for `longhornio/backing-image-manager`

2021-04-06 17:32 UTC, innobead commented
@shuo-wu please rebase the code and remove the draft for ready-for-review. Thanks.

2021-04-07 03:52 UTC, shuo-wu commented
Updated. I have tested it. It's ready for review.

2021-04-07 05:06 UTC, innobead requested changes
LGTM, just need to update the image tag.

2021-04-07 05:06 UTC, innobead commented on chart/values.yaml
> +      tag: master
need to have a tag for the image instead of master

2021-04-07 05:06 UTC, innobead commented on chart/questions.yml
> +    default: master
same here

2021-04-07 06:07 UTC, innobead approved these changes

2021-04-07 06:08 UTC, merged

2021-04-07 06:13 UTC, PhanLe1010 reviewed
LGTM. 
Left a comment

2021-04-07 06:13 UTC, PhanLe1010 commented on chart/templates/crds.yaml
> +    additionalPrinterColumns:
Do we want to include the  `.status.currentState` as other CRD?

2021-04-07 06:18 UTC, shuo-wu commented on chart/templates/crds.yaml
> +    additionalPrinterColumns:
It's nice to have. Let me add it with a new PR.

2021-04-07 06:21 UTC, PhanLe1010 commented on chart/templates/crds.yaml
> +      jsonPath: .spec.image
A quick quesition, any reason that we prefer `.spec.image` instead of `.status.currentImage` as other CRDs?

2021-04-07 06:26 UTC, shuo-wu commented on chart/templates/crds.yaml
> +      jsonPath: .spec.image
when I use a newer version of the backing image manager, we will directly create new CRs for the new version. In other words, we won't modify `spec.image` then we don't need `status.currentImage`. Same for InstanceManager and ShareManager.

2021-04-07 06:27 UTC, PhanLe1010 commented on chart/templates/crds.yaml
> +      jsonPath: .spec.image
I see. Thanks