Make service ipFamilies configurable
longhorn/longhorn pull request #2451
Opened 2021-04-07 18:32 UTC by poksiala

Signed-off-by: Panu Oksiala <panu@oksiala.fi>

2021-04-13 00:53 UTC, jenting commented
Thank you for your contribution @poksiala
I'll review and test it this week.

2021-04-16 07:27 UTC, jenting reviewed
@poksiala comment left

2021-04-16 07:27 UTC, jenting commented on chart/templates/deployment-ui.yaml
> +  type: {{ .Values.service.ui.type }}
Is this line duplicated?

2021-04-28 03:15 UTC, jenting commented on chart/templates/deployment-ui.yaml
> +  type: {{ .Values.service.ui.type }}
@poksiala would you mind taking a look at the comment I left?

2021-04-30 07:45 UTC, poksiala commented on chart/templates/deployment-ui.yaml
> +  type: {{ .Values.service.ui.type }}
Hey sorry I did not get a notification about your earlier message. I'll fix this a it later today.

2021-04-30 10:11 UTC, jenting commented on chart/templates/deployment-ui.yaml
> +  type: {{ .Values.service.ui.type }}
Many thanks @poksiala

2021-05-04 02:59 UTC, jenting commented
Thank you @poksiala. Would you mind add DCO to the latest commit?

2021-05-04 02:59 UTC, jenting requested changes
Thank you @poksiala. Would you mind add DCO to the latest commit?

2021-05-05 06:24 UTC, poksiala commented
> Thank you @poksiala. Would you mind add DCO to the latest commit?

Do you mean signing the commit? I can do it in few hours once I get to my PC

2021-05-05 06:28 UTC, jenting commented
> > Thank you @poksiala. Would you mind add DCO to the latest commit?
> 
> Do you mean signing the commit? I can do it in few hours once I get to my PC

Yes, please.

2021-05-05 14:54 UTC, poksiala commented
> > > Thank you @poksiala. Would you mind add DCO to the latest commit?
> > 
> > 
> > Do you mean signing the commit? I can do it in few hours once I get to my PC
> 
> Yes, please.

Done!

2021-05-05 14:56 UTC, jenting approved these changes
LGTM, thank you @poksiala

2021-05-06 02:03 UTC, shuo-wu commented
Notice that this feature is announced beta version in v1.21. And the prerequisite is v1.20. Is it OK to merge this PR now?
https://kubernetes.io/docs/concepts/services-networking/dual-stack/#prerequisites

2023-12-12 04:52 UTC, innobead commented
This PR has been pending for a while. Closing first, and feel free to continue if you want.

2023-12-12 04:52 UTC, closed without merging