Add LEP - automatic rebalance replica
longhorn/longhorn pull request #2581
Opened 2021-05-10 05:44 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/587

2021-05-11 10:36 UTC, innobead requested changes
LGTM, some comments waiting to resolve.

Another concern is when the replicas get deleted for automatic rebalancing, does it mean the snapshots of the deleted replicas will be left over in the original nodes?

If yes, this probably will cause some extra resource usage overhead, probably we need to tackle it in another ticket. I remember users have some requests for that to clean up the leftover snapshots.

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +Have a Longhorn setting to enable automatic distribution of the off-balanced replicas when a new node is added to the cluster.
```suggestion
Have a Longhorn setting to enable automatic distribution of the off-balanced replicas when a newly available node to the cluster
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +Currently, the user needs to be aware when nodes are offline and a new node is added back to the cluster to manually delete the replicas to rebalance onto the new node.
```suggestion
Currently, the user needs to be aware when nodes are offline and a new node is added back to the cluster to manually delete the replicas to rebalance onto the newly available node.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +This enhancement proposes to add a new Longhorn setting `Replica Node Level Auto Balancing` to enable detection and deletion of the unbalanced replica to achieve automatic rebalancing.
```suggestion
This enhancement proposes is to add a new Longhorn setting `Replica Node Level Auto Balancing` to enable detection and deletion of the unbalanced replica to achieve automatic rebalancing.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +Have a Support replica auto balance.
```suggestion
Support replica automatic balancing.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +Add new setting `Replica Node Level Auto Balancing` to trigger replica deletion when a new node is available to cluster.
```suggestion
Add new setting `Replica Node Level Auto Balancing` to enable replica automatic balancing when a newly available node to the cluster.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +Before this enhancement user needs to check and manually delete replicas to have replicas schedule to the new node. If the user does not take action, this could lead to no redundancy volumes.
```suggestion
Before this enhancement, the user needs to check and manually delete replicas to have deleted replicas reschedule to newly available nodes. If the user does not take action, this could lead to no redundancy volumes.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +After this enhancement user does not need to worry about manually balancing replicas when nodes are offline.
```suggestion
After this enhancement, the user does not need to worry about manually balancing replicas when there are newly available nodes.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and comes back online after some time, I want Longhorn to automatically detect and schedule replicas evenly to all nodes.
```suggestion
When a cluster node is offline and comes back online after some time, I want Longhorn to automatically detect and reschedule replicas evenly to all nodes.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +So I do not have to worry and standby 24/7 to check and manually rebalance replicas when nodes are down.
```suggestion
So I do not have to worry and standby 24/7 to check and manually rebalance replicas when there are newly available nodes.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and a new cluster is added, I want Longhorn to automatically detect and schedule replicas evenly to all nodes
```suggestion
When a cluster node is offline and a new cluster is added, I want Longhorn to automatically detect and reschedule replicas evenly to all nodes
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +So I do not have to worry and standby 24/7 to check and manually rebalance replicas when nodes are down.
```suggestion
So I do not have to worry and standby 24/7 to check and manually rebalance replicas when there are newly available nodes.
```

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +There is no API change
Actually, we have the contract change for the new setting.

2021-05-11 10:36 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +1. Add new setting `Replica Node Level Auto Balancing`.
What's the default value? If enabled, any side effects or notice users need to be aware of.

2021-05-11 10:57 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Have a Longhorn setting to enable automatic distribution of the off-balanced replicas when a new node is added to the cluster.
Fixed.

2021-05-11 10:58 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Currently, the user needs to be aware when nodes are offline and a new node is added back to the cluster to manually delete the replicas to rebalance onto the new node.
Fixed.

2021-05-11 10:58 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Have a Support replica auto balance.
Fixed.

2021-05-11 11:02 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Add new setting `Replica Node Level Auto Balancing` to trigger replica deletion when a new node is available to cluster.
Fixed.

2021-05-11 11:02 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Before this enhancement user needs to check and manually delete replicas to have replicas schedule to the new node. If the user does not take action, this could lead to no redundancy volumes.
Fixed.

2021-05-11 11:03 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and comes back online after some time, I want Longhorn to automatically detect and schedule replicas evenly to all nodes.
Fixed.

2021-05-11 11:03 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and a new cluster is added, I want Longhorn to automatically detect and schedule replicas evenly to all nodes
Fixed.

2021-05-11 11:04 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +So I do not have to worry and standby 24/7 to check and manually rebalance replicas when nodes are down.
Fixed.

2021-05-12 01:37 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +There is no API change
Thank you for point out. I think we can use /v1/settings, updated the PR.

2021-05-12 01:46 UTC, c3y1huang commented
> I previously left a comment on how to improve replica deletion, to ensure that the data is cleaned up by utilizing a finalizer on the replica CR. ref [#685 (comment)](https://github.com/longhorn/longhorn/issues/685#issuecomment-817121946)

Thank you @joshimoo for pointing out, I've added to non-goal to be tackled separately.

2021-05-12 04:05 UTC, shuo-wu requested changes
1. This feature is a little bit similar to the data locality feature. The main difference is that the data locality requires the new replica to be scheduled to a specific node but this feature requires the new replica to be scheduled to a list of nodes on which there is no replica for the volume.
2. Notice that you plan to delete the redundant replica before the new replica rebuilding. This will lead to the volume becoming `degraded`, which is not recommended. Even though most of the time the redundant replica is not meaningful for the HA.
3. The modification for ReplicaController is not right:
    1. ReplicaController should not update volume status. A controller's responsibility is to update the **status** of its own CRs and the **spec** of other CRs. 
    2. The scheduling-related checking happens in VolumeController. Since Longhorn knows all replicas in the VolumeController sync loop, there is no need to add a new field `volume.status.rebalanceReplicas`.
    3. I am not sure why you use `HealthyAt` to determine which replica should be deleted. I think we can randomly remove a replicate one.
4. Besides node offline and new node adding, there is one more case that would trigger this feature: node becoming schedulable/unschedulable.
5. Do we need to introduce the per volume spec for this feature? I mean, we can allow users to enable this feature for specific volumes by adding a new volume spec.

In general, I think you can refer to the design of the data locality feature.

2021-05-12 04:50 UTC, c3y1huang commented
Thank you @shuo-wu for the review and comment.

Moving this to draft to work on.

2021-05-12 05:40 UTC, shuo-wu commented
BTW, the current design for the data locality feature maybe not perfect since the flow is a little bit complicated IIRC. If you have any better ideas, please share with us.

2021-05-18 05:29 UTC, shuo-wu requested changes

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +
Besides, there is a new field in volume resources.

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +  - The default value is nil.
The default value is `false`

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +    1. Record replica names if DiskID is duplicated for the volume.
`DiskID`? or you mean the related Node?

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +    2. Find the number of volume owners.
What are `volume owners`? The nodes that contain the running volume replicas?

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +```
Why using ``` to wrap the test steps... Same below.

2021-05-18 05:29 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +Given cluster with 3 nodes
Add step number for manual tests. e.g.:

1. Given cluster with 3 nodes and Longhorn setting
```
kubectl -n longhorn-system --type=merge patch settings/replica-soft-anti-affinity -p '{"value": "true"}'
kubectl -n longhorn-system get settings/replica-soft-anti-affinity
kubectl -n longhorn-system --type=merge patch settings/replica-replenishment-wait-interval -p '{"value": "1"}'
kubectl -n longhorn-system get settings/replica-replenishment-wait-interval
kubectl -n longhorn-system --type=merge patch settings/replica-auto-rebalance -p '{"value": "true"}'
kubectl -n longhorn-system get settings/replica-auto-rebalance
```
2. Create a Pod using a 3-replica Longhorn volume on `node-1`
......

2021-05-18 07:07 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Given cluster with 3 nodes
I think we would benefit to adopt to BDD-style Given/When/Then when writing tests. This gives a clearer way to show the prepare/test/result phases. It's currently looking a bit confusing because integration tests are using steps, so I will change them as well.

2021-05-19 01:46 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +```
Addressed.

2021-05-19 12:11 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +  - The default value is nil.
Addressed.

2021-05-19 12:12 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +    1. Record replica names if DiskID is duplicated for the volume.
Thank you for the hint. Updated to use Node ID instead.

2021-05-19 12:12 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +    2. Find the number of volume owners.
Thank you for the hint. Updated to use Node ID instead.

2021-05-19 12:15 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +
Thanks, fixed.

2021-05-20 03:17 UTC, shuo-wu requested changes

2021-05-20 03:17 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
Min{number of replicas in volume spec - number of occupied node zones, number of zones contains schedulable nodes - number of occupied node zones}

Similar below

2021-05-20 03:17 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +  5. Return the number of available nodes if less than the number to rebalance, or return the number to rebalance.
The auto rebalance should happen during the calculation. Is returning this number meaningful?

Similar below

2021-05-20 03:17 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - When the number of running replica is less than the number of replicas in volume spec.
You can consider this (volume `healthy`) as a prerequisite rather than checking it during the auto rebalance.

2021-05-20 03:17 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +      - global setting `Replica Zone Level Soft Anti-Affinity` is `False`.
With this limitation, can Longhorn do auto rebalance for the following case:

1. `Replica Zone Level Soft Anti-Affinity` is `True`. 
2. There are 3 replicas and 2 zones. And 2 replicas are in the same zone and even on the same node.
3. Add a new node to the above zone that contains 2 replicas.

2021-05-20 11:33 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +  - The default value is `False`.
Thanks for noticing, I think it's better to use `replicaAutoBalance` with the available value of `enabled` and `disabled` to avoid confusion and the default value will be the same as the global setting.

2021-05-20 11:35 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +  2. Skip volume replica rebalance when volume spec `DisableReplicaRebalance` is `True`.
Thanks, removed the global setting check, I think it's better to check only volume spec.

2021-05-20 11:37 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +      - global setting `Replica Zone Level Soft Anti-Affinity` is `True`.
Thanks for catching this, I think it should be safe to remove the condition, so it will always check for zone first.

2021-05-20 11:38 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +      - global setting `Replica Zone Level Soft Anti-Affinity` is `True`.
I've also included this scenario in integration tests.
```
Scenario: replica auto-balance to different zone when zone anti-affinity is disabled.
```

2021-05-20 11:39 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
I do not understand this. Can you elaborate?

2021-05-20 11:45 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +  5. Return the number of available nodes if less than the number to rebalance, or return the number to rebalance.
The plan is to add the returned as part of 
[replenishCount](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1501).

2021-05-20 11:49 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +      - global setting `Replica Zone Level Soft Anti-Affinity` is `False`.
Replica auto-balance will look for available nodes if cannot find an available zone.

I've included this scenario in the integration tests.
```
Scenario: replica auto-balance to same zones when zone anti-affinity is enabled.
```

2021-05-20 12:09 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - When the number of running replica is less than the number of replicas in volume spec.
Good suggestion. Addressed.

2021-05-20 14:30 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
[4.] is only part of the formula. 

Take your case with the volume with 5 replicas:

Case-1:
If there is no new zone added, it will return 0 to rebalance, because both zones contain running replicas, and nodes within zone-A and zone-B will not be counted as the available nodes.
```
2. List all available nodes with conditions: 
- node zone not duplicated with any of the current running replicas.
3. Do nothing:
     - When available nodes list is empty.
```

Case-2:
If zone-C is then added with 2 replicas then the replicas to rebalance would return 1.

Case-3:
if 4 zones are added, then the replicas would return 3.

2021-05-21 04:08 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +  - The default value is `False`.
To totally avoid confusion or misunderstanding, this field can be an enum with 3 options: `enabled`, `disabled`, and `follow the global setting`/`ignored`.

2021-05-21 04:37 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
OK. This calculation is complicated. I am thinking if we can directly use the following logic:

1. List available zones (contains node schedulable for the volume replicas):
    1. Reschedule the node-level duplicates replica to one node of each available zone
    2. If the node-level duplicates replica count is 0, then reschedule the zone-level duplicates replica to one node of each available zone.
2. List available nodes (that doesn't contain the volume replica but is schedulable for the replicas):
    1. Reschedule the node-level duplicates replica to one node of each available zone.

This avoids the calculation while getting the final rebalance result.

2021-05-21 05:12 UTC, innobead requested changes

2021-05-21 05:20 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +- When creating a new volume, the body of the request sent to /v1/volumes has a new field `replicaAutoBalance` set to `disabled` or `enabled`.
After the explanation by @c3y1huang , we need a way to determine if the value set by the user or not.

2021-05-21 05:21 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Manual tests - 1 node offline, 2 node online
Probably we don't need manual test cases here, because they are similar to the test cases described in the integration tests. (you can add some manual test cases for QA if need)

2021-05-21 06:21 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Manual tests - 1 node offline, 2 node online
Removed.

2021-05-21 06:22 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Manual tests - 1 node offline, 2 node online
Manual tests removed.

2021-05-21 06:24 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +And zone-1 and zone-2 should contain 3 replica in total.
Fixed.

2021-05-21 07:02 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Scenario: replica auto-balance to same zones when zone anti-affinity is enabled.
Addressed.

2021-05-21 07:02 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Scenario: replica auto-balance to different zone when zone anti-affinity is disabled.
Addressed.

2021-05-21 07:03 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Scenario: replica auto-balance with zone anti-affinity enabled.
Addressed.

2021-05-21 07:03 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Add new volume spec `replicaAutoBalance` to enable/disable automatic replica rebalancing for individual volume.
Addressed.

2021-05-21 07:03 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +And Wait for replicas to re-schedule to node-1, node-2.
Addressed.

2021-05-21 07:04 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +1. When the user enabled `replica-soft-anti-affinity` and `replica-zone-soft-anti-affinity` and deployed PVC and deployment. The replica is distributed evenly to all 2 zones at this point.
Addressed.

2021-05-21 07:04 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +2. In case of node-2 is offline, the user will see replica was on node2 gets re-scheduled to node-1 or node-3. And also icon and note will appear on UI `Limited node redundancy: at least one healthy
Addressed.

2021-05-21 07:04 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +1. When the user enabled `replica-soft-anti-affinity` and deployed PVC and Pod on node-1. The replica is distributed evenly to all 3 nodes at this point.
Addressed.

2021-05-21 07:04 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and a new cluster is added, I want Longhorn to automatically detect and reschedule replicas evenly to some volumes only.
Addressed.

2021-05-21 07:05 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +When a cluster node is offline and a new cluster is added, I want Longhorn to automatically detect and reschedule replicas evenly to all nodes
Addressed.

2021-05-21 07:05 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Story 3 - replica automatic rebalance for individual volume
Addressed.

2021-05-21 07:05 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Story 2 - zone offline
Addressed.

2021-05-21 07:06 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Add new global setting `Replica Auto Balance` to enable replica automatic balancing when a node is newly available to the cluster.
Addressed.

2021-05-21 07:06 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Support individual volume replica automatic balancing.
Addressed.

2021-05-21 07:07 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +Have a Longhorn global setting and volume spec to enable/disable automatic distribution of the off-balanced replicas when a node is newly available to the cluster.
Addressed.

2021-05-21 07:08 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +This enhancement proposes is to add a new Longhorn global setting `Replica Auto Balance` to enable detection and deletion of the unbalanced replica to achieve automatic rebalancing. And this enhancem
Addressed.

2021-05-21 08:12 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
Removed affinity settings conditions.

2021-05-21 10:16 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
I mean, with the above simple flow, we can avoid considering so many conditions and calculating the rebalance number separately. Not sure if it make sense for you.

2021-05-21 10:54 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +  - The default value is `False`.
The `ignore` option sounds good to me. And will also try to replace `enable` with `least-effort` and `best-effort`.

2021-05-21 11:05 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Story 3 - zone offline
```suggestion
#### Story 3 - zone temporary offline
```

2021-05-21 11:11 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Story 3 - zone offline
Fixed.

2021-05-24 11:40 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
To put it simply, rebalance is done in 2 phases, rebalance zones then rebalance nodes. This from my understanding is similar to your statement. I've reworded the implementation so hopefully takes away the distractions of the conditions.

As for affinity settings, it will be ignored to leave for ReplicaScheduler to handle.

2021-05-25 03:07 UTC, shuo-wu approved these changes
LGTM

2021-05-25 03:07 UTC, shuo-wu commented on enhancements/20210510-automatic-rebalance-replica.md
> +     - number of replicas in volume spec - number of occupied node zones.
Nice rewording. It's much clear now.

2021-05-25 03:09 UTC, innobead approved these changes

2021-05-25 03:13 UTC, innobead approved these changes
LGTM, just one minor change needed

2021-05-25 03:13 UTC, innobead commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Integration tests - test_replica_auto_balance_least_effort
zone_least_effort

2021-05-25 04:07 UTC, c3y1huang commented on enhancements/20210510-automatic-rebalance-replica.md
> +#### Integration tests - test_replica_auto_balance_least_effort
Fixed.

2021-05-25 04:12 UTC, c3y1huang commented
Updated the integration test steps.

2021-05-25 04:21 UTC, merged