Asynchronous pull backup volumes into cluster CR
longhorn/longhorn pull request #2623
Opened 2021-05-25 08:41 UTC by jenting

#### Issues

#1955
#2536
#2543

2021-05-25 20:01 UTC, joshimoo commented
related #1761 I have some code stashed somewhere where I started on creating CR for backups, not sure how useful that code still is today :)

2021-05-26 09:52 UTC, shuo-wu requested changes

2021-05-26 09:52 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +We'll create a new Custom Resource Definition (CRD) called _backups`_ to save pulled backup volumes and its historical volume backups as the Custom Resource (CR).
Can you talk more about this CRD?
Will Longhorn create one CR for each backup or backup volume record in the external backupstore? After reading this LEP, I still have no basic picture about this new CRD

2021-05-26 09:52 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +There is already a backup store monitor that runs as a timer, the timer period is the setting `backupstore-poll-interval`. Within it, it runs:
1. Need to consider the modification of the backup target setting. If the setting is changed, all CRs should be removed, right?
2. Need to think about the CR update conflict, and how Longhorn balances the below workload to all workers of all nodes. Do we need a new controller for the new CRD?

2021-05-26 12:02 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +We'll create a new Custom Resource Definition (CRD) called _backups`_ to save pulled backup volumes and its historical volume backups as the Custom Resource (CR).
I've updated it.

2021-05-26 13:07 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +There is already a backup store monitor that runs as a timer, the timer period is the setting `backupstore-poll-interval`. Within it, it runs:
> 1. Need to consider the modification of the backup target setting. If the setting is changed, all CRs should be removed, right?

I'd prefer to remove it when running synchronous in the controller, that is:
- Backup Volume:
1. Pull the backup volumes that are in the backup store and aren't in the cluster CR, create a new CR.
2. Delete the backup volumes that are in the cluster CR and aren't in the backup store, delete the CR.
- Volume Backups:
1. Calculate the difference set of the volume backups that are in the backup store and aren't in the cluster CR, add it to the backup volume CR's `spec.backups`.
2. Calculate the difference set of the volume backups that are in the cluster CR and aren't in the backup store, delete it from the backup volume CR's `spec.backups`
3. Update the backup volume CR

> 2. Need to think about the CR update conflict, and how Longhorn balances the below workload to all workers of all nodes. Do we need a new controller for the new CRD? I think Joshua mentions some ideas in a Github ticket. You can refer to it first.

Now, the backup store monitor running as a goroutine in the setting controller. My current thought is to keep it as-is.
I'm fine to create a new controller _or_ keep it in the current setting controller. WDYT?

I don't fully understand the question `how Longhorn balances the below workload to all workers of all nodes`. But I'll try to answer my understanding. The current [code](https://github.com/longhorn/longhorn-manager/blob/254aa17/controller/setting_controller.go#L645-L677) would run the workload randomly, this is how Joshua enhance it at v1.1.1 to prevent each node access the external backup store.

2021-05-27 04:24 UTC, shuo-wu requested changes
1. Putting all info in `spec` rather than status is a little bit weird. By definition, `status` reflects the current situation of a resource, while `spec` reflects the desired situation.
2. The benefit of launching a new controller is that, each controller is responsible for monitoring and updating some backup volumes only. Currently, Longhorn picks up a random node and asks it to monitor all backup volumes, which means we will put all workloads/tasks on a node. Of course, the alternative is, launching a go monitor on each node and ask each monitor to check part of  backup volumes. 
3. Besides, it's better to put Resource creation, deletion, and spec update in one controller, and put the status update in another controller. In other words, you need to explain the life cycle management of new CRs in this LEP

2021-05-27 04:43 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +and its historical volume backups metadata as the Custom Resource (CR). For each backup volume, we'll create a new CR.
Good suggestion.

2021-05-27 04:59 UTC, jenting commented
> 1. Putting all info in `spec` rather than status is a little bit weird. By definition, `status` reflects the current situation of a resource, while `spec` reflects the desired situation.

I have thought this before. The reason why I choose to put it onto `spec` rather than `status` is that the field `spec`  is easier to make a change if we'd like to debug or test it via [kubectl edit CRD](https://github.com/longhorn/longhorn/wiki/dev:-How-to-modify-the-status-subresource-with-%60kubectl-edit%60-(CRD)).

Never mind, I'll move it from `spec` to `status` field.

> 2. The benefit of launching a new controller is that, each controller is responsible for monitoring and updating some backup volumes only. Currently, Longhorn picks up a random node and asks it to monitor all backup volumes, which means we will put all workloads/tasks on a node. Of course, the alternative is, launching a go monitor on each node and ask each monitor to check part of backup volumes.
> 3. Besides, it's better to put Resource creation, deletion, and spec update in one controller, and put the status update in another controller. In other words, you need to explain the life cycle management of new CRs in this LEP

I agree to create a separate control called `backup_volume_sync_controller` to handle synchronize the external backup store to cluster CR instead of putting this in `setting_controller`, this makes each controller is responsible for different task/function and the controller name is easier to know what's it's purpose.

However, I haven't thought the benefit of each node check part of the backup volumes because it'd make the logic inside different nodes more complicated. But I believe you want to achieve that if a backup volume (backup-volume-A) existed in the cluster and located in a node (Node-1), then this node ((Node-1) is responsible for the backup volume (backup-volume-A), right?

I'll update the life cycle management of new CRs but now my idea is spec update and status update all in one controller `backup_volume_sync_controller`.

2021-05-27 05:00 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +  - `spec.backups[volumeBackupName].size`: the size field inside a historical volume backup metadata.
Yes, the volume backup data size.

2021-05-27 05:01 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +  - `spec.backups[volumeBackupName].volumeBackingImageURL`: the volumeBackingImageURL field inside a historical volume backup metadata.
Okay, I removed all backing image related fields.

2021-05-27 05:54 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +  - `spec.backups[volumeBackupName].volumeBackingImageURL`: the volumeBackingImageURL field inside a historical volume backup metadata.
Please retain `volumeBackingImageName`. This field is still available

2021-05-27 06:05 UTC, shuo-wu commented
If you plan to add a controller, you can call it `backup_volume_controller`. `sync` is redundant. 

Adding field `OwnerID` for the new CR is enough: first-come, first-served. Since there is no preference when choosing the OwnerID for this CR. 

If you want to manually modify the status, you can refer to this doc: https://github.com/longhorn/longhorn/wiki/dev:-How-to-modify-the-status-subresource-with-%60kubectl-edit%60-(CRD)

After moving fields from `spec` to `status`, there is almost nothing in `spec`. If `spec` contains fields like `backupTarget`, you can consider updating the `spec` in the setting controller.

2021-05-27 06:14 UTC, shuo-wu requested changes
1. Some fields in the backup volume/backup cfg are confusing. Can we rename it in this CR? e.g.,
`status.created`, `status.backups[volumeBackupName].url`, `status.backups[volumeBackupName].created`...
2. Remember to consider that there can be multiple clusters using the same backupstore. This means the backup/backup volumes would be suddenly create/removed without HTTP API calls

2021-05-27 06:14 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +- `status.name`: the name field inside the backup volume metadata.
Remove this one. The backup volume name is already in `metadata`

2021-05-27 06:14 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +
Test the case: 2 clusters share the same backupstore

2021-05-27 06:14 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +After this enhancement, if the user ever configured the setting `backupstore-poll-interval` to `0`, then the user is unable to list backup volumes
Can we just add a warning in UI rather than directly forbidding listing (historical) backup volumes?

2021-05-27 08:42 UTC, innobead requested changes
In general, LGTM but some comments required to resolve.

P.S. except for pulling, I would suggest when doing the implementation, you can also check if there are some possible solutions for `push mode` like watch/notify when the backup info changes in the remote backup store, so we can efficiently do the pulling when there is something really changed.

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +Asynchronous pull backup volumes and historical volume backups into cluster custom resource (CR).
```suggestion
Final consistent backup volumes with historical volume backups from the remote backup store
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +from the external backup store.
```suggestion
Currently, Longhorn uses a blocking way for communication with the remote backup store, so there will be some potential voluntary or involuntary factors (ex:  network latency) impacting the functions relying on remote backup stores like listing volume backups or even causing further [cascading problems](###related-issues) after the backup store operation.

This enhancement is to propose an asynchronous way to pull backup volumes and historical volume backups from the external backup store (S3/NFS) then persistently saved via cluster custom resources. 

This can resolve the problems above mentioned by asynchronously querying the list of backup volumes and historical volume backups from the remote backup store for final consistent available results. It's also scalable for the costly resources created by the original blocking query operations.
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +
```suggestion
Decrease the query latency when listing volume backups _or_ historical volume backups in the circumstances like lots of volume backups, lots of historical volume backups, or the network latency between the Longhorn cluster and the remote backup store.
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +custom resource (CR). Therefore, we'll create a new Custom Resource Definition (CRD) called _backups_ to save the backup volumes and historical volume backups.
```suggestion
custom resource (CR). Therefore, we'll create a new Custom Resource Definition (CRD) called _backupvolumes_ to save the backup volumes and historical volume backups.
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +1. Pull the backup volumess and historical volume backups that **are in** the external backup store and **aren't in** the cluster CR only.
```suggestion
1. Pull the backup volumes and historical volume backups that **are in** the external backup store and **aren't in** the cluster CR only.
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +Then if the user clicks the `Backup` on the GUI, the user can list backup volumes _or_ list historical volume backups without timeout issue.
```suggestion
Then if the user clicks the `Backup` on the GUI, the user can eventually list backup volumes _or_ list historical volume backups without timeout issue.
```

2021-05-27 08:42 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +With this enhancement, the CR _backups.longhorn.io_ is updated when the asynchronous timer be triggered.
```suggestion
With this enhancement, the CR _backupvolumes.longhorn.io_ is updated when the asynchronous timer be triggered.
```

2021-05-27 10:09 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +    $ backup inspect s3://backupbucket@minio/?backup=backup-fa78d89827664840\u0026volume=pvc-004d8edb-3a8c-4596-a659-3d00122d3f07
How about this? Since the URL and volume name is mandatory, but the backup name is optional.
```
backup inspect <URL> <volume-name> --backup <backup-name>
```

2021-05-27 10:13 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +    $ backup inspect s3://backupbucket@minio/?backup=backup-fa78d89827664840\u0026volume=pvc-004d8edb-3a8c-4596-a659-3d00122d3f07
Good to me. Actually, the mandatory option is better to use `argument` :+1:

2021-05-27 15:28 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +
Good suggestion, thank you.

2021-05-31 10:19 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +   It watches the change of the settings `backup-target`, and `backup-target-credential-secret`, and `backupstore-poll-interval`. Within the controller, it runs:
I assume AssumRole logic should take effect automatically.a

2021-05-31 10:27 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +   After `backupstore-poll-interval` seconds, list backup volumes or list historical volume backups on the Longhorn GUI, the deleted one does not exist anymore.
Before this period, just make sure that any operation against to the missing volume backup should be failed w/ error message.

2021-05-31 10:28 UTC, innobead approved these changes
In general, LGTM. 

Some comments need to be noted. Leaving to @shuo-wu or @joshimoo to review before the merge.

2021-06-01 06:22 UTC, shuo-wu requested changes
If possible, I still prefer to separate backupvolume creation & deletion from backup_volume_controller. Here is the possible solution:
1. For setting_controller, it can take care of:
    1. Update `spec.backupStore` and `spec.pollInterval` if the settings change
    2. List backup volumes (volume only), then create or delete CRs.
2. For backup_volume_controller, it should consider:
    1. inspect all backups for **each** backup volume then update **status**.
    2. how to archive **periodic** inspection based on the poll interval? There may be 3 possible options: 
        1. Somehow modifying [the resync period](https://github.com/longhorn/longhorn-manager/blob/52db49fce3b9b8f2112404d837fb64eaeb5f67e3/controller/controller_manager.go#L64-L71) for this controller only. But I am not sure if it is possible. 
        2. Launching a goroutine for each backupvolume. But there may be  lots of goroutines if there are hundreds of backupvolumes. It may be a waste of resources.
        3. Add `spec.RequestUpdateAt`. This field will be updated by setting_controller (periodically) or HTTP APIs(immediately). The field update can trigger backup_volume_controller. Then backup_volume_controller can blindly sync with the remote backupstore and update a new field named `status.LastUpdateAt`.

2021-06-01 13:57 UTC, jenting commented
> If possible, I still prefer to separate backupvolume creation & deletion from backup_volume_controller. Here is the possible solution:
> 
> 1. For setting_controller, it can take care of:
>    
>    1. Update `spec.backupStore` and `spec.pollInterval` if the settings change
>    2. List backup volumes (volume only), then create or delete CRs.

Hmmm.. if we have two controllers running the access remote backup store, this means it'll duplicate code on check the poll interval. I'm thinking what's the pros of separate sync backup volumes and volume snapshot backups on the different controllers.

> 2. For backup_volume_controller, it should consider:
>    
>    1. inspect all backups for **each** backup volume then update **status**.
>    2. how to archive **periodic** inspection based on the poll interval? There may be 3 possible options:
>       
>       1. Somehow modifying [the resync period](https://github.com/longhorn/longhorn-manager/blob/52db49fce3b9b8f2112404d837fb64eaeb5f67e3/controller/controller_manager.go#L64-L71) for this controller only. But I am not sure if it is possible.
>       2. Launching a goroutine for each backupvolume. But there may be lots of goroutines if there are hundreds of backupvolumes. It may be a waste of resources.

Or we could launch just one goroutine. This is like the current backup store monitor implementation https://github.com/longhorn/longhorn-manager/blob/254aa17/controller/setting_controller.go#L297

>       3. Add `spec.RequestUpdateAt`. This field will be updated by setting_controller (periodically) or HTTP APIs(immediately). The field update can trigger backup_volume_controller. Then backup_volume_controller can blindly sync with the remote backupstore and update a new field named `status.LastUpdateAt`.

In fact, we could implement by checking `(time.Now() - status.LastUpdateAt) > spec.pollInterval`? If yes, run the sync logic; otherwise, skip this reconcile loop. The only drawback is if the `spec.pollInterval < the controller resync period`, the poll interval equals to the controller resync period.

2021-06-01 15:25 UTC, joshimoo commented
Here is some idea of a design I would probably go with, if you want to go a different way that's fine.

------
Add a BackupTarget CRD, that defines all necessary information for the target + poll interval.
This way the user can add multiple backup targets easily and we can remove the settings and instead allow defining a default target as part of the installation process or by the creating a CRD.

Add BackupTarget controller, that is responsible for polling the backup target and managing the cluster Backup CRD resources (add / delete) based on new information on the backup target.

-------
Add a Backup CRD, that defines all necessary information for the actual backup and is responsible for the creation / deletion of that backup. Add a finalizer to the backup crds, so that deletion of the CRD can be verified and then removed.

This way the user/we can initiate a backup solely by the creation of a CRD and manage the lifecycle of that backup as well.
The collection of backups with Label vol == X represents a backup volume.

Add a Backup controller that is responsible for managing the lifecycle of a backup.

-----
(optional, but probably nice to have) 
Add a BackupVolume CRD that contains summary information about all the volume backups.
I am not sure we need this, but if we do we can have a BackupVolume controller that updates the BackupVolume summary information based on the existing Backup CRD's. This can also contain the Recurring Job information

--------------------------------
With the above design we can easily add the following user features:

- Add a DR-controller that is responsible for the creation of DR-Volumes / lastest backup updates of all volumes that are present on the BackupTarget when the Target/BackupVolume is marked for this.
This feature would add values to our users, since now they can just mark a single BackupTarget and we will automatically replicate all volumes from a different cluster, so the whole cluster is ready for failover, previously the user needs to manually create each DR volume.

- Allows the user to manage creation/deletion of Backups via creation of Backup CRD's
This makes it easy for the user to manage recurring backups themselves but also creation of exceptional case backups, for example create a backup for each volume before node maintenance. Is easily done by creation of a BackupCRD per volume.

- Simplifies the CSI snapshot mechanism
- Persists the Backup information (1=1 mapping of snapshots-backup per backup target)

-----------------------------

If you want to explore this design further let me know and I will help you flesh it out :)

2021-06-02 05:27 UTC, jenting commented
> Here is some idea of a design I would probably go with, if you want to go a different way that's fine.
> 
> Add a **BackupTarget** CRD, that defines all necessary information for the target + poll interval.
> This way the user can add multiple backup targets easily and we can remove the settings and instead allow defining a default target as part of the installation process or by the creating a CRD.

When designing this LEP, I thought this, and this will benefit if we want to support HA backup target in the future.
In fact, when designing this LEP, I'm a bit struggle with should we have the `status.LastUpdateAt` in each BackupVolume CR?
I'd prefer put the `status.LastUpdateAt` to BackupTarget CR.

However, to make this LEP focus on async poll backup volumes, so I drop the design and only focus on the BackupVolume CRD.
But if other @longhorn/maintainer think it's good to have the BackupTarget CRD along with BackupVolume CRD, I'm fine to update this LEP. What does other thinking?

> Add a **Backup** CRD, that defines all necessary information for the actual backup and is responsible for the creation / deletion of that backup. Add a finalizer to the backup crds, so that deletion of the CRD can be verified and then removed.
> 
> This way the user/we can initiate a backup solely by the creation of a CRD and manage the lifecycle of that backup as well.
> The collection of backups with Label vol == X represents a backup volume.
> 
> Add a Backup controller that is responsible for managing the lifecycle of a backup.
> (optional, but probably nice to have)
> Add a **BackupVolume** CRD that contains summary information about all the volume backups.
> I am not sure we need this, but if we do we can have a BackupVolume controller that updates the BackupVolume summary information based on the existing Backup CRD's. This can also contain the Recurring Job information
> 
Could you please explain more on separate the Backup CRD and BackupVolume CRD pros and cons?

Furthermore, the BackupVolume CRD is still needed since there is some information contains in the backup volume metadata (`volume.cfg`) like the volume size.

2021-06-02 06:17 UTC, shuo-wu commented
Having duplicate poll code is better than asking a controller to create/delete its CRs or update spec for the CRs. The responsibility of a controller is always to push and update the current status to the spec by issuing some operations. It does not involve in updating the CR spec or managing the lifecycle.

---

Launching CRD BackupTarget is a good idea. IMO, the pros are:
    1. It separates the responsibility of creating/deleting missing/redundant BackupVolume (or Backup) CRs from setting_controller. So that setting_controller won't be overwhelmed by the backup polling.
    2. It allows easily defining default backup target during Longhorn installation.
    3. HA backup target? Not sure if this is required

---

Separating the Backup CRD from BackupVolume CRD means, Longhorn doesn't need to send requests to engines/replicas in the API layer when receiving backup-related calls. Instead, backup_controller will sends/retry sending requests to the engines based on the Backup CRs

2021-06-09 04:59 UTC, jenting commented
@shuo-wu @joshimoo This is ready to review, my only concern is Note 2.
https://github.com/longhorn/longhorn/blob/da882bb33fcfd066619cd20223bf3ebb12383d37/enhancements/20210525-async-pull-backups.md#note
I can't think of a way from backup_controller to notify backup_volume_controller to update the newly created backup volume status. This would make if the user clicks `Create Backup` -> `Backup`, the user can't see the newly created backup volume until the backup volume controller updates the BackupVolume CR status from the remote backup store.

2021-07-13 05:26 UTC, shuo-wu requested changes

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +   10. Updates the BackupVolume CR status field according to the backup volumes' config, and also updates the BackupVolume CR `status.lastSyncedAt`.
Should these 2 steps stand behind step 3? If there are backup updates, there must be modifications happening on the config file. 
Besides, I am thinking about the necessity of API `backup config-metadata`. If we can directly identify if there are modifications by checking the content of the config file, why do we want an extra API call? There are too much data in the config file, and checking the last modified time of the config file would save some bandwidth cost?

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
Need to clarify if Longhorn should create a BackupVolume CR in this API when it doesn't exist.

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
Adding the finalizer here? Shouldn't be the finalizer set once the CR is created?

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
when will `status.backupCreateAt` be set? Can we use this field to indicate if the backup creation is complete?

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +   Watches the changes of Setting CR `settings.longorn.io` field `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval`. The setting controller is responsible to create/u
What will happen if the backup target changes? Add it's better to add a test for this case.

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +- Create a single cluster with 2 volumes (vol-A and vol-B).
It's better to mention the main purpose of each test.

2021-07-13 05:26 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     configModificationTime: the backup volume config modification time. (Time)
1. Do we really need this? I don't find when the controllers will use it.
2. If YES, do not put this field in `spec`.

2021-07-13 05:59 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +       5. Updates the BackupTarget CR `spec.forceSync = false` if `spec.forceSync = true`.
okay!

2021-07-13 06:09 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +   10. Updates the BackupVolume CR status field according to the backup volumes' config, and also updates the BackupVolume CR `status.lastSyncedAt`.
Before backup refactoring,
- Longhorn list and read BackupVolume and/or Backup config from the remote backup store when the user clicks the `Backup` at the GUI.
- Longhorn list and read BackupVolume config within the setting_controller timer (the timer period is the poll interval).

After backup refactoring, the backup_volume_controller and backup_controller be triggered every 30 secs. It means every 30 secs, the read API be triggered. Moreover, the Read API is a time-consuming API than the HEAD API.

I was thinking that if the Backup config has been synced, do not read the Backup config again. Because in reality, the backup config should be created once.
However, when I look at the integration test, Longhorn did a test that the Backup config might be corrupted after a successful backup config was created.

2021-07-13 06:13 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
It's a bit tricky for the volume that has never run snapshot backup before.

When the user creates volume backup, the Backup CR is created, and the BackupVolume CR is created after the BackupVolume Config be pulled from the remote backup store. (It depends on the backup store poll interval).

If the backup store poll interval is 1 hour, it means that the user could see the BackupVolume on the GUI after 1 hour. Therefore, the BackupVolume CR is created for a better user experience.

2021-07-13 06:19 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
If the Backup CR is created with the finalizer. When the user deletes the remote backup store Backup config, the backup_volume_controller will delete the Backup CR, then the backup_controller reconciles the Delete event to delete the remote backup store Backup even if has been deleted already.

To add the finalizer is when the remote backup store config also needs to do clean up. That's why I only add the finalizer when the HTTP DELETE API be called.

2021-07-13 06:20 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
Yes, when the backup creation complete.

2021-07-13 07:55 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +   Watches the changes of Setting CR `settings.longorn.io` field `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval`. The setting controller is responsible to create/u
The backup target changes did nothing, the backup_target_controller reconciles to create/delete BackupVolume CRs and back_volume_controller reconciles to create/delete Backup CRs.

The only to note is when backup target is not accessible, the BackupVolume CRs and Backup CRs will be deleted.

2021-07-13 09:51 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +   Watches the changes of Setting CR `settings.longorn.io` field `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval`. The setting controller is responsible to create/u
If Longhorn decides to create BackupVolume CR in this HTTP API, it can set `backuptarget.spec.forceSync` to avoid waiting for the pull interval. 
If you want to keep the current design unchanged, it's better to explain this case in the doc.

2021-07-13 09:51 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
If Longhorn decides to create BackupVolume CR in this HTTP API, it can set `backuptarget.spec.forceSync` to avoid waiting for the pull interval. 
If you want to keep the current design unchanged, it's better to explain this case in the doc.

2021-07-13 09:54 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +   Watches the changes of Setting CR `settings.longorn.io` field `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval`. The setting controller is responsible to create/u
Got it. After syncing with the new backup target, the controllers will delete all expired CRs automatically as well as creating new CRs based on the backup target contents.

2021-07-13 09:59 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
I prefer the assumption you raised here. 
When backup-controller sends a delete call to the remote backup store for a non-existing backup file, it will receive either a not-found error or a success response. Then backup-controller knows the cleanup is done and it's safe to delete the CR itself by upsetting the finalizer. With this design, the deletion workflow is consistent with other kinds of CRs.

2021-07-13 09:59 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
Then do we still need `status.backupCreate`?

2021-07-13 10:50 UTC, joshimoo commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
The finalizers should be added as part of CR creation.
And only removed after validation that the necessary resources have been cleaned up.

In this case, that the backup.cfg is truly gone on the backupstore.
As @shuo-wu mentioned a missing (NotFound) backup.cfg can be treated as a successful delete.

Just to elaborate a finalizer should be used to prevent deletion, till all necessary validation has been done. 

Some examples below:
(dependent resources have been removed, volume is safe to delete, replica data has been deleted on the file system, node is gone, etc)

2021-07-14 02:13 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
Yes, if the backup is in progress, the `status.BackupCreateAt` is empty. Then when the backup_controller reconciles again and sees the `status.BackupCreateAt` is empty, the back_controller calls the snapshot backup process again.

2021-07-14 02:19 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
Oops, I had a bad memory of this yesterday.

After re-read the code, Longhorn would not create BackupVolume CR in this HTTP API call.
Instead, after backup completion and the BackupVolume CR does not exist, it creates the BackupVolume CR and set `backupvolume.spec.forceSync=true` in the `backup_controller``.

But I like your approach that set `backuptarget.spec.forceSync` to avoid waiting for the pull interval :+1:

2021-07-14 02:20 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
Got it. I'll add the finalizer when the CR is created.

2021-07-14 03:11 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
If Longhorn creates BackupVolume CR in the backup-controller, there is no need to set `backuptarget.spec.forceSync`.

Notice that Creating a BackupVolume CR at the beginning matches the current behavior: Before the 1st backup is created, users can find an empty BackupVolume on the UI backup page.

2021-07-14 03:15 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
Oh, OK. This field actually indicates if the backup creation is **started** or not. Can you rename this field to avoid misunderstanding?

2021-07-14 05:05 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +       3. Find the difference backup volumes `backupVolumesToPull = backupStoreBackups - clusterBackupVolumes` and create BackupVolume CR `metadata.name` + `spec.forceSync = true`.
Fix the typo.

2021-07-14 05:06 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Generate the backup name <backup-name>.
Okay, now I implement it as when the backup completion (progress 100%) then creating the BackupVolume CR.

2021-07-14 05:08 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +    3.  Check if the Backup CR `spec.snapshotName != ""` and `status.backupCreate == false`. If yes, call longhorn engine/replica for backup creation. Then fork a go routine to monitor the backup cre
Change the wording to `status.backupCreationIsStarted`.

2021-07-14 05:14 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +       5. Updates the BackupTarget CR `spec.forceSync = false` if `spec.forceSync = true`.
Use `spec.forceSync` and `status.forceSynced` would be easier for the user to control directly patch the BackupTarget CR _or_ BackupVolume CR to immediately force sync the CRs.

For example:
```shell
kubectl patch lhbt default --type merge -p '{"spec":{"forceSync":true}}'

kubectl patch lhbv <backup-volume-name> --type merge -p '{"spec":{"forceSync":true}}'
```

2021-07-14 13:14 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
After recap my memory. The reason _why_ I only add finalizer on the HTTP Delete API is because I want to prevent if the user deletes the BackupVolume/Backup CR by accident. The controller reconciles to delete the remote config file.
Although we could add a field `spec.toDelete`, however, I realized that adding a finalizer would be much easier and simple to understand. WDYT? @shuo-wu @joshimoo

2021-07-14 13:18 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +       5. Updates the BackupTarget CR `spec.forceSync = false` if `spec.forceSync = true`.
I'm thinking that I could use the `status.LastSyncedAt` to controller whether to force sync the backup_volume_controller.

For example, in the backup_controller, after snapshot backup completion, set the BackupVolume CR `status.LastSyncedAt = nil`. At backup_volume_controller, since the `status.LastSyncedAt = nil`, it will run sync immediately.

But I'm not sure at your point, is it okay/safe for the backup_controller to update the BackupVolume CR `status` field?

2021-07-15 01:09 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +       5. Updates the BackupTarget CR `spec.forceSync = false` if `spec.forceSync = true`.
This is not recommended. The user should be responsible for updating the spec only. Then Kubernetes/Longhorn can do something based on the spec.
IMO, if users want to force sync a Backup or BackupVolume via CR update, they should set the timestamp correctly. we don't need to consider if the field can be manually set **easily** here.

2021-07-15 02:53 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
When will the BackupVolume/Backup CRs be deleted by accident? During Longhorn uninstallation? For the uninstallation, Longhorn can remove/unset the backup target first then BackupVolume/Backup CR deletion won't lead to actual backup file cleanup.

2021-07-15 03:54 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +   10. Updates the BackupVolume CR status field according to the backup volumes' config, and also updates the BackupVolume CR `status.lastSyncedAt`.
As we discussed in the session, after the backup creation complete, the controller doesn't need to check the backup cfg file anymore. But the for the backup volume cfg file, I think the backup-volume controller would call the `head` API first then determine if we need to inspect the cfg file and list all backups when the sync is required.

2021-07-15 04:45 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     1. Add the finalizer to the Backup CR with the given backup name.
The users delete the BackupVolume/Backup CRs manually :(
Since the external backup is the last mile to protect the data, we should make sure the backup data won't be deleted if the user just accidentally deletes CRs.

2021-07-19 05:33 UTC, shuo-wu requested changes

2021-07-19 05:33 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +            2.  create the BackupVolume CR `metadata.name` + `metadata.finalizers["longhorn.io"]` if BackupVolume CR not exist.
There is no need to mention the finalizers during creation. 

Similar above.

2021-07-19 08:05 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     deleteRemoteConfig: indicate to delete the remote backup config or not. (bool)
backup_controller calls the longhorn/backstore to delete remote backup config (and the related block files if needed) when delete CR event comes in and `spec.deleteRemoteConfig=true`.

2021-07-19 08:06 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +            2.  create the BackupVolume CR `metadata.name` + `metadata.finalizers["longhorn.io"]` if BackupVolume CR not exist.
updated!

2021-07-19 08:06 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +   8.  Call the longhorn engine to get the backup volume config's last modification time `backup head <volume-config>` and compares to `status.lastModificationTime`. If the config last modification t
updated!

2021-07-19 09:11 UTC, shuo-wu commented on enhancements/20210525-async-pull-backups.md
> +     deleteRemoteConfig: indicate to delete the remote backup config or not. (bool)
Then the naming of this field is confusing. How about naming it to something like `fileCleanupRequired`?

2021-07-19 11:12 UTC, jenting commented on enhancements/20210525-async-pull-backups.md
> +     deleteRemoteConfig: indicate to delete the remote backup config or not. (bool)
Sure~

2021-07-29 08:55 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +     ownerID: the node ID which should responsible for run sync the remote backup target. (string)
```suggestion
     ownerID: the node ID which is responsible for running operations of backup target controller (string)
```

2021-07-29 08:55 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +     ownerID: the node ID which should responsible for run sync the remote backup target. (string)
```suggestion
     ownerID: the node ID which is responsible for running operations of backup volume controller (string)
```

2021-07-29 08:56 UTC, innobead commented on enhancements/20210525-async-pull-backups.md
> +     ownerID: the node ID which should responsible for run sync the remote backup target. (string)
```suggestion
     ownerID: the node ID which is responsible for running operations of the backup controller (string)
```

2021-07-29 09:07 UTC, innobead reviewed
In general, LGTM.

@shuo-wu and @joshimoo do you have any concerns about this proposal?

2021-07-29 11:56 UTC, shuo-wu approved these changes
LGTM

2021-07-30 00:44 UTC, merged