Add LEP - backup policy
longhorn/longhorn pull request #2737
Opened 2021-06-25 12:23 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/467

2021-06-25 23:08 UTC, yasker requested changes
Volume to backup policy should be a one-way relationship instead of a two-way relationship. 

I don't think it's necessary to store any information regarding which volume has the policy in the backup policy itself. That information's life cycle should be with volume, rather than the policy itself.

Also, need to change the name of the policy from `backup policy` since it can contain a recurring snapshot job as well.

Probably call it `Recurring Job Policy`, or something covers both snapshot and backup.

I can understand the motivation for moving the tracking into the policy controller. It might be to reduce the complexity of the volume controller, but we don't need to do anything other than writing the policy name into the volume (which should be next to the existing customized recurring job, basically a new type of recurring job), and update labels(there can be multiple policies tie to a volume). 

If the policy was deleted, we can warn the user that the policy no longer exists for the volume. That can be in a condition. We don't need to remove the policy name from the volume (and we cannot because it's in the spec). The latter reminds me that, how will we clean up the volume name from the policy CR? It should be in the spec but the controller cannot change the spec.

Also, the backup job related to the recurring job policy is better to be handled in one place, maybe by the recurring job policy controller, in case the policy itself was changed during the volume's life cycle. Essentially, for the cronjob running for certain recurring job policy, it should be able to find all the volumes that are using the policy at the moment (by using the label), then do the job. It can even potentially throttle the operations in parallel, make sure we're not going to overwhelm the system.

And CRD definition/update needs to be in the LEP as well.

2021-06-25 23:08 UTC, yasker commented on enhancements/20210624-backup-policy.md
> +I want the ability to automatically remove volume names in the backup policy when volumes don't exist in the cluster.
It should be only volume referring to the backup policy.

We can select volumes for certain backup policies using labels. But it's unnecessary to record who is using which backup policy.

2021-06-25 23:08 UTC, yasker commented on enhancements/20210624-backup-policy.md
> +When a volume is removed and restored to the cluster, the backup policy should automatically pick up the volume assignment and re-create the recurring job.
Do you mean we're storing the backup policy in the backup's metadata? It doesn't make sense to have the local backup policy tie to a volume.

2021-06-25 23:08 UTC, yasker commented on enhancements/20210624-backup-policy.md
> +2. Once the volume is created, update the backup policy spec with `kubectl` or UI to include volume name. This will automatically create the recurring job to the assigned volume.
Update the volume instead of updating the backup policy.

It's like PVC might have an associated storage class, but storage class doesn't need to know about PVC.

2021-06-25 23:08 UTC, yasker commented on enhancements/20210624-backup-policy.md
> +  - Printer Colume should include `Name`, `Default`, `Recurring`, `Retain`, `Age`.
Need type. Can be snapshot or backup.

2021-06-25 23:08 UTC, yasker commented on enhancements/20210624-backup-policy.md
> +  - Update the ClusterRole to include `backuppolices` and `backuppolicies/status`
I don't think we need `status`.

2021-06-28 12:34 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +Users can assign volumes to backup policies. The assigned volumes inherent the recurring job settings from the backup policy and will automatically create/update/delete the recurring job.
Updated the LEP to have backup policy reference by the volume recurring job.

2021-06-28 12:38 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +- Ability to enable cleanup backup policy volume list when volumes get removed from the cluster.
No longer part of the goal because the life cycle now goes with the volume.

2021-06-28 12:39 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +- Should have backup policy status for each volume assigned, including `error`, `lastUpdateTime`.
No longer part of the goal because the life cycle now goes with the volume and no point in storing the update status in the policy.

2021-06-28 12:40 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +- Include recurring job settings; `name`, `cron`, `retain`.
Added.

2021-06-28 12:41 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +I want the ability to automatically remove volume names in the backup policy when volumes don't exist in the cluster.
Fixed.

2021-06-28 12:44 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +When a volume is removed and restored to the cluster, the backup policy should automatically pick up the volume assignment and re-create the recurring job.
Removed the user story because we will do policy reference with volume's recurring job.

2021-06-28 12:44 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +2. Once the volume is created, update the backup policy spec with `kubectl` or UI to include volume name. This will automatically create the recurring job to the assigned volume.
Fixed.

2021-06-28 12:44 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +  - Printer Colume should include `Name`, `Default`, `Recurring`, `Retain`, `Age`.
Added type.

2021-06-28 12:45 UTC, c3y1huang commented on enhancements/20210624-backup-policy.md
> +  - Update the ClusterRole to include `backuppolices` and `backuppolicies/status`
Removed.

2021-06-28 19:31 UTC, yasker requested changes

2021-07-13 11:09 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +> Question: Should the default recurring job policy overrule the storageClass recurring backup jobs? Or should they co-exist?
Reflecting on [comment](https://github.com/longhorn/longhorn/pull/2737#discussion_r660053424). Does it make sense to update the volume spec with the default recurring job policy on first-time volume creation? 
```
spec:
  recurringJobs:
  - name: test
    task: policy
```

2021-07-13 18:31 UTC, yasker commented on enhancements/20210624-recurring-job-policy.md
> +> Question: Should the default recurring job policy overrule the storageClass recurring backup jobs? Or should they co-exist?
There are two ways of doing it:
1. Don't add them in. So the controller needs to scan for the volumes without a schedule and run them on schedule.
    * Pros: No modification to the volume. And once the user decides to set a schedule for the volume, the default schedule will be automatically overridden.
    * Cons: It's not clear from a volume perspective that if the volume will be backed up based on the schedule.
2. Add the reference in.
    * Exactly the opposite as the first option.

I don't have a clear preference over one or the other. What do you think?

2021-07-15 01:28 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +> Question: Should the default recurring job policy overrule the storageClass recurring backup jobs? Or should they co-exist?
ATM, I am favoring adding the default recurring job to the volume spec on first-time volume creation, for reasons:
1. The behavior is consistent with storageClass. When the recurring job is applied in the SC it will also get added to the volume spec.
2. I've not found a good way that can identify the first-time volume is created to apply the default with the recurring job controller. But we can leverage the volume controller to identify this and add to the volume spec and the recurring job controller can then scan and reference for cronjob creation.

2021-07-15 09:49 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +- Recurring job policy should include recurring job settings; `name`, `type`. `cron`, `retain`.
Fixed.

2021-07-15 09:50 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +2. Create `Recurring Snapshot and Backup Schedule` with UI and input recurring job name as `Name` and type as `Policy`. Then click `Save` should see automatically filled in `Schedule`, `Retain`.
Addressed.

2021-07-15 09:50 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +1. Create a recurring job policy with `default` set to `true` in UI or `kubectl`.
Fixed wording.

2021-07-15 09:51 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +    1. Update the ownership of `Default` backup and snapshot policy when a backup or snapshot policy is updated/created with `.Spec.Default`.
Not required anymore. Removed.

2021-07-15 09:51 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +    2. Update the associated volume recurring job `.Cron`, `.Retain` when the recurring job policy is updated.
Removed.

2021-07-15 23:23 UTC, yasker commented on enhancements/20210624-recurring-job-policy.md
> +> Question: Should the default recurring job policy overrule the storageClass recurring backup jobs? Or should they co-exist?
In fact, we will apply the policy to all the volumes without any backup policy, not only for the first-time volume creation. Since it's the `default` as a `fail-safe`, it should act as a catch-all.

For example, if a volume is created with a recurring job, and later the job was removed. The default policy should still cover it.

After you describe the process, I realized there is another issue with this approach: we shouldn't modify the volume's spec, since it's user-created and defined.

2021-07-16 05:16 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +  - Update the ClusterRole to include `recurringjobpolices`.
Discussed with @yasker and we will keep the same as the [others](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml#L47-L51).

2021-07-16 05:20 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +  - The volume recurring job name will reference the recurring job policy name. It should be 8 characters or less. If the policy is named with more than 8 characters, an error shows on UI. This can b
Discussed with @yasker and we will name the cronjob the same as the policy name by introducing new longhorn-manager command to use per policy.

2021-07-16 12:14 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +> Question: Should the default recurring job policy overrule the storageClass recurring backup jobs? Or should they co-exist?
Thank you for clarifying the expectation. Fixed.

2021-07-16 12:14 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +  1. Before `createCronJob`, get the recurring job policy by name and update the volume jobs `.Cron` and `.Retain`.
Fixed.

2021-07-27 03:34 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +    3. Delete the cron job if annotation `last-applied-cronjob-volume` is different from the desire volume list.
Discussed with @yasker and will remove the cron job annotation and add labels in volume instead.

2021-07-27 09:11 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +    3. Delete the cron job if annotation `last-applied-cronjob-volume` is different from the desire volume list.
Because the [K8s limits label key and value to 63 chars](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set), and Longhorn does not limit the number of policy can apply for each volume, so we will probably need to have one label for each policy.
```
- apiVersion: longhorn.io/v1beta1
  kind: Volume
  metadata:
    creationTimestamp: "2021-07-27T07:06:35Z"
    finalizers:
    - longhorn.io
    generation: 2
    labels:
      longhorn.io/job-policy-backup1: backup
      longhorn.io/job-policy-backup2: backup
      longhorn.io/job-policy-backup3: backup
      longhorn.io/job-policy-snapshot1: snapshot
      longhorn.io/job-policy-snapshot2: snapshot
      longhorn.io/job-policy-snapshot3: snapshot
      longhornvolume: pvc-1bad969c-7f40-466f-9e2f-c7ffc5ea527a
    name: pvc-1bad969c-7f40-466f-9e2f-c7ffc5ea527a
    namespace: longhorn-system
    resourceVersion: "650605"
```
And also need to implement logic to update the labels.

2021-07-27 12:25 UTC, shuo-wu requested changes
After checking this LEP,  I still prefer to ask policy CRs to record the volume references in specs. Here are the cons of the current design:
1. Users need to understand the recurring jobs in volume spec and non-default recurring policies before using default policies correctly. 
2. Both VolumeController and the new PolicyController should be responsible for creating/deleting recurring job CRs, which is not elegant enough. 
3. The policy controller needs to list all volumes that require the related policy anyway. Then why not directly update and record the volume list at the beginning (when users set the recurring jobs for volumes via HTTP APIs)?
4. This adds more complexity for volume CRs.
5. There is no way to separate all recurring-related concepts from volume CRD as the further refactoring. The current design also prevents Longhorn from introducing more fancy features. e.g., Adding tag-selector for volumes and recurring policies, which provide more flexibility of configuring the volume recurring jobs.

cc @yasker @joshimoo

2021-07-27 12:25 UTC, shuo-wu commented on enhancements/20210624-recurring-job-policy.md
> +  - Create and update CronJob per policy.
Here, the controller can: 
    1. List all volumes that require the policy.
        1. If the volume is not attached while the setting is not `true`, remove the volume from the list.
        2. For a default policy, remove all volumes that have recurring jobs or policies set.
    2. Delete the recurring job CR if it doesn't match the spec or no volume is using the policy
    3. Create a recurring job CR if there is a volume using the policy

2021-07-27 14:10 UTC, c3y1huang commented
Seems like there are different opinions on if Longhorn should reference volume in cronjob/policy or policy should reference in volume.

I've updated to include:
- Option 1: Volume referenced in the cron job annotation.
- Option 2: Policy referenced in the volume label.

2021-07-27 16:38 UTC, shuo-wu commented
> * Option 1: Volume referenced in the cron job annotation.

Volume list can be stored in policy spec or label as well. The problem is, which one is responsible for recording the reference.

2021-07-27 21:39 UTC, yasker commented
@shuo-wu We cannot keep the `default` policy in the volume spec since the user owns the volume spec, we cannot change it at our will. Think how users would operate it using Kubernetes API instead of Longhorn API, which is the ultimate goal.

The ultimate goal for this design is to transition into a separate recurring job instead of embedded with the volume object, which is way too crowded already.

> 1. Users need to understand the recurring jobs in volume spec and non-default recurring policies before using default policies correctly.

There are only two scenarios here:
1. If there is anything in the `volume.spec.recurringJob`, use it.
2. Otherwise, the default recurring job policy applies.

> 2. Both VolumeController and the new PolicyController should be responsible for creating/deleting recurring job CRs, which is not elegant enough.

I have the same thought. So the ultimate goal is to move recurring jobs completely outside of volume spec to be handled by `recurring job controller` (currently known as `recurring job policy controller`), but that's a bigger work than scoped.

> 3. The policy controller needs to list all volumes that require the related policy anyway. Then why not directly update and record the volume list at the beginning (when users set the recurring jobs for volumes via HTTP APIs)?

The policy controller doesn't need to do it. The job can do it on the fly when it's executing.

Again, we cannot rely on HTTP APIs. We are moving away from it into Kubernetes native API.

> 4. This adds more complexity for volume CRs.

Nothing was added in the volume CRs except for the policy and label, which are ignored by the volume controller. It's not the volume controller who will schedule the recurring job for recurring job policies, it's a separate cronjob scheduled by the recurring job controller.

> 5. There is no way to separate all recurring-related concepts from volume CRD as the further refactoring. The current design also prevents Longhorn from introducing more fancy features. e.g., Adding tag-selector for volumes and recurring policies, which provide more flexibility of configuring the volume recurring jobs.

I don't follow. This design is essentially moving away from using the volume CRD for recurring jobs. Tag selector for the volumes can be defined in the separate recurring job CR later. We can also use labels to select multiple recurring job policies, like what we've done with the `default` recurring job policies.

2021-07-27 22:29 UTC, joshimoo commented on enhancements/20210624-recurring-job-policy.md
> +    3. Delete the cron job if annotation `last-applied-cronjob-volume` is different from the desire volume list.
On a quick look I think a 1 way mapping is all we need.
Volumes don't need to know which policies apply to them.
This gets double important once we introduce volume groups.

The Policy/Recuring whatever crd should keep track of the volumes that it applies to.
One idea for this is to specify a volume/group label selector as part of the spec / annotation of the policy crd.

Then it's easy to implement volume groups just by tagging the volumes with the associated group.
It's also easy to offset the backup creation while only doing a sync snapshot.

The policy/job controller can then just create backup crds once the backup refactor is included.
Will have a deeper look at the LEP tomorrow.

2021-07-27 22:42 UTC, joshimoo commented
I agree and I think I mentioned this before, the volume really doesn't need any knowledge about anything related to backup policy / recurring jobs definitions.

The Policy CRD can reference an arbitrary set of volumes via the definition of a labelSelector as part of  the policy spec.
The default policy just becomes `Select label == *` the selectors are pseudo code for demonstration only.
This allows for all kinds of flexibility either by just using the volume.name label or by specifying additional labels on the volumes.

Some Example policies below:

Example Policy for a volume group X
Select label volume-group == X

A policy that only selects kafka volumes.
Select label app == kafka

A policy that only applies to 2 volumes in the whole cluster
Select label where volume in (X | Y)

**Have a look at the set based selectors.**
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement

2021-07-27 23:00 UTC, yasker commented
In fact, more I think about this, more I realized we probably should move to use recurring job policy 100%. That means users can only set recurring job policy to the volume, no more separate entry for snapshot/backup is needed. Thinking about it, when would you want your 100 volumes all starts to backup at totally different times with totally different configurations?

What they would prefer instead is:
1. Create a recurring job policy.
2. Set certain volumes to use it.

All of those can work today since we've introduced the recurring job policy controller. We just need to migrate all the previous recurring jobs (including storage class) into new auto-created policies when upgrade.

So:
1. Volume spec will only contain the recurring job policy names.
2. Those names will be added to the volume as labels, as @joshimoo mentioned above. 
    * If there is no recurring job policy for the volume, the `default` policy label will be automatically added to the volume.
3. Recurring job controller will start the cron jobs according to the cron in the policy
    * it doesn't care who are the volumes will be backed up at this time.
4. When the time comes, the cron job will retrieve the content of the recurring job policy by the name, and find who are the volumes have the related label, and perform the snapshot/backup operations:
    * if the recurring job policy is set to default, search for `default` in addition to the `name`.
    * Does the snapshot/backup operation one by one. The operation order can be defined as `sequential`, `consistent` (for volume group snapshot), or `throttled` (with a concurrent number as parameter) in the future.
    * Be careful with the retry mechanism here. We don't want to re-backup previously successfully backed up volumes if a later volume failed.
    * The policy can also use a label selector to the volume, but that would require volume to have some labels. I think we can implement this part later.

2021-07-28 03:35 UTC, yasker commented
Had a discussion with @c3y1huang and @shuo-wu , we will move to 100% recurring job policy (now it will be called just `recurring job` since it's the only way to create recurring job.)

Also, `default` will become a group of recurring jobs (instead of a special case). Volume can select one or more recurring jobs, and/or one or more recurring job groups. The recurring job controller will be responsible for label the volume for the `default` recurring job group if no other recurring job was found. The `default` recurring job group will not be removed by the recurring job controller if users add more recurring jobs. Users need to remove the `default` recurring job group manually.

Also, a recurring job can be performed for a volume group with a special `volume-group: xxx` label. It will be evaluated during the runtime of the cronjob. I assume this selector will be kept in the recurring job CR. 

For individual volumes, the recurring job information will be kept in the volume's metadata instead of the recurring job CR itself, since it's easier to use the label to filter volumes instead of keeping a list in the recurring job CR itself.

cc @joshimoo

2021-07-28 03:43 UTC, c3y1huang commented
More notes from the discussion with @yasker and @shuo-wu.
- Remove recurringJobs from volume spec.
- Change recurring job policy to recurring job.
- Volume will contain two types of label - `job`, `job-group`.
- Remove the field `Default` and use `Group` instead. The recurring job applies if recurring jobs contain default group.
- Do not need to treat default snapshot and backup separately. Only need to determine if the volume policy label exists.
- Translate existing recurring jobs to the label during the upgrade.
- Add `throttle` to the longhorn-manager binary and recurring job spec. Options `sequential`, `consistent` comes later.

2021-07-28 08:30 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +       1. Skip volume if volume is not `attached` or `allow-recurring-job-while-volume-detached` is not set to `true`.
Fixed.

2021-07-28 08:34 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +4. Select existing recurring job policy from the `Name` list.
I am thinking `Setting/Recurring Job`. What do you think?

2021-07-28 13:20 UTC, shuo-wu commented on enhancements/20210624-recurring-job-policy.md
> +4. Select existing recurring job policy from the `Name` list.
I think we can directly add a new button on the top of the UI like `Volume` or `Setting`. Since this page may be frequently used. It is a core feature.

2021-08-04 12:22 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +4. Select existing recurring job policy from the `Name` list.
Make sense. Fixed.

2021-08-04 12:56 UTC, c3y1huang commented on enhancements/20210624-recurring-job-policy.md
> +  - Create and update CronJob per policy.
> Here, the controller can:
> 
> 1. List all volumes that require the policy.
>    
>    1. If the volume is not attached while the setting is not `true`, remove the volume from the list.

This will be done in binary on-the-fly with the label selector.

>    2. For a default policy, remove all volumes that have recurring jobs or policies set.

Volume controller will be responsible for adding the default policy.

> 2. Delete the recurring job CR if it doesn't match the spec or no volume is using the policy

I think we should keep the recurring job CR, the recurring job will also be responsible to remove any excess corn jobs.

> 3. Create a recurring job CR if there is a volume using the policy

Users will mostly be creating their own recurring job CRs. I think the only case where Longhorn will be creating for the user is during upgrade migration or for the PVC cases.

2021-08-05 19:04 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +1. Translate all volume spec recurringJobs to label `longhorn.io/job-<jobTask>-<RandomID>: enabled`.
We don't need `<RandomID>` for upgrade.

The recurring job is defined by:
1. Task
2. cron
3. Retain

So, as long as those three fields are the same, we can regarding it as the same recurring job. For example, we can name a recurring job: `<task>-<retain>-<hashing of cron>`, e.g. `backup-3-abcdef12` which `abcdef12` is some hashing result from the cron field.

2021-08-05 19:10 UTC, yasker requested changes

2021-08-05 19:10 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +  1. Add new command `snapshot-job <job.name>` with flags `--groups`, `--label`, `--retain`, `--concurrent` `--backup`.
`recurring-job` instead of `snapshot-job`.

Also,`recurring-job` command can get those parameters automatically as well, since it has the access to the Kubernetes API server. So we don't need to recreate the job every time when the spec changes.

So the only necessary command line is
```
longhorn-manager -d\
           recurring-job <job.name>\
           --manager-url <url>
```

2021-08-06 09:10 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +1. Translate all volume spec recurringJobs to label `longhorn.io/job-<jobTask>-<RandomID>: enabled`.
Thank you. Fixed.

2021-08-06 09:11 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  1. Add new command `snapshot-job <job.name>` with flags `--groups`, `--label`, `--retain`, `--concurrent` `--backup`.
Make sense, fixed.

2021-08-06 14:37 UTC, yasker requested changes

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +  "type": "recurringJob"
Where are the labels? It was a part of recurring job definition in volume spec. https://github.com/longhorn/longhorn-manager/blob/2dfb1487f325f019a003d15db056535fe18c7252/types/resource.go#L170

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +2. In UI, Navigate to Volume, `Recurring Snapshot and Backup Schedule`.
`Recurring Jobs Schedule` is fine.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +3. When clicked on the `New` should have the option to choose from `single` or `group`.
The flow is unclear after choosing `single` or `group`.

E.g.
1. ... `single` or `group`
    1. If `single` is chosen, ...
    2. If `group` is chosen, ...

Though we can also update them in the UI. Doesn't need to be 100% accurate here.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +5. The selected recurring job(s) will show the `Type`, `Schedule`, `Retain`, `Concurrency` information from the `RecurringJob` CR.
Missing labels field.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +3. Add job label to volume removed the `default` recurring jobs.
It's a bit hard to implement this once we added the `default` recurring job group label to the volume. I am fine with not removing the `default` group automatically. Users might want to add more jobs on top of the existing `default` group.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +  3. Get volumes by label selector `longhorn.io/job-group-<job.group>: enabled` to filter out volumes if the job is set with a group.
`jobgroup` instead of `job-group`. Since the job group might start with `group-xxx` name then it will be confusion.

In fact it's better to name the selector `recurring-job.longhorn.io/<job-name>` and `recurring-job-group.longhorn.io/<group-name>`.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty, or label with `default` job-group.
It's probably better to do the upgrade from `spec.recurringJobs` to `recurring job` in the upgrade path (https://github.com/longhorn/longhorn-manager/tree/master/upgrade ) , not in the datastore.

2021-08-06 14:37 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +       - Include labels `longhorn.io/job`.
Update the label accordingly.

2021-08-09 10:51 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  "type": "recurringJob"
Fixed.

2021-08-09 10:52 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +2. In UI, Navigate to Volume, `Recurring Snapshot and Backup Schedule`.
Fixed.

2021-08-09 10:52 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +3. When clicked on the `New` should have the option to choose from `single` or `group`.
Addressed.

2021-08-09 10:53 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +5. The selected recurring job(s) will show the `Type`, `Schedule`, `Retain`, `Concurrency` information from the `RecurringJob` CR.
Fixed.

2021-08-09 10:53 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +3. Add job label to volume removed the `default` recurring jobs.
Removed (3).

2021-08-09 10:54 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  3. Get volumes by label selector `longhorn.io/job-group-<job.group>: enabled` to filter out volumes if the job is set with a group.
Addressed.

2021-08-09 10:55 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +       - Include labels `longhorn.io/job`.
Fixed.

2021-08-09 15:34 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty, or label with `default` job-group.
This is related to the volume created by the storage class, not the upgrade. Discussed with @yasker , will introduce `recurringJobSelectors` and parameter `recurringJobs` will be deprecated in future.

2021-08-10 00:38 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty, or label with `default` job-group.
`recurringJobSelector`, the singular form (not the plural) to keep consistent with other selectors.

2021-08-10 14:19 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty, or label with `default` job-group.
Added the implementation for `recurringJobSelector` also the upgrade migration from `recurringJobs` to `recurringJobSelector` for the storage class parameter.

2021-08-10 15:06 UTC, yasker requested changes
Only minor comments. Looks good in general. I will do a final review next time.

2021-08-10 15:06 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty.
Hmm, once we've done with the upgrade, I assume the recurringJobs should be empty?

2021-08-10 15:06 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +       - Include labels `recurring-job.longhorn.io` and `recurring-job-task.longhorn.io`.
What do we need `recurring-job-task.longhorn.io` for?

2021-08-10 15:06 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +3. When clicked on the `New` should have the option to choose from `Job` or `Job Group`.
Oh, I see the creation part has been addressed below. So this is the list part.

2021-08-11 02:17 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  > Since the storage class and upgrade migration contains recurringJobs spec. So we will keep the `VolumeSpec.RecurringJobs` in code to create the recurring jobs for volumes from the `storageClass`.
https://github.com/longhorn/longhorn/issues/2866
https://github.com/longhorn/longhorn/issues/2865

2021-08-11 02:21 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty.
The upgrade will automatically convert the `recurringJobs` to `recurringJobSelector` and also the volume spec `recurringJobs` to labels. The `recurringJobs` will be empty after upgrade, However this field is still functional, for example if the user add the `recurringJobs` into storageClass then it will get converted to labels and a new recurring job CR will get created.

2021-08-11 02:29 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +- The recurring job should include settings; `name`, `groups`, `task`, `cron`, `retain`, `concurrency`.
Fixed.

2021-08-11 02:30 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +    1. User sees all existing recurring jobs from the `Name` drop-down list.
Addressed.

2021-08-11 02:31 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +       - Include labels `recurring-job.longhorn.io` and `recurring-job-task.longhorn.io`.
Since the names should be unique so I think this is not needed. Removed.

2021-08-11 03:01 UTC, yasker commented on enhancements/20210624-label-driven-recurring-job.md
> +     1. Add recurring job label if `VolumeSpec.RecurringJobs` is not empty.
So we still keep the storage class recurring jobs functional for v1.2.0. In that case, this will be fine.

2021-08-11 03:02 UTC, yasker approved these changes
LGTM. Feel free to merge if there is no objection from other maintainers.

2021-08-12 02:56 UTC, shuo-wu requested changes

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +- In the manager/volume, create recurring jobs for volumes from the `storageClass` if not already exist.
Shouldn't this be done by the CSI? In the CSI volume creation function, we can find all matching recurring job CRs based on field `recurringJobs` or `recurringJobSelector`. If there is no matching result, the plugin can send HTTP calls to create new ones.

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  > Since the storage class and upgrade migration contains recurringJobs spec. So we will keep the `VolumeSpec.RecurringJobs` in code to create the recurring jobs for volumes from the `storageClass`.
We can retain the field itself but remove the code related to it. In the new version, all volumes created by the old StorageClass can directly use labels as well:
1. In the CSI plugin, check the old StorageClass `recurringJobs` and filter out the recurring job CRs based on corn value. If no exist, the plugin can create them.
2. Create a volume and set recurring job labels

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  2. Add volume labels by volume `ActionRecurringJobAdd` API with `input.IsStorageClass`. Volume manager will delete the default label when sees `input.IsStorageClass`.
Can the volume creation API directly accept the recurring job lists as a new input field?

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +    - `volumeInformer` get all recurring job from volume recurring job labels and `enqueueRecurringJob`. It will also label and update the volume with `default` job-group if no recurring job label is
I am thinking if we really need this informer. The main purpose of this controller is to create, update, and delete the corn jobs. If we don't delete the corn jobs when there is no volume using a recurring job, this workflow can be simplified and the informer is no longer required.

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +      1. Delete the cron job with selected labels: `recurring-job.longhorn.io/<Name>`.
Do you mean removing the labels for all volumes referred to this curring job?

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +*Given* an `Operation` drop-down list next to the recurring job.
Add a button for batch deletion on the top left.

2021-08-12 02:56 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +A new page for `Recurring Job` to create/update/delete recurring jobs.
In the Recurring job list page, which fields need to be shown in that list/table? And can we aggregate recurring jobs by group names?

2021-08-12 06:59 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +Replace volume spec `recurringJobs` with the label-driven model. Allow users to create recurring backup/snapshot jobs with new `RecurringJob` CRD. The created recurring jobs can be referenced by addi
Addressed.

2021-08-12 07:02 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +1. When volumes are all using the same recurring backup/snapshot policy, means all volumes will perform backups at the same time. As the original issue suggested, `Ideally, a range should be provided
This does look a bit confusing, I've removed this because job concurrency is added and this statement was removed from the original issue.

2021-08-12 07:02 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +I want to create backup/snapshot recurring jobs that can be referenced in volume by the job name.
Addressed.

2021-08-12 07:03 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +Have the option to set default recurring jobs via `StorageClass` or `RecurringJob`. The `RecurringJob` respects when the `recurringJobs` are given in the `StorageClass`.
Reworded the statement.

2021-08-12 07:03 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +4. The `recurringJobs` will get removed from the storageClass.
Removed.

2021-08-12 07:04 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +6. Recurring job CRs will get created from volume spec `recurringJobs`.
Yes. Updated the statement.

2021-08-12 07:05 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +#### Add Recurring Job CRD.
No special labels in the recurring job CRD, the labels and annotation will be set in the cronjob instead.

2021-08-12 07:06 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  1. Add new command `recurring-job <job.name> --longhorn-manager <URL>`.
I think we can remove it. Updated the statement.

2021-08-12 07:06 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  5. Use the concurrent number parameter to throttle goroutine with channel. Each goroutine creates `NewJob()` and `job.run()` for the volumes.
Both.

2021-08-12 07:08 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +- In the manager/volume, create recurring jobs for volumes from the `storageClass` if not already exist.
Yes, it makes sense to have this done in CSI. Updated.

2021-08-12 07:20 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +    - `volumeInformer` get all recurring job from volume recurring job labels and `enqueueRecurringJob`. It will also label and update the volume with `default` job-group if no recurring job label is
I am not sure if it makes sense from the user's point of view if the job pod still gets created if no volume is referencing it. No strong opinions on this one...

2021-08-12 07:24 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +      1. Delete the cron job with selected labels: `recurring-job.longhorn.io/<Name>`.
I think we should keep the volume labels in case the recurring job gets deleted by accident, the user can add it back and the recurring job is still referenced for the volume.

2021-08-12 07:27 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +*Given* an `Operation` drop-down list next to the recurring job.
Scenario updated.

2021-08-12 08:07 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +A new page for `Recurring Job` to create/update/delete recurring jobs.
> In the Recurring job list page, which fields need to be shown in that list/table? 

I've updated a table in the commit.

> And can we aggregate recurring jobs by group names?

I think we can aggregate with the search box.

2021-08-12 09:05 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  2. Add volume labels by volume `ActionRecurringJobAdd` API with `input.IsStorageClass`. Volume manager will delete the default label when sees `input.IsStorageClass`.
I don't understand what you mean... If the input `recurringJobs` is not empty, it means Longhorn can add the corresponding labels in the manifest before calling the creation API. And there is no need to use the `default` group for the volume.

2021-08-12 09:10 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +    - `volumeInformer` get all recurring job from volume recurring job labels and `enqueueRecurringJob`. It will also label and update the volume with `default` job-group if no recurring job label is
Yes. The cron job will launch pods that do nothing then directly become `complete`. That's the cost of this idea. I think it's acceptable. But the benefit is, this controller no longer needs to take care of volume. This makes both the enqueuing and the reconcile loop become simpler.

2021-08-12 09:11 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  > Since the storage class and upgrade migration contains recurringJobs spec. So we will keep the `VolumeSpec.RecurringJobs` in code to create the recurring jobs for volumes from the `storageClass`.
Since you decide to create recurring jobs in CSI, we don't need to do this anymore, right?

2021-08-12 09:23 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +A new page for `Recurring Job` to create/update/delete recurring jobs.
Not sure why there are 2 search boxes below. Maybe I need to wait for a UI demo image before discussing this part.

2021-08-12 13:18 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +    - `volumeInformer` get all recurring job from volume recurring job labels and `enqueueRecurringJob`. It will also label and update the volume with `default` job-group if no recurring job label is
I've removed the volume informer and I think it wouldn't hurt if we keep the cron job cleanup.

2021-08-12 13:22 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  2. Add volume labels by volume `ActionRecurringJobAdd` API with `input.IsStorageClass`. Volume manager will delete the default label when sees `input.IsStorageClass`.
After discussing with @shuo-wu , I've updated to use `Volume.Spec.RecurringJobSelector` for recurring job labeling 
 during `CreateVolume` for storageClass.

2021-08-12 13:23 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +A new page for `Recurring Job` to create/update/delete recurring jobs.
Sorry, there should be only one. Updated.

2021-08-12 13:31 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  > Since the storage class and upgrade migration contains recurringJobs spec. So we will keep the `VolumeSpec.RecurringJobs` in code to create the recurring jobs for volumes from the `storageClass`.
> Since you decide to create recurring jobs in CSI, we don't need to do this anymore, right?

Not entirely sure if you are referring to the deprecation notice or the field removal?

For field removal, the recurringJob parameter will still be functional, but it will be translated to labels and recurring job CRs instead of `recurringJobs` in volume spec. The `recurringJobs` in volume spec will no longer be visible.

2021-08-13 08:51 UTC, shuo-wu requested changes

2021-08-13 08:51 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +    4. Update cron job if the new cron job spec is different from the `last-applied-cronjob-spec`.
Contradict to statement 2

2021-08-13 08:51 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +    2. When there is no volume with label `recurring-job.longhorn.io/<Name>: enabled` and `recurring-job-group.longhorn.io/<Group>: enabled`.
As we discussed before, the controller doesn't need to remove the cron job even if there is no volume using it. Let the cron job create a pod that does nothing. I don't think users care about this.

2021-08-13 08:51 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  - Use defer to clean up CronJob.
`defer`? I think you can do cleanup only when the deletion timestamp of a recurring job is not empty.

BTW, do you consider using cascading deletion here?
1. Add owner reference when creating the cron job for each recurring job.
2. Set option `DeletePropagationForeground` in the recurring job deletion function.

2021-08-13 08:55 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  - Use defer to clean up CronJob.
It will sit in the `reconcileRecurringJob` I think we can discuss the detail in the implementation PR.

2021-08-13 09:05 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +    2. When there is no volume with label `recurring-job.longhorn.io/<Name>: enabled` and `recurring-job-group.longhorn.io/<Group>: enabled`.
Removed.

2021-08-13 09:06 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +    4. Update cron job if the new cron job spec is different from the `last-applied-cronjob-spec`.
Fixed.

2021-08-13 11:34 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  - Use defer to clean up CronJob.
Sure

2021-08-13 11:47 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +  2. Add volume labels by volume `ActionRecurringJobAdd` API with `input.IsStorageClass`. Volume manager will delete the default label when sees `input.IsStorageClass`.
I mean, adding a new field in the [HTTP API layer](https://github.com/longhorn/longhorn-manager/blob/d4ee01d214c95768048294eaadae2595ba6b6f0e/api/model.go#L22) then we can specify the recurring jobs in the HTTP VolumeCreation call. It doesn't mean that this field needs to be added in `VolumeSpec` or `VolumeStatus`. You can refer to [this field as an example](https://github.com/longhorn/longhorn-manager/blob/d4ee01d214c95768048294eaadae2595ba6b6f0e/api/model.go#L979).

2021-08-13 12:36 UTC, shuo-wu requested changes

2021-08-13 12:36 UTC, shuo-wu commented on enhancements/20210624-label-driven-recurring-job.md
> +     2. Remove the `recurringJobs` from volume spec.
For `CreateVolume` and `UpdateVolume`:
1. Add recurring job labels if `Volume.Spec.RecurringJobs` is not empty. Then unset `Volume.Spec.RecurringJobs`.
2. Label with `default` job-group if no other recurring job label exists.

2021-08-13 12:42 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +     2. Remove the `recurringJobs` from volume spec.
Fixed.

2021-08-13 16:58 UTC, shuo-wu approved these changes

2021-08-13 21:55 UTC, c3y1huang commented on enhancements/20210624-label-driven-recurring-job.md
> +  1. Remove `updateRecurringJobs` method.
Just realize the `updateRecurringJobs` method cannot get removed since the volume informer is not in the recurring job controller. This method should be responsible to add default labels if no other labels exist.

cc @yasker @shuo-wu

2021-08-16 05:01 UTC, innobead approved these changes
LGTM

@c3y1huang thanks for this kind of very detailed design documentation more than a proposal I expect.

2021-08-16 05:05 UTC, merged