Add LEP for CSI volume cloning
longhorn/longhorn pull request #2864
Opened 2021-08-10 23:31 UTC by PhanLe1010

longhorn/longhorn#1815

2021-08-13 13:02 UTC, shuo-wu requested changes

2021-08-16 08:39 UTC, innobead approved these changes
In general, LGTM.

@shuo-wu has some questions needed to resolve.
@joshimoo probably needs to check if he did not check it yet.

2021-08-16 08:39 UTC, innobead commented on enhancements/20210810-volume-clone.md
> +  Copy the snapshot from a replica of the source volume to the new replica by calling `SnapshotCloneCmd()`.
Do we consider copying a near replica snapshot of source volume first on the same host where the replica of target volume? If not, probably we can think of it w/ different cloning strategy in the future (not for this time).

2021-08-16 08:39 UTC, innobead commented on enhancements/20210810-volume-clone.md
> +`VolumeCreate` API will check/validate data a new field, `DataSource` which is a new field in `v.Spec` that
I think Phan already mentioned in the below implementation part.

2021-08-16 08:39 UTC, innobead commented on enhancements/20210810-volume-clone.md
> +        VolumeCloneStateFailed         = VolumeCloneState("failed")
Do we need `in progress` state? or actually `initiated` already meaning `in progrss`?

2021-08-18 07:58 UTC, innobead commented
@PhanLe1010 Please help resolve @shuo-wu comments, then we can merge. Thanks.

2021-08-18 23:50 UTC, PhanLe1010 commented
@innobead 
I will fix this one after fixing the PR on manager side. I am hitting some issue with that PR

2021-08-19 18:15 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +  Take a snapshot of the source volume.
Thank you. fixed

2021-08-19 18:17 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +  Copy the snapshot from a replica of the source volume to the new replica by calling `SnapshotCloneCmd()`.
I think this approach saves network bandwidth but hurt the disk bandwidth since all IOs will be on the same disk at the same time

2021-08-19 18:17 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +  Later on, when the target volume is attached by workload pod, Longhorn will start rebuilding other replicas.
It will be an enhancement for next release

2021-08-19 18:18 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +        VolumeCloneStateFailed         = VolumeCloneState("failed")
Yeah, `initiated` means we are working on it.

2021-08-19 18:18 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +Implement a generalized function, `SyncContent()`, which syncs the content of a `ReaderWriterAt` object to a file on a remote host.
Thank you. fixed

2021-08-19 18:19 UTC, PhanLe1010 commented on enhancements/20210810-volume-clone.md
> +  Take a snapshot of the source volume.
Thank you. fixed

2021-08-19 22:46 UTC, PhanLe1010 commented
Addressed review comment and Added the tests

2021-08-20 01:18 UTC, merged