Add config value for ingress path
longhorn/longhorn pull request #3097
Opened 2021-10-02 13:30 UTC by AlaaAttya

Add config value for ingress path

by setting `ingress.path` you can specify the default ingress path for longhorn

2021-10-06 05:46 UTC, jenting commented on chart/values.yaml
> +  ## then you can access the UI by using the followig full path {{host}}+{{path}}
```suggestion
  ## then you can access the UI by using the following full path {{host}}+{{path}}
```

2021-10-06 08:12 UTC, shuo-wu reviewed
And we can add a subquestion for this field in `question.yml` so that users can config it via Rancher UI. Here is the example: https://github.com/longhorn/longhorn/blob/e98b0992b32cce7a3bbd0bb0ac13dc6064562661/chart/questions.yml#L568-L573

2021-11-18 23:54 UTC, jenting commented
@AlaaAttya are you willing to address the PR comment?

2021-11-19 01:32 UTC, jenting commented
Thank you @AlaaAttya 
If possible, would you like to address this comment https://github.com/longhorn/longhorn/pull/3097#pullrequestreview-772330624?

If not, we could file another PR to address it, thank you.

2022-01-30 14:37 UTC, AlaaAttya commented
@jenting just update the PR. sorry for the late reply

2022-02-08 04:07 UTC, shuo-wu reviewed
Can you rebase then squash all modifications into a single commit? The modifications LGTM

2022-02-08 04:07 UTC, shuo-wu commented on chart/questions.yaml
> +      label: ingress path
NIT: 
```
      label: Ingress Path
```

2022-02-09 21:55 UTC, AlaaAttya commented on chart/questions.yaml
> +      label: ingress path
done 👍

2022-02-10 01:01 UTC, jenting commented
@AlaaAttya 
could you please rebase then squash all modifications into a single commit?

2022-02-10 19:34 UTC, AlaaAttya commented
> @AlaaAttya could you please rebase then squash all modifications into a single commit?

just did 👍

2022-02-11 03:53 UTC, shuo-wu submitted a review, later dismissed

2022-02-11 05:57 UTC, jenting submitted a review, later dismissed

2022-02-22 13:14 UTC, AlaaAttya commented
@innobead is it ready to get merged?

2022-02-22 13:58 UTC, innobead commented on chart/questions.yaml
> +      label: Ingress Path
```suggestion
  - variable: ingress.path
    default: "/"
    description: "If ingress is enabled you can set the default ingress path"
    type: string
    required: true
    label: Ingress Path
```

2022-02-22 13:59 UTC, innobead requested changes
The formating of questions.yaml is not right, except that. LGTM.

2022-02-24 00:37 UTC, jenting commented
> The formating of questions.yaml is not right, except that. LGTM.

I help update the format, this is ready to review.

2022-02-24 03:33 UTC, shuo-wu approved these changes

2022-02-24 14:08 UTC, innobead approved these changes

2022-02-24 14:08 UTC, merged