change secret name to align with storage class name
longhorn/longhorn pull request #3239
Opened 2021-11-11 22:18 UTC by khushboo-rancher

I thought same name of secret aligned with the above storage class example will make more sense. :) 

Signed-off-by: Khushboo <fnu.khushboo@suse.com>

2021-11-12 05:53 UTC, innobead requested changes

2021-11-12 05:53 UTC, innobead commented on enhancements/2021.07.26-pv-encryption.md
> -  name: longhorn-crypto
Let's keep this as the same as examples.

2021-11-17 19:16 UTC, khushboo-rancher commented on enhancements/2021.07.26-pv-encryption.md
> -  name: longhorn-crypto
Done

2021-11-24 07:14 UTC, innobead approved these changes

2021-11-24 07:15 UTC, innobead commented
@khushboo-rancher the branch has conflicts, needs to resolve first before merging.

2021-12-01 17:25 UTC, joshimoo submitted a review, later dismissed
LGTM

2021-12-01 23:34 UTC, innobead approved these changes

2021-12-01 23:34 UTC, merged