Add LEP for storage network with multus
longhorn/longhorn pull request #3277
Opened 2021-11-18 10:08 UTC by c3y1huang

Have a global setting to allow users to set a dedicated network for storage with Multus and NetworkAttachmentDefinition.

https://github.com/longhorn/longhorn/issues/2285

2021-12-07 04:44 UTC, shuo-wu reviewed
I am thinking if the backing image or volume download feature will break the network isolation and lead to any risks when this kind of storage network is set up.

2021-12-07 04:44 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +#### Instance Manager Controller
Similar logic should be applied to the backing image part. Notice that Longhorn directly uses PodIP when talking with backing image manager/data source pods. e.g.: https://github.com/longhorn/longhorn-manager/blob/7bd89abdbae3c406ec56094364cf6c2da1d36d9d/api/forwarder.go#L185

If you are not familiar with the backing image part, I can explain more details for you in a separate session.

2021-12-07 04:44 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +- Setup and configuration of the Multus and network-attachment-definition.
Will we have a simple example as a quick hands-on?

2021-12-07 04:44 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +- The setting `storage-network` will be used for `k8s.v1.cni.cncf.io/networks` annotation.
The setting `storage-network` will be the value of annotation `k8s.v1.cni.cncf.io/networks`.

2021-12-08 06:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The setting `storage-network` will be used for `k8s.v1.cni.cncf.io/networks` annotation.
Addressed.

2021-12-08 07:04 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +#### Instance Manager Controller
Thank you for the discussion. Part added. And as discussed, we can probably leave out the upload and download of backing image as in my opinion storage network is mainly for inter-cluster.

2021-12-08 07:10 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Setup and configuration of the Multus and network-attachment-definition.
I prefer not to expose the example in the doc because it takes some more manual setups on the cluster nodes and could also vary base on platforms. However, I will be adding manual instructions and sample in the test case.

2021-12-08 09:00 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +- Setup and configuration of the Multus and network-attachment-definition.
OK, got it.

2021-12-08 14:14 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- The storage network applies for Longhorn data plan (engine, replica) traffic, segregate from the Longhorn control plan traffic.
data plane: engine, replica and backing image data sources.

2021-12-08 14:18 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- Setup and configuration of the Multus and network-attachment-definition.
Correct. 

It also means we will not focus on what types of the network or ipam being to used for the storage network like overlay, ipvlan/macvlan, etc. Just need to make sure the second interface also fulfill the conditions of the first cluster network. (ref: http://kubernetes.io/docs/concepts/cluster-administration/networking/)

2021-12-08 14:20 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- Upload and download of backing image.
I assume we only care about the traffic between our data path components. So for backing image, image sync between nodes or volume to/from backing image are what we care.

2021-12-08 14:40 UTC, innobead requested changes

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
`k8s.v1.cni.cncf.io/networks` should be only to apply to the pods related to data path? why longhorn-manager needs this? I assume only engine/replica instance manager pods or even backing image data source pods need that.

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- The `Engine`, `Replica` and `BackingImageManager` status IP uses the network interface IP from the instance manager's `storage-network` interface.
What does `status IP` mean here? and the purpose?

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- During setting application, the instance manager status will be marked to error. This should trigger instance manager pod re-creation with annotation from the `storage-network` setting value.
Or should we only allow this setting taking effect until all volumes detached then recreate these managed pods? Making instnace manager pods error to recreate, it sounds lke a little unsafe to possibly cause some data loss?

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- Include `network-attachment-definition` for all namespaces in the support bundle.
Do you mean multus workloads? We don't manage multus deployment/provision, this should not be covered in our support bundle.

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check and return if NetworkAttachmentDefinition does not exist in the cluster.
Maybe we don't need this, otherwise you will need to operate NAD resources w/ RBAC. 

Just apply the annotation and if NAD and mutlus not there, just nothing happens. (note: because you can do the pre-check, but can't do the post-check to make sure the NAD still there. This condition check is probably a little meaningless)

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +1. Use the instance managers `k8s.v1.cni.cncf.io/networks: <STORAGE-NETWORK>` network interface IP for `Engine` and `Replica` `Status.IP` instead of instance manager status IP.
What's the purpose?

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +1. Assume the secondary network interface in Pod is from `storage-network`. Check the existence of a secondary network interface and use the IP instead of the Pod IP from the environment variable.
Do we consider the case of backing image sync among nodes?

2021-12-08 14:40 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +1. Update manager Daemonset `.Spec.Template.Annotation[k8s.v1.cni.cncf.io/networks]` to the `storage-network` setting value.
Why manager needs the second interface?

2021-12-09 01:20 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The `Engine`, `Replica` and `BackingImageManager` status IP uses the network interface IP from the instance manager's `storage-network` interface.
Longhorn uses the status IP to commute data between engine -> replica, backing-image-manager <-> backing-image-manager. For example, https://github.com/longhorn/longhorn-manager/blob/master/controller/backing_image_manager_controller.go#L708 and https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L1228.

2021-12-09 01:58 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check and return if NetworkAttachmentDefinition does not exist in the cluster.
I am thinking if we should also add the validation to the HTTP API client so it can be validated when the setting is changed via UI. Or just keep it silent when NAD doesn't exist? WDYT?

2021-12-09 02:37 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Assume the secondary network interface in Pod is from `storage-network`. Check the existence of a secondary network interface and use the IP instead of the Pod IP from the environment variable.
The backing-image-manager <-> backing-image-manager will use the backing-image-manager status IP which will get updated.

2021-12-09 02:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The storage network applies for Longhorn data plan (engine, replica) traffic, segregate from the Longhorn control plan traffic.
Fixed.

2021-12-09 02:51 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
You are right, it's not required. Removed.

2021-12-09 02:53 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Use the instance managers `k8s.v1.cni.cncf.io/networks: <STORAGE-NETWORK>` network interface IP for `Engine` and `Replica` `Status.IP` instead of instance manager status IP.
https://github.com/longhorn/longhorn/pull/3277#discussion_r765364137

2021-12-09 02:53 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Update manager Daemonset `.Spec.Template.Annotation[k8s.v1.cni.cncf.io/networks]` to the `storage-network` setting value.
Not required, removed.

2021-12-09 03:44 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
Sorry, Longhorn manager does need to have the second interface for the controller to update the status. For example, https://github.com/longhorn/longhorn-manager/blob/master/engineapi/engine.go#L92.

2021-12-09 03:49 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check and return if NetworkAttachmentDefinition does not exist in the cluster.
After discussing with @innobead , Longhorn will not check the NAD because we do not want to add the dependency to operate the NAD resources.

2021-12-09 03:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Include `network-attachment-definition` for all namespaces in the support bundle.
After discussing with @innobead , Longhorn will include the NADs in the support bundle because we do not want to add the dependency to operate the NAD resources.

2021-12-09 03:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Update manager Daemonset `.Spec.Template.Annotation[k8s.v1.cni.cncf.io/networks]` to the `storage-network` setting value.
https://github.com/longhorn/longhorn/pull/3277#discussion_r765411366

2021-12-09 04:47 UTC, innobead commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
The status update should be through the controller interface instead?

2021-12-09 07:27 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
Currently, the Longhorn engine uses single IP for control, sync, and data. The easiest way is to add a secondary interface to the manager so the engine controller can get command over replicas. To separate that would take much more effort.

2021-12-17 08:07 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The manager DaemonSet `spec.template.metadata` will have `k8s.v1.cni.cncf.io/networks` annotation with the `storage-network` setting value.
LEP updated.

2021-12-17 08:09 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- The `Engine`, `Replica` and `BackingImageManager` status IP uses the network interface IP from the instance manager's `storage-network` interface.
Introduce new `StorageIP` status instead. LEP updated.

2021-12-17 08:09 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- During setting application, the instance manager status will be marked to error. This should trigger instance manager pod re-creation with annotation from the `storage-network` setting value.
Addressed.

2021-12-17 08:09 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Include `network-attachment-definition` for all namespaces in the support bundle.
Removed.

2021-12-17 08:09 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check and return if NetworkAttachmentDefinition does not exist in the cluster.
Removed.

2021-12-17 08:10 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Assume the secondary network interface in Pod is from `storage-network`. Check the existence of a secondary network interface and use the IP instead of the Pod IP from the environment variable.
LEP updated.

2021-12-17 10:43 UTC, shuo-wu reviewed
In general, `Implementation Overview` - `Engine` is still confusing. You can have tables to list the CRD changes and API changes.

2021-12-17 10:43 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> ++               Address:          address.Cluster + "," + address.Storage,
Do we need to directly add required inputs for the engine/replica process creation instead? But this means the live upgrade is no longer supported.

2021-12-17 10:43 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +    cloneStatus:
How about the IP of these status fields? Are they all using storage IPs?

2021-12-17 10:43 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
Sorry, I still don't understand why the cluster IP is required. And what are the data-related commends? I think it's a little bit hard to define if a command is a data-related commend or not.

If I understand correctly:
1. Longhorn manger pods use the storage network to talk with engine processes, replica processes, and the instance manager pods. And this is why you need to add the longhorn manager pods to the storage network.
2. Engine processes always use the storage network talk with replica processes.

2021-12-17 10:43 UTC, shuo-wu commented on enhancements/20211118-storage-network-with-multus.md
> +- Factory creates should be provided with a cluster address to use for the service URLs. Also a storage address for data connection.
Same here. Why does a replica/engine process require the cluster IP?

2021-12-20 08:15 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
The storage-network will only be applied for the storage related data traffic (read-n-write, file sync), for example [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L439), [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/backend/remote/remote.go#L267) and [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L374) .The talking between processes will still be using the cluster-network, hence we don't need to apply storage-network in Longhorn manager.

2021-12-20 08:16 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +    cloneStatus:
Yes, they should be showing with the storage IPs.

2021-12-20 08:16 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> ++               Address:          address.Cluster + "," + address.Storage,
Let me re-check on the live upgrade.

2021-12-20 09:17 UTC, jenting reviewed
Are the user easily to know the reason that failed with these operations like volume attachment failed, replica replication failed is because of the storage network misconfigured?

2021-12-20 12:47 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +# Title
Thanks, updated.

2021-12-20 12:47 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Attach then volumes.
Thanks, updated.

2021-12-20 12:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be network interface IP from the parent manager's `storage-network` interface or use the `status.IP`
Reworded.

2021-12-20 13:05 UTC, c3y1huang commented
> Are the user easily to know the reason that failed with these operations like volume attachment failed, replica replication failed is because of the storage network misconfigured?

The user is responsible to get the correct network configurations in. Multus deployment and configuring networks are out of scope. 

Longhorn can probably validate the secondary CNI at the setting controller with the informer. But unless we implement a network-attachment-definition controller, we will not know about any user post-updates that may break the traffics.

When misconfiguration happens, the best we could do is to ask for network-attachment-definition CRs, look for clues in the engine CRs and ask the user to check the ping response.

2021-12-20 13:06 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Factory creates should be provided with a cluster address to use for the service URLs. Also a storage address for data connection.
https://github.com/longhorn/longhorn/pull/3277#discussion_r772156302

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- Reflect/Show the correct addresses used in the `Engine`, `Replica`, and `BackingImageManager` CRs.
If I understand correctly, the correct addresses mean the `status.IP` and `status.storageIP` for cluster control address and storage address, right?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- When updating the *storage-network* `Setting`, Longhorn will restart all instance manager `Pods` and backing image manager `Pods` to apply the CNI annotations.
Does the backing image data source Pods need to restart as well? [1]

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Longhorn instance manager and backing image manager `Pods` will restart.
[1]

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check the `Engine`, and `Replica` CRs and see `StorageIP` in status and address in the *storage-network* subnet/CIDR range.
I _guess_ the BackingImageManager CR should contain the `status.storageIP` as well, correct?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +BackingImage:
BackingImageManager?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
Would you mind providing an example of what's the engine's command to launch a new replica before and after this LEP?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- When creating a new replica client, use the storage address to get the host. The host in the client will be used for data transfers and sync. Use the cluster address for the service URLs.
Is the host means the host interface?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating instance manager `Pod` CRs.
```suggestion
1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating instance manager `Pod`.
```

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating instance manager `Pod` CRs.
If the instance manager Pods already exist, do we need to restart the instance manager Pods? Or we only need to annotate the existing instance manager Pods? [2]

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Use the `k8s.v1.cni.cncf.io/networks: <STORAGE-NETWORK>` network interface IP in instance managers `Pod` CR for the `Engine` and `Replica` `StorageIP` in status. When *storage-network* `Setting` i
Not quite understand this sentence. If I understand correctly, it means we'll update the `status.storageIP` _or_ `status.IP` from the instance manager Pod's annotation `k8s.v1.cni.cncf.io/networks: <STORAGE-NETWORK>` network interface IP address?

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the *storage-network* `Setting` value when creating backing image data source `Pod`.
[2]

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating backing image manager `Pod` CRs.
[2]

2021-12-20 22:56 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +Scenario: `Engine`, `Replica` and `BackingImageManager` should use IP in `storage-network` `NetworkAttachmentDefinition` subnet/CIDR range after setting update.
Do the `BackingImageDataSource` needs as well? Or this part means the CR `status.storageIP`?

2021-12-21 01:44 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Reflect/Show the correct addresses used in the `Engine`, `Replica`, and `BackingImageManager` CRs.
All fields with addresses should reflect. I've updated the LEP.

2021-12-21 01:46 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- When updating the *storage-network* `Setting`, Longhorn will restart all instance manager `Pods` and backing image manager `Pods` to apply the CNI annotations.
Hmm.. I don't think we are expecting users to do any operation during storage-network setting updates, and the volume will need to be detached for the setting to apply, hence there shouldn't be any backing image data source Pods.

2021-12-21 01:47 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check the `Engine`, and `Replica` CRs and see `StorageIP` in status and address in the *storage-network* subnet/CIDR range.
Yes, it's covered in the `Backing Image Manager Controller` section.

2021-12-21 01:47 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +BackingImage:
Thanks, fixed.

2021-12-21 01:51 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +BackingImage:
Thanks, fixed!

2021-12-21 02:03 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Check the `Engine`, and `Replica` CRs and see `StorageIP` in status and address in the *storage-network* subnet/CIDR range.
Thanks, fixed.

2021-12-21 02:11 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
There will be no change in the engine command's arguments, most of the commands already included the cluster IP in `--url`. If I'm correct, the `controller` command is the only one that doesn't include the correct IP in `--url` and `--replica` will include both storage and cluster network addresses.

2021-12-21 02:14 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- When creating a new replica client, use the storage address to get the host. The host in the client will be used for data transfers and sync. Use the cluster address for the service URLs.
Sorry, that was hard to understand. What I mean is the host in the `ReplicaClient` object. Reworded.

2021-12-21 02:14 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating instance manager `Pod` CRs.
> Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting

Updated.

2021-12-21 02:16 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Annotate with `k8s.v1.cni.cncf.io/networks` to the `storage-network` setting value when creating instance manager `Pod` CRs.
> If the instance manager Pods already exist, do we need to restart the instance manager Pods? Or we only need to annotate the existing instance manager Pods? [2]

Yes, it should be restarted and already covered in the `Setting Controller` section.

2021-12-21 02:17 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +1. Use the `k8s.v1.cni.cncf.io/networks: <STORAGE-NETWORK>` network interface IP in instance managers `Pod` CR for the `Engine` and `Replica` `StorageIP` in status. When *storage-network* `Setting` i
Reworded.

2021-12-21 02:18 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +Scenario: `Engine`, `Replica` and `BackingImageManager` should use IP in `storage-network` `NetworkAttachmentDefinition` subnet/CIDR range after setting update.
https://github.com/longhorn/longhorn/pull/3277#discussion_r772773296

2021-12-21 04:33 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> ++               Address:          address.Cluster + "," + address.Storage,
I've tested the live upgrade. We are inputting the cluster and storage network to the `controller --replica` argument so it shouldn't break the live upgrade.
https://github.com/longhorn/longhorn/pull/3277#discussion_r772781052

2021-12-21 06:28 UTC, jenting reviewed
The only part I don't quite understand now is how we tackle the backing image data source Pods.
- Should we add annotations to the backing image data source Pods?
- Should the baking image data source Pods be restarted after annotations?
- Should we add the `status.storageIP` to the backing image data source CRD?

2021-12-21 06:28 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be the network interface IP from the parent manager's `storage-network` interface. The `k8s.v1.cni.cn
Could you please elaborate more on who is the parent manager? The longhorn-manager _or_ Multus manager?

2021-12-21 06:28 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- When updating the *storage-network* `Setting`, Longhorn will restart all instance manager `Pods` and backing image manager `Pods` to apply the CNI annotations.
Because I saw the above line would annotate the backing image data source Pods, so I'm wondering should the backing image data source Pods should be restarted or not.

2021-12-21 06:28 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
May I say that the value of `--url` and `<pod IP>` are the same?

2021-12-21 06:50 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- For data-related commands must include cluster address and the storage address. Use the existing global `--url` command argument as the service URL for GRPC operations. Provide storage address to t
Mostly true except for the controller. [here](https://github.com/longhorn/longhorn-manager/blob/master/manager/engine.go#L220) -> [here](https://github.com/longhorn/longhorn-manager/blob/master/engineapi/engine.go#L49) -> [here](https://github.com/longhorn/longhorn-manager/blob/master/engineapi/engine.go#L61-L74)

2021-12-21 08:22 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- When updating the *storage-network* `Setting`, Longhorn will restart all instance manager `Pods` and backing image manager `Pods` to apply the CNI annotations.
The annotation will be applied for the new backing image data Pod. Since the backing image data source Pods requires volume to be attached, users will not be able to update the storage-network Settings.

2021-12-21 08:37 UTC, c3y1huang commented
> The only part I don't quite understand now is how we tackle the backing image data source Pods.
> 
> * Should we add annotations to the backing image data source Pods?

Yes, for data fetch from replica.

> * Should the baking image data source Pods be restarted after annotations?

No, user will not be able to update the storage-network setting while volume is attached.

> * Should we add the `status.storageIP` to the backing image data source CRD?

IMO No, the backing image data source Pods will be removed once it finishes data fetch. I couldn't think where Longhorn could use that info.

2021-12-21 08:47 UTC, jenting commented on enhancements/20211118-storage-network-with-multus.md
> +- When updating the *storage-network* `Setting`, Longhorn will restart all instance manager `Pods` and backing image manager `Pods` to apply the CNI annotations.
I see.

2021-12-21 09:20 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Replace single string address in `replicaAddressMap` with maps of cluster address and storage address in the `Engine` CRD.
Thanks, reworded.

2021-12-21 09:21 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Monitor for `NetworkAttachmentDefintition` CRs. This means the user will need to ensure the traffic is reachable between `Pods` and across different `Nodes`. Without monitoring, Longhorn will not g
Thanks, fixed.

2021-12-21 09:23 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be the network interface IP from the parent manager's `storage-network` interface. The `k8s.v1.cni.cn
Reworded.

2021-12-23 03:54 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be the network interface IP from the corresponding manager `Pod` `storage-network` interface; the cor
After discussing with @shuo-wu , using `BackingImageDataSource` `storageIP` makes more sense instead of checking the second network interface in Pod. I will update it later.

/cc @jenting

2021-12-23 05:58 UTC, yasker commented
One question @shuo-wu raised in https://github.com/longhorn/longhorn/pull/3277#discussion_r773112940 is, is it possible for us to use one IP for engine and replica?

Engine and replica can communicate via the storage IP. And Instance Manager can start engine and replica processes using the storage IP.

However, we need to decide what IP to use for the Longhorn manager to communicate with Instance Manager, Engine process, and implicitly replica process (via e.g. backup command). There are two scenarios:
1. The cluster network is routable to the storage network. Then the Longhorn manager can communicate with IM, engine, and replica without any problem.
    * But then we will require additional routing rules for those networks.
2. The cluster network is NOT routable to the storage network. Then either IM, engine, and replica need to have two IPs (one for each network) to keep the communication, or Longhorn Manager needs to be in the storage network as well. 
    * But it's hard to put Longhorn Manager in the storage network since that means Longhorn Manager needs to modify it's own spec. 
    * Can we mitigate the issue by only putting IM in charge of the communication, and keeping the single IP for engine and replica? That means Longhorn Manager won't have direct access to the engine and replicas, which is hard to implement in the current architecture. 

In the end, I feel the dual IP approach is probably the most flexible solution at the moment.

However, can we run the engine binary for communication in the IM instead of the Manager pod? If we can do that, we can avoid mgr directly communicate with the engine and replica, so keep the single IP for the engine and replica.

2022-01-03 09:40 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be the network interface IP from the corresponding manager `Pod` `storage-network` interface; the cor
I've revisited this logic and am not sure if applying `storageIP` to `BackingImageDataSource` makes sense.

The `BackingImageDataSource` can only get and update its `storageIP` after the backing image data source Pod is created. Currently, the backing image manager used `status.podIP` to export volume. So for this to work somehow we need to update the Pod again so it contains the storageIP from the `BackingImageDataSource`?

I think it's more straightforward if we check for the secondary network when doing volume export. What do you think @shuo-wu ?

2022-01-03 13:00 UTC, c3y1huang commented on enhancements/20211118-storage-network-with-multus.md
> +- Introduce new `storageIP` status in `Engine`, `Replica` and `BackingImageManager` CRDs. It will be the network interface IP from the corresponding manager `Pod` `storage-network` interface; the cor
After discussing with @shuo-wu , it's not easy to get the `storageIP` into the `BackingImageDataSource` Pod without adding a new API. Another way we agreed is to specify the interface name with the annotation and check for the pod network interface matching the annotated interface name.

2022-01-04 02:49 UTC, yasker commented
Talked with @c3y1huang . Since the code is almost ready, let's see how does it look like to implement the dual IP for the engine. It's the more flexible approach. The only concern I have is the complexity.

2022-01-05 00:57 UTC, c3y1huang commented
Ran the coretest yesterday and there are still 2 unexpected fails that require time to fix before I wrap up for the draft PR.

Shuo also suggested tackling https://github.com/longhorn/longhorn/issues/2821 with this issue so there is no engine binary invocation so keeping single IP for the engine and replica.

IMO if we decided to include https://github.com/longhorn/longhorn/issues/2821 in v1.3.0, then it would be best to tackle it together as Shuo suggested.

2022-01-05 02:47 UTC, shuo-wu commented
> @shuo-wu also suggested tackling #2821 with this issue so there is no engine binary invocation and use IM for proxy so keeping single IP for the engine and replica.
> 
> IMO if we decided to include #2821 in v1.3.0, then it would be best to tackle it together as @shuo-wu suggested.

If allowing a process to use a single (storage network) IP is preferred, I would suggest handling #2821 first.

2022-01-05 14:19 UTC, innobead commented
> > @shuo-wu also suggested tackling #2821 with this issue so there is no engine binary invocation and use IM for proxy so keeping single IP for the engine and replica.
> > IMO if we decided to include #2821 in v1.3.0, then it would be best to tackle it together as @shuo-wu suggested.
> 
> If allowing a process to use a single (storage network) IP is preferred, I would suggest handling #2821 first.

It seems we would like to have single IP to avoid complicated dual IP management, but the precondition is to have IM as a proxy to serve the requests from LM. 

If that's the case, what efforts will probably be introduced?
- A new proxy server in IM
- Extra requests processing and dispatching to the downstream engine/replica servers (controller/replica server)
- If the proxy dies, the downstream communications will not work. This is different from the current design that each communication between LM and engine/replica process is independent.

I do care about potential extra costs possibly introduced to IM pods, and then it will probably impact the stability of engine/replica processes. Dual IPs will not introduce extra resource costs instead of complicated IP management. 

This is a trade-off I would say but still encourage you guys to figure out the pros and cons, then update this LEP.

2022-01-06 11:20 UTC, c3y1huang commented
After discussing with @innobead and @shuo-wu , we have reached a consensus to add in the gRPC proxy. The communication between MGR and IM will use the cluster network then proxy to engine/replica processes via the storage network.

pros:
The long stream connection to replace MGR calls for engine binary. This should improve manager performance.
The is no direct communication between MGR and engine/replica processes so keeping single IP to the processes.
In case of disconnection, the client should automatically restore, and the proxy is running along with the gGRPC server which life cycle is the same as the IM pod.
Fits better with the SPDK implementation.

cons:
There is no upper bound to the IM pod, hence when the resource consumed reached the host's upper bound might make the node unresponsive. However, the assumption is proxy shouldn't cost too much extra overhead since they are in the same pod. After implementation, we should do some performance tests.

2022-05-03 12:53 UTC, innobead requested changes
In general, LGTM.

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - Check for the existing gRPC client in the _proxyHandler_, and check the connection liveness with the `Ping` request.
Suggest adding the context for this and the following statements only if at least one volume is attached. If no volumes on that node, there should be no any engine client connections.

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +    type EngineClient interface {
I would suggest just using embedded interface w/ reusing the existing interfaces instead if possible. Usually for any exposed interfaces, we will not just update but rather extend w/ another interface, so we are still able to retrieve the corresponding implementation based on a different interface.

```golang
type EngineClientProxy interface {
    EngineClient
    BackupTargetClient
    
    IsGRPC() bool
    ResetAndStopProxyClient(*longhorn.InstanceManager) error
    Start(*longhorn.InstanceManager, logrus.FieldLogger, *datastore.DataStore) error
    Ping() error
}
```

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +    	ResetAndStopProxyClient(*longhorn.InstanceManager) error
Why not just use `Stop` for the method name?

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - The setting should be in the form of `< NAMESPACE>/<NETWORK-ATTACHMENT-DEFINITION-NAME>`.
Need to have a validation in validation webhook.

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Use the replica `status.storageIP` instead of the replica `status.IP` for the replicaAddressMap.
Why not using the same variable but have another flag to determine this IP is from the storage network?

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +1. Get the IP from instance manager Pod annotation `k8s.v1.cni.cncf.io/network-status`. Use the IP for `Engine` and `Replica` Storage IP. When the `storage-network` setting is empty, The Storage IP w
It seems we can just use the original variable `IP` for all cases, because you still use `StorageIP` adaptively here.

2022-05-03 12:53 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +1. Do not update the `storage-network` setting and return an error when `Volumes` are attached.
I feel there will probably a timing issue for this validation at runtime, and how can you validate this during the upgrade case if users configure the storage network in values.yaml, then upgrade the chart?

If this is not 100% granted validation, I would suggest letting users configure, but it will take effect only if all volumes detached. However, we can have a tip info next to the setting description.

2022-05-04 10:11 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Add Longhorn Manager to the storage network. The Manager needs to restart itself to get the secondary storage network IP.
Addressed.

2022-05-04 10:12 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Use the management network for Manager to Instance Manager communication.
Updated.

2022-05-04 10:12 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Use the storage network for in-cluster data traffic.
Updated.

2022-05-04 10:16 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Support backward compatibility of existing engine instance manager after upgrade.
Updated

2022-05-04 10:16 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +### Proxy Manager request through Instance Manager gRPC proxy
Updated.

2022-05-04 10:18 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Allow falling back to engine binary calls when gRPC connection to Instance Manager is not available.
Updated.

2022-05-04 10:59 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - Check for the existing gRPC client in the _proxyHandler_, and check the connection liveness with the `Ping` request.
There will be one gRPC connection for each `controllerID`. I think we should keep the connections persistent to avoid the on/off intermediate state.

2022-05-04 11:00 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +    type EngineClient interface {
Updated.

2022-05-04 11:02 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +    	ResetAndStopProxyClient(*longhorn.InstanceManager) error
Sounds good, updated.

2022-05-04 11:02 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - The setting should be in the form of `< NAMESPACE>/<NETWORK-ATTACHMENT-DEFINITION-NAME>`.
Reworded.

2022-05-04 11:06 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Use the replica `status.storageIP` instead of the replica `status.IP` for the replicaAddressMap.
We need to keep dual IP for the Manager to Backing Image Manager communication. Therefore, having the same storageIP in engine/replica status for consistency.

2022-05-04 11:06 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +1. Get the IP from instance manager Pod annotation `k8s.v1.cni.cncf.io/network-status`. Use the IP for `Engine` and `Replica` Storage IP. When the `storage-network` setting is empty, The Storage IP w
https://github.com/longhorn/longhorn/pull/3277#discussion_r864709057

2022-05-04 11:54 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - Check for the existing gRPC client in the _proxyHandler_, and check the connection liveness with the `Ping` request.
Ok, let's keep it as is first. It's actually nice to have.

2022-05-04 14:44 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - The EngineClient interface is used for `Proxy`, existing `Engine` and existing `BackupTargetClient`. Update any inconsistent collection of methods.
This statement looks a little confusing, but I guess what you want to explain is:

`A new EngineClientProxy interface will be introduced for the Proxy, which includes proxy specific methods and implementation of the existing EnglineClient and BackupTargetClient interfaces. This will be adaptive when using EngineClient  for the proxy or non-proxy/fallback case.`

2022-05-04 14:47 UTC, innobead submitted a review, later dismissed
LGTM

2022-05-05 00:39 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +  - The EngineClient interface is used for `Proxy`, existing `Engine` and existing `BackupTargetClient`. Update any inconsistent collection of methods.
Exactly, updated.

2022-05-05 13:25 UTC, shuo-wu reviewed
LGTM except for the live upgrade issue.

2022-05-05 13:25 UTC, shuo-wu commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Will we disable the volume/engine live upgrade in v1.3.0?

2022-05-06 01:14 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Actually what I meant is the volume/engine live upgrade will be blocked by [CheckInstanceManagerCompatibilty](https://github.com/longhorn/longhorn-manager/blob/master/engineapi/instance_manager.go#L247). 
This means after the cluster upgrade, the volume needs to do a detach/attach first to restart the processes. Then the user can do the volume engine live upgrade.

2022-05-06 01:25 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Reworded.

2022-05-06 03:14 UTC, shuo-wu commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
For the old volumes, Longhorn should fall back to using the binary. And using binary means using the old version of IM client, Then can we do live upgrade in this case?

2022-05-06 03:27 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
We could probably work around the current IM compatibility check with some logic
```
if im.Status.APIVersion == InstanceManagerProxyMinAPIVersion {
}
```
But I feel if we enforce the volume detach/attach in this version we can ensure the engine binary is safe to deprecate in the next major release. What do you think?

2022-05-06 03:31 UTC, shuo-wu commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Personally, I prefer your idea. But we cannot determine this. 😂.
cc @innobead

2022-05-06 03:38 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
After talking to @innobead 
```
For better support perspective, we should do:
- keep live upgrade well, but we will claim the old way (engine-binary) being deprecated in 1.4

This will be a soft notice for users to know we will not enforce any change in 1.3, but it will happen in 1.4
```

2022-05-06 03:41 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Updated.

2022-05-06 03:41 UTC, innobead commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
- Should support live upgrade as usual
- For deprecate engine binary, we can do it in 1.4 instead, but users should be noticed this change in our doc/release note. 

Basically, for any enforced change, we should avoid doing it at the same time when it's introduced. WDYT

2022-05-06 03:47 UTC, c3y1huang commented on enhancements/20220428-storage-network-through-grpc-proxy.md
> +- Do not support because of the instance manager API version bump.
Got it. Sounds fair to me.

2022-05-10 00:51 UTC, innobead approved these changes

2022-05-10 00:52 UTC, merged