Update CRD with v1beta1 and v1beta2
longhorn/longhorn pull request #3366
Opened 2021-12-03 06:41 UTC by derekbit

Longhorn 2955

Signed-off-by: Derek Su <derek.su@suse.com>

2021-12-06 13:01 UTC, jenting requested changes

2021-12-06 13:01 UTC, jenting commented on chart/templates/crds.yaml
> +  labels:
Please add this back `{{- include "longhorn.labels" . | nindent 4 }}`, similar below.

2021-12-07 03:38 UTC, jenting approved these changes

2021-12-07 03:44 UTC, innobead approved these changes

2021-12-07 03:44 UTC, merged