Allow to add annotations on the serviceAccount managed by the helm chart
longhorn/longhorn pull request #3432
Opened 2021-12-17 16:05 UTC by signaleleven

This is necessary, for instance, to instruct EKS to assign an IAM role to workloads using the serviceaccount (similar to kube2iam and kial, but EKS specific)

Signed-off-by: Michael Sacchi <michael.sacchi@signal-eleven.com>

2021-12-21 06:18 UTC, jenting requested changes

2021-12-21 06:18 UTC, jenting commented on chart/templates/serviceaccount.yaml
> +  {{- with .Values.annotations }}
```suggestion
  {{- with .Values.serviceAccount.annotations }}
```

2021-12-21 07:59 UTC, jenting commented
Would you mind squashing the commits into one?

2021-12-21 22:58 UTC, jenting approved these changes

2022-01-03 06:31 UTC, innobead approved these changes
LGTM

2022-01-03 06:31 UTC, merged