Add ServiceMonitor and PrometheusRule.
longhorn/longhorn pull request #3580
Opened 2022-01-30 02:31 UTC by reitermarkus

Allow easily enabling monitoring and alerts for volumes.

2022-01-30 20:29 UTC, reitermarkus commented
I took the examples from https://longhorn.io/docs/1.2.3/monitoring/alert-rules-example/, i.e. https://github.com/longhorn/website/blob/450c526feaffce56ed2f8eafcc0ee76736bbe7f7/content/docs/1.2.3/monitoring/alert-rules-example.md.

It seems to me that the `LonghornVolumeActualSpaceUsedWarning` is pretty useless since almost all of my volumes have an actual size that is > 100% of the normal size. Am I right in this assumption, or should I be increasing all my volumes sizes to fit the actual size?

2022-02-12 21:36 UTC, reitermarkus commented
@jenting, any comment on the usefulness of the `LonghornVolumeActualSpaceUsedWarning`?

2022-02-14 10:56 UTC, innobead commented
> It seems to me that the `LonghornVolumeActualSpaceUsedWarning` is pretty useless since almost all of my volumes have an actual size that is > 100% of the normal size. Am I right in this assumption, or should I be increasing all my volumes sizes to fit the actual size?

@shuo-wu it seems related to a recent topic people are asking about `why actual size large than the volume size`. If that's the case, probably we need to revisit how to make this alert much more meaningful? 

cc @PhanLe1010

2022-02-14 12:03 UTC, shuo-wu commented
Yes. We need a separate doc that explains why and when the actual size can be greater than the spec size.

2022-02-14 12:32 UTC, innobead approved these changes
LGTM

2022-02-14 17:45 UTC, reitermarkus commented
> why and when the actual size can be greater than the spec size

I think I understand why it is larger: The actual size includes all snapshots.

The warning will be shown when the actual size is bigger than the allocated size, so my question was: Is a warning for this condition meaningful? I think this will happen with pretty much any volume once you have enough snapshot, won't it?

If the warning is meaningful, what is the correct path forward to fix it?

2022-02-14 22:34 UTC, PhanLe1010 requested changes
> The warning will be shown when the actual size is bigger than the allocated size, so my question was: Is a warning for this condition meaningful? I think this will happen with pretty much any volume once you have enough snapshots, won't it?

I think this alert is meaning full to detect the case in which a volume has too many snapshots that the actual size is much bigger than the spec size (i.g. by 5 times). Users can change the threshold value to 2x/3x/4x/.. depending on their use case.

2022-02-14 22:34 UTC, PhanLe1010 commented on chart/values.yaml
> +  enabled: false
The metrics are always exposed by default. Can we make it clear that this field enables the Prometheus service monitor?
```suggestion
  prometheusServiceMonitor:
    enabled: false
```

2022-02-14 22:35 UTC, PhanLe1010 commented
Linking this PR to the corresponding issue https://github.com/longhorn/longhorn/issues/1473

2022-02-15 07:42 UTC, innobead requested changes

2022-02-15 07:42 UTC, innobead commented on chart/templates/prometheusrules.yaml
> +          expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
Just a revisit. I think it's also good to have the percentage here configurable w/ a default value, so users are able to adjust based on their need. 

The same suggestion is applying to other % rule expressions.

2022-02-15 08:03 UTC, shuo-wu commented
The doc/explanation related to the volume actual size is tracked in https://github.com/longhorn/longhorn/issues/3627

2022-02-22 14:01 UTC, innobead commented
ping @reitermarkus a few comments ☝️ waiting to resolve

2022-02-24 00:35 UTC, jenting commented on chart/values.yaml
> +        threshold: 90 # warn when above this percentage
Any reason _why only_ make this threshold configurable?

2022-02-24 03:27 UTC, reitermarkus commented on chart/values.yaml
> +        threshold: 90 # warn when above this percentage
I didn't want to make too many more changes here since I migrated my cluster to Talos which doesn't support Longhorn at the moment so I have no way to test any more changes currently.

2022-03-17 03:13 UTC, jenting commented on chart/values.yaml
> +  ## Enable a default set of Prometheus alerting rules.
Providing a default Prometheus service monitor is good.

I'm thinking that should we provide the default Prometheus rules in the helm chart? Since different users _probably_ would like to change different thresholds.

2022-03-18 07:04 UTC, innobead commented on chart/values.yaml
> +  ## Enable a default set of Prometheus alerting rules.
I would suggest exposing all adjustable thresholds w/ default values.

2022-06-02 08:04 UTC, wirwolf commented
Hello. I copy these rules to my helm chart
https://github.com/SomeBlackMagic/helm-charts/tree/master/charts/longhorn-monitoring
In this chart, i can disable some rules or change the severity level.

2022-09-07 20:44 UTC, HujinoKun commented
any ETAM?

2023-08-24 11:18 UTC, innobead commented
This contribution seems pending for a long while w/o an update. Let's follow up with https://github.com/longhorn/longhorn/issues/6585 instead.

@reitermarkus feel free to reopen and continue this contribution if you want. Thanks.

2023-08-24 11:18 UTC, closed without merging