Allow use of existing private registry secret
longhorn/longhorn pull request #3673
Opened 2022-02-27 10:54 UTC by wilson1999112

Signed-off-by: wilson1999112 <wilson1999112@gmail.com>

2022-02-27 10:56 UTC, wilson1999112 commented
Hi @innobead,
The PR addresses issue #2157
There are 3 ways to install longhorn as mention in the doc: 
1. Using a Manifest File
2. Using a Helm Chart
3. Using a Rancher App

For 1., just type the name of the existing private registry secret.

For 2./3., modify `chart/values.yaml`.
For example in `chart/values.yaml`:
1. If you want to create a new secret for longhorn, enter your user/pass like this:
```
privateRegistry:
  secretCreation: true
  registryUrl: <REGISTRY_URL>
  registryUser: <REGISTRY_USER>
  registryPasswd: <REGISTRY_PASSWORD>
  registrySecret: <REGISTRY_SECRET_NAME>
```
2. if you want to make use of the existing private registry secret, enter your user/pass like this:
```
privateRegistry:
  secretCreation: false
  registryUrl: <REGISTRY_URL>
  registryUser: ~
  registryPasswd: ~
  registrySecret: <REGISTRY_SECRET_NAME>
```

2022-02-28 02:30 UTC, jenting requested changes
We need to update the `question.yaml` as well.

2022-02-28 06:31 UTC, wilson1999112 commented
> We need to update the `questions.yaml` as well.

addressed, thank you.

2022-02-28 16:01 UTC, innobead requested changes

2022-03-01 02:31 UTC, wilson1999112 commented on chart/questions.yaml
> +  label: Secret creation
done!

2022-03-17 03:05 UTC, jenting reviewed
We could consider moving lines 145-162 under line 170, which makes the UX more intuitive.
- WAS
![image](https://user-images.githubusercontent.com/49380831/158728410-1b85678e-38a0-42f9-8ffd-d401a0e44175.png)

- IS
![image](https://user-images.githubusercontent.com/49380831/158728358-a7b46a98-c2eb-4c25-846b-64059bbfe992.png)

2022-03-17 03:05 UTC, jenting commented on chart/questions.yaml
> +    description: "User used to authenticate to private registry"
```suggestion
    description: "User used to authenticate to private registry."
```

2022-03-17 03:05 UTC, jenting commented on chart/questions.yaml
> +    description: "Password used to authenticate to private registry"
```suggestion
    description: "Password used to authenticate to private registry."
```

2022-03-17 03:05 UTC, jenting commented on chart/questions.yaml
> +  description: "If create secret is true, create a Kubernetes secret with this name; else use the existing secret of this name. Use it to pull images from your private registry."
```suggestion
  description: "If create a new private registry secret is true, create a Kubernetes secret with this name; else use the existing secret of this name. Use it to pull images from your private registry."
```

2022-03-18 04:15 UTC, jenting approved these changes
I helped address the comment.

LGTM

2022-03-18 05:49 UTC, innobead approved these changes
LGTM

2022-03-18 05:50 UTC, merged

2022-04-06 09:35 UTC, innobead commented on chart/questions.yaml
> +  description: "If create a new private registry secret is true, create a Kubernetes secret with this name; else use the existing secret of this name. Use it to pull images from your private registry
Ok this has been updated actually cc @c3y1huang @kaxing