chart: set securityContext of webhook
longhorn/longhorn pull request #3702
Opened 2022-03-05 08:26 UTC by derekbit

Longhorn #3701

Signed-off-by: Derek Su <derek.su@suse.com>

2022-03-05 13:53 UTC, jenting submitted a review, later dismissed

2022-03-08 08:43 UTC, innobead requested changes

2022-03-08 08:43 UTC, innobead commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
This is like a workaround, because webhook containers don't really need to run in privileged mode. (I know we are reusing longhorn-manager image)

What about adding another non-default user in longhorn-manager image, then we specify `runAsUser` instead? Then, we can keep the least privilege principle, although this is still not a perfect way for me.

2022-03-09 03:23 UTC, derekbit commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
> this is still not a perfect way for me

What's the better way to this issue except for the `runAsUser`?

2022-03-09 03:53 UTC, innobead commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
The default user in the image is non-root then we don't need to update the spec actually.

2022-03-09 05:19 UTC, derekbit commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
IIUC

We can add the uid and gid creation to the longhorn-manager Dockerfile
```
# Use an unprivileged user
RUN groupadd -g 10001 longhorn
RUN useradd -m -u 10001 longhorn -g longhorn
USER 10001:10001
```

By default, the webhook will run with user 10001.

But, the `runAsUser: 0` needs to be added in the remaining containers using longhorn-manager image those need to run with `root`.

Correct?

2022-03-09 05:21 UTC, derekbit commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
IIUC

We can add the uid and gid creation to the longhorn-manager Dockerfile

# Use an unprivileged user
RUN groupadd -g 10001 longhorn
RUN useradd -m -u 10001 longhorn -g longhorn
USER 10001:10001
By default, the webhook will run with user 10001.

But, the runAsUser: 0 needs to be added in the remaining containers using longhorn-manager image those need to run with root.

Correct?

2022-03-09 05:29 UTC, innobead commented on chart/templates/deployment-webhook.yaml
> +          privileged: true
As discussed, just add `runAsUser` w/o updating the Dockerfile, because longhorn-manager is still used by other components which need root and privileged mode.

2022-03-09 05:41 UTC, innobead approved these changes

2022-03-09 05:41 UTC, merged