Add LEP 'Snapshot Prune'
longhorn/longhorn pull request #3754
Opened 2022-03-17 13:05 UTC by shuo-wu

Longhorn#3613

2022-03-17 20:55 UTC, yasker requested changes
It seems the whole LEP is talking about `removed snapshot` but somehow referring to it as `snapshot`.

2022-03-18 19:04 UTC, yasker approved these changes
The content LGTM. Have some grammar errors though.

2022-03-18 19:04 UTC, yasker commented on enhancements/20220317-snapshot-prune.md
> +When the snapshot purge is triggered, replica will identify if the snapshot being removed is the latest snapshot by checking one child of it is the volume head. If YES, it will start the snapshot pru
We need to make sure this is done only **after** all the other snapshots have done coalescing and deletion.

2022-03-21 08:42 UTC, innobead approved these changes
LGTM

2022-03-21 08:43 UTC, merged

2022-03-21 08:43 UTC, innobead commented
cc @longhorn/dev for this new introduction.