Add LEP - Support K8s CA
longhorn/longhorn pull request #3831
Opened 2022-04-08 12:20 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/2203

2022-04-11 03:32 UTC, shuo-wu requested changes

2022-04-11 03:32 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +- Pods with [local storage volume mounts]( local storage volume mounts) (longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter).
How about share manager pods and backing image datasource/manager pods?

For backing image manager pods, if the disk/node contains the only file of one backing image, then you cannot add the annotation for the pod.

For share manager pods, the eviction means you need to stop the RWX volume service for a while and relaunch them on other nodes. Probably we cannot do anything for this until HA RWX support is done.

2022-04-11 03:32 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +- Delete engine IM PBD when the volume is detached.
Do you mean actively deleting the PDB when there is no process in the IM? It's better to add more details here. e.g., the new PDB sync-up function logic would be like:
1. Check if the PDB can be deleted (I am not sure if the following conditions are corrects or not, will leave them to you for further verifications)
    1. If the node is already gone/tainted/...
    2. If the IM or IM pod is already gone
    3. For engine IM PDB, if there is no engine process......
    4. For replica IM PDB, If there is no replica scheduled......
2. Check if the PDB can be created
    1. volume attachment requirement
    2. replicas are scheduled
    3. ......

2022-04-11 03:32 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +Given Enable `kubernetes-autoscaler-support` setting.
How about the cluster config?

2022-04-11 03:32 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +And annotate new nodes with `scale-down-disable` to test when CA tries to scale-down all volume replica nodes.
You mean disabling the scaling down for the new node that does not contain any volume replica, then check if CA could kick out the 2 other nodes?

2022-04-11 03:32 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +### Test plan
As I mentioned above, need to have tests with backing images or share managers

2022-04-11 04:32 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Pods with [local storage volume mounts]( local storage volume mounts) (longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter).
ATM I don't think there is anything we could do about backing image datasource/manager, and share manager pods. The nodes running with those pods will be blocked by CA local storage condition.

2022-04-11 07:02 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +# Support Kubernetes CA
Addressed.

2022-04-11 07:04 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +Given Enable `kubernetes-autoscaler-support` setting.
Updated.

2022-04-11 07:04 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +And annotate new nodes with `scale-down-disable` to test when CA tries to scale-down all volume replica nodes.
Reworded.

2022-04-11 07:04 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +### Test plan
Added.

2022-04-12 02:45 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +- Pods with [local storage volume mounts]( local storage volume mounts) (longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter).
For the backing image manager, I think we can do something here. 
As I mentioned, if all backing image files on the node contain duplicates, it's fine to add annotation `cluster-autoscaler.kubernetes.io/safe-to-evict` for the related backing image manager.
The backing image managers won't remove the related files immediately when there is no replica using them. There is a setting named `Backing Image Cleanup Wait Interval` controlling it. Hence, this may unnecessarily block CA.
Of course, the handling of the backing image manager is nice to have. If it makes the logic too complicated, we can skip it now.

2022-04-12 03:07 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - The replica has been started. There are no other schedulable nodes with healthy volume replica and have replica IM PDB.
How about other corner cases I mentioned before? Maybe we can revisit this after the implementation

2022-04-12 03:12 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +And cluster should have 2 nodes.
The statement here is a little bit confusing...

2022-04-13 01:37 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Pods with [local storage volume mounts]( local storage volume mounts) (longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter).
After the internal meeting discussion, this feature will be marked experiential and will skip handling of the CA blocked by backing image manager/share manager pod for now.

2022-04-13 01:43 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +And cluster should have 2 nodes.
Updated.

2022-04-13 02:10 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - The replica has been started. There are no other schedulable nodes with healthy volume replica and have replica IM PDB.
I mean, the node is already gone/tainted, or the IM or IM pod is already gone. Some cases are already handled in the current implementation. You may need to reorganize them during this implementation.

2022-04-13 02:20 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +And CA scale-down should be blocked by replica instance-manager pod PDB.
I am thinking we can delete the engine IM PBD but keep at least 1 replica IM PBD when the volume is detached.

2022-04-13 02:22 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +And CA scale-down should be blocked by share manager local storage mount.
Removed.

2022-04-13 03:36 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +        - The replica has been started. There are no other schedulable nodes with healthy volume replica and have replica IM PDB.
Added the implementation to cover node un-schedulable case.

2022-04-13 11:52 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There is no engine instance process in IM (im.Status.Instance)
NIT: When handling the Replica IM PDB, there is no need to consider engine processes.

2022-04-13 11:52 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
If the processes are redundant replica processes, will the replica IM PDB be removed then get recreated immediately?

2022-04-13 13:00 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +Longhorn considers a node can be removed when conditions are met, else it will block scale down to avoid potential data loss:
How about pods w/ local storage volume mounts mentioned above? the nodes they are running on will never be eligible for cluster autoscaler, right?

2022-04-13 13:05 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Volume attached
```suggestion
    - Any volume attached
```

2022-04-13 13:08 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Volume detached and can find another schedulable node with volume replica and replica IM PDB.
```suggestion
    - All volume detached, replicas of each detailed volume should be replicated to other schedulable nodes protected by replica IM PDB.
```

2022-04-13 13:08 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Not contain a backing image pod
```suggestion
    - Not contain a backing image manager pod
```

2022-04-13 13:10 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +- share-manager node not running on the node.
You can reuse the goals you mentioned above because these are the same.

2022-04-13 13:24 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate managed deployments with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager` (longhorn-ui, longhorn-csi-plugin
```suggestion
- Annotate managed deployments with local storage volume mounts with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager` (longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, and csi-snapshotter).
```

2022-04-13 13:26 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
This seems like a side-effect caused by the redundant replicas, so probably we should not tackle this here?

2022-04-13 14:07 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    When Annotate new nodes with `scale-down-disable`.
Do you mean `cluster-autoscaler.kubernetes.io/scale-down-disabled`? It's better to describe clearly.

2022-04-13 14:10 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
Is the deployment having a volume?

2022-04-13 14:12 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +    When Trigger CA to scale-up by increase deployment replicas.
Do you mean the deployment replicas w/ node affinity to enforce a new node is needed?

2022-04-13 14:16 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +#### Scenario: test CA should block scale down of node running backing image manager pod
```suggestion
#### Scenario: test CA should block scale down of node running backing image manager/share manager pod
```

2022-04-13 14:18 UTC, innobead reviewed
In general, LGTM. However, some comments needed to be resolved/answered. 

Just ensure we will make this an experimental feature in 1.3.0.

2022-04-14 01:51 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There is no engine instance process in IM (im.Status.Instance)
Fixed.

2022-04-14 01:57 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +Longhorn considers a node can be removed when conditions are met, else it will block scale down to avoid potential data loss:
Reworded.

2022-04-14 01:57 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Volume attached
Fixed.

2022-04-14 01:57 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Contain backing image pod
Fixed.

2022-04-14 01:57 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Contain share manager pod
Fixed.

2022-04-14 02:05 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Volume detached and can find another schedulable node with volume replica and replica IM PDB.
Hmm..the suggested change looks like we will rebuild the replicas to another node. 

This is a condition statement to ensure the last replica of the detached volume is protected and we do not rebuild replicas to another node.

2022-04-14 02:05 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Not contain a backing image pod
Fixed.

2022-04-14 02:07 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- share-manager node not running on the node.
Maybe we don't need to duplicate this, I've removed this block.

2022-04-14 02:07 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    - Engine/Replica instance-managerPDB will block the node if the volume is attached.
Fixed.

2022-04-14 02:11 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate managed deployments with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager` (longhorn-ui, longhorn-csi-plugin
Fixed.

2022-04-14 02:11 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    When Annotate new nodes with `scale-down-disable`.
Fixed.

2022-04-14 02:16 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
The deployment does not need volume, this is used to trigger CA scaling and will contain CPU requests.
```
        resources:
          limits:
            cpu: 300m
            memory: 30Mi
          requests:
            cpu: 150m
            memory: 15Mi
```

2022-04-14 02:21 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    When Trigger CA to scale-up by increase deployment replicas.
The deployment does not need node affinity. We will increase the deployment replica numbers and let it consume more CPU resources than the cluster nodes can provide. This triggers CA to scale up and vice versa.

2022-04-14 02:23 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Volume data should be the same.
Are you referring to `And Volume data should be the same.`?
This is followed by the `Then` statement above.

2022-04-14 02:25 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +#### Scenario: test CA should block scale down of node running backing image manager pod
https://github.com/longhorn/longhorn/pull/3831#discussion_r847911269

2022-04-14 02:41 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
I mean, the replica on the node is not the only healthy one of a volume. In the above deletion logic, the PDB will be removed since this kind of replica won't prevent the deletion. But the controller will recreate the PDB immediately based on this line.

2022-04-14 03:18 UTC, shuo-wu reviewed
BTW, you can add TODOs for backing image manager and share manager handling.

2022-04-14 03:18 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate engine and replica instance-manager pods when no IM not in state stop/error.
I am confused about this. Why cannot we annotate the IM pods when the IM is state stop or error? As long as the PDBs are handled correctly, I don't think we need to consider the pods.

2022-04-14 03:18 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +When setting `kubernetes-cluster-autoscaler-enabled` to `true`:
```suggestion
When setting `kubernetes-cluster-autoscaler-enabled` is `true`, Longhorn will add annotation `cluster-autoscaler.kubernetes.io/safe-to-evict` for the following pods:
```

2022-04-14 03:18 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate managed deployments using local storage volume mounts with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager`
```suggestion
The workloads that are managed by longhorn-manager and contain local storage. The managed components are labeled with ......
```
BTW, do we need to handle longhorn-manager?

2022-04-14 03:40 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
We will only remove the PDB of the detached volume, and only if there is another node with the same volume replica IM PBD. In case all replicas are on the same node of the detached volume, then all replica IM PDB will get created and none will get removed.

2022-04-14 04:06 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate engine and replica instance-manager pods when no IM not in state stop/error.
> I am confused about this. Why cannot we annotate the IM pods when the IM is state stop or error? 

We can probably disregard the IM state. Updated.

> As long as the PDBs are handled correctly, I don't think we need to consider the pods.

We need to consider the pods because they are bare pods and also using local storage mounts that will not pass the CA pre-check.

2022-04-14 04:08 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +When setting `kubernetes-cluster-autoscaler-enabled` to `true`:
Updated.

2022-04-14 04:08 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate managed deployments using local storage volume mounts with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager`
Updated.

2022-04-14 04:10 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +- Annotate managed deployments using local storage volume mounts with `cluster-autoscaler.kubernetes.io/safe-to-evict`. Managed deployments are labeled with `longhorn.io/managed-by: longhorn-manager`
> BTW, do we need to handle longhorn-manager?

No. CA pre-check bypasses DaemonSets.

2022-04-14 04:30 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Volume data should be the same.
I think what happens here is:
1. Volume rebuilds new replicas on other nodes.
2. The CA finally evicts the blocking node which previously contains the only replica. This means the cluster node number should be the same as that at the beginning.
3. The volume data is still intact after the rebuilding & eviction.

You may need to explicitly mean the 2nd behavior & result.

2022-04-14 04:31 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
You can put this example here.

2022-04-14 05:21 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
the PDB of the detached volume?? another node with the same volume replica IM PBD?? Sorry I cannot follow...

2022-04-14 05:28 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
I think we can describe this part from another perspective: The IM PDB will be created **and retained** only when it's required. And once it's required, we cannot delete the PDB. Required means either of the following happen:
  1. There are volumes/engines running on the node. We need to guarantee that the volumes won't crash
  2. The only available/valid replica of a volume is on the node, no matter whether the volume itself is detached or not. Here we need to prevent the volume data from being lost.

2022-04-14 06:22 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +        - There are instance processes in IM (im.Status.Instance).
1. The behavior of creating engine/replica IM PBD  is the same as now when there are volumes attached.
2. We keep only the replica IM PBD of 1 of the nodes when the volume is detached.

> I think we can describe this part from another perspective: The IM PDB will be created **and retained** only when it's required. And once it's required, we cannot delete the PDB. Required means either of the following happen:
> 
> 1. There are volumes/engines running on the node. We need to guarantee that the volumes won't crash
> 2. The only available/valid replica of a volume is on the node, no matter whether the volume itself is detached or not. Here we need to prevent the volume data from being lost.

The implementation overview is written based on scenarios, and I think we are in the same direction.

I've put your suggestion of the description under the proposal section to clarify what we want to achieve.

2022-04-14 07:24 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
Updated.

2022-04-14 09:44 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
Should the CPU request be large enough so that the current nodes cannot fit the requirement?

2022-04-14 09:44 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +After enhancement, instance manager PBD will be actively managed by Longhorn:
typo `PBD` -> `PDB`. Same below

2022-04-14 09:51 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
We can calculate the number of deployment replicas with the allocatable CPU.
```
10 * math.ceil(allocatable_millicpu/cpu_request*node_number/10)
```

2022-04-14 10:48 UTC, shuo-wu reviewed
In general LGTM except for the existing comments left by David.

2022-04-14 10:48 UTC, shuo-wu commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
NIT: The calculation result is for increasing 1-node scaling-up,  right? You can add this expectation there.

2022-04-14 16:28 UTC, innobead approved these changes
LGTM

2022-04-14 16:29 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +        - Enqueue the replica instance-manager of another schedulable node with the volume replica.
Ensure not Enqueue.

2022-04-15 00:57 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +    And Create deployment with cpu request.
The expectation is to double the cluster node number and I have it with the following `When Trigger CA to scale-up by increase deployment replicas.`

2022-04-15 00:59 UTC, c3y1huang commented on enhancements/20220408-support-kubernetes-ca.md
> +        - Enqueue the replica instance-manager of another schedulable node with the volume replica.
We want to enqueue another schedulable replica IM to create the PDB when the current is un-schedulable.

2022-04-15 02:14 UTC, innobead commented on enhancements/20220408-support-kubernetes-ca.md
> +        - Enqueue the replica instance-manager of another schedulable node with the volume replica.
Thanks, it's clear now, but it was not easy to understand a bit.

The point is to ensure at least one healthy replica is still available in another node when the volume is detached and the volume owner node is being eligible for CA by removing it's PDB.

2022-04-15 02:26 UTC, merged