Update deployment for cluster autoscaler support
longhorn/longhorn pull request #3879
Opened 2022-04-21 04:34 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/2203

2022-04-21 10:09 UTC, innobead commented on chart/questions.yaml
> +    description: "Enable this setting will notify Longhorn that the cluster is using Kubernetes cluster-autoscaler.
```suggestion
    description: "Enabling this setting will notify Longhorn that the cluster is using Kubernetes cluster-autoscaler.
```

2022-04-21 10:09 UTC, innobead commented on chart/questions.yaml
> +    Longhorn prevents data loss by only allowing CA to scale down a node that met all conditions:
```suggestion
    Longhorn prevents data loss by only allowing the Cluster Autoscaler to scale down a node that met all conditions:
```

2022-04-21 10:10 UTC, innobead requested changes
LGTM, just some rewords needed.

2022-04-21 12:09 UTC, c3y1huang commented on chart/questions.yaml
> +    description: "Enable this setting will notify Longhorn that the cluster is using Kubernetes cluster-autoscaler.
Updated.

2022-04-22 03:20 UTC, shuo-wu commented on chart/questions.yaml
> +      - No volume attached
NIT: Just realized that this statement may be confusing. Should be `No volume attached to the node` instead.

2022-04-22 03:20 UTC, shuo-wu commented on chart/questions.yaml
> +      - Is not the last node containing the replica of a detached volume.
NIT: For a running volume on another node, we cannot remove the node either when it contains the last replica.

2022-04-22 03:20 UTC, shuo-wu commented on chart/templates/default-setting.yaml
> +    kubernetes-cluster-autoscaler-enabled: {{ .Values.defaultSettings.kubernetesClusterAutoscalerEnabled }}
Note: We will switch to using CRs for default settings in v1.3.0. But we can upgrade this whole YAML later.

2022-04-22 04:59 UTC, c3y1huang commented on chart/questions.yaml
> +      - Is not the last node containing the replica of a detached volume.
Fixed.

Also in https://github.com/longhorn/longhorn-manager/pull/1305

2022-04-22 04:59 UTC, c3y1huang commented on chart/templates/default-setting.yaml
> +    kubernetes-cluster-autoscaler-enabled: {{ .Values.defaultSettings.kubernetesClusterAutoscalerEnabled }}
Fixed.

2022-04-22 04:59 UTC, c3y1huang commented on chart/questions.yaml
> +      - No volume attached
Fixed.

2022-04-22 05:05 UTC, innobead approved these changes

2022-04-22 05:06 UTC, merged