Add LEP for high available nfs for RWX volume
longhorn/longhorn pull request #4299
Opened 2022-07-27 09:58 UTC by derekbit

[Longhorn 2293](https://github.com/longhorn/longhorn/issues/2293)

Signed-off-by: Derek Su <derek.su@suse.com>

2022-08-02 06:06 UTC, derekbit commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +- Implement a dedicated recovery backed for Longhorn and make the NFS server highly available
Updated. Thank you.

2022-08-02 10:14 UTC, innobead reviewed
LGTM, just one question.

2022-08-02 10:14 UTC, innobead commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    The speed of a share-manager pod and volume's failover is affected by the cluster's settings and resources, so it is unpredictable how long it takes to failover. Thus, the NFS client mount option
After changing the mount option to `hard`, is there any limitation caused unpredictable failover?

2022-08-02 10:16 UTC, innobead commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    1. Introduce a recovery-backend service backed by multiple recovery-backend pods.
Will the recovery-backend be able to share w/ multiple RWX volumes if it has replica design for availability? This is about costs for each share manager pod.

2022-08-02 15:02 UTC, derekbit commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    The speed of a share-manager pod and volume's failover is affected by the cluster's settings and resources, so it is unpredictable how long it takes to failover. Thus, the NFS client mount option
With the `hard` mount option, the client will hold the data and reconnect to the server repeatedly until the server comes back. It means the data won't be lost during the retries.

2022-08-02 15:08 UTC, derekbit commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    1. Introduce a recovery-backend service backed by multiple recovery-backend pods.
Yes. This is a design of a share recovery-backed service for all RWX volumes. As you mentioned, one recovery-backend service for one RWX volume will cost too much. I will state it more in the LEP.

2022-08-04 05:47 UTC, derekbit commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    The speed of a share-manager pod and volume's failover is affected by the cluster's settings and resources, so it is unpredictable how long it takes to failover. Thus, the NFS client mount option
Updated in the user experience, thank you.

2022-08-04 05:47 UTC, derekbit commented on enhancements/20220727-high-available-nfs-for-rwx-volume.md
> +    1. Introduce a recovery-backend service backed by multiple recovery-backend pods.
Updated, thank you.

2022-08-04 06:22 UTC, innobead commented
As discussed, because right now we more focus on consistency instead, suggest adding two things that will be further discussed after the metadata backend introduction. 

- Current limitation of active-active or active-passive 
- How to shorten the failover time (this is about resilience)

2022-09-05 16:37 UTC, innobead commented
> As discussed, because right now we more focus on consistency instead, suggest adding two things (non goals for now) that will be further discussed after the metadata backend introduction.
> 
> * Current limitation of active-active or active-passive
> * How to shorten the failover time (this is about resilience)

@derekbit Will you add the above items? then we can merge this. Thanks.

2022-09-05 16:37 UTC, derekbit commented
> > As discussed, because right now we more focus on consistency instead, suggest adding two things (non goals for now) that will be further discussed after the metadata backend introduction.
> > 
> > * Current limitation of active-active or active-passive
> > * How to shorten the failover time (this is about resilience)
> 
> @derekbit Will you add the above items? then we can merge this. Thanks.

Yes, I'm working on this part.

2022-09-21 03:44 UTC, derekbit commented
ping cc. @innobead

2022-10-17 04:39 UTC, innobead requested changes
LGTM, just a few comments to resolve if possible

2022-10-17 04:39 UTC, innobead commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    ```
The example is not consistent with the above definition like the content should be under `Data` key in the manifest, also annotations should not be part of labels. 

Is it possible to understand what the encoded content looks like in the example?

2022-10-17 04:39 UTC, innobead commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    2. Turn into the deployment into a daemonset in [example]([https://github.com/longhorn/longhorn/blob/master/examples/rwx/rwx-nginx-deployment.yaml](https://github.com/longhorn/longhorn/blob/maste
typo, `Automatically` instead

2022-10-17 04:39 UTC, innobead commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +            - Lock reclaim process can be finished earlier than the 90-seconds grace period .
If unable to finish in the configured grace period, what happened? client connection recovery failed, so the new client connection will be built? will be any data consistency concern?

2022-10-17 04:39 UTC, innobead commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +        Turn off the node where share-manager is running. Once the share-manager pod is recreated on a different node, check
Can we describe what expectation will be before the share-managed recreated successfully?

2022-10-17 04:39 UTC, innobead commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    To allow the NFSv4 clients to reclaim locks after the failover of the NFS server, the grace period is enabled by setting
Can we describe the negative cases like below? what users will notice and what the result they should expect or recover, or even the risk they could take.
- The new share manager is unable to create
- The client reclaim is failed somehow like timeout

2022-12-01 01:24 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    2. Turn into the deployment into a daemonset in [example]([https://github.com/longhorn/longhorn/blob/master/examples/rwx/rwx-nginx-deployment.yaml](https://github.com/longhorn/longhorn/blob/maste
Updated, thank you.

2022-12-01 01:35 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    ```
Updated the format and the example.

2022-12-06 17:18 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    To allow the NFSv4 clients to reclaim locks after the failover of the NFS server, the grace period is enabled by setting
Add a `Notice` section. Thank you.

2022-12-06 17:18 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +        Turn off the node where share-manager is running. Once the share-manager pod is recreated on a different node, check
Updated. Thank you.

2022-12-06 17:20 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +            - Lock reclaim process can be finished earlier than the 90-seconds grace period .
The client will receive the IO error from the NFS server. Then, client will create a new lock. Then, the data consistency is the potential issue if there are multiple clients accessing the same file.

Updated, thank you.

2022-12-06 19:00 UTC, c3y1huang requested changes

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +- Implement a dedicated recovery backed for Longhorn and make the NFS server highly available
```suggestion
- Implement a dedicated recovery backend for Longhorn and make the NFS server highly available.
```

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +1. The changes and improvements should not impact the usage of the RWX volumes
```suggestion
1. The changes and improvements should not impact the usage of the RWX volumes.
```

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
Can you elaborate on how `users have to make sure the hostname of each node in the Longhorn system is unique`?

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +        - add_revoke_fh
What is this for?

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    3. Then, the data from above operations are persisted by sending to the recovery-backend service.  The data will be saved in the configmap, `recovery-backend-${share-manager-pod-name}`.
```suggestion
    3. Then, the data from the above operations are persisted by sending to the recovery-backend service. The data will be saved in the configmap, `recovery-backend-${share-manager-pod-name}`.
```

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +            - If the clients can continue working without IO error.
```suggestion
            - The clients can continue working without IO error.
```

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    If locks cannot be reclaimed after a grace period, the locks are discarded and return IO errors to the client. The client reestablishes a new lock. The IO errors will potentially lead to the data
Can you elaborate more on `The IO errors will potentially lead to the data consistency concern`?

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +            - If locks cannot be reclaimed after a grace period, the locks are discarded and return IO errors to the client. The client reestablishes a new lock. The IO errors will potentially lead t
Do we need `The IO errors will potentially lead to the data consistency concern` in the test?

2022-12-06 19:00 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    2. Turn into the deployment into a daemonset in [example]([https://github.com/longhorn/longhorn/blob/master/examples/rwx/rwx-nginx-deployment.yaml](https://github.com/longhorn/longhorn/blob/maste
`Turn into the deployment into a daemonset`?

2022-12-07 00:00 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +            - If locks cannot be reclaimed after a grace period, the locks are discarded and return IO errors to the client. The client reestablishes a new lock. The IO errors will potentially lead t
Actually, it is not easy to test. I cannot figure out a good test method for it.

2022-12-07 00:02 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    3. Byte-range file locking
This case is for the multiple locks in one file.

2022-12-07 02:26 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
Do you mean `how`?
By checking each node's hostname using `hostname` command.

2022-12-07 02:29 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    If locks cannot be reclaimed after a grace period, the locks are discarded and return IO errors to the client. The client reestablishes a new lock. The IO errors will potentially lead to the data
The IO error should be handled by the application. However, not every application can handle the IO errors depends on their implementation. Thus, it might break the IO operation and lead to the data loss. So, the data consistency might be a potential issue.

2022-12-07 02:37 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +- Implement a dedicated recovery backed for Longhorn and make the NFS server highly available
Updated. Thank you.

2022-12-07 02:37 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +1. The changes and improvements should not impact the usage of the RWX volumes
Updated. Thank you.

2022-12-07 02:55 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    3. Then, the data from above operations are persisted by sending to the recovery-backend service.  The data will be saved in the configmap, `recovery-backend-${share-manager-pod-name}`.
Updated. Thank you.

2022-12-07 02:57 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +        - add_revoke_fh
Remove the delegation which is a mechanism to reduce latency. The delegation will be revoked during recovery.

2022-12-07 02:59 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +    If locks cannot be reclaimed after a grace period, the locks are discarded and return IO errors to the client. The client reestablishes a new lock. The IO errors will potentially lead to the data
Updated. Thank you.

2022-12-07 03:19 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
What will happen when the hostname is not unique? Can we validate this condition in Longhorn?

2022-12-07 03:40 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
If two clients have same hostname and connect to the same server, the exit of any client will remove the client id from the backend. Then, the lock reclaim during recovery of the other client will fail.

> Can we validate this condition in Longhorn?

I have no idea how to validate it in the runtime. Any idea?

2022-12-07 05:10 UTC, derekbit commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
Currently, I will add the check in the environment_check.sh.
https://github.com/longhorn/longhorn/issues/5012

2022-12-08 14:08 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
Can the hostname not be unique in K8s?
Ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
> Unique hostname, MAC address, and product_uuid for every node.

2022-12-08 14:36 UTC, merged

2022-12-09 00:19 UTC, c3y1huang commented on enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md
> +4. To make the improvement work, users have to make sure the hostname of each node in the Longhorn system is unique.
I see.