Add PSP support to environment_check.sh
longhorn/longhorn pull request #4316
Opened 2022-07-29 04:29 UTC by spijet

This will allow hardened cluster users (e.g. RKE2 with `cis-1.6` profile enabled) to run the environment check script painlessly.

I'm not sure if this behaviour should be on by default, so I'm willing to add a knob to turn the PSP support on or off as needed. Or maybe try to auto-detect it by asking cluster. :)

2022-08-01 02:35 UTC, shuo-wu requested changes
Or maybe we can add an option/arg to enable the PSP support. By default, this option can be disabled.

2022-08-01 02:35 UTC, shuo-wu commented on scripts/environment_check.sh
>  apiVersion: apps/v1
It seems that `---` is missed

2022-08-01 02:35 UTC, shuo-wu commented on scripts/environment_check.sh
> +---
It seems that this `---` is redundant.

2022-08-02 20:02 UTC, spijet commented
Hello everyone!
I'm currently out of town, will get back to this issue when I'm back home.

> 
> 2 авг. 2022 г., в 10:42, David Ko ***@***.***> написал(а):
> 
> ﻿
> Assigned #4316 to @spijet.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.

2022-11-07 11:18 UTC, innobead commented
FYI. From 1.4, the PSP enablement will be removed by default, so basically we don't need this anymore. Any concerns? cc @PhanLe1010

2022-11-08 07:23 UTC, spijet commented
I fixed the issue with wrongly-placed `---` in `environment_check` using the GitHub UI and forgot to add the sign-off. D:

2022-11-08 08:27 UTC, spijet commented
OK, I figured it out. :)

Now I'll check if I can add a knob to make it configurable.

2022-11-08 08:37 UTC, spijet commented
@shuo-wu I'm not sure if I fully understand how exactly the `environment_check.sh` script gets called when deploying Longhorn, so I'll need some help. :)

I can wrap this whole section into an `if [ "${LONGHORN_ENABLE_PSP}" = 'true' ]` or something like that and then we can pass this variable via environment, if that's OK?

2023-01-06 14:03 UTC, shuo-wu requested changes
Can we add an option for the script to disable/enable PSP? Since PSP is deprecated in Kubernetes v1.25.

2023-01-06 14:03 UTC, shuo-wu commented on scripts/environment_check.sh
> +  volumes: ['*']
I am thinking if allowing `hostPath` only is enough

2023-01-06 14:03 UTC, shuo-wu commented on scripts/environment_check.sh
> +  hostNetwork: true
Does this script touch the host network?

2023-03-15 09:01 UTC, innobead commented
It seems pending for a while . Closing first but feel free to continue contributing. Thank you.

2023-03-15 09:02 UTC, closed without merging