Extend LEP for failed data cleanup
longhorn/longhorn pull request #4334
Opened 2022-08-01 06:19 UTC by mantissahz

The LEP decribes the design to delete the failed backups by
`backup_volume_controller`.

Longhorn 3898

Signed-off-by: James Lu <james.lu@suse.com>

2022-08-01 08:49 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +When a user or recurring job tries to make a backup and store it in the remote backup target, many situations will cause the backup procedure failed. In some cases, there will be some failed backups
`...this kind of backups are no longer tracked by the Longhorn system...`

These backups are still tracked by Longhorn system and managed by the backup resources.

2022-08-01 08:51 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +After the enhancement, Longhorn automatically finds out the failed backups of backup volumes. Then Longhorn cat delete the failed backups automatically.
```suggestion
After the enhancement, Longhorn can delete the failed backups automatically after enabling auto-deletion.
```

2022-08-01 08:53 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users might not be aware of that backup was failed and deleted.
Actually, user can visualize the failed backups on UI in current implement. Correct?

2022-08-01 08:54 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
You can mention the UX if the auto-deletion is enabled.

2022-08-01 08:58 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the global auto-deletion option of failed backups for users.
Conflict with the **Goals**?

2022-08-01 09:01 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed. Longhorn will leave this kind of the backups behind and will not delet
`Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed.`

A little confused. We don't examine the remote backup data and just rely on the backup resources' status, right?

2022-08-01 09:04 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
https://github.com/longhorn/longhorn/pull/4264#issuecomment-1198845250
Failed backups will be deleted automatically without options.
Or do we still need a global auto-delete options?

2022-08-01 09:05 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the global auto-deletion option of failed backups for users.
goal is to delete failed backups automatically w/o any option.

2022-08-01 09:09 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
IIRC, you would like to have an auto-deletion option in previous discussion?

2022-08-01 09:10 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users might not be aware of that backup was failed and deleted.
If we have the auto-deletion option, and it is disable.

2022-08-01 09:12 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed. Longhorn will leave this kind of the backups behind and will not delet
You are right, it's a bit confusing sentence. I will modify it.

2022-08-01 09:14 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users might not be aware of that backup was failed and deleted.
Got it. You can combine the two UX and make the statement more clear. Actually, users can still be aware of the failure in the event log.

2022-08-01 09:16 UTC, shuo-wu commented on enhancements/20220801-failed-backups-cleanup.md
> +1. The monitor for each backup is created by the `backup_controller` to check and save the backup status and the `backup_controller` will handle the failed backup if the backup status is `Error` or `
Tip:
The monitor in `backup_controller` will be stopped once the backup creation is complete or failed. After the creation, the sync-up of the backups is controlled by `Spec.SyncRequestedAt` and `Status.LastSyncedAt`.

I don't think you need to concern the backup CR state update in this LEP

2022-08-01 09:16 UTC, shuo-wu commented on enhancements/20220801-failed-backups-cleanup.md
> +- Continue to update backup status with a linear timer after exponential backOff timer returned checking backup status completed
This seems to be the existing implementation. Do we need to do anything here?

Same for the below `Backup Controller` part.

2022-08-01 09:16 UTC, shuo-wu commented on enhancements/20220801-failed-backups-cleanup.md
> +Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed. Longhorn will leave this kind of the backups behind and will not delet
Will we clean up if the remote backup target gets failed? The `backup_target_controller` will do cleanup when the URL is unset.

2022-08-01 09:20 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
Yes, I would like to have an auto-deletion but well documentation is acceptable. https://github.com/longhorn/longhorn/pull/4264#issuecomment-1198877129
OK, I will submit a new version with an auto-deletion option.
Thanks.

2022-08-01 09:26 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
In fact, I prefer the design without auto-deletion because failed backups are useless in Longhorn and we don't need to keep them. I'm a bit confused about the last discussion and the current LEP.
You can keep the current desine and ignore the related questions.

2022-08-01 09:28 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Continue to update backup status with a linear timer after exponential backOff timer returned checking backup status completed
yeah, it's the same, it could be deleted.

2022-08-01 10:00 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed. Longhorn will leave this kind of the backups behind and will not delet
Do you mean that would we clean up the failed backups or all backups if the remote backup target get failed? Now It seams that we just set remote backup target `backupTarget.Status.Conditions` and ignore it.

2022-08-01 10:27 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +When a user or recurring job tries to make a backup and store it in the remote backup target, many situations will cause the backup procedure failed. In some cases, there will be some failed backups
Modified, use `handled` instead of `tracked`.

2022-08-01 10:27 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +After the enhancement, Longhorn automatically finds out the failed backups of backup volumes. Then Longhorn cat delete the failed backups automatically.
not changed

2022-08-01 10:29 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users might not be aware of that backup was failed and deleted.
Actually event log is mentioned in next statement. Do I need to merge the two statements into one?

2022-08-01 10:30 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
Keep the current design, thanks

2022-08-01 10:31 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +   The reconciliation procedure of the `backup_controller` gets the latest backup status from the monitor and then according to the backup status, the `backup_controller` will inform the `backup_voum
Removed backup_controller and backup monitor from this LEP. Thanks.

2022-08-01 10:31 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +1. The monitor for each backup is created by the `backup_controller` to check and save the backup status and the `backup_controller` will handle the failed backup if the backup status is `Error` or `
Removed backup_controller and backup monitor from this LEP. Thanks.

2022-08-01 10:31 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Continue to update backup status with a linear timer after exponential backOff timer returned checking backup status completed
Removed backup_controller and backup monitor from this LEP. Thanks.

2022-08-01 10:42 UTC, shuo-wu commented on enhancements/20220801-failed-backups-cleanup.md
> +Failed backup identifies a failed backup on the remote backup target or not when making a backup to remote backup target failed. Longhorn will leave this kind of the backups behind and will not delet
Yes. Then we don't need to do anything for the failed Backup CRs either when Longhorn cannot reach to the remote backup target.

2022-08-01 10:51 UTC, shuo-wu commented on enhancements/20220801-failed-backups-cleanup.md
> +### User Experience In Detail
Having a TTL mechanism would be better. But you can leave this to the next version

2022-08-01 11:46 UTC, c3y1huang commented on enhancements/20220801-failed-backups-cleanup.md
> +Additional nodes.
Can you explain what this is?

2022-08-01 12:11 UTC, c3y1huang requested changes

2022-08-01 12:11 UTC, c3y1huang commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users can check the event log to understand why the backup failed and deleted.
Do we need to worry about Kubernetes event TTL? IIRC it defaults to 1 hour.

2022-08-01 13:02 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users can check the event log to understand why the backup failed and deleted.
Good point. This can be an opt-in setting to allow users to enable this cleanup function as the orphaned replica auto cleanup.

2022-08-01 13:18 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- Automatically deletion of failed backups when detected without any option.
```suggestion
- Automatic deletion of failed backups when detected without any option.
```

2022-08-01 13:18 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the auto-deletion of failed backups exceeded the TTL.
```suggestion
- Support the auto-deletion of failed backups that exceeded the TTL.
```

2022-08-01 13:19 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- The process should not be stuck the reconciliation of the controllers.
```suggestion
- The process should not be stuck in the reconciliation of the controllers.
```

2022-08-01 13:41 UTC, derekbit commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users can check the event log to understand why the backup failed and deleted.
Off topic: Just curious. Some regulations or companies might ask to keep the events or logs for auditing. Does longhorn have such design? Or, this should be handled in kubernetes rather than longhorn?

2022-08-01 13:57 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users can check the event log to understand why the backup failed and deleted.
Another good point.

Frankly, keeping event/log is quite general, even for K8s. This really depends on what user experience we would like to provide. For users, they can always use external event collection to achieve this if they want to keep events for reasons.

2022-08-01 14:32 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +Additional nodes.
Sorry about this nonsense, this section would explain why not leverage the current orphan framework.

2022-08-01 15:48 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +After the enhancement, Longhorn automatically finds out the failed backups of backup volumes. Then Longhorn cat delete the failed backups automatically.
I would like to add the auto-deletion option bu default is enabled.
Modified this part as your suggestion. Thanks.

2022-08-01 15:48 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +  - Users might not be aware of that backup was failed and deleted.
Modified, could you check this again? Thanks.

2022-08-01 15:51 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the global auto-deletion option of failed backups for users.
Modified

2022-08-01 15:54 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +                       │  get failed bakcups  │
Modified. Thanks.

2022-08-01 15:54 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Automatically deletion of failed backups when detected without any option.
Modified. Thanks.

2022-08-01 15:54 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the auto-deletion of failed backups exceeded the TTL.
Modified. Thanks.

2022-08-01 15:55 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- The process should not be stuck the reconciliation of the controllers.
Modified. Thanks.

2022-08-01 15:59 UTC, mantissahz commented
>However, as discussed last week, please help explain in this proposal why not leverage the current orphan framework for this resource clean up like pros and cons, and this will clarify a design understanding for members/users.

Add the explanation in the last section.

2022-08-02 03:01 UTC, shuo-wu approved these changes

2022-08-02 03:08 UTC, c3y1huang approved these changes

2022-08-02 04:17 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- Trigger `backup_volume_controller` to delete the failed backups.
I believe this trigger point in by leveraging `backupVolume.Spac. SyncRequestedAt`.

2022-08-02 04:24 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- `backups` CRs with `Error` or `Unknown` state will be removed soon by `backup_volume_controller` by default when the `backup_monitor` detects the backup failed.
Probably need to check if `Unknown` is needed by checking if it's possibly a temporary or impermanent state.

2022-08-02 04:25 UTC, innobead approved these changes

2022-08-02 04:30 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +2. Cascading deletion of orphaned CR and backup CR would be more complicated than we just handle the failed backups immediately when backup procedure failed. Both in this LEP or orphan framework we w
Not sure if this can just simply rely on the `ownerReference` of backup when deleting the corresponding orphaned backup resource. Or actually any other concerns except orphan resource management efforts?

2022-08-02 04:30 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +3. Listing orphaned backups and failed backups on both two UI pages `Orphaned Data` and `Backup` might be a bit confusing for users. Deleting items manually on either of two pages would be involved i
Agreed.

2022-08-02 04:31 UTC, merged

2022-08-02 04:31 UTC, innobead commented
@mantissahz Thanks for this proposal, and you can start the development.