lep: add Rollout Longhorn
longhorn/longhorn pull request #4388
Opened 2022-08-09 11:01 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/1455

2022-08-11 03:20 UTC, c3y1huang commented
test

2022-08-11 03:21 UTC, c3y1huang commented
test

2022-08-11 03:21 UTC, c3y1huang commented
@c3y1huang

2022-09-12 08:38 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +- Support to create Longhorn-relate resources dump and upload to the backup target.
This seems duplicated as the second goal, suggest removing.

2022-09-12 09:34 UTC, innobead requested changes

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +- Rollout while there are volumes still attached.
This is a criteria, so needs to mention in the design like rollout will be only worked during maintenance.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +- Delete resources none-existing to the rollout.
Do you mean Longhorn resources?

So is it possible for users to understand what resources are created from a rollout? I feel rollout is a system snapshot, any risk to managing longhorn resources cleanly?

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +                                                               backupstore/rollouts/
Just a note: right now, the folder usage and design on the backup target usage is only for a single cluster.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +                                                   [  rollout.zip ] <--|--> [ rollout.cfg ]
Suggest having a checksum when having any compressed artifact.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers deletion of the rollout saved in the backup target.
You also can mention that rolloutsave resource management is similar to the current backup resource.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Each of the `RolloutSave` created by this controller will have the `longhorn.io/version: <version>` label.
Not sure if it's possible to add the cluster name as well? users will be easy to recognize where the rollback comes from.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Responsible for generating the rollout file and uploading it to the backup target.
If a rolloutsave is from the backup target, the corresponding rollback generation should not be created. This should be the same as backup resource.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +              [ rollout.cfg: manager ] ----> [[ longhorn-rollout-load controller ]]
Why need another `longhorn-rollout-load controller`? `longhorn-rollout controller` not enough?

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers deletion of the rollout saved in the backup target.
```suggestion
    - Deleting the custom resource triggers the deletion of the rollout saved in the backup target.
```

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers the deletion of the rollout job.
```suggestion
    - Deleting the custom resource triggers the deletion of the rollout job.
```

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers the deletion of the rollout job.
How about if the rollout is in the middle? How to make the system back to normal? Do we support retry or just replay another new rollout?

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +1. Introduce a new `longhorn-rollout-load` controller.
Then, this is not a controller but a just task instead so it will be another app in longhorn-manager/

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +  - Responsible for adding `longhorn.io/last-rollout`, and `longhorn.io/last-rollout-at` annotation to rolled-out resources.
These annotations are good.

2022-09-12 09:34 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +After the enhancement, the user can downgrade Longhorn when there is a pre-upgrade rollout saved in the backup target.
Does this mean users can downgrade to any previous version? As I mentioned above, should clarify what version are allowed to rollback like the just previous version or any compatible previous version.

And, what validation we should provide is for avoiding an unexpected downgrade.

2022-09-12 09:42 UTC, innobead approved these changes

2022-09-12 09:42 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    - Responsible for creating a new rollout job that runs a `longhorn-rollout-load` controller.
- Can we have the rollout job not immediately triggered but activatable instead? 
- Another question: more than one rollouts, how will they be handled? execute one by one by the creation time?

2022-09-12 09:42 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    [Save] [Load] [Delete]                                                            [Search Box   v ][__________][Go]
What does `Load` mean here? any different from `Save`?

2022-09-12 09:42 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +    [] | 1.4.0    | demo-1 | Error   | error uploading rollout: failed to execute: /var/l + ======= + ngine-binaries/c3y1huang-research-000-lh-ei/longhorn [rollout upload
If it becomes `Error`, what does it mean for users? Do users need to create another rolloutsave to trigger again?

2022-09-12 09:42 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +  - The users can load the rollout from a different Longhorn version.
Should be a compatible version

2022-09-12 09:42 UTC, innobead requested changes
Not approved yet, wrong click

2022-09-12 10:28 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Each of the `RolloutSave` created by this controller will have the `longhorn.io/version: <version>` label.
I couldn't find a way to do so. Ref https://github.com/kubernetes/apimachinery/blob/7fb03423f864da053f3849d76d4c58d0a3442fe6/pkg/apis/meta/v1/types.go#L258-L260

2022-09-12 10:47 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +              [ rollout.cfg: manager ] ----> [[ longhorn-rollout-load controller ]]
Having an extra rollout-load controller is for compatibility purposes.
- The `rollout controller` is running on the current cluster manager and is responsible for managing rollout CRs and creating rollout jobs.
- The `longhorn-rollout controller` runs on an independent manager image (the image will be stored in the rollout.cfg). The controller will also be using the correct engine image(also stated in the rollout.cfg) for the backup target interactions.

2022-09-13 07:42 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +- Support to create Longhorn-relate resources dump and upload to the backup target.
Reworded. Let me know if these still feels duplicated.

2022-09-13 07:43 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers deletion of the rollout saved in the backup target.
Updated.

2022-09-13 07:44 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers deletion of the rollout saved in the backup target.
Updated.

2022-09-14 04:09 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +- Support restore from `lastBackup` when the volume doesn't exist in the cluster.
After discussing with @innobead , the rollout-load controller will not handle concurrent volume restoring from the backup.
https://github.com/longhorn/longhorn/issues/4558

2022-09-14 04:15 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +- Delete resources none-existing to the rollout.
Don't think we should delete existing volumes even if the volume doesn't exist in the rollout.

However, as discussed with @innobead , we can probably enhance it later and make this an option for the users.

2022-09-14 04:18 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Delete the custom resource triggers the deletion of the rollout job.
The rollout is a one-shot operation, if the rollout status Errors, the user can create a new rollout.

2022-09-14 04:18 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +1. Introduce a new `longhorn-rollout-load` controller.
https://github.com/longhorn/longhorn/pull/4388#discussion_r968262470

2022-09-14 04:21 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Responsible for creating a new rollout job that runs a `longhorn-rollout-load` controller.
> * Can we have the rollout job not immediately triggered but activatable instead?

As discussed with @innobead , the use case is unclear. We can enhance it later when the use case is clearer.

> * Another question: more than one rollouts, how will they be handled? execute one by one by the creation time?

We are allowing one rollout at a time. It will be handled in the validator.

2022-09-14 04:22 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    [] | 1.4.0    | demo-1 | Error   | error uploading rollout: failed to execute: /var/l + ======= + ngine-binaries/c3y1huang-research-000-lh-ei/longhorn [rollout upload
https://github.com/longhorn/longhorn/pull/4388#discussion_r970290793

2022-09-14 04:24 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    [Save] [Load] [Delete]                                                            [Search Box   v ][__________][Go]
`Save` is to save the current Longhorn system to the backup store.
`Load` is to rollout the Longhorn system from the backup store.

2022-09-14 05:16 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +- Rollout while there are volumes still attached.
Added `webhook validator` sections.

2022-09-14 05:17 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +                                                   [  rollout.zip ] <--|--> [ rollout.cfg ]
Updated.

2022-09-14 05:18 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +    - Responsible for generating the rollout file and uploading it to the backup target.
Added note below.

2022-09-14 08:22 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +After the enhancement, the user can downgrade Longhorn when there is a pre-upgrade rollout saved in the backup target.
Like discussed. I think it's fine to roll back or roll forward since the rollout will also handle custom resource definitions. It will create the CRD if it is missing, or add to the existing one if the version is different from the current cluster.

2022-09-14 08:24 UTC, innobead commented on enhancements/20220902-longhorn-rollout.md
> +After the enhancement, the user can downgrade Longhorn when there is a pre-upgrade rollout saved in the backup target.
Good to know, then test cases should be covered.

2022-09-14 08:28 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +After the enhancement, the user can downgrade Longhorn when there is a pre-upgrade rollout saved in the backup target.
Added note to the design.

2022-09-14 08:28 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +  - The users can load the rollout from a different Longhorn version.
https://github.com/longhorn/longhorn/pull/4388#discussion_r970483912

2022-09-14 09:03 UTC, c3y1huang commented on enhancements/20220902-longhorn-rollout.md
> +- Support rollout Longhorn at a different version (upgrade rollback).
https://github.com/longhorn/longhorn/pull/4388#discussion_r970483912

2022-09-23 10:19 UTC, shuo-wu reviewed
The naming in the LEP is confusing.  The term` rollout` can be:
1. CRD `Rollout`. The indicator of starting to restore resources from the backup target.
2. Or the file stored in the backup target

I recommended renaming the file in the backup target to `RolloutSave`. This

2022-09-23 10:19 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +1. Restore resources asynchronously and annotate with `longhorn.io/last-rollout`, and `longhorn.io/last-rollout-at`.
But the below resources will be restored in sequence, right?

2022-09-23 10:19 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
This git commit typically means the manager git commit ID. Do we need to store the commit id for other images? NO?

2022-09-26 05:17 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +  + longhorn/
The ShareManager is ignored because rollout volume goes through the normal volume handing flow,
- The share manager controller will create ShareManager for none-existing `rwx` volumes.
- The volume controller will sync ShareManager's image for existing detached volumes.

Any reason we need to include the ShareManager in the rollout file?

2022-09-26 06:10 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +  rollout: demo-2
The intention to separate the CR name and `Spec.rollout` is to allow the user to keep records of the past success/failed Rollouts instead of having to replace the CR for every rollout.

2022-09-26 06:18 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +1. Restore resources asynchronously and annotate with `longhorn.io/last-rollout`, and `longhorn.io/last-rollout-at`.
There will be a go routine running for each KIND of resource. The go routine will also check for resource dependencies before rolling out, ex: persistent volume must exist before rolling out the persistent volume claim.

2022-09-26 06:21 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
Actually, I'm not clear on the use case of having the commit ID for all images. Can you elaborate? Or we can add them as enhancement later.

2022-09-26 06:23 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +  version: v1.4.0
Yes, the intention is to group the backup store rollouts base on the Longhorn versions.

2022-09-26 07:48 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +### Non-goals [optional]
Updated.

2022-09-26 07:49 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +  + longhorn/
No. Then ignoring share managers is fine. Thank you for the explanation!

2022-09-26 07:55 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +   - PodSecurityPolicies with Longhorn Role in the `rules`.
We can remove PSP from the rollout if we've decided to deprecate PSP in https://github.com/longhorn/longhorn/issues/4003. Since the issue hasn't been concluded, we will still handle it and I've added a note.

2022-09-26 07:56 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
The engine controller will ignore the live upgrade requests when the engine images before and after the upgrade have the same commit id:
https://github.com/longhorn/longhorn-manager/blob/ce5b0c0aeefe545e9bab8e69d3f261e6c5db8bdf/controller/engine_controller.go#L1636-L1644

2022-09-26 07:59 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +   type RolloutSave struct {
Yes, for the UI. Updated.

2022-09-26 08:12 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +  rollout: demo-2
Got it. This is the specified RolloutSave name. The naming is a little bit confusing..

2022-09-26 08:13 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +  version: v1.4.0
Then why does the rollout record it? This is already recorded in `RolloutSave.Status`

2022-09-26 08:15 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +    	Created      string                    `json:"created,omitempty"`
`CreatedAt`

2022-09-26 08:16 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
As for the manager commit ID, IIRC, it will be shown in the bottom left of the UI page when the non-official version is used

2022-09-26 08:39 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +  version: v1.4.0
You are right! We don't need it.

2022-09-26 09:59 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +  version: v1.4.0
Removed.

2022-09-26 09:59 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +    	Created      string                    `json:"created,omitempty"`
Updated.

2022-09-26 10:06 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
Mainly for new clusters, but also applies to an existing cluster if volume doesn't already exist.

2022-09-26 10:16 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
Not sure if we will hit the same case. ATM We don't support rolling out to a cluster while volumes are attached.

2022-09-26 11:14 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +    	LonghornGitCommit     string      `json:"longhornGitCommit"`
OK. I just explain the general user case of the commit ID in Longhorn. It's not related to this feature.
I am fine with either retaining this or removing it.

2022-10-17 14:57 UTC, innobead requested changes

2022-10-17 14:57 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +revert the Longhorn resources or restore it to another Longhorn cluster.
```suggestion

This feature is to support Longhorn cluster backup & restore, and also helps with rollback the cluster to the previous healthy state after a failed upgrade.

Currently, Longhorn has documents to guide users on how to restore the Longhorn cluster as below; however, the solution relies on third-party tools, not out-of-the-box, and also involves tedious human intervention.
- [Restore to a new cluster using Velero](https://longhorn.io/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero/)
- [Restore to a cluster contains data using Rancher snapshot](https://longhorn.io/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-cluster-contains-data-using-rancher-snapshot/)

With this new feature, Longhorn's custom resources will be backed up and bundled as a system backup file, then saved to the remote backup target. 

Later, users can choose a system backup to restore to a new cluster or an existing cluster; nevertheless, it can help with the cluster rollback to fix the corrupted cluster state just after a failed upgrade.

```

2022-10-17 14:57 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +revert the Longhorn resources or restore it to another Longhorn cluster.
Don't suggest making the new term in the summary, but rather keep the summary w/ clear descriptions of what problems you would like to resolve instead. 

The new terminologies can be introduced later to avoid some confusion w/ the correct backup or context.

2022-10-17 14:57 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
For some items, you can aggregate to make goals clear and complete.

```suggestion
- Support system/cluster backup via backing up Longhorn custom resources, bundle them, and upgrade to the backup target.  (Original: `RolloutSave`, but how about `SystemBackup`?)
- Support system/cluster restore to a new/existing cluster from a system backup (Original: `Rollout`, but how about `SystemRestore`?)
- Support restoring volume from `lastBackup` when the volume doesn't exist in the cluster during the system restore.
```

2022-10-18 01:26 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
I am ok with different namings.
So we also need to have different names for the 3 controllers:
- rollout-save controller > system-backup controller
- rollout controller > system-restore controller
- rollout-load controller > system-rollout controller

Also the file name:
- rollout.zip > system-backup.zip

WDYT @innobead @shuo-wu ?

2022-10-18 02:56 UTC, shuo-wu commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
I am fine with the new naming. Or as I mentioned, modifying the remote file naming as rollout-save.zip

2022-10-18 03:24 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
`system-rollout controller`, probably `system-restore-rollout controller`?

@c3y1huang I know you already spent efforts on it, so if you are confident about these changes, and no one has different preferences, then let's go with the new naming to make it much meaningful.

2022-10-18 04:42 UTC, innobead requested changes
In general, LGTM. 

Some feedbacks to make the proposal much clear to understand. We also need to pay attention to if the system-restore failed, how to handle for day2.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +### Non-goals [optional]
Update each item in this section accordingly if needed due to naming change.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +        |----------- [[ longhorn-backup-target controller ]] ----------|
This part is very similar to what we do for Backup? I will be great for design if something we can abstract or consolidate here, but it can be a later work. 

The flow is general, but just the resource different: one is backup, and the other is system-backup.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +1. Introduce a new `longhorn-rollout-save` controller.
As I mentioned, this is similar to `backup-controller` today.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +    - A new custom resource triggers the resources dump and uploads the generated rollout file to the backup target.
Can you mention what CRDs and their resources will be backed up? as you explained in Rollout/system restore section.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +### Rollout
When doing the system restore, does the system need to be maintenance mode like all volumes needed to detached? I feel it's not possible to do something similar to engine upgrade during the system upgrade.


If there is some limitation or pre-conditions, need to emphasize or add to the implementation.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +### Save Rollout
When doing system backup, anything users need to pay attention or prerequisites like I asked in the system restore section.

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +    - Responsible for restoring resources from the rollout file.
As discussed before, few requestions:
- Can explain how it will work for restoring the system backup to an existing cluster or how is the difference than rollback the failed cluster to a previous healthy state?
- For restoring to the existing cluster, how to handle the resource version different (for example: v1beta1 -> v1, v1 -> v1beta1). (We discussed it should work, but it is worth explaining here) 
- If cross-version system restore will be a concern, what version policy will be to limit the restore path

2022-10-18 04:42 UTC, innobead commented on enhancements/20220913-longhorn-rollout.md
> +#### Rollout
Can we add a test case when a rollout failed in the middle? What's the state and how to recover by retry/create another rollout.

2022-10-18 06:52 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +revert the Longhorn resources or restore it to another Longhorn cluster.
Updated.

2022-10-18 06:52 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +- Support restoring from `lastBackup` when the volume doesn't exist in the cluster.
Updated.

2022-10-18 06:52 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +### Non-goals [optional]
Updated.

2022-10-18 06:54 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +        |----------- [[ longhorn-backup-target controller ]] ----------|
Yes, it's similar.

2022-10-18 06:55 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +    - A new custom resource triggers the resources dump and uploads the generated rollout file to the backup target.
Added anchor and link.

2022-10-18 06:58 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +### Rollout
They are covered in the `webhook validator` sections.

2022-10-18 07:11 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +### Rollout
Also noted to the proposal sections for visibility.

2022-10-18 07:12 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +### Save Rollout
https://github.com/longhorn/longhorn/pull/4388#discussion_r997806385

2022-10-18 07:56 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +    - Responsible for restoring resources from the rollout file.
Added notes.

2022-10-18 07:56 UTC, c3y1huang commented on enhancements/20220913-longhorn-rollout.md
> +#### Rollout
Updated.

2022-10-18 12:11 UTC, innobead commented on enhancements/20220913-longhorn-system-backup-restore.md
> +    > 1. When the CustomResourceDefinition is missing the version for the restoring resource, the system restore doesn't replace or remove the existing CustomResourceDefinitions. Instead, the control
Also, need to pay attention to if any file/meta saved on disks will impact the compatibility as well like metadata for volume head, snapshots, backing image, etc.

2022-10-18 12:19 UTC, innobead approved these changes
In general, LGTM>

2022-10-18 12:19 UTC, innobead commented on enhancements/20220913-longhorn-system-backup-restore.md
> +    > 1. When the CustomResourceDefinition is missing the version for the restoring resource, the system restore doesn't replace or remove the existing CustomResourceDefinitions. Instead, the control
cc @shuo-wu @derekbit

2022-10-24 11:37 UTC, shuo-wu commented on enhancements/20220913-longhorn-system-backup-restore.md
> +    > 1. When the CustomResourceDefinition is missing the version for the restoring resource, the system restore doesn't replace or remove the existing CustomResourceDefinitions. Instead, the control
Here, I think the system restore just needs to try its best effort with a warning message. 
It's hard to guarantee this compatibility... But typically we will add some fields with backward compatibility for the resources rather than directly modifying/deleting fields. Hence this should be fine.

2022-10-24 11:39 UTC, shuo-wu commented on enhancements/20220913-longhorn-system-backup-restore.md
> +- Test system restore to cluster with multiple engine images.
Yes it's better to add some clarifications. For example, if we plan to deprecate and remove some fields in v1.4.0, we should announce the incompatibility between v1.4.0 and the old versions.

2022-10-26 00:43 UTC, c3y1huang commented on enhancements/20220913-longhorn-system-backup-restore.md
> +#### Engine: commands
Currently, the communication to the backup target is using engine binary. So I think we should do the same for the system backup/restore.

2022-11-04 13:32 UTC, shuo-wu reviewed
In general LGTM

2022-11-04 13:32 UTC, shuo-wu commented on enhancements/20220913-longhorn-system-backup-restore.md
> +    - Each of the `SystemBackup` created by this controller will have the `longhorn.io/version: <version>` label.
NIT: We don't need this kind of detail in the proposal section. And this will be mentioned in the below implementation part.

2022-11-04 13:32 UTC, shuo-wu commented on enhancements/20220913-longhorn-system-backup-restore.md
> +      - PersistentVolumeClaims with Longhorn StorageClass in spec.
How about the StorageClasses with `provisioner: driver.longhorn.io`

2022-11-04 13:32 UTC, shuo-wu commented on enhancements/20220913-longhorn-system-backup-restore.md
> +| 1                | the destination system backup URL |
NIT: Do we need to use 2 flags `--src-path` and `--dest-url` instead to make this cmd more easy-to-use?

2022-11-07 03:47 UTC, c3y1huang commented on enhancements/20220913-longhorn-system-backup-restore.md
> +    - Each of the `SystemBackup` created by this controller will have the `longhorn.io/version: <version>` label.
Removed.

2022-11-07 03:48 UTC, c3y1huang commented on enhancements/20220913-longhorn-system-backup-restore.md
> +      - PersistentVolumeClaims with Longhorn StorageClass in spec.
I've missed this. Updated, thanks!

2022-11-07 03:48 UTC, c3y1huang commented on enhancements/20220913-longhorn-system-backup-restore.md
> +| 1                | the destination system backup URL |
Since those are mandatory fields, I prefer to use arguments instead. This is the same as `cp` and `rsync`.

2022-11-07 10:37 UTC, innobead approved these changes

2022-11-07 10:37 UTC, innobead commented on enhancements/20220913-longhorn-system-backup-restore.md
> +1. View `System Backups` and `System Restores` on the same page.
Remember adding events when any operations happening or status changed as backup.

Also, for failed system backup, need to have a consistent behavior for the clean up. https://github.com/longhorn/longhorn/blob/master/enhancements/20220801-failed-backups-cleanup.md

2022-11-07 10:37 UTC, merged

2022-11-08 00:29 UTC, c3y1huang commented on enhancements/20220913-longhorn-system-backup-restore.md
> +1. View `System Backups` and `System Restores` on the same page.
Got it.