Failed backups cleanup: update deploy YAML
longhorn/longhorn pull request #4433
Opened 2022-08-17 02:47 UTC by mantissahz

Add a new option `failed-backup-ttl` and update the LEP for failed backup cleanup.

longhorn/longhorn#3898

Signed-off-by: James Lu <james.lu@suse.com>

2022-08-17 02:48 UTC, mantissahz commented
After https://github.com/longhorn/longhorn-manager/pull/1477 merged.

2022-08-17 07:33 UTC, innobead commented on chart/questions.yaml
> +  - variable: defaultSettings.failedBackupTTL
Ensure you verify this on the Rancher marketplace.

2022-08-23 07:40 UTC, innobead requested changes

2022-08-23 07:40 UTC, innobead commented on chart/questions.yaml
> +    description: "In seconds. This setting determines how long Longhorn will keep the backup resource that was failed. Set to 0 to disable the auto-deletion.
The description is out of sync from the longhorn-manager PR.

2022-08-23 07:40 UTC, innobead commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the auto-deletion of failed backups that exceeded the TTL.
nit: The proposal change should be in another separate commit to ensure each commit has its own purpose.

2022-08-23 17:27 UTC, innobead commented on chart/questions.yaml
> +			Disabling **Backupstore Poll Interval** also means to disable failed backup auto-deletion."
It seems extra tab/space before the statement. See if need to reformate.

2022-08-24 01:22 UTC, mantissahz commented on chart/questions.yaml
> +  - variable: defaultSettings.failedBackupTTL
Checked by creating a external repo.

2022-08-24 01:22 UTC, mantissahz commented on chart/questions.yaml
> +    description: "In seconds. This setting determines how long Longhorn will keep the backup resource that was failed. Set to 0 to disable the auto-deletion.
Synced with PR

2022-08-24 01:23 UTC, mantissahz commented on enhancements/20220801-failed-backups-cleanup.md
> +- Support the auto-deletion of failed backups that exceeded the TTL.
Yeah, separated. Thanks.

2022-08-24 01:23 UTC, mantissahz commented on chart/questions.yaml
> +			Disabling **Backupstore Poll Interval** also means to disable failed backup auto-deletion."
Removed the tab. Thanks.

2022-08-24 01:23 UTC, innobead approved these changes

2022-08-24 01:23 UTC, merged

2022-08-24 01:24 UTC, innobead commented
@mantissahz Please backport to 1.3 and 1.2. Thanks.