Patch 2
longhorn/longhorn pull request #4576
Opened 2022-09-16 12:29 UTC by msoGTA

This PR is link to the following issue [https://github.com/longhorn/longhorn/issues/4574]
 add possibility to use nodeSelector on the storageClass #4574

2022-09-19 01:07 UTC, mantissahz commented
@msoGTA appreciate your contribution,
Check the DCO failed, `There are 2 commits incorrectly signed off`.
Please use `git commit -s` to sign-off in your commits. Thanks.

2022-09-19 01:23 UTC, innobead requested changes
Thanks for the contribution!

Please also update questions.yaml which is used for Rancher chart interactive installation.

2022-09-19 01:23 UTC, innobead commented on chart/values.yaml
> +    name: longhorn # longhorn is the value of the label and can be named differnetly
Suggest renaming `name` to `selector` and the default value should be `[]`, because it supports type list instead.

2022-09-19 01:24 UTC, innobead commented on chart/values.yaml
> +    name: longhorn # longhorn is the value of the label and can be named differnetly
cc @c3y1huang we should make the same pattern for `recurringJobSelector`. You can create a ticket for future refactoring. 

```yaml
  recurringJobSelector:
    enable: false
    jobList: []
```

2022-09-19 05:10 UTC, msoGTA commented on chart/values.yaml
> +    name: longhorn # longhorn is the value of the label and can be named differnetly
Hi innobead, thanks for your review. I just pushed a new commit with your suggestions. Regards.

2022-09-19 08:07 UTC, innobead commented on chart/values.yaml
> +    name: longhorn # longhorn is the value of the label and can be named differnetly
Thanks, please consolidate your commits to one, and update questions.yaml (you can reference previous commit history to know how to update that from other settings) as I mentioned above. Also, remember to sign off the commit.

2022-09-20 05:52 UTC, msoGTA commented on chart/values.yaml
> +    name: longhorn # longhorn is the value of the label and can be named differnetly
Hi, I made the requested changes. 
Regards

2022-09-30 06:59 UTC, innobead approved these changes
LGTM

But just notice some naming of settings in persistence seems are inconsistent, so we probably need to refactor them later. (minor)

2022-09-30 07:00 UTC, merged

2022-09-30 07:00 UTC, innobead commented
@weizhe0422 Please help handle this contribution later at https://github.com/longhorn/longhorn/issues/4574. Thanks. 

@msoGTA thanks for the contribution!

2022-09-30 12:39 UTC, msoGTA commented
You are welcome :) @innobead