lep: add Snapshot Checksum Calculation and Bit Rot Detection
longhorn/longhorn pull request #4606
Opened 2022-09-22 03:22 UTC by derekbit

[Longhorn 4210](https://github.com/longhorn/longhorn/issues/4210)
[Longhorn 3198](https://github.com/longhorn/longhorn/issues/3198)

Signed-off-by: Derek Su <derek.su@suse.com>

2022-09-29 07:54 UTC, derekbit commented
@PhanLe1010 
The feature willl resync snapshots periodically. Do you have any concern for the resync and the period?

2022-09-30 03:09 UTC, shuo-wu requested changes

2022-09-30 03:09 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    3. Then, compare the checksums with  `snapshot.status.checksum`. If the snapshot’s checksum is mismatched with  `snapshot.status.checksum`, set the replica to `ERR` and start rebuilding.
As we discussed, we can:
  1. Record the file modification time before and after the calculation. Then we know whether the calculation result is valid or not.
  2. If the file modification time since the last calculation, we don't need the repeat calculation.

@joshimoo mentioned that we can record the versioning info rather than the file modification time in the metafile. But I don't know how that can avoid the timestamp mess-up issue.

2022-09-30 03:09 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    2. If  `snapshot.status.checksum` is empty, create a monitor and issue a snapshot checksum calculation request. Then, the checksums of snapshot files in each replica will be calculated individual
As we discussed in the meeting, the per-snapshot monitor implementation may lead to a scalability issue. You can use per-node monitoring or rely on the engines.

2022-09-30 03:23 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    2. If  `snapshot.status.checksum` is empty, create a monitor and issue a snapshot checksum calculation request. Then, the checksums of snapshot files in each replica will be calculated individual
Can you elaborate more on the `rely on the engines`?
cc @PhanLe1010

2022-10-05 08:48 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    2. If  `snapshot.status.checksum` is empty, create a monitor and issue a snapshot checksum calculation request. Then, the checksums of snapshot files in each replica will be calculated individual
Use per-node monitor instead.

2022-10-09 11:32 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **Automatic Snapshot Checksum Calculation and Verification**
How about the engine or replica part?
As I mentioned before, we can rely on the file modification time to skip some unnecessary calculations.

2022-10-13 17:25 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **Automatic Snapshot Checksum Calculation and Verification**
Added a section `Snapshot Disk File Hashing` for the replica part.

2022-10-15 02:25 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If current time exceeds the sum of `node.status.lastV
This is trying to use a setting to relax system loading due to polling way.

See https://github.com/fsnotify/fsnotify can help with this case to use an asynchronous way by being notified by system if there are watched snapshots get changed.

2022-10-15 08:38 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If current time exceeds the sum of `node.status.lastV
The walkthrough of all snapshots and hash calculation/verification is necessary. The filesystem cannot be aware of the data corruption caused by the underlying block device's bit rot. fsnotify seems helpless in the bit rot detection feature.

2022-10-15 08:46 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If current time exceeds the sum of `node.status.lastV
But fsnotify might be helpful to detect any snapshot creation/purge/merge. Once per-node monitor gets the change notification, and then it send a hash calculation request to longhorn-engine.

2022-10-15 10:53 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If current time exceeds the sum of `node.status.lastV
You should be right, especially for silent data corruption.

2022-10-15 13:28 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If current time exceeds the sum of `node.status.lastV
Just note here: a typical way to detect the silent corruption. 
https://github.com/trapexit/scorch/tree/1.0.1

2022-10-16 01:07 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - Add `node.status.lastSnapshotVerifyAt` for recording the start timestamp of the last checksum verification.
Updated, thank you.

2022-10-17 04:30 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    2. Get the value of the extended attribute `user.longhorn-system.checksum` recording the checksum and `ctime` of the disk file in last calculation.
Using the extended attribute is really a good idea!

2022-10-17 04:30 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    3. Return checksum or error to engine.
NIT: This part looks a little bit redundant...

2022-10-17 11:59 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    3. Return checksum or error to engine.
I will reorganize `Snapshot Disk File Hashing`` and `Snapshot Disk File Verification` and make them more clear.

2022-10-17 12:03 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    3. The worker waits until each replica's snapshot file's checksum calculation has been completed. It periodically polls the engine and checks the status during waiting periods.
Yeah, both backup and snapshot calculation need same improvement later.

2022-10-17 14:03 UTC, innobead reviewed
In general, LGTM, but some comments needed to resolve first.

2022-10-17 14:03 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    4. After the checksum calculation, get `ctime` information of the disk file again. Then, compare 1's and 4's `ctime`.
Do we need the step 4? I thought after each recalculation, the new checksum will always be updated to the extended attribute.

2022-10-17 14:13 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +            - Use the  `snapshot.status.checksum` as the ground truth, set the replicas with different checksums to ERR
Yeah, the replicas cannot be fixed (rebuilding) in some extreme cases.

2022-10-17 14:15 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Send a snapshot hashing/checking task to  `snapshotVerifyTaskChan` channel after receiving one snapshot `UPDATE` event.
Yeah, I also have the same concern. Can I introduce sqlite or other persistent and lightweight database.

2022-10-17 14:21 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Send a snapshot hashing/checking task to  `snapshotVerifyTaskChan` channel after receiving one snapshot `UPDATE` event.
Do we really need to have that queue persistent? I thought you already introduced the concept of periodical snapshot-check, so probably volatility is good enough, because in the end it will be requested to calculate the checksum again even if it was missed last time, right?

2022-10-17 14:46 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Send a snapshot hashing/checking task to  `snapshotVerifyTaskChan` channel after receiving one snapshot `UPDATE` event.
The channel receives the snapshot change events ([codes](https://github.com/longhorn/longhorn-manager/pull/1519/files#)). If we use a bounded channel,  it might result in a stuck node controller if the snapshot verification workers consumes the tasks slowly. So, putting the change events into a persistent db can avoid the memory pressure and the potention stuck issue. WDYT?

2022-10-17 15:03 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    4. After the checksum calculation, get `ctime` information of the disk file again. Then, compare 1's and 4's `ctime`.
I see, then we need to emphasize this reason in the doc because it is worth understanding the purpose.

2022-10-18 08:09 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Send a snapshot hashing/checking task to  `snapshotVerifyTaskChan` channel after receiving one snapshot `UPDATE` event.
After discussing with @derekbit , propose to adopt the below items.
- Use a buffered channel for snapshot update events, then process them w/ best efforts.
- Use non-blocking to send events to the channel, so if the channel is full, just simply drop, because we would expect the events will be required to be processed periodically in the following iterations. It will be eventual consistency for snapshot checksum calculation and verification. 
- However, it's unable to guarantee that the unprocessed events just dropped will be processed soon or later, because there is no queue for them. So, suggest the remaining unprocessed snapshots of the volume, the partial snapshots of which have been processed, should be prioritized earlier to ensure the volume can be processed and completed in a reasonable time which could be expected.

2022-10-18 10:54 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Responsible for executing hashing/checking tasks
This means that each node monitor should track the in-process replica calculation on all other nodes, which seems pretty complicated and it's hard to avoid race conditions...

2022-10-18 10:57 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Responsible for executing hashing/checking tasks
Or maybe we can add something like labels for the replicas before starting the checksum calculation. This should simplify the issue but we cannot strictly guarantee the concurrent count.

2022-10-18 10:59 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Responsible for executing hashing/checking tasks
Yeah, just do best effort.

2022-10-19 09:23 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  - While the replica process is receiving the snapshot disk file hashing request
Reorganized, thank you.

2022-10-19 09:23 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    4. After the checksum calculation, get `ctime` information of the disk file again. Then, compare 1's and 4's `ctime`.
Updated. Thank you.

2022-10-20 02:05 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Responsible for executing hashing/checking tasks
Add the worker pool in the replica's sync-agent for controlling number of concurrent calculations.

2022-10-20 02:07 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +          Send a snapshot hashing/checking task to  `snapshotVerifyTaskChan` channel after receiving one snapshot `UPDATE` event.
Use a non-blocking channel instead.

2022-10-28 01:27 UTC, c3y1huang requested changes

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +Longhorn system supports volume snapshotting and stores the snapshot disk files on the local disk. However, it is impossible to verify the data integrity of snapshots due to the lack of the checksums
```suggestion
Longhorn system supports volume snapshotting and stores the snapshot disk files on the local disk. However, it is impossible to verify the data integrity of snapshots due to the lack of the checksums of the snapshots in current implementation. As a result, if the underlying storage bit rots, no way is available to detect the data corruption and repair the replicas. In the enhancement, the snapshot checksum is calculated after the snapshot is taken and is verified periodically. When a corrupted snapshot is detected, a replica rebuild is triggered to repair the snapshot.
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. The system will consume computing and disk IO resources while hashing snapshot disk files. In the meantime, the performance will be impacted.
Do you have an estimate on much impact will be on the performance?

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- `SnapshotHash` issues a snapshot hashing request to engin.
```suggestion
- `SnapshotHash` issues a snapshot hashing request to engine.
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - fast-check: Enable snapshot disk file hashing and fast data integrity checking. Longhorn system only hashes snapshot disk files if their are not hashed or the modification time are changed. In
```suggestion
    - fast-check: Enable snapshot disk file hashing and fast data integrity checking. Longhorn system only hashes snapshot disk files if they are not hashed or if the modification time changed. In this mode, filesystem-unaware corruption cannot be detected, but the impact on system performance can be minimized.
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processPeriodicSnapshotVerify()`**: Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If cur
```suggestion
    - **1 goroutine `processPeriodicSnapshotVerify()`**: Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If the current time exceeds the sum of `node.status.lastVerifiedAt` and `snapshot-data-integrity-interval`, then it populates engines' snapshots and sends snapshot hashing/checking tasks to the `snapshotVerifyTaskChan` channel. 
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to the their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process.
```suggestion
3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process.
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +        - Use the  `snapshot.status.checksum` as the **final checksum**, set the replicas that have mismatching checksums to `ERR`
```suggestion
        - Use the `snapshot.status.checksum` as the **final checksum**, and set the replicas that have mismatching checksums to `ERR`
```

2022-10-28 01:27 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +### CRC64 (ISO)
Can we have more info on what this section is for?

2022-10-28 01:52 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. The system will consume computing and disk IO resources while hashing snapshot disk files. In the meantime, the performance will be impacted.
I only measure the CPU usage during checksumming.
Do you want to check the io performance? If yes, I can benchmark it.

2022-10-28 02:08 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +### CRC64 (ISO)
No prob. Updated it as well as the test plan. Thank you.

2022-10-28 02:09 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +A snapshot hashing worker pool is created while starting the sync-agent server. The sync-agent receives the snapshot hashing requests and push them into the boundded and non-blocking `taskQueue` chan
Updated. Thank you.

2022-10-28 02:09 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +        - Use the  `snapshot.status.checksum` as the **final checksum**, set the replicas that have mismatching checksums to `ERR`
Updated. Thank you.

2022-10-28 02:09 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +4. The worker waits until each snapshot disk file's checksum calculation has been completed. It periodically polls the engine and checks the status during waiting period.
Updated. Thank you.

2022-10-28 02:09 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to the their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process.
Updated. Thank you.

2022-10-28 02:09 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processPeriodicSnapshotVerify()`**: Periodically create snapshot hashing/checking tasks. The period is determined by the global setting `snapshot-data-integrity-interval`. If cur
Updated. Thank you.

2022-10-28 02:10 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - fast-check: Enable snapshot disk file hashing and fast data integrity checking. Longhorn system only hashes snapshot disk files if their are not hashed or the modification time are changed. In
Updated. Thank you.

2022-10-28 02:10 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- `SnapshotHash` issues a snapshot hashing request to engin.
Updated. Thank you.

2022-10-28 02:10 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +Longhorn system supports volume snapshotting and stores the snapshot disk files on the local disk. However, it is impossible to verify the data integrity of snapshots due to the lack of the checksums
Updated. Thank you.

2022-10-28 02:20 UTC, c3y1huang commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. The system will consume computing and disk IO resources while hashing snapshot disk files. In the meantime, the performance will be impacted.
> I only measure the [CPU usage](https://github.com/longhorn/longhorn/issues/4210#issuecomment-1286484094) during checksumming. 

It would be nice if we could put it here, so there is a better picture of the impact mentioned.

> Do you want to check the impact on io performance? If yes, I can benchmark it.

Do you think there will be an impact on io performance?

2022-10-28 02:24 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. The system will consume computing and disk IO resources while hashing snapshot disk files. In the meantime, the performance will be impacted.
Yes, I think io perfmance should be impacted.
No prob. I will add the results here. Thank you.

2022-10-28 12:59 UTC, shuo-wu reviewed
In general LGTM

2022-10-28 12:59 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  - Usage: `longhorn --url ${engine-ip}:{$engine-port} snapshot hash tcp://${replica-sync-agent-ip}:${replica-sync-agent-port} --snapshot-name ${name}`
NIT: I am thinking if we need to use the first port (replica gPRC server port) for simplicity. Then cmd function should be able to get the sync agent port based on the first port.

2022-10-28 12:59 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  2. Get the value of the extended attribute `user.longhorn-system.checksum` recording the checksum and `ctime` of the file in the last calculation.
NIT: `user.longhorn-system.checksum.crc64`

2022-10-28 12:59 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processSnapshotChangeEvent()`**: Send a snapshot hashing/checking task to the bounded and non-blocking `snapshotVerifyTaskChan` buffered channel after receiving one snapshot `UPD
NIT: Can we use a workqueue (like the controllers) instead? IIRC, the workqueue can help eliminate duplications.

2022-10-30 11:28 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. The system will consume computing and disk IO resources while hashing snapshot disk files. In the meantime, the performance will be impacted.
Provided the perfomance comparison table.

2022-10-30 11:40 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    3. The worker waits until each replica's snapshot file's checksum calculation has been completed. It periodically polls the engine and checks the status during waiting periods.
Will be improved in https://github.com/longhorn/longhorn/issues/4725

2022-10-31 01:22 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processSnapshotChangeEvent()`**: Send a snapshot hashing/checking task to the bounded and non-blocking `snapshotVerifyTaskChan` buffered channel after receiving one snapshot `UPD
Using a workqueue is a good method. The workqueue's capacity is unlimited, so the system's memory might be run out if there are lots of verification tasks. So, I use the bounded channel here.

2022-10-31 01:23 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  2. Get the value of the extended attribute `user.longhorn-system.checksum` recording the checksum and `ctime` of the file in the last calculation.
I'm thinking if `user.longhorn-system.metadata` is better. `user.longhorn-system.checksum` contains
hashing method, hash value and ctime. WDYT?

2022-10-31 13:07 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  2. Get the value of the extended attribute `user.longhorn-system.checksum` recording the checksum and `ctime` of the file in the last calculation.
`user.longhorn-system.checksum` with hashing method, hash value and time looks good.

2022-10-31 13:09 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processSnapshotChangeEvent()`**: Send a snapshot hashing/checking task to the bounded and non-blocking `snapshotVerifyTaskChan` buffered channel after receiving one snapshot `UPD
The queue depth is determined by the snapshot count in the cluster. Hence I think the unlimited capacity should be fine. Besides, the monitor can forget some keys when the keys reach the retry limit.

2022-10-31 13:11 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processSnapshotChangeEvent()`**: Send a snapshot hashing/checking task to the bounded and non-blocking `snapshotVerifyTaskChan` buffered channel after receiving one snapshot `UPD
Got it. Replacing the channel with workqueue is good to me.

2022-11-01 09:59 UTC, derekbit commented
I think `SnapshotDataIntegrityInterval` might not be user-friendly.
If we use `SnapshotDataIntegrityCron` instead, users can specify the off-peak time for hashing/verifying snapshots. WDYT? @shuo-wu @innobead

2022-11-01 13:45 UTC, shuo-wu commented
> I think `SnapshotDataIntegrityInterval` might not be user-friendly. If we use `SnapshotDataIntegrityCron` instead, users can specify the off-peak time for hashing/verifying snapshots. WDYT? @shuo-wu @innobead

Good idea! It's nice to have this feature!

2022-11-02 00:59 UTC, innobead commented
> I think `SnapshotDataIntegrityInterval` might not be user-friendly. If we use `SnapshotDataIntegrityCron` instead, users can specify the off-peak time for hashing/verifying snapshots. WDYT? @shuo-wu @innobead

Do you mean users could have more control to decide how often or frequently to run those operations? If YES, would we have any validation to avoid too aggressive execution? I assume we will do the same for interval if still using `SnapshotDataIntegrityInterval`.

2022-11-02 01:56 UTC, derekbit commented
> > I think `SnapshotDataIntegrityInterval` might not be user-friendly. If we use `SnapshotDataIntegrityCron` instead, users can specify the off-peak time for hashing/verifying snapshots. WDYT? @shuo-wu @innobead
> 
> Do you mean users could have more control to decide how often or frequently to run those operations?

Yes, for exmaple, set `0 0 * * SUN` for one execution at 00:00 on Sunday.

> If YES, would we have any validation to avoid too aggressive execution? 

If the previous verification is not finished yet, the new job won't start. Then, we can avoid the aggressive execution.

>  I assume we will do the same for interval if still using SnapshotDataIntegrityInterval.

Yes,. But users have to calculate the interval and set the value at a specific moment, then the next job can run at the next desired moment. I think it is not friendly and intuitive enough.

2022-11-02 02:09 UTC, innobead commented
@derekbit then, LGTM

2022-11-02 05:19 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +    - **1 goroutine `processSnapshotChangeEvent()`**: Send a snapshot hashing/checking task to the bounded and non-blocking `snapshotVerifyTaskChan` buffered channel after receiving one snapshot `UPD
Updated. Thank you.

2022-11-02 13:54 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. Task workers fetch tasks from `snapshotVerifyTaskQueue` and check if the snapshot disk file needs to be hashed. The rules are
NIT: mention the concurrent limit issue

2022-11-02 13:54 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +A per-node concurrent snapshot hashing limit at the same time is configurable by editing the global setting `snapshot-data-integrity-per-node-concurrent-limit` to prevent exhaustion of computing and
The sync agent server is a per-replica server. Does sending the value to it work?

2022-11-02 14:18 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +A per-node concurrent snapshot hashing limit at the same time is configurable by editing the global setting `snapshot-data-integrity-per-node-concurrent-limit` to prevent exhaustion of computing and
No. The design is changed and will be based on our discussion. I'll update this part.

2022-11-03 02:18 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +2. Task workers fetch tasks from `snapshotVerifyTaskQueue` and check if the snapshot disk file needs to be hashed. The rules are
Update the steps.

2022-11-03 02:18 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +A per-node concurrent snapshot hashing limit at the same time is configurable by editing the global setting `snapshot-data-integrity-per-node-concurrent-limit` to prevent exhaustion of computing and
Updated the concurrent limit part.

2022-11-06 14:38 UTC, derekbit commented
Please help review again. Thank you.
cc @shuo-wu @c3y1huang @innobead @joshimoo

2022-11-07 03:19 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process. To ensure only one in-progress calculat
NIT: need to talk a little bit more about how the workers rely on the file lock to achieve the concurrent limit... 
`To ensure only one in-progress calculation, the worker holds the per-node file lock`. This is confusing. It's more like we are hashing the snapshot one by one.

2022-11-07 10:40 UTC, innobead reviewed
MacOS's .DS_Store in this PR. Suggest adding to .gitignore, because it seems quite commont to hit this wrong commit when using Mac.

2022-11-07 11:17 UTC, innobead requested changes
In general, LGTM. Just some minor items needed to resolve, then we can merge this.

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  - Add `node.status.snapshotPeriodicCheckStatus.state` for indicating current periodic check state. The value can be `idle` or `in-progress`.
Probably can check what state we use in other status to make the pattern consistent like using suffix `ed` or `ing`.

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
Local volume or 1-replica volume can skip hash and check.

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +4. The worker waits until each snapshot disk file's checksum calculation has been completed. It periodically polls the engine and checks the status during the waiting period.
Because we don't have global even queue/broker, it's possible to make replica call back to the engine instead of polling? (probably can do it in later version)

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process. To ensure only one in-progress calculat
I would rather suggest adding concurrent check to non-goals w/ the reason we found at the moment.

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **snapshot-data-integrity-cron-job**
We will have a default value when enabling `snapshot-data-integrity`?

2022-11-07 11:17 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **If the global setting `snapshot-data-integrity` is set to `fast-check`**
If a replica is found corrupted, could send an event to make it outstanding to you when monitoring K8s events.

2022-11-07 11:18 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **snapshot-data-integrity-cron-job**
The default value is `disabled`.

2022-11-07 11:19 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **If the global setting `snapshot-data-integrity` is set to `fast-check`**
Yeah. The event is emitted in the implementation.

2022-11-07 11:20 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
I thought the single replica case.
Because we are still able to detect the silent corruption in single replica's snapshot disk files, I don't skip the hash and check.

2022-11-07 11:23 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
But how do you recognize there is an error when only one replica? just compare the new value with the previously saved info in the snapshot checksum field?

2022-11-07 11:25 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **snapshot-data-integrity-cron-job**
Asked about the cron job instead of the global setting for `snapshot-data-integrity`

The answer from @derekbit , `default value: “0 0 */7 * *“. One week might be reasonable`

2022-11-07 11:40 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +#### Global Settings
We can add `snapshot-data-integrity` for volume level setting. The other two settings can only be configured globally.

How about it?

2022-11-07 11:43 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +#### CLI
Only for troubleshooting and consistency.

2022-11-07 11:51 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +4. The worker waits until each snapshot disk file's checksum calculation has been completed. It periodically polls the engine and checks the status during the waiting period.
Yes, I think it is possible, but not sure if there is any potential issue. We can improve in the later version.

2022-11-07 11:55 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
> But how do you recognize there is an error when only one replica?

Compare the ctime and checksum of the disk file and the values recorded in the xattr.
If ctime are identical, but checksums are mismatched, it indicats the silent corruption happen. In this case, we just emit an error event and won't do any handling.

2022-11-07 12:07 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
BTW, the silent corruption detection algo is described in `If the global setting snapshot-data-integrity is set to enabled`

2022-11-07 12:19 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +#### Global Settings
Sounds good to me. It seems the other two are sub settings.

2022-11-07 12:19 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +  - Add `node.status.snapshotPeriodicCheckStatus.state` for indicating current periodic check state. The value can be `idle` or `in-progress`.
Then we are good.

2022-11-07 12:20 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
Ok, so the same as n replicas. Let's keep it as is first, then see any feedback later.

2022-11-07 12:21 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +4. The worker waits until each snapshot disk file's checksum calculation has been completed. It periodically polls the engine and checks the status during the waiting period.
Sounds good. Please create a following issue then. Thanks.

2022-11-07 12:35 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
BTW, we will per volume setting. User can disable it manually if replica=1.

2022-11-07 12:37 UTC, innobead commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +      - Volume-head disk file, i.e. `Volume Head` in the following figure
It sounds good, so they can do the customization if they want.

2022-11-07 12:57 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +- **If the global setting `snapshot-data-integrity` is set to `fast-check`**
Updated. Thank you.

2022-11-07 12:57 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +#### Sync-Agent gRPC API
Updated. Thank you.

2022-11-07 12:57 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process. To ensure only one in-progress calculat
> I would rather suggest adding concurrent check to non-goals w/ the reason we found at the moment.

Added. Thank you.

2022-11-07 13:03 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +#### Global Settings
Added the `volume.spec.dataIntegrityCheck`.

2022-11-07 13:35 UTC, derekbit commented
Add `volume.spec.snapshotDataIntegrity`. The value can be `global`, `disabled`, `enabled` and `fast-check`.
`global` means the setting will following the value in the global setting `snapshot-data-integrity`.
@innobead

2022-11-07 13:42 UTC, innobead commented
The enum of value should be ignored, enabled, disabled, and fast-check.

2022-11-07 13:49 UTC, merged

2022-11-07 13:54 UTC, derekbit commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process. To ensure only one in-progress calculat
> But it’s better to have a brief test over the calculation time. For example, when calculating a 100G or 1T snapshot (empty, full of data, intermittent data blocks), how long it will take? Then we can provide some suggestions about the hashing check interval or if the fast-check should be used when there are lots of snapshots in the cluster.

@shuo-wu I think this can be added in official doc for users' reference. WDYT?

2022-11-08 01:44 UTC, shuo-wu commented on enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
> +3. Issue snapshot hashing requests to their associated engines. Then, the checksum of the snapshot disk file is calculated individually in the replica process. To ensure only one in-progress calculat
Sure!