Dockerfile for 'recovery from longhorn backup w/o system installed' doc
longhorn/longhorn pull request #4677
Opened 2022-10-04 07:22 UTC by weizhe0422

Longhorn 1521

Signed-off-by: Ray Chang <ray.chang@suse.com>

2022-10-04 10:26 UTC, innobead requested changes
Suggest createing a script `restore-backup-to-file.sh` in scripts folder and use docker command inside the script to run `longhornio/longhorn-engine` to exeucte instead of having Dockerfile. 

A executable script is better than a Dockerfile which means users need to build first, then run later..

2022-10-04 10:26 UTC, innobead commented on examples/restore_to_file.Dockerfile.template
> +FROM rancher/longhorn-engine:v0.4.1
Please use `longhornio/longhorn-engine` image instead, also I would suggest using 1.3.1 image.  We also need to update `restore_to_file.yaml.template` as well.

2022-10-04 13:10 UTC, weizhe0422 commented on examples/restore_to_file.Dockerfile.template
> +FROM rancher/longhorn-engine:v0.4.1
Update the Longhorn-engine image version as 1.3.1

https://github.com/longhorn/longhorn/blob/2a1c04cf7ea3696c0552e986b64fab5f1b13fd69/examples/restore_to_file.yaml.template#L19

2022-10-04 13:31 UTC, weizhe0422 commented
I will modify the DOCKERFILE generated by shell script.

2022-10-04 17:03 UTC, innobead requested changes
@weizhe0422 you misunderstood my previous review... I did not ask you to create a script to generate Dockerfile but rather run `docker run` command directly via `longhornio/longhorn-engine` to restore the backup to a file. 

for example:
```shell
# Use -e to add required environment variables
# Use -v to bind mount to specify the generate the place
docker run longhornio/longhorn-engine:v1.3.1 longhorn backup restore-to-file <backup-url> --backing-file <backing-file> --output-file <output-file> --output-format <output-format>
```

Also, actually, the backup could be based on a backing image, so need to consider this case as well. Please check `--backing-file`.

2022-10-04 17:17 UTC, weizhe0422 commented
I will reprocess the PR, sorry to misunderstand the comment.

2022-10-05 07:38 UTC, weizhe0422 commented
Script that starts the `longhornio/longhorn-engine` docker container to execute.

- w/o specify backing image
![image](https://user-images.githubusercontent.com/17548901/194005242-752e1b1a-0266-45c8-93c1-e1693b969ffd.png)
- w/ specify backing image
![image](https://user-images.githubusercontent.com/17548901/194005865-2521bfc6-dc7c-4e82-98d1-25957ed6f3be.png)

2022-10-06 07:51 UTC, innobead requested changes
Just noticed you changed the script with an interactive way, which is good for one time execution, but not good for automation, so it will limit how users can use it. 

I would suggest making the script to run directly with optional options, so it will let users to decide how they will use this script. WDYT?

You can refer to other scripts in scripts folder.

2022-10-06 12:23 UTC, weizhe0422 commented
I would get these parameters as script options instead of interactive mode.

2022-10-13 13:52 UTC, innobead commented
> I would get these parameters as script options instead of interactive mode.

@weizhe0422 if it's ready to review, you can request to avoid it pending for a while. Thanks.

2022-10-13 14:32 UTC, weizhe0422 commented
Extract parameter as script options, and also check whether the required parameter is blank or not. 

- w/o specify backing image
![image](https://user-images.githubusercontent.com/17548901/195620452-152993f4-c311-4110-a666-ce951a0a5941.png)
- w specify backing image
![image](https://user-images.githubusercontent.com/17548901/195625318-0e72600b-bb58-4a5e-88f0-3bf4d7e0716f.png)

2022-10-14 12:43 UTC, c3y1huang commented on scripts/restore-backup-to-file.sh
> +              --output-file ${target_directory} --output-format ${output_format}
Can the user access the output file when the `${target_directory}` is not in `/tmp/restore`?

2022-10-14 12:43 UTC, c3y1huang commented on scripts/restore-backup-to-file.sh
> +              longhornio/longhorn-engine:v1.3.1 longhorn backup \
What about making the version tag a parameter? Do you think it will be beneficial?

2022-10-16 11:51 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +              longhornio/longhorn-engine:v1.3.1 longhorn backup \
I think this can be an optional parameter. If the user leaves the version number blank, "latest" is used instead.

2022-10-17 10:46 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +              longhornio/longhorn-engine:v1.3.1 longhorn backup \
We can't use master-head in the script for users to use, because it's not dev image.

I think Chinya suggestion probably better to have a version parameter provided by users, but actually you can simply guide user to use the right version via doc like `./scripts/restore-backup-to-file.sh --version <version> ...` and <version> can be replaced by `v{{< current-version >}}` in the doc.

2022-10-18 05:57 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +              longhornio/longhorn-engine:v1.3.1 longhorn backup \
I got it, I will just provide another argument for user to specify version and mentions it on document.

2022-10-18 06:11 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +              --output-file ${target_directory} --output-format ${output_format}
I try to set the target directory so that it is not under `/tmp/restore`, it returns an error saying that the folder cannot be created or accessed.  And the template yaml file also mention it should be in `/tmp/restore`
https://github.com/longhorn/longhorn/blob/4ba39a989b4b482d51fd4bc651f61f2b419428bd/examples/restore_to_file.yaml.template#L23-L25

I will modify the script file to make `/tmp/restore` as the target directory prefix like `--output-file /tmp/restore/${target_directory}`

2022-10-18 09:20 UTC, derekbit commented on examples/restore_to_file.yaml.template
> +    image: longhornio/longhorn-engine:v<LONGHORN_VERSION>
```suggestion
    image: longhornio/longhorn-engine:<LONGHORN_VERSION>
```

2022-10-18 09:20 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +   echo "  -v, --version                (Required) Specify Lognhorn version to execute, e.g. 1.3.2"
```suggestion
   echo "  -v, --version                (Required) Specify Lognhorn version to execute, e.g. v1.3.2"
```

2022-10-18 09:20 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +usage () {
Can you add a short description of the script's purpose?
e.g.
```
# gzip -h
Usage: gzip [OPTION]... [FILE]...
Compress or uncompress FILEs (by default, compress FILES in-place).

Mandatory arguments to long options are mandatory for short options too.

  -c, --stdout      write on standard output, keep original files unchanged
...
...
```

2022-10-18 09:20 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +   echo "  -f, --output-format          (Required) Output file foramt, and the supported options are raw or qcow2."
```suggestion
   echo "  -f, --output-format          (Required) Output file foramt. Supported format: raw or qcow2."
```

2022-10-18 09:30 UTC, weizhe0422 commented on examples/restore_to_file.yaml.template
> +    image: longhornio/longhorn-engine:v<LONGHORN_VERSION>
Thank you and I will follow the comment to fix it.

2022-10-18 09:36 UTC, derekbit approved these changes
In general, LGTM.

2022-10-18 09:36 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +   echo "Restore a Longhorn backup to a raw image or a qcow2 image w/o system installed."
```suggestion
   echo "          [--backing-file <backing_file_path>]"
   
   echo "Restore a Longhorn backup to a raw or qcow2 formatted image."
```

2022-10-18 09:39 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +   echo "Restore a Longhorn backup to a raw image or a qcow2 image w/o system installed."
fix: removed the redundant words in description

2022-10-18 09:57 UTC, innobead commented on examples/restore_to_file.yaml.template
> +    image: longhornio/longhorn-engine:<LONGHORN_VERSION>
Because of changing this, you need to update https://longhorn.io/docs/<each version>/advanced-resources/data-recovery/recover-without-system/ accordingly.

2022-10-18 09:58 UTC, innobead requested changes

2022-10-18 09:58 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +		-v|--version)
Wrong indent.

2022-10-18 09:58 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +		-h|--help)
Wrong indent.

2022-10-18 10:05 UTC, innobead requested changes

2022-10-18 10:05 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +	key="$1"
I think you are using a tab instead of empty space. For shell script, please use 2 spaces instead of a tab. https://google.github.io/styleguide/shellguide.html#s5.1-indentation (you can check other scripts)

2022-10-18 10:23 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +	key="$1"
I referenced another script but forgot to replace tabs with spaces and it was completely fixed.

I would look at the coding style documentation you provided.

2022-10-18 10:30 UTC, weizhe0422 commented on examples/restore_to_file.yaml.template
> +    image: longhornio/longhorn-engine:<LONGHORN_VERSION>
Yes, I will also update the documentation to let users know that the version number parameter needs to be specified.

https://github.com/longhorn/website/pull/580

2022-10-18 10:38 UTC, innobead commented on examples/restore_to_file.yaml.template
> +    image: longhornio/longhorn-engine:<LONGHORN_VERSION>
Good!

2022-10-18 10:52 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +if [ ! ${aws_access_key} ] || [ ! ${aws_secret_access_key} ] ||
After reference the [this](https://www.linux.org/threads/what-does-z-flag-mean-in-shell-script-used-in-if-condition.17899/post-54067) and also check `test help`, I think using `-z` is the formal way to check the string is empty or not.

2022-10-18 11:02 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +if [ ! ${aws_access_key} ] || [ ! ${aws_secret_access_key} ] ||
> Usually, use -z to check whether the variable is an empty string or not, but think the bang operator could work as well.

Yeah.

2022-10-18 11:58 UTC, innobead requested changes
Almost there, after resolving the rest of the comments, then it can be merged. 

Also, https://www.shellcheck.net/wiki/SC2086, always has a good habit to evaluate the variable as a string w/ double quote.

2022-10-18 11:58 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +fi
As per https://github.com/longhorn/longhorn-engine/blob/52ac3b6d0ca410957f53729c9aabbcb9e3bc007c/app/cmd/restore_to_file.go#L140-L140, `backing-file` is optional by including empty string, so you should not need to have if-else, but just one.

2022-10-19 01:00 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +   echo "  -h, --help                   Usage message"
BTW, does it support restoring from NFS backup target?

2022-10-19 05:23 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +   echo "  -h, --help                   Usage message"
@weizhe0422 ?

2022-10-19 05:31 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +   echo "  -h, --help                   Usage message"
I think it can be retrieve from NFS, but I still try to verify it is workable.

2022-10-19 07:39 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +   echo "  -h, --help                   Usage message"
U should need to use privilege mode, because it's different from the s3 case.

2022-10-19 16:24 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +   echo "  -h, --help                   Usage message"
After fixing as per the comments, I confirmed that the backup destination can be NFS.
![image](https://user-images.githubusercontent.com/17548901/196747526-5a219eca-7796-48f6-8c2d-d0efff121c0a.png)

So I modified the logic to check the required parameters to only check for AWS related parameters when `s3` is set as the backup destination.  And also enable privilege mode when execute the docker container.

2022-10-20 09:21 UTC, weizhe0422 commented
Mounting NFS folder in docker container, after check the [Linux manual page](https://man7.org/linux/man-pages/man2/mount.2.html), there is need `SYS_ADMIN` capacity to mount filesystems. 

I think there are two ways to make mount filesystems successfully.
 1. Enabled all capabilities to the container: `docker run --privileged=true ...`
 2. Grant capabilities to perform administrator operations: `docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined...`

The [Docker document](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) recommend to use the 2nd way. And using the 2nd way will make sure to mount keep kernel files ( e.g. `/sys/fs`, `/proc/fs`) as read-only.

Here is the result to benchmark using different parameters:
![image](https://user-images.githubusercontent.com/17548901/196908961-c2f5be62-174f-4939-b687-4fdd69df9a1a.png)

Ref.
 - https://serverfault.com/questions/824809/chrome-under-docker-cap-sys-admin-vs-privileged

2022-10-20 11:39 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +fi
```suggestion
if [[ ! "${backup_url}" =~ ^[Ss]3 ]]; then
    DOCKER_CAP = "....."
    DOCKER_SEC = "....."
fi

docker run ${DOCKER_CAP} ${DOCKER_SEC} \
              -v /tmp/restore:/tmp/restore \
              longhornio/longhorn-engine:"${version}" longhorn backup \
              restore-to-file ""${backup_url}"" \
              --output-file "/tmp/restore/${output_file}" \
              --output-format "${output_format}" \
              --backing-file "${backing_file}"
fi
```

Probably can simplify the codes like this.

2022-10-20 12:39 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +fi
Thank you. I will rewrite to simplify the code.

2022-10-20 12:50 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +            --backing-file "${backing_file}"
```suggestion
# Compose the docker arguments
if [[ "${backup_url}" =~ ^[Ss]3 ]]; then
            CUSTOMIZED_ARGS="-e AWS_ACCESS_KEY_ID="${aws_access_key}" -e AWS_SECRET_ACCESS_KEY="${aws_secret_access_key}" "
else
            CUSTOMIZED_ARGS="--cap-add SYS_ADMIN --security-opt apparmor:unconfined"
fi

# Start restoring a backup to an image file. 
docker run ${CUSTOMIZED_ARGS} -v /tmp/restore:/tmp/restore \
            longhornio/longhorn-engine:"${version}" longhorn backup \
            restore-to-file ""${backup_url}"" \
            --output-file "/tmp/restore/${output_file}" \
            --output-format "${output_format}" \
            --backing-file "${backing_file}"
```

2022-10-20 12:57 UTC, derekbit commented on scripts/restore-backup-to-file.sh
> +fi
See above comment.

2022-10-20 13:32 UTC, derekbit approved these changes

2022-10-20 14:03 UTC, innobead requested changes

2022-10-20 14:03 UTC, innobead commented on scripts/restore-backup-to-file.sh
> +            --backing-file "${backing_file}"
```suggestion
usage () {
   echo "USAGE: $0 --aws-access-key <your_aws_access_key>  \ "
   echo "          --aws-secret-access-key <your_aws_secret_access_key> \ "
   echo "          --backup-url s3://backupbucket@ap-northeast-1/backupstore?backup=<backup_name>&volume=<volume_name> \ "
   echo "          --target-directory /tmp/restore/volume.raw \ "
   echo "          --output-format raw \ "
   echo "          [--backing-file <backing_file_path>]"
   echo "Restore a Longhorn backup to a raw image or a qcow2 image."
   echo ""
   echo "  -u, --backup-url             (Required) Backups S3/NFS URL. e.g., s3://backupbucket@us-east-1/backupstore?backup=backup-bd326da2c4414b02&volume=volumeexamplename"
   echo "  -o, --output-file            (Required) Output file, e.g., /tmp/restore/volume.raw"
   echo "  -f, --output-format          (Required) Output file format, e.g., raw or qcow2"
   echo "  -v, --version                (Required) Longhorn version, e.g., v1.3.2"
   echo "      --aws-access-key         (Optional) AWS credentials access key"
   echo "      --aws-secret-access-key  (Optional) AWS credentials access secret key"
   echo "  -b, --backing-file           (Optional) backing image. e.g., /tmp/bakingfile.qcow2"
   echo "  -h, --help                   Usage message"
}

error_invalid_params() {
  usage
  exit 1
}

while [[ "$#" -gt 0 ]]; do
  key="$1"
  case $key in
    --aws-access-key)
    aws_access_key="$2"
    shift # past argument
    shift # past value
    ;;
    --aws-secret-access-key)
    aws_secret_access_key="$2"
    shift # past argument
    shift # past value
    ;;
    -u|--backup-url)
    backup_url="$2"
    shift # past argument
    shift # past value
    ;;
    -o|--output-file)
    output_file="$2"
    shift # past argument
    shift # past value
    ;;
    -f|--output-format)
    output_format="$2"
    shift # past argument
    shift # past value
    ;;
    -b|--backing-file)
    backing_file="$2"
    shift # past argument
    shift # past value
    ;;
    -v|--version)
    version="$2"
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    usage
    exit 0
    shift
    ;;
    *)
    error_invalid_params
    ;;
    esac
done

# Check the required parameters exits
if [ -z "${backup_url}" ] || [ -z "${output_file}" ] || [ -z "${output_format}" ] || [ -z "${version}" ]; then
      error_invalid_params
fi

if [[ "${backup_url}" =~ ^[Ss]3 ]]; then
  if [ -z "${aws_access_key}" ] || [ -z "${aws_secret_access_key}" ]; then
      error_invalid_params
  fi
fi

# Compose the docker arguments
if [[ "${backup_url}" =~ ^[Ss]3 ]]; then
  CUSTOMIZED_ARGS="-e AWS_ACCESS_KEY_ID="${aws_access_key}" -e AWS_SECRET_ACCESS_KEY="${aws_secret_access_key}" "
else
  CUSTOMIZED_ARGS="--cap-add SYS_ADMIN --security-opt apparmor:unconfined"
fi

# Start restoring a backup to an image file. 
docker run ${CUSTOMIZED_ARGS} -v /tmp/restore:/tmp/restore \
            longhornio/longhorn-engine:"${version}" longhorn backup \
            restore-to-file ""${backup_url}"" \
            --output-file "/tmp/restore/${output_file}" \
            --output-format "${output_format}" \
            --backing-file "${backing_file}"
```

2022-10-20 15:25 UTC, weizhe0422 commented on scripts/restore-backup-to-file.sh
> +            --backing-file "${backing_file}"
Thank you. 

I have checked the suggested version and made some modifications.

2022-10-20 15:27 UTC, merged