Kubernetes 1.2.5 support
longhorn/longhorn pull request #4695
Opened 2022-10-11 00:53 UTC by PhanLe1010

1. Set enablePSP to false by default
1. Bump K8s min version support and CSI sidecar versions * Min Kubernetes version from 1.18 to 1.21 * longhornio/csi-resizer v1.2.0 -> v1.3.0 * longhornio/csi-snapshotter: v3.0.3 -> v5.0.1
1. Update CSI snapshot examples from v1beta1 to v1
1. Updating images file
1. Gnerating new longhorn.yaml from the chart for kubectl

longhorn/longhorn#4003
longhorn/longhorn#4239

2022-10-11 17:05 UTC, innobead reviewed
LGTM, but the same question for uninstall at https://github.com/longhorn/longhorn-manager/pull/1518#issuecomment-1275002235

2022-10-11 22:31 UTC, joshimoo reviewed
LGTM need to check on the uninstall job namespace change. https://github.com/longhorn/longhorn-manager/pull/1518#discussion_r992826517

As well as make sure we communicate the potential issue with older invalid csi snapshots, which were created before the upstream snapshot controller implemented a webhook for these.
https://github.com/longhorn/longhorn-manager/pull/1518#discussion_r992824473

2022-10-13 17:21 UTC, innobead requested changes
I didn't see `longhorn/templates/psp.yaml` removed from this PR? anything missing here?

2022-10-13 17:28 UTC, PhanLe1010 commented
> I didn't see longhorn/templates/psp.yaml removed from this PR? anything missing here?

The default value for `enablePSP` is switched to false which means we don't shi it by default. Some users on Kubernetes < 1.25 may still need it so we keep the template there

2022-10-13 17:48 UTC, innobead commented
> > I didn't see longhorn/templates/psp.yaml removed from this PR? anything missing here?
> 
> The default value for `enablePSP` is switched to false which means we don't shi it by default. Some users on Kubernetes < 1.25 may still need it so we keep the template there

100% correct!

2022-10-13 17:48 UTC, merged