Extend the LEP to allow customization of the cipher
longhorn/longhorn pull request #4777
Opened 2022-10-24 09:24 UTC by mantissahz

Extend the old LEP `pv-encryption.md` to allow users customize the options of cipher used by `cryptsetup`.

longhorn/longhorn#3353

Signed-off-by: James Lu <james.lu@suse.com>

2022-10-25 02:03 UTC, c3y1huang commented on enhancements/20221024-pv-encryption.md
> +- create the secret for that volume in the configured namespace with customization options of the cipher for instance `cipher`, `key-size` and `hash`
Do we need to add those to the test-plan?

2022-10-25 10:57 UTC, derekbit commented on enhancements/20221024-pv-encryption.md
> +  CRYPTO_KEY_SIZE: "256" # this is optional
What are the default values? Any tradeoff about different settings?

2022-10-25 14:38 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +  CRYPTO_KEY_SIZE: "256" # this is optional
The default values are listed as the example.
Yes, cipher and key-size have the dependency, some ciphers could not use 512 key-size.
And There are different speeds of encryption and decryption for different cipher choices.

2022-10-26 06:24 UTC, c3y1huang requested changes

2022-10-26 06:24 UTC, c3y1huang commented on enhancements/20221024-pv-encryption.md
> +- `CRYPTO_KEY_CIPHER` allow users to choose the cipher algorithm when creating an encrypted volume by `cryptsetup`,
```suggestion
- `CRYPTO_KEY_CIPHER` allow users to choose the cipher algorithm when creating an encrypted volume by `cryptsetup`
```

2022-10-26 06:24 UTC, c3y1huang commented on enhancements/20221024-pv-encryption.md
> +- `CRYPTO_KEY_SIZE` sets key size in bits. The argument has to be a multiple of 8 and maximum interactive passphrase length is 512 (characters.)
```suggestion
- `CRYPTO_KEY_SIZE` sets the key size in bits. The argument has to be a multiple of 8 and the maximum interactive passphrase length is 512 (characters)
```

2022-10-26 06:24 UTC, c3y1huang commented on enhancements/20221024-pv-encryption.md
> +- check if customized options of the cipher are correct
```suggestion
- check if the customized options of the cipher are correct
```

2022-10-26 06:24 UTC, c3y1huang commented on enhancements/20221024-pv-encryption.md
> +- user is able to create & use an encrypted volume with customization options of the cipher
```suggestion
- user is able to create & use an encrypted volume with cipher customization options
```

2022-10-26 06:39 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +- `CRYPTO_KEY_CIPHER` allow users to choose the cipher algorithm when creating an encrypted volume by `cryptsetup`,
Modified. Thanks.

2022-10-26 06:39 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +- `CRYPTO_KEY_SIZE` sets key size in bits. The argument has to be a multiple of 8 and maximum interactive passphrase length is 512 (characters.)
Modified. Thanks.

2022-10-26 06:39 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +- check if customized options of the cipher are correct
Modified. Thanks.

2022-10-26 06:39 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +- user is able to create & use an encrypted volume with customization options of the cipher
Modified. Thanks.

2022-10-26 06:40 UTC, derekbit commented on enhancements/20221024-pv-encryption.md
> +  CRYPTO_KEY_SIZE: "256" # this is optional
Is CRYPTO_KEY_SIZE  necessary If `CRYPTO_KEY_HASH` is known?

2022-10-26 07:11 UTC, mantissahz commented on enhancements/20221024-pv-encryption.md
> +  CRYPTO_KEY_SIZE: "256" # this is optional
No, it seems that they are not dependent on each other.

2022-10-26 21:18 UTC, joshimoo approved these changes
LGTM

2022-10-27 00:34 UTC, c3y1huang approved these changes

2022-11-01 08:46 UTC, innobead approved these changes
LGTM.

But think further, probably we need to have specific settings for each provider in the future, even though right now all default to dm_crypt except CRYPTO_KEY_PROVIDER.

2022-11-01 08:47 UTC, merged