feat(support bundle): deploy
longhorn/longhorn pull request #4915
Opened 2022-11-22 03:44 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/2759

2022-11-24 06:27 UTC, innobead requested changes

2022-11-24 06:27 UTC, innobead commented on chart/templates/clusterrolebinding.yaml
> +  name: cluster-admin
Need to mention this in the doc.

2022-11-24 06:27 UTC, innobead commented on chart/values.yaml
> +      tag: v0.0.13
`longhornio/support-bundle-kit` instead

2022-11-24 06:27 UTC, innobead commented on chart/questions.yaml
> +  - variable: defaultSettings.supportBundleFailedHistoryLimit
Need the description.

2022-11-24 14:55 UTC, innobead approved these changes

2022-11-24 15:00 UTC, merged

2022-11-25 04:11 UTC, c3y1huang commented on chart/templates/clusterrolebinding.yaml
> +  name: cluster-admin
Update to https://github.com/longhorn/website/pull/620.

2022-11-25 04:20 UTC, innobead commented on chart/values.yaml
> +      tag: v0.0.13
Will need another new release, then update here before merging