feat(system-backup/restore): deploy
longhorn/longhorn pull request #4916
Opened 2022-11-22 06:09 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/1455

2022-11-29 10:37 UTC, innobead requested changes

2022-11-29 10:37 UTC, innobead commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
Why need this?

2022-12-07 10:12 UTC, innobead commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
I remembered we have a privileged issue related to webhooks, so we don't want to do some validation but rely on the host. @derekbit do you remember that?

2022-12-08 02:30 UTC, c3y1huang commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
We had no validation against the backup store.

2022-12-08 05:36 UTC, derekbit commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
> The validator will execute the engine binary to check if the backup already exists in the backup store.

It's a newly added feature, right?

> I remembered we have a privileged issue related to webhooks, so we don't want to do some validation but rely on the host. @derekbit do you remember that?

Yes, we limit the permission
```
        securityContext:
          runAsUser: 2000
```

2022-12-08 05:40 UTC, c3y1huang commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
https://github.com/longhorn/longhorn/issues/3701

2022-12-08 06:14 UTC, c3y1huang commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
Reverted the privilege change.

2022-12-08 08:39 UTC, c3y1huang commented on chart/templates/deployment-webhook.yaml
> +          path: /var/lib/longhorn/
https://github.com/longhorn/longhorn-manager/pull/1593

2022-12-08 14:38 UTC, innobead approved these changes

2022-12-08 14:38 UTC, merged