exclude Kasten explicitly
longhorn/longhorn pull request #4982
Opened 2022-12-01 22:26 UTC by Tejeev

There are two ways I was thinking we could word the if.  With an external variable saving any kasten resources, then an if that checks if the variable has a value, or just running the grep in the if statement.  I'm not sure which you would prefer but looks like this script tends to the former, so I prioritized that and commented out the latter.  Tested on the customer cluster, but I made some minor changes while transposing here so still need to run some tests

2022-12-08 11:18 UTC, innobead commented
@Tejeev Please fix the DCO check. Thanks.

2022-12-08 11:18 UTC, innobead commented
cc @longhorn/qa

2022-12-10 02:10 UTC, PhanLe1010 requested changes
I have some comments.

After resolving these comments, we need to do 2 tests for this PR @Tejeev 

1. Test with a cluster that has Kasten again. Can you help with this one @Tejeev because Longhorn team doesn't have this setup?
2. Test with a cluster that doesn't have Kasten. I can test this one

2022-12-10 02:10 UTC, PhanLe1010 commented on scripts/longhorn_rancher_chart_migration.sh
> +KASTENRESOURCES=`kubectl api-resources --kubeconfig ${DOWNSTREAM_KUBECONFIG} | grep kasten`
Bug: if there is no kasten resource in the cluster, this command will return exit code 1 which stops the whole script.

2022-12-10 02:10 UTC, PhanLe1010 commented on scripts/longhorn_rancher_chart_migration.sh
> +fi
If there is no KASTENRESOURCES, we should not get them right?

```suggestion
if [ -z "${KASTENRESOURCES}" ]; then
  RESOURCES=$(kubectl get-all --kubeconfig ${DOWNSTREAM_KUBECONFIG} --exclude AppRevision -o name -l io.cattle.field/appId=${RELEASE_NAME} 2>/dev/null | sort)
fi
else
  RESOURCES=$(kubectl get-all --kubeconfig ${DOWNSTREAM_KUBECONFIG} --exclude AppRevision,applications.apps.kio.kasten.io,passkeys.vault.kio.kasten.io -o name -l io.cattle.field/appId=${RELEASE_NAME} 2>/dev/null | sort)
fi
```

2023-02-05 02:03 UTC, closed without merging