feat(lep): concurrent backup restore design
longhorn/longhorn pull request #4991
Opened 2022-12-05 03:22 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/4558

2022-12-05 16:53 UTC, derekbit commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Category = SettingCategoryDangerZone,
Why put the setting in the `SettingCategoryDangerZone` category?

2022-12-05 17:02 UTC, derekbit commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Set the value to **0** to disable backup restore.
At first glance of the statement, I thought it means the replica on the node cannot be restored if the value is **0**.

IIUC, `concurrent-backup-restore-per-node-limit` limits the number of engines for backup restore in the node.  **0** means the engines on the nodes canno do backup restore, although its all replicas are all on different nodes. Correct? If yes, **0** might be a bit of confusing to users.

2022-12-05 17:09 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Set the value to **0** to disable backup restore.
Not sure if I understand what you mean, a bit confused.

Setting it to 0 means all engines on any node cannot do the backup restore. This means regardless of where the replicas are, none will be able to restore.

2022-12-05 17:12 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Category = SettingCategoryDangerZone,
I am just putting it in the same zone as the [Concurrent Replica Rebuild Per Node Limit](https://longhorn.io/docs/1.3.2/references/settings/#concurrent-replica-rebuild-per-node-limit) since those settings look similar. But just my 2 cents, we can put it somewhere else.

2022-12-05 17:14 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +1. Tag  Longhorn Engine when backup restore started. The value is `in-progress`. The number of Longhorn Engines with this labeled value will be compared to the [concurrent-backup-restore-per-node-lim
Fixed, thanks.

2022-12-05 17:15 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +1. Introduce a new `concurrent-backup-restore-limit` setting.
Sure. Updated.

2022-12-05 17:24 UTC, derekbit commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Set the value to **0** to disable backup restore.
Ah, thank you. Got it. It is a global setting.

2022-12-05 17:25 UTC, derekbit commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Category = SettingCategoryDangerZone,
Not sure the definition of `General` and `DangerZone`? Any rule we can follow?
cc @shuo-wu @innobead

2022-12-06 04:52 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Category = SettingCategoryDangerZone,
This is the commit message for adding this catalog (danger zone). It's a highlight to remind users when changing settings in this catalog will potentially cause some impacts on active volumes. But, there is no enforcement here, but notice purpose instead.

```
setting: recreate instance manager pod when GuaranteedEngineCPU changed

Make sure user don't change GuaranteedEngineCPU when there are active
workload running.

Also, add catalog `Danger Zone` for settings that may have big impact on
running workload.
```

2022-12-06 12:42 UTC, innobead requested changes

2022-12-06 12:42 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Have a new `concurrent-backup-restore-per-node-limit` setting allows user to limit the concurring backup restoring. This can help to lower the potential risk of overloading cluster when volume reques
Suggest renaming to `concurrent-volume-backup-restore-per-node-limit` to differentiate system backup restore.

2022-12-06 12:42 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +
Can we just make it simple to have a similar mechanism in engine controller as we have done for replica rebuilding? You can create an atomic count in the controller, then pass it to each monitor. 

https://github.com/longhorn/longhorn-manager/blob/5a80438e195cdb19fabcbc2a916a1dc41a3c3272/controller/replica_controller.go#L508-L512

2022-12-08 00:37 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Set the value to **0** to disable backup restore.
Will this setting impact DR volume? I would expect DR volume will not be impacted, because it's delta volume restore, so should not be counted here.

2022-12-08 00:38 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Default  = 5
The same as the default number of replica rebuilding.

2022-12-08 00:39 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +	restoringCounterAquired bool
`restoringCounterAquired` purpose?

2022-12-08 00:41 UTC, innobead requested changes

2022-12-08 00:41 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +1. Decrease the restoring counter when restoring counter is aquired and:
`Decrease the restoring counter when restoring counter is acquired when:`

2022-12-08 01:22 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Set the value to **0** to disable backup restore.
Updated 
`> Ignore checking on DR volumes (volume.Status.IsStandby).`

2022-12-08 01:22 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +Category = SettingCategoryDangerZone,
Moved to `General`.

2022-12-08 01:28 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +
This is better. Thanks and updated.

2022-12-08 02:12 UTC, innobead submitted a review, later dismissed

2022-12-08 02:13 UTC, innobead commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +   	# The purpose is to ensure we don't blindly increase/decrease the restoring counter.
Not sure, but will check the implementation PR.

2022-12-08 11:46 UTC, c3y1huang commented on enhancements/20221205-concurrent-backup-restore-limit.md
> +   	# The purpose is to ensure we don't blindly increase/decrease the restoring counter.
Updated.

2022-12-08 14:37 UTC, merged