OCP / OKD Documentation and Helm Support
longhorn/longhorn pull request #5004
Opened 2022-12-06 04:06 UTC by ArthurVardevanyan

Picking up where: https://github.com/longhorn/longhorn/pull/2909 left off.

Related Issue: https://github.com/longhorn/longhorn/issues/1831

Been using Longhorn on my OKD HomeLab Since OKD/OCP 4.10/1.24

Since these Launches are around the corner, targeting: 
- OCP: 4.12 / 1.25 
- Longhorn 1.4.0

Main Modifications from Previous PR:
- Removed Extra(?) Mount Points to Daemonset
- Converted Policy Commands to Yaml Cluster Role RBAC
- Removed ISCSI Setup as this is handled already by RHCOS/FCOS
- General Documentation Updates

Testing: 

Still need to Test OCP Side.

Exact Tested Version so Far:
- https://amd64.origin.releases.ci.openshift.org/releasestream/4.12.0-0.okd/release/4.12.0-0.okd-2022-12-05-210624
- https://github.com/longhorn/longhorn/commit/207e74ecd4a23dcd20f43e40a8a8e57cf2e54700

Bundle from Test:
Bundle doesn't generate, daemon-set selectors are not spinning up pods.

I did notice a startup "error/warning" on the manager pods, they may be related to 1.4.0-dev work, as I don't see those on my 1.3.2 / 4.11 Cluster.

Note current Bug with OKD 4.11.Z Versions  > [4.11.0-0.okd-2022-11-19-050030](https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.11.0-0.okd-2022-11-19-050030)
REF: https://github.com/longhorn/longhorn/issues/4988)

OKD 4.11.Z Versions  <=  [4.11.0-0.okd-2022-11-19-050030](https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.11.0-0.okd-2022-11-19-050030)
REF: https://github.com/longhorn/longhorn/issues/4988, I have not ran into issues previously. 

PR is Functional as it sits, however still needs some housekeeping.

2022-12-06 04:41 UTC, innobead commented
@ArthurVardevanyan it seems you are active on OKD deployment, so do you want to own https://github.com/longhorn/longhorn/issues/183?

2022-12-11 23:31 UTC, ArthurVardevanyan commented
##  4.11.0-0.okd-2022-11-19-050030 [Longhorn 1.3.2]
Their may be some noise, this a long-lasting cluster.
[longhorn-support-bundle_00e45f14-1554-4313-bb2b-27dbf74ab4c7_2022-12-11T22-25-07Z.zip](https://github.com/longhorn/longhorn/files/10203429/longhorn-support-bundle_00e45f14-1554-4313-bb2b-27dbf74ab4c7_2022-12-11T22-25-07Z.zip)

![Screenshot from 2022-12-11 17-05-26](https://user-images.githubusercontent.com/21159051/206932415-e870f611-5dac-474a-901a-518bdb8c63d0.png)
##  4.12.0-0.okd-2022-12-11-164611 [Longhorn 1.4.0.-dev]
Their might be some noise from a rolling reboot.
New Support Bundle Feature still isn't complete: 
Temporary Workaround, didn't include in chart.: 
```yaml
- kind: ServiceAccount
  name: default # supportbundle-agent-support-bundle daemonset doesn't use a dedicated service account.
  namespace: {{ include "release_namespace" . }}
  ```
[supportbundle_19d7497d-0deb-425a-990d-a2a6e367b09e_2022-12-11T23-17-27Z.zip](https://github.com/longhorn/longhorn/files/10203553/supportbundle_19d7497d-0deb-425a-990d-a2a6e367b09e_2022-12-11T23-17-27Z.zip)
![Screenshot from 2022-12-11 18-29-01](https://user-images.githubusercontent.com/21159051/206935353-3c3f3d3b-54c5-45be-b66c-2c3f436bc9d0.png)

2022-12-11 23:36 UTC, ArthurVardevanyan commented
> @ArthurVardevanyan it seems you are active on OKD deployment, so do you want to own #1831?

Sure, No Preference either way.
I have no plans to stop using Longhorn + OKD

This PR should be good to take a look at. It covers the basic use cases.

2023-01-01 21:34 UTC, ellakk commented
Great work! This worked great on OKD version 4.11.0-0.okd-2022-12-02-145640, although i needed to apply the machineconfig patch from #4988 to avoid the attach/detach loop.

2023-02-09 12:52 UTC, innobead commented
@longhorn/qa Could someone help with this testing? I would like to see the test from QA as well.

2023-02-09 15:32 UTC, khushboo-rancher commented
@roger-ryao Could you please help testing this?

2023-02-22 09:59 UTC, roger-ryao commented
We could install longhorn with helm on K3s, but I need to take time to build up OKD and test this PR.

2023-03-13 21:59 UTC, wtownse commented
Trying to get longhorn to install on a single node OCS cluster for testing.  I am using the helm chart and got it to start installing but I hit an issue with the CSI driver install.  it says ndoe is not support mount propagation although I set it to shared in a machine config for the CRIO service.  Does anyone have any ideas here?

2023-03-13 23:12 UTC, ArthurVardevanyan commented
> I am trying to get longhorn to install on a single node OCS cluster running version 4.12 for testing a single node small footprint deployment. I am using the helm chart and got it to start installing but I hit an issue with the CSI driver install. it says node is not support mount propagation although I set it to shared in a machine config for the CRIO service. Does anyone have any ideas here?
> 
> Hypervisor: proxmox 7.0/kvm VM: CPU passthrough intel E5 CPU: 8 cores RAM: 32G /dev/sdb is mounted to /var/lib/longhorn

I have not experienced this issue before, the team is going to need the relevant logs from the failing pods.

I stood up a brand new 3M/3W (KVM) cluster at:
OKD: https://github.com/okd-project/okd/releases/tag/4.12.0-0.okd-2023-03-05-022504
Longhorn: https://github.com/longhorn/longhorn/commit/a22e7cd960e06cb0cc6b2d13405a31c837dbc737

Didn't experience any issues.

2023-03-14 13:57 UTC, wtownse commented
Right I suspect my issue has to do with running single node.  I also suspect it would be the same issue in a compact cluster.  Single node ignition won't even format the drive in OKD.
[root@mirror-vm disconnected-mirror]# oc get pods -n longhorn-system
NAME                                           READY   STATUS             RESTARTS         AGE
engine-image-ei-b907910b-9nhjl                 1/1     Running            0                19h
longhorn-admission-webhook-55c7565b89-jcpwz    1/1     Running            0                19h
longhorn-admission-webhook-55c7565b89-wqx7k    1/1     Running            0                19h
longhorn-conversion-webhook-5df5fb4d44-7r4km   1/1     Running            0                19h
longhorn-conversion-webhook-5df5fb4d44-lsltd   1/1     Running            0                19h
longhorn-driver-deployer-7fcf47b74c-n2k76      0/1     CrashLoopBackOff   203 (3m7s ago)   19h
longhorn-manager-xrxbq                         1/1     Running            0                19h
longhorn-recovery-backend-76d9bd58d7-5b65m     1/1     Running            0                19h
longhorn-recovery-backend-76d9bd58d7-7ckp9     1/1     Running            0                19h
longhorn-ui-54df99bfc-fk78t                    1/1     Running            0                19h
longhorn-ui-54df99bfc-jxc7r                    1/1     Running            0                19h
[root@mirror-vm disconnected-mirror]# oc logs longhorn-driver-deployer-7fcf47b74c-n2k76 -n longhorn-system
Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init)
W0314 13:49:51.847849       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-03-14T13:50:41Z" level=warning msg="Got an error when checking MountPropagation with node status, node master-0.example.com is not support mount propagation"
time="2023-03-14T13:50:41Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node master-0.example.com is not support mount propagation"
[root@mirror-vm disconnected-mirror]#

However I have set the Mountflags to shared with a machine config.
[core@master-0 ~]$ sudo systemctl show crio | grep MountFlags
MountFlags=shared
[core@master-0 ~]$

Sorry if this is a messy post.

2023-03-14 18:54 UTC, ArthurVardevanyan commented
> Right I suspect my issue has to do with running single node. I also suspect it would be the same issue in a compact cluster. Single node ignition won't even format the drive in OKD.
> 
> [root@mirror-vm disconnected-mirror]# oc get pods -n longhorn-system NAME READY STATUS RESTARTS AGE engine-image-ei-b907910b-9nhjl 1/1 Running 0 19h longhorn-admission-webhook-55c7565b89-jcpwz 1/1 Running 0 19h longhorn-admission-webhook-55c7565b89-wqx7k 1/1 Running 0 19h longhorn-conversion-webhook-5df5fb4d44-7r4km 1/1 Running 0 19h longhorn-conversion-webhook-5df5fb4d44-lsltd 1/1 Running 0 19h longhorn-driver-deployer-7fcf47b74c-n2k76 0/1 CrashLoopBackOff 203 (3m7s ago) 19h longhorn-manager-xrxbq 1/1 Running 0 19h longhorn-recovery-backend-76d9bd58d7-5b65m 1/1 Running 0 19h longhorn-recovery-backend-76d9bd58d7-7ckp9 1/1 Running 0 19h longhorn-ui-54df99bfc-fk78t 1/1 Running 0 19h longhorn-ui-54df99bfc-jxc7r 1/1 Running 0 19h [root@mirror-vm disconnected-mirror]# oc logs longhorn-driver-deployer-7fcf47b74c-n2k76 -n longhorn-system Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init) W0314 13:49:51.847849 1 client_config.go:617] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work. time="2023-03-14T13:50:41Z" level=warning msg="Got an error when checking MountPropagation with node status, node master-0.example.com is not support mount propagation" time="2023-03-14T13:50:41Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node master-0.example.com is not support mount propagation" [root@mirror-vm disconnected-mirror]#
> 
> However I have set the Mountflags to shared with a machine config. [core@master-0 ~]$ sudo systemctl show crio | grep MountFlags MountFlags=shared [core@master-0 ~]$
> 
> Sorry if this is a messy post.

Could you try without the Secondary Drive?

I stood up a single Node OKD, and wasn't able to reproduce the issue.
```bash
arthur@arthur-ryzen:~$ kubectl get pods -n longhorn-system -o wide
NAME                                                  READY   STATUS    RESTARTS      AGE   IP             NODE       NOMINATED NODE   READINESS GATES
csi-attacher-66f9979b99-2gdwm                         1/1     Running   1 (10m ago)   10m   10.128.0.114   master-0   <none>           <none>
csi-attacher-66f9979b99-gxx4c                         1/1     Running   1 (10m ago)   10m   10.128.0.115   master-0   <none>           <none>
csi-attacher-66f9979b99-kwrxh                         1/1     Running   1 (10m ago)   10m   10.128.0.113   master-0   <none>           <none>
csi-provisioner-64dcbd65b4-6b2ph                      1/1     Running   1 (10m ago)   10m   10.128.0.118   master-0   <none>           <none>
csi-provisioner-64dcbd65b4-mjqd5                      1/1     Running   1 (10m ago)   10m   10.128.0.116   master-0   <none>           <none>
csi-provisioner-64dcbd65b4-wrq4m                      1/1     Running   1 (10m ago)   10m   10.128.0.117   master-0   <none>           <none>
csi-resizer-ccdb95b5c-2224q                           1/1     Running   1 (10m ago)   10m   10.128.0.120   master-0   <none>           <none>
csi-resizer-ccdb95b5c-q7j6z                           1/1     Running   1 (10m ago)   10m   10.128.0.121   master-0   <none>           <none>
csi-resizer-ccdb95b5c-ztj9t                           1/1     Running   1 (10m ago)   10m   10.128.0.119   master-0   <none>           <none>
csi-snapshotter-546b79649b-4kqcn                      1/1     Running   1 (10m ago)   10m   10.128.0.125   master-0   <none>           <none>
csi-snapshotter-546b79649b-chkj7                      1/1     Running   1 (10m ago)   10m   10.128.0.123   master-0   <none>           <none>
csi-snapshotter-546b79649b-vt52b                      1/1     Running   1 (10m ago)   10m   10.128.0.122   master-0   <none>           <none>
engine-image-ei-b907910b-dlmvn                        1/1     Running   0             11m   10.128.0.110   master-0   <none>           <none>
instance-manager-e-73d743b844144d6e182f17993d5d2140   1/1     Running   0             11m   10.128.0.111   master-0   <none>           <none>
instance-manager-r-73d743b844144d6e182f17993d5d2140   1/1     Running   0             10m   10.128.0.126   master-0   <none>           <none>
longhorn-admission-webhook-6b4f44984f-72c6t           1/1     Running   0             11m   10.128.0.107   master-0   <none>           <none>
longhorn-admission-webhook-6b4f44984f-ftzdr           1/1     Running   0             11m   10.128.0.106   master-0   <none>           <none>
longhorn-conversion-webhook-878c67f9b-7pfhh           1/1     Running   0             11m   10.128.0.104   master-0   <none>           <none>
longhorn-conversion-webhook-878c67f9b-95t78           1/1     Running   0             11m   10.128.0.108   master-0   <none>           <none>
longhorn-csi-plugin-h4mbn                             3/3     Running   1 (10m ago)   10m   10.128.0.124   master-0   <none>           <none>
longhorn-driver-deployer-867fbc9fd7-tzf97             1/1     Running   0             11m   10.128.0.100   master-0   <none>           <none>
longhorn-manager-cw5jx                                1/1     Running   1 (11m ago)   11m   10.128.0.99    master-0   <none>           <none>
longhorn-recovery-backend-86f65c69dc-82rrh            1/1     Running   0             11m   10.128.0.103   master-0   <none>           <none>
longhorn-recovery-backend-86f65c69dc-98znk            1/1     Running   0             11m   10.128.0.101   master-0   <none>           <none>
longhorn-ui-79885997d9-hk6hr                          2/2     Running   0             11m   10.128.0.105   master-0   <none>           <none>
longhorn-ui-79885997d9-sz4k9                          2/2     Running   0             11m   10.128.0.102   master-0   <none>           <none>
                                                                                                                                                                                                                   
arthur@arthur-ryzen:~$ kubectl get nodes -o wide                  
NAME       STATUS   ROLES                         AGE   VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                        KERNEL-VERSION          CONTAINER-RUNTIME
master-0   Ready    control-plane,master,worker   42m   v1.25.4+18eadca   10.10.10.10   <none>        Fedora CoreOS 37.20230205.3.0   6.1.9-200.fc37.x86_64   cri-o://1.25.1                                                                                                                                                                                                                
```
<img src="https://user-images.githubusercontent.com/21159051/225106282-3e72d06a-6a29-4a2f-835b-1dc070275e7c.png " width="600"  />
<img src="https://user-images.githubusercontent.com/21159051/225106279-cf8e67a5-1aa2-405c-af54-58704d1ed2c6.png" width="200"  />

2023-03-14 19:09 UTC, wtownse commented
I had initially installed with only one drive then added the second one after the fact during troubleshooting.  When I attempted to create a single node okd it failed since the drive would not get formatted using single node ignition.  I use the script below to generate the iso.  I will try again with the same version of fedora coreos you have listed in your post.


rm -rf ./okd
rm -rf install-config.yaml
wget -qO- https://github.com/okd-project/okd/releases/download/4.12.0-0.okd-2023                                                                                                              -03-05-022504/openshift-install-linux-4.12.0-0.okd-2023-03-05-022504.tar.gz | ta                                                                                                              r xvz
wget -qO- https://github.com/okd-project/okd/releases/download/4.12.0-0.okd-2023                                                                                                              -03-05-022504/openshift-client-linux-4.12.0-0.okd-2023-03-05-022504.tar.gz | tar                                                                                                               xvz
ISO_URL=$(./openshift-install coreos print-stream-json | grep location | grep x8                                                                                                              6_64 | grep iso | cut -d\" -f4)
#ISO_URL="https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.                                                                                                              20230110.3.1/x86_64/fedora-coreos-37.20230110.3.1-live.x86_64.iso"
echo $ISO_URL
curl -L $ISO_URL > rhcos-live-okd.iso

cat > install-config.yaml << EOF
apiVersion: v1
baseDomain: example.com
controlPlane:
  name: master
  hyperthreading: Disabled
  replicas: 1
compute:
- name: worker
  hyperthreading: Disabled
  replicas: 0
metadata:
  name: test-cluster
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.16.130.0/24
  networkType: OVNKubernetes
bootstrapInPlace:
  installationDisk: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0
platform:
  none: {}
fips: false
EOF

REG_SECRET='{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'

echo -n "pullSecret: '" >> install-config.yaml && echo $REG_SECRET | jq -c . | s                                                                                                              ed "s/$/\'/g" >> install-config.yaml

echo -n "sshKey: '" >> install-config.yaml && cat ~/.ssh/id_rsa.pub | sed "s/$/\                                                                                                              '/g" >> install-config.yaml

rm -rf ./okd

mkdir okd
yes | cp -rf install-config.yaml okd/
./openshift-install --dir=okd create single-node-ignition-config

 alias coreos-installer='podman run --privileged --pull always --rm \
        -v /dev:/dev -v /run/udev:/run/udev -v $PWD:/data \
        -w /data quay.io/coreos/coreos-installer:release'

yes | cp -rf okd/bootstrap-in-place-for-live-iso.ign iso.ign
coreos-installer iso ignition embed -fi iso.ign rhcos-live-okd.iso
#coreos-installer iso kargs modify -a coreos.inst.install_dev=/dev/sda rhcos-liv                                                                                                          e-okd.iso

2023-03-14 20:25 UTC, wtownse commented
I have faced the same issue as mentioned here.  https://github.com/okd-project/okd/discussions/1235  I can only assume you are using a seperate bootstrap node instead of bootstrap in place?  Just verifying as my next step is to try that scenario.  Also to my mind the fact that single node works in OCP while failing in OKD tells me something is different enough to possibly affect longhorn as well.

2023-03-14 20:31 UTC, ArthurVardevanyan commented
> I have faced the same issue as mentioned here. [okd-project/okd#1235](https://github.com/okd-project/okd/discussions/1235) I can only assume you are using a seperate bootstrap node instead of bootstrap in place? Just verifying as my next step is to try that scenario. Also to my mind the fact that single node works in OCP while failing in OKD tells me something is different enough to possibly affect longhorn as well.

Correct, I am doing a more traditional install, bootstrap + nodes, and in the case of the last test, bootstrap + single master, no worker.

I have not played around with "true single node" install yet.

2023-03-14 23:02 UTC, wtownse commented
Thanks!  Single node with bootstrap in place works perfect with OCP.  I will install a single node OKD and let you know of my findings.  May I ask what you are using for hardware/virtualization?

2023-03-14 23:04 UTC, ArthurVardevanyan commented
> Thanks!  Single node with bootstrap in place works perfect with OCP.  I will install a single node OKD and let you know of my findings.  May I ask what you are using for hardware/virtualization?

Ryzen 3000/5000s, Debian as Host OS, and kvm/quemu as the hypervisor.

2023-03-15 14:10 UTC, wtownse commented
Are the defaults enough to get a working longhorn install?  I see the same issue in single node okd.  I cloned your repo with the following command.
git clone https://github.com/ArthurVardevanyan/longhorn.git

Then installed with.
helm install longhorn ./longhorn/chart/ --namespace longhorn-system --no-hooks

I have uninstalled and installed several times.  I applied a machine config to set the crio MountFlags to shared after the first install.

[root@localhost opt]# oc get pods -n longhorn-system
NAME                                           READY   STATUS             RESTARTS          AGE
engine-image-ei-b907910b-nd887                 1/1     Running            1                 12h
longhorn-admission-webhook-55c7565b89-68tnn    1/1     Running            1                 12h
longhorn-admission-webhook-55c7565b89-jtsc9    1/1     Running            1                 12h
longhorn-conversion-webhook-5df5fb4d44-pfs7n   1/1     Running            1                 12h
longhorn-conversion-webhook-5df5fb4d44-wp2hx   1/1     Running            1                 12h
longhorn-driver-deployer-7fcf47b74c-tmd4p      0/1     CrashLoopBackOff   129 (3m55s ago)   12h
longhorn-manager-bbgnm                         1/1     Running            1                 12h
longhorn-recovery-backend-76d9bd58d7-xwnvh     1/1     Running            1                 12h
longhorn-recovery-backend-76d9bd58d7-zxz4v     1/1     Running            1                 12h
longhorn-ui-54df99bfc-42h9v                    1/1     Running            1                 12h
longhorn-ui-54df99bfc-bqnml                    1/1     Running            1                 12h
[root@localhost opt]# oc logs longhorn-driver-deployer-7fcf47b74c-tmd4p -n longhorn-system
Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init)
W0315 13:50:14.769460       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-03-15T13:51:04Z" level=warning msg="Got an error when checking MountPropagation with node status, node master-01.test-cluster.example.com is not support mount propagation"
time="2023-03-15T13:51:04Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node master-01.test-cluster.example.com is not support mount propagation"

2023-03-20 03:59 UTC, ArthurVardevanyan commented
@wtownse This problem may be specific to OKD /w SNO Installer, might want to open an issue up on OKD.

2023-06-13 11:24 UTC, innobead commented
@weizhe0422 Please help review this and verify it after 1.5.0.

2023-07-24 07:13 UTC, mantissahz approved these changes
In general LGTM

2023-07-26 03:15 UTC, shuo-wu commented on chart/ocp-readme.md
> +## Preparing nodes
Is this required if a user does not need to customize default disks and nodes? I think it's better to indicate the must-have changes then mention this part in an add-on list.

2023-07-26 03:15 UTC, shuo-wu commented on chart/templates/clusterrole.yaml
> +              "engineimages/finalizers", "nodes/finalizers", "instancemanagers/finalizers",
Not sure why we only need to add these 3 finalizers rather than listing the finalizers for all Longhorn resources.

2023-07-26 03:15 UTC, shuo-wu commented on chart/values.yaml
> +  # privileged: true
Should we set these to true by default once `openshift` is enabled?

2023-08-07 01:13 UTC, mantissahz commented
@ArthurVardevanyan could you please try to resolve the conversions?

I had verified the PR on OKD 4.14 environment.
By the steps:
1. Label nodes
2. Create a file system and the mount point for disks on nodes
3. Create a deploying manifest file from Helm by commands
```bash
helm template longhorn --namespace longhorn-system --values values.yaml --no-hooks  > longhorn.yaml
oc create namespace longhorn-system -o yaml --dry-run=client | oc apply -f -
oc apply -f longhorn.yaml -n longhorn-system
```

2023-08-12 17:18 UTC, ArthurVardevanyan commented on chart/templates/clusterrole.yaml
> +              "engineimages/finalizers", "nodes/finalizers", "instancemanagers/finalizers",
I don't recall the exist reason, but here is additional context: https://github.com/longhorn/longhorn/issues/1831

2023-08-12 18:25 UTC, ArthurVardevanyan commented on chart/values.yaml
> +  # privileged: true
Done

2023-08-12 18:25 UTC, ArthurVardevanyan commented on chart/ocp-readme.md
> +## Preparing nodes
Updated

2023-08-21 18:10 UTC, innobead requested changes
In general, LGTM. 

Please fix the remaining comments. Thanks.

2023-08-21 18:10 UTC, innobead commented on chart/values.yaml
> +      tag: latest  # Pin to OCP/OKD 4.X Version
Suggest using a specific version instead of latest.

2023-08-21 18:11 UTC, innobead commented
@mantissahz Please help re-verify this PR after @ArthurVardevanyan resolves the comments. Thanks.

2023-08-21 18:21 UTC, ArthurVardevanyan commented on chart/values.yaml
> +      tag: latest  # Pin to OCP/OKD 4.X Version
Pinned to Latest Stable Release

2023-08-21 18:22 UTC, ArthurVardevanyan commented on deploy/longhorn.yaml
> +    app.kubernetes.io/version: v1.4.0-dev
Updated

2023-08-21 18:22 UTC, ArthurVardevanyan commented on chart/values.yaml
> +          operator: "Equal"
Fixed

2023-08-21 18:26 UTC, innobead approved these changes
LGTM

2023-08-24 11:12 UTC, merged

2023-08-24 11:14 UTC, innobead commented
@ArthurVardevanyan I would like to have you help with the following contribution for OCP/OKD support to make sure it's sustained. Thanks first. 

@mantissahz Please move forward with the QA process. Thanks.