feat(lep): consolidate instance managers
longhorn/longhorn pull request #5457
Opened 2023-03-01 08:42 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/5208

2023-03-15 14:55 UTC, derekbit commented on enhancements/20230303-consolidate-instance-managers.md
> +- For the attached volumes during/after the Longhorn upgrade, the old engine and replica instance managers should continue servicing data plane operations until the first volume detachment.
Should it be `last volume detachment`?

2023-03-15 14:55 UTC, derekbit commented on enhancements/20230303-consolidate-instance-managers.md
> +- Online/offline upgrade volume engine should be functional. The replicas will automatically migrate to use the new `aio` type instance managers, and the `engine` type instance manager will continue
Just curious. What does `aio` mean? Is it an abbreviation for ...?

2023-03-15 14:55 UTC, derekbit commented on enhancements/20230303-consolidate-instance-managers.md
> +Longhorn architecture includes engine and replica instance manager pods on each node. After the upgrade, Longhorn adds an additional engine and replica instance manager pods. When the cluster is set
After the consolidation, how many cpu will be requested for the new instance manager?

2023-03-16 00:43 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +- For the attached volumes during/after the Longhorn upgrade, the old engine and replica instance managers should continue servicing data plane operations until the first volume detachment.
I've reworded this a bit to clarify the statement. PTAL.

2023-03-16 00:44 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +- Online/offline upgrade volume engine should be functional. The replicas will automatically migrate to use the new `aio` type instance managers, and the `engine` type instance manager will continue
This is an abbreviation for all-in-one.

2023-03-16 01:21 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +Longhorn architecture includes engine and replica instance manager pods on each node. After the upgrade, Longhorn adds an additional engine and replica instance manager pods. When the cluster is set
The total CPU consumption for `im-e+im-r` is similar to `im-aio`, and the engine process is the main consumer of CPU resources. After consolidation, the CPU request percentage of instance managers will be reduced by half, since there will be a single instance manager pod for both process types.

2023-03-16 01:23 UTC, derekbit commented on enhancements/20230303-consolidate-instance-managers.md
> +- Online/offline upgrade volume engine should be functional. The replicas will automatically migrate to use the new `aio` type instance managers, and the `engine` type instance manager will continue
Thank you.

2023-03-16 01:25 UTC, derekbit commented on enhancements/20230303-consolidate-instance-managers.md
> +Longhorn architecture includes engine and replica instance manager pods on each node. After the upgrade, Longhorn adds an additional engine and replica instance manager pods. When the cluster is set
Sounds great. Can we add a brief paragraph for the improvement?

2023-03-16 01:33 UTC, innobead requested changes

2023-03-16 01:33 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +Longhorn architecture includes engine and replica instance manager pods on each node. After the upgrade, Longhorn adds an additional engine and replica instance manager pods. When the cluster is set
Where is the info about the most resource consumption from engine processes? If having, we should add that to this LEP. 

I am also thinking if we can do more granular testing to understand if the resource consumption is linear growth, so it will be helpful for us to do the right estimation.

2023-03-16 01:43 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +     instances:
Not sure if I understand the question, can you elaborate a bit more?
Currently, the instances are already separated by `-e-` and `-r-` as shown in the CR.

2023-03-16 01:44 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +     instances:
```yaml
       demo-0-e-fe37f92c:
         spec:
           name: demo-0-e-fe37f92c
         status:
           endpoint: ""
           errorMsg: ""
           listen: ""
           portEnd: 10015
           portStart: 10015
           resourceVersion: 0
           state: running
           type: ""
       demo-0-r-1605cbd6:
         spec:
           name: demo-0-r-1605cbd6
         status:
           endpoint: ""
           errorMsg: ""
           listen: ""
           portEnd: 10014
           portStart: 10000
           resourceVersion: 0
           state: running
           type: ""
```

2023-03-16 02:31 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +Longhorn architecture includes engine and replica instance manager pods on each node. After the upgrade, Longhorn adds an additional engine and replica instance manager pods. When the cluster is set
Updated improvement outline and some observed results (with and without IO).

As for the estimation, I think we can do more samplings after the implementation.

2023-03-16 14:05 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +     instances:
Separated the `instance` field into `instanceEngines` and `instanceReplicas` fields.

2023-04-19 06:53 UTC, innobead commented
@shuo-wu @derekbit let's review this. thanks.

2023-04-19 23:39 UTC, derekbit commented
The LEP is straightforward. In general, LGTM.

2023-04-26 05:43 UTC, shuo-wu commented on enhancements/20230303-consolidate-instance-managers.md
> +- Map the status of the engine/replica process to the corresponding instanceEngines/instanceReplicas fields in the InstanceManager instead of the instances field.
Will Longhorn do this for the old engine instance managers?

2023-04-26 05:43 UTC, shuo-wu commented on enhancements/20230303-consolidate-instance-managers.md
> +Based on the assumption when upgrading from v1.5.x to 1.6.x, volumes should have detached at least once and migrated to `aio` type instance managers. Then the cluster should not have volume depending
There is no limitation for the engine version of running volumes during the upgrade. Do we need to add this kind of check before upgrade?

2023-04-26 06:22 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +Based on the assumption when upgrading from v1.5.x to 1.6.x, volumes should have detached at least once and migrated to `aio` type instance managers. Then the cluster should not have volume depending
@mantissahz , should we cover this in https://github.com/longhorn/longhorn/issues/5131?

2023-04-26 06:24 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +- Map the status of the engine/replica process to the corresponding instanceEngines/instanceReplicas fields in the InstanceManager instead of the instances field.
The upgrade strategy section covers field transfer, which means this is applicable to older instance managers as well.

2023-04-26 08:13 UTC, innobead requested changes
In general LGTM. Few questions need to answer.

2023-04-26 08:13 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +- Separate the `instance` field into `instanceEngines` and `instanceReplicas` fields.
This is good. Don't change the existing property to keep backward compatibility.

2023-04-26 08:13 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +- Map the status of the engine/replica process to the corresponding instanceEngines/instanceReplicas fields in the InstanceManager instead of the instances field.
These new properties are only for new replicas, volume live upgrade or volume reattachment.

For existing volumes, all info will be still saved in the old instances properly, right?

2023-04-26 08:13 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +Based on the assumption when upgrading from v1.5.x to 1.6.x, volumes should have detached at least once and migrated to `aio` type instance managers. Then the cluster should not have volume depending
Upgrade enforcement is for longhorn version instead of engine image version for now.

We should add a way to tackle this when working on 1.6. However, it will be good to describe here.

2023-04-26 08:13 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +- Remove the `engine`, `replica`, and `aio` instance manager types. There is no need for differentiation.
Oh you will do it in phase 2.

2023-04-26 08:47 UTC, shuo-wu commented on enhancements/20230303-consolidate-instance-managers.md
> +Based on the assumption when upgrading from v1.5.x to 1.6.x, volumes should have detached at least once and migrated to `aio` type instance managers. Then the cluster should not have volume depending
You mean we plan to add checks for the engine version of running volumes or the old instance manager existence in v1.6, right?

2023-04-26 08:57 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +- Online/offline upgrade volume engine should be functional. The replicas will automatically migrate to use the new `aio` (all-in-one) type instance managers, and the `engine` type instance manager w
> Don't need to create another type aio, but rather the type is unnecessary except for backward compatibility for the current type (engine/replica). 

We are creating a new type here so resources can [match using the instance manager labels](https://github.com/longhorn/longhorn-manager/blob/v1.4.1/controller/instance_manager_controller.go#L829). The [type is included as part of the labels](https://github.com/longhorn/longhorn-manager/blob/v1.4.1/types/types.go#L400).

> Type property should be deprecated and removed eventually.

Yes, in phase 2.

2023-04-26 09:04 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +- Map the status of the engine/replica process to the corresponding instanceEngines/instanceReplicas fields in the InstanceManager instead of the instances field.
During the upgrade process, the instance field for all existing instance managers will be moved to either `instanceEngines` or `instanceReplicas`. I've taken this approach so there is no need to handle the instance field separately.

2023-04-27 01:07 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +- Map the status of the engine/replica process to the corresponding instanceEngines/instanceReplicas fields in the InstanceManager instead of the instances field.
Do you mean Longhorn upgrade no matter if volumes are still attached? I thought those fields are only after reattachment or new volume.

2023-05-03 01:17 UTC, c3y1huang commented on enhancements/20230303-consolidate-instance-managers.md
> +Based on the assumption when upgrading from v1.5.x to 1.6.x, volumes should have detached at least once and migrated to `aio` type instance managers. Then the cluster should not have volume depending
https://github.com/longhorn/longhorn/issues/5842

2023-05-03 01:31 UTC, innobead commented on enhancements/20230303-consolidate-instance-managers.md
> +Phase 2:
Need to create an issue for this. 

ref: https://github.com/longhorn/longhorn/issues/5844

2023-05-03 01:57 UTC, innobead approved these changes
LGTM

2023-05-03 01:57 UTC, merged