feat: introduce helm hook `pre-upgrade`
longhorn/longhorn pull request #5567
Opened 2023-03-15 14:19 UTC by mantissahz

Add helm hook `pre-upgrade` file `preupgrade-job.yaml` to protect the system from unsupported upgrade path.

longhorn/longhorn#5131

2023-04-06 12:40 UTC, innobead commented
@mantissahz is this ready for review?

2023-04-06 12:43 UTC, mantissahz commented
@innobead LEP https://github.com/longhorn/longhorn/pull/5583 is not approved yet

2023-04-06 13:19 UTC, innobead commented
@mantissahz https://github.com/longhorn/longhorn/pull/5583#pullrequestreview-1374813656

2023-04-14 07:29 UTC, innobead commented
ready?

2023-04-14 07:37 UTC, mantissahz commented
This PR should wait for https://github.com/longhorn/longhorn-manager/pull/1763 because the new command `pre-upgrade` of `longhorn-manager` will be introduced.

2023-05-04 10:31 UTC, innobead requested changes

2023-05-04 10:31 UTC, innobead commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
Why need privileged?

2023-05-05 01:12 UTC, mantissahz commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
It's learned from `post-upgrade` and `uninstall` but it seems we don't need privileged if we change nothing.

2023-05-05 01:26 UTC, innobead commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
yeah, make sure the reason for that is.

@shuo-wu @PhanLe1010 @derekbit do you know why we need `privileged` for `post-upgrade` and `uninstall` job?

2023-05-05 01:35 UTC, PhanLe1010 commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
Good question. It was enabled by this commit https://github.com/longhorn/longhorn/commit/eb767033390cc31c2a01ec3f93dfd2eb3ff05b1a

But I just walk through the post-upgrade and uninstall job. They are just doing operation against kubeAPI. Not sure why we need them to be privileged

2023-05-05 05:05 UTC, innobead commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
Let's work on https://github.com/longhorn/longhorn/issues/5862 @mantissahz

2023-05-07 15:02 UTC, mantissahz commented on chart/templates/preupgrade-job.yaml
> +          privileged: true
Removed this setting first. Thanks

2023-05-07 17:24 UTC, innobead approved these changes
LGTM. 

Will merge this until the manager PR is merged.

2023-05-08 04:47 UTC, merged

2023-05-24 10:01 UTC, shuo-wu commented on chart/templates/preupgrade-job.yaml
> +      - name: longhorn-post-upgrade
NIT: Why is the name `longhorn-post-upgrade`?

2023-05-24 12:14 UTC, mantissahz commented
@innobead 
fixed, https://github.com/longhorn/longhorn/pull/5996