refactor (webhook and recovery service): merge webhook and recovery service into longhorn manager daemonset
longhorn/longhorn pull request #5649
Opened 2023-03-23 09:20 UTC by ChanYiLin

Ref: [longhorn/longhorn#5590](https://github.com/longhorn/longhorn/issues/5590)

Webhook and Recovery services are deployed as deployment. There's a chance that these deployments' replicas are on the same worker node.
We would like to merge webhook and recovery services into longhorn manager daemonset to leverage the benefit of daemonset and increase the stability and maintainability.

Update Note:
- remove webhook deployment
- remove recovery backend service deployment
- change admission webhook port to 8443
- change webhook and recovery backend service label selector to `longhorn-manager`

2023-03-23 09:55 UTC, ChanYiLin commented
Just found out admission and conversion webhook listen to the same port, need to modify

2023-04-06 12:39 UTC, innobead approved these changes
LGTM. This should be meregd until the manager PR is merged.

Need to update the [important doc](https://github.com/longhorn/website/blob/master/content/docs/1.5.0/deploy/important-notes/index.md) to describe the old deployments should be deleted by users after upgrading.

2023-04-06 13:37 UTC, ChanYiLin commented
@innobead 
the upgrade path with help delete the deprecated deployment ([ref](https://github.com/longhorn/longhorn-manager/pull/1805/files#diff-54e77ae1d9149f7ea519019af64a71e75f8029573fbb71ee209c944508a11502))
should we still ask users to check and delete them manually?

Based on Shuo's comment, I update some port numbers to make it easy to manage.

2023-04-06 13:38 UTC, innobead commented
> @innobead the upgrade path with help delete the deprecated deployment ([ref](https://github.com/longhorn/longhorn-manager/pull/1805/files#diff-54e77ae1d9149f7ea519019af64a71e75f8029573fbb71ee209c944508a11502)) should we still ask users to check and delete them manually?

This is the best option, if we can do it automatically, then no need to request users to do any manual operations. 

> Based on Shuo's comment, I update some port numbers to make it easy to manage.

Sounds good :+1:

2023-04-08 04:39 UTC, ChanYiLin commented
fixed readiness probe using `http`  led to TLS handshake error
by setting
```
readinessProbe:
  httpGet:
    path: /v1/healthz
    port: 9501
    scheme: HTTPS
```

2023-04-27 07:46 UTC, innobead requested changes
In genreal, LGTM. 2 comments need to resolve.

2023-04-27 08:02 UTC, ChanYiLin commented on chart/templates/daemonset-sa.yaml
> +            port: 9501
conversion webhook is the first server starting, the pod should be ready for receiving the request from svc right after it
because admission webhook is the next one and it will use **conversion svc endpoint** 
this `readinessProbe` detect 9501(conversion webhook) when it is ready, the pod is ready.

2023-04-27 08:03 UTC, ChanYiLin commented
Fixed, thanks!

2023-04-27 08:14 UTC, innobead approved these changes

2023-04-27 08:17 UTC, merged