feat(lep): extend csi snapshot to support backingimage
longhorn/longhorn pull request #5771
Opened 2023-04-17 09:16 UTC by ChanYiLin

ref: longhorn/longhorn#5005

Extend csi snapshot to support BackingImage

Summary:
- Users can use VolumeSnapshot with type `bi` to create/delete BackingImage
- Users can restore a Volume with a VolumeSnapshot (create a Volume with BackingImage)
- Users can restore a Volume with an existing BackingImage (pre-provision)
    - Create the VolumeSnapshot/VolumeSnapshotContent to associate to the existing BackingImage
- Users can restore a Volume with non-existing BackingImage (on-demand provision)
    - Create the VolumeSnapshot/VolumeSnapshotContent to provide BackingImage parameters
    - Create BackingImage based on the parameters when the users create PVC from the VolumeSnapshot

2023-04-26 13:59 UTC, innobead requested changes
In general, LGTM. Some comments needed to answer.

Also, when testing, need to consider some resilience cases for example: if a volume is created from a bi snapshot on demand, but the BI somehow is failed to created, what's the status of the volume.

2023-04-26 13:59 UTC, innobead commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +- If BackingImage with the given name already exists, create the volume.
So in this case, actually users can just provide the backing image name only? `bi://backingImage={value}`

2023-04-26 13:59 UTC, innobead commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +    3. Verify it failed since the Volume `test-vol` is not attached
This should be tackled after https://github.com/longhorn/longhorn/issues/3715 is finished for volume auto attachment.

2023-04-27 06:50 UTC, ChanYiLin commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +            snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecks
<img width="973" alt="截圖 2023-04-27 下午2 49 23" src="https://user-images.githubusercontent.com/7100904/234782117-d715aee7-10d4-44e8-a0e1-29a7a50b4cd3.png">

this is actually one line
as you can see in the preview, there is no indent issue

2023-04-27 06:53 UTC, ChanYiLin commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +    - `backingImage`: Name of the BackingImage
as discussed, we can support this but will not include this in this version.
This needs to introduce a **new type** for backing image and handle this case separately in the code.

2023-04-27 06:55 UTC, ChanYiLin commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +- If BackingImage with the given name already exists, create the volume.
As discussed, this can be supported by using `bi://backing?backingImageDataSourceType=backing&backingImage=${BACKINGIMAGE_NAME}`
so we can handle this type and skip all the existing validation.

But we are not going to include this type in this version

2023-04-27 06:57 UTC, ChanYiLin commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +    3. Verify it failed since the Volume `test-vol` is not attached
Yes.

2023-04-27 07:05 UTC, ChanYiLin commented
> In general, LGTM. Some comments needed to answer.
> 
> Also, when testing, need to consider some resilience cases for example: if a volume is created from a bi snapshot on demand, but the BI somehow is failed to created, what's the status of the volume.

Two functions involved in this feature, they are triggered by csi sidecar
- `createSnapshot`: **When creating VolumeSnapshot -> csi create VolumeSnapshotContent**
    - This function will be triggered and create the BackingImage.
    - BackingImage creation is an async call, create and return directly. Return error when create BackingImage call fails.
- `createVolume`: **When creating PVC -> csi create PV**
    - Prepare and check the BackingImage first, it it doesn't exist, create the BackingImage
    - Create the volume, it waits until the volume is completed or **timeout**.
    - So if the BackingImage is not ready for a period of time. createVolume() returns error timeout to the csi sidecar and PV create will fail.

2023-04-27 07:52 UTC, innobead commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +            snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecks
I mean

```yaml
source:
    snapshotHandle: 
```

2023-04-27 07:55 UTC, innobead commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +    3. Verify it failed since the Volume `test-vol` is not attached
cc @PhanLe1010

2023-04-27 08:15 UTC, ChanYiLin commented on enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md
> +            snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecks
fixed, thanks!

2023-04-27 08:18 UTC, innobead approved these changes

2023-04-27 08:18 UTC, merged