feat(lep): upgrade checker info collection
longhorn/longhorn pull request #5790
Opened 2023-04-20 06:30 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/5235

2023-05-03 02:19 UTC, innobead requested changes
In general, LGTM.

Some comments need to resolve.

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +#### `Allow Upgrade Checker To Collect Information` Setting
Change the name to `Allow Collecting Longhorn Usage Metrics`

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +  Description: "Enabling this setting will allow Longhorn to send additional information to the upgrade checker. This information will help us better understand how Longhorn is being used, which will
Users have no idea about upgrade checker, so we can simplify this.

>Enabling this setting will allow Longhorn to provide additional usage metrics to https://metrics.longhorn.io/. This information will help us better understand how Longhorn is being used, which will ultimately contribute to future improvements.

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +  > Note: this value may not be accurate if the cluster node is a virtual machine.
Can we have another default value for this case if it's unknown.

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Os distro (`os_distro`)
Can we understand if the node is from public cloud?

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +The following information is sent from the first cluster node in the sort list:
What do you mean `first cluster node`? So other nodes will not report these info?

2023-05-03 02:19 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +  - Settings that requires processing to identify their general purpose:
For backup, just collect type/protocol.

2023-05-08 09:41 UTC, c3y1huang commented on enhancements/20230420-upgrade-checker-info-collection.md
> +The following information is sent from the first cluster node in the sort list:
Reworded.

2023-05-08 09:43 UTC, c3y1huang commented on enhancements/20230420-upgrade-checker-info-collection.md
> +  - Settings that requires processing to identify their general purpose:
Not exactly sure what to update there. I assume you meant the following nesting bullet point.
> SettingNameBackupTarget (the backup target type/protocol, ex: cifs, nfs, s3)

2023-05-08 09:56 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Os distro (`os_distro`)
probably can see if there is cloud-init somehow, no need to be very specific

2023-05-08 10:00 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +  - Settings that requires processing to identify their general purpose:
Yes.

2023-05-08 10:07 UTC, c3y1huang commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Os distro (`os_distro`)
I couldn't find a generic method to determine whether a node is from the public cloud.

One approach could be to check the metadata endpoint of the cloud provider, for example when executing `curl -s http://169.254.169.254/latest/meta-data/` returns a response if that node is on AWS. However, I don't think this is a good approach

The closes we could get to is the Kubernetes node provider ID. Although this cannot identify whether a node is from a public cloud, it can at least indicate if the cluster is from a cloud-managed Kubernetes cluster.

2023-05-08 10:22 UTC, innobead approved these changes
LGTM, but some minor optional feedback.

2023-05-08 10:22 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Number of volumes of different data locality (`longhorn_volume_<disable/best_effort/strict_local/unknown>_frontend_count`).
`longhorn_volume_data_locality_<disable/best_effort/strict_local/unknown>_count`

2023-05-08 10:22 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Number of volumes of different frontend (`longhorn_volume_<blockdev/iscsi>_frontend_count`).
`longhorn_volume_frontend_<blockdev/iscsi>_count`

2023-05-08 10:22 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +time                app_version average_longhorn_engine_image_cpu_usage_core average_longhorn_engine_image_memory_usage_mib average_longhorn_instance_manager_cpu_usage_core average_longhorn_instance_
`average_longhorn_engine_image_memory_usage_mib` to `longhorn_engine_average_image_memory_usage_mib` 

Use `longhorn` prefix is needed or even no need to have a prefix since these infos are reported to upgrade responder.

2023-05-09 02:13 UTC, c3y1huang commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Number of volumes of different frontend (`longhorn_volume_<blockdev/iscsi>_frontend_count`).
Changed all naming conventions to `Longhorn-<kind>-<field>-<value>-count`.

2023-05-09 06:29 UTC, innobead commented on enhancements/20230420-upgrade-checker-info-collection.md
> +- Os distro (`os_distro`)
> The closes we could get to is the Kubernetes node provider ID. Although this cannot identify whether a node is from a public cloud, it can at least indicate if the cluster is from a cloud-managed Kubernetes cluster.

:point_up: this simple way should be better for us.

2023-05-09 06:30 UTC, merged