LEP: Object Support for Longhorn
longhorn/longhorn pull request #5832
Opened 2023-04-30 22:57 UTC by jecluis

We are proposing Object support for Longhorn, by integrating aquarist-labs/s3gw into Longhorn, and seamlessly provide S3-compatible object endpoints from Longhorn volumes.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2023-05-02 08:44 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +        PublicDomain: <string>,
Can this be empty if we do not want to expose the endpoint externally? Perhaps directly something that more closely aligns with an `ingress` CRD (which would then likely include the SSL/TLS setup as well)?

2023-05-02 08:44 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +        Credentials: longhorn.ObjectEndpointCredentials {
Definitely. At this point I just know of no better way to both convey that we need them, nor on how to keep them. Suggestions welcome! :)

2023-05-02 08:49 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +`s3gw` execution, and calling on `VolumeManager.Create()` for volume creation.
As part of these parameters, I think we may want to introduce a flag to the backend that prevents this volume from being managed independently via the LH UI (by default at least) - plus, this would enable the UI to also be able to understand that it might want to show endpoint-specific metrics.

`claimedBy` to reference the endpoint?

2023-05-02 08:54 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +        PublicDomain: <string>,
That's a good question. We'll have to figure that out, as I don't have a good answer for this now. @m-ildefons
 and @giubacc , do you have opinions on this? :)

2023-05-02 08:56 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +`s3gw` execution, and calling on `VolumeManager.Create()` for volume creation.
I didn't want to specify new fields in `longhorn.Volume` because I don't know the impacts of such a thing, but that's something I'd be interested in knowing whether it is feasible. @PhanLe1010 can you please chime in here?

Also, maybe labels will do the trick, instead of adding a new field?

2023-05-04 10:15 UTC, giubacc commented on enhancements/20230430-object-endpoint.md
> +        PublicDomain: <string>,
More on this topic: my previous comment is probably more adherent with an Helm installation and could not apply with the LEP CRD implementation.
Is there btw, the possibility that the LEP CRD provisioning an s3gw installation for a LH volume actually instantiates an Helm template via the helm API invoked by the Go code of the controller.
In this case I don't see contraindications for our existing chart templates to be used by the controller too (in the hypothesis the controller goes in the Helm API usage direction); otherwise I would say this is even desirable.

Another question that comes now to my mind is: are we going in the direction to make a provisioned S3 endpoint for a LH volume as _editable_?
Or are we saying that it would be _immutable_?
In the latter case, this would mean that an user should first delete and then recreate the endpoint in the case she would change something.

2023-05-08 09:05 UTC, innobead commented
@shuo-wu @PhanLe1010 review this after 1.5.0.

2023-05-08 09:13 UTC, l-mb commented
> @shuo-wu @PhanLe1010 review this after 1.5.0.

Hi @innobead, would it be possible to give the team a casual review of the approach already? If so, we could get started on a tentative/draft PR of the actual controller already, which might drive further discussion without waiting a few weeks. We just don't want to head down the entirely wrong way :)

2023-05-08 09:17 UTC, innobead commented
@l-mb , NP. I think members will try to review it when available. I have reviewed it in general, and it should be fine in general but some detailed needs to craft over time. Having a controller is correct as described in the PRD.

2023-05-08 11:37 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +        PublicDomain: <string>,
@giubacc I think we'd want it to be editable (as far as that's possible). Recreating an endpoint via delete/create would be very expensive with data migration etc.

If there are parameters/attributes that are indeed immutable after creation, those should be clearly flagged.

2023-05-30 09:43 UTC, votdev commented on enhancements/20230430-object-endpoint.md
> +`s3gw` execution, and calling on `VolumeManager.Create()` for volume creation.
@PhanLe1010 ^^^^^^^^^

2023-07-14 08:04 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +longhorn.ObjectEndpoint{
Looking at other CRDs (e.g. longhorn-manager/k8s/pkg/apis/longhorn/v1beta2/sharemanager.go) in the longhorn manager repo, it might be necessary to also save a [status](https://book-v1.book.kubebuilder.io/basics/status_subresource.html) in this CRD as well.

E.g.:
```golang
longhorn.ObjectEndpoint {
  ObjectMeta metav1.ObjectMeta {
    Name <string>
  },
  Spec: longhorn.ObjectEndpointSpec {
    ... (as below)
  },
  Status longhorn.ObjectEndpointStatus {
    State ObjectEndpointState,
    Endpoint <string>,
  }
}
```

2023-07-18 15:44 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +        Image: <s3gw-image-name>,
I have my doubts that it'll be necessary to specify this, when the s3gw image to use is already specified as command line option to the longhorn-manager.
Of course having this on a per-volume basis would allow a user to upgrade the s3gw without a longhorn release or run different version of the s3gw, but I'm not sure that use case is all that valuable.

2023-07-18 15:51 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +        Volume: <string>,
Rather than specify a (Longhorn) volume here, I think it might be better to just specify a storage class and a size, since we don't want to re-use existing volumes here anyways.
Assuming that no suitable volume exists, a new one will be generated, or if one does already exist it will be bound. Either way, this binding will be recorded in the status property. This is much more akin to the way PVCs and PVs work together.

2023-07-18 16:02 UTC, giubacc commented on enhancements/20230430-object-endpoint.md
> +        Volume: <string>,
Maybe I'm misunderstanding, but in our current vision, a LH volume has to exist before the user decides to attach to it an s3 endpoint (?) .
From the LH gui, I'd expect you can see a LH volume and clicking on that you can add an s3 endpoint, not the contrary.
Say that you can specify only an s3 endpoint and from that, the system takes care of provisioning all the needed resources is, IMO, a step further (not that is not good, it is conceptually different).

2023-07-19 08:39 UTC, giubacc commented on enhancements/20230430-object-endpoint.md
> +        Volume: <string>,
I'm not against this idea; I actually think it is a good feature, I only think this as a one step further in respect to what I think should be an initial implementation.
If we want to proceed incrementally, I suggest to firstly assume that we have an already allocated LH volume and from that the user can instantiate an s3 endpoint.
Once done this, in a phase-2 we can implement the other more complex scenario where the user can do all in one single step.

2023-07-19 08:50 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +        Volume: <string>,
There is already exploratory work towards the proposed approach. We will ascertain what is most feasible as we go. For now, the plan is as I explained above.

2023-07-20 06:55 UTC, PhanLe1010 reviewed
I have left some questions.

I am still learning S3GW and COSI, so please forgive me if my questions don't make sense or if they are naive

2023-07-20 06:55 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +* Then the user clicks "Ok".
Is it correct that all of the endpoints of information here may potentially be recorded into a CRD (like `ObjectEndpoint.longhorn.io`)? 

If so, would it be better to have a separate Longhorn UI page, e.g. `/endpoints`, for all endpoints. In this page, users can create enpoints by specifying all parameters. One of the parameter will be longhorn volume name to be used as backend storage for the endpoint. WDYT?

2023-07-20 06:55 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +`s3gw-ui` pod for management and administration.
From what I am reading on S3GW documentation, looks like one s3gw-ui instance currently can only manage one `s3gw` backend (which is equivalent to one `ObjectEndpoint` CRD in this LEP). Is it correct?

I think in general, users may have multiple EndPoints CRs in one cluster. What would we do in this case:
1. Do we also create one `s3gw-ui` instance for each endpoint? This might be too overkill
2. Will we have one `s2gw-ui` instance that can manage all endpoints like [this s3gw design document](https://s3gw-docs.readthedocs.io/en/latest/design/0001-ui-backend/#:~:text=down%20the%20line.-,Multiple%20s3gw%20instances%20managed%20by%20the%20same%20s3gw%2Dui,single%20s3gw%2Dui%20able%20to%20centrally%20manage%20multiple%20s3gw%20service%20instances.,-Considered%20Options)

2023-07-20 06:55 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +interface.
The `ObjectEndpoint` design sounds reasonable to me

2023-07-20 06:55 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +`s3gw` execution, and calling on `VolumeManager.Create()` for volume creation.
Why would the Longhorn volume need to be managed independently by Longhorn UI? After all, it is still a Longhorn volume that have all features like snapshots/backup like other Longhorn volumes, so Longhorn UI can/should still be able to manage it, right? 

For showing endpoint-specific metrics associated with the Longhorn volume, may be Longhorn UI just need to detect that there is an ObjectEndpoint CR that is linked to this volume and show a like to the ObjectEndpoint UI page. WDYT?

2023-07-20 06:55 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +longhorn.ObjectEndpoint{
Yes, a `Status` seems to be needed if we want to track the status of this endpoint

2023-07-20 09:07 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +* Then the user clicks "Ok".
This is a point of discussion right now within our team as well. If you look at the mockup for the UI (https://github.com/aquarist-labs/s3gw/issues/512) it proposes a workflow that requires a user to create a volume first before being able to expose it. However this has rough edges, because s3gw requires exclusive access to its volume. I'm personally in favor of a solution where object endpoints are handled independently from volumes and Longhorn will manage the creation of volumes in the background on its own, much like you suggest here, because then the user will only have to care about the amount (as in Gigabytes) of objects and the storage class.

2023-07-20 09:48 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +`s3gw-ui` pod for management and administration.
Currently each `s3gw-ui` instance can only service one `s3gw` backend. That is correct.

2023-07-20 13:49 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +* Then the user clicks "Ok".
Lets keep in mind that the mock up pointed to by @m-ildefons was initially created taking into account a parallel discussion that is not reflected in this LEP, so should not be considered.

The proposal of the LEP, and the path being explored, focuses on having the Longhorn Volume being magically created (i.e., without the user ever having to care about it) when creating a new Object Endpoint.

As to what @PhanLe1010 mentioned, I also believe having a specific page for all object endpoints may make sense. This way we can add more relevant information than we would otherwise via the Volumes interface. Besides, the volumes interface will nonetheless show volumes that have been claimed by the object endpoints, but that's a lower level of abstraction, and independent from the object endpoints interface.

2023-07-20 13:52 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +`s3gw-ui` pod for management and administration.
@PhanLe1010 that is definitely something being considered. We could technically use one single `s3gw-ui` (once the `s3gw-ui` backend is in place) to manage multiple `s3gw` endpoints. However, given that is not yet fully implemented and tested, nor is the workflow fully determined, I'd suggest we assume one `s3gw-ui` instance per `s3gw` endpoint for now.

2023-07-20 13:53 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +Object Support for Longhorn
Will be included in the next revision of this document.

2023-07-21 14:17 UTC, m-ildefons commented
For the current POC implementation I've been playing around with different settings that may or may not be useful in the `ObjectEndpoint` CRD. This led me to the conclusion that for the features described in this LEP, the following form of a CRD would be best suited:
```
---
apiVersion: longhorn.io/v1beta2
kind: ObjectEndpoint
metadata:
  name: test-endpoint
  namespace: longhorn-system
spec:
  storageClass: longhorn
  credentials:
    accessKey: foo
    secretKey: bar
  size: 5Gi
```
The differences to the proposed CRD are:

- The `Image` field is missing. This field is unnecessary as the Longhorn manager already knows which image it should use to deploy the s3gw, as that is given as command line option.

- `PublicDomain` and `SSLCertificate` are missing because I haven't implemented the features making use of these settings yet.

- `Volume` field has been replaced by the optional `storageClass` and `size` fields. These two fields describe the desired properties of the backing volume sufficiently. The controller can then automatically deploy the resources necessary to realize this. This makes it easier on a user to deploy an object endpoint, since they don't have to deploy a volume first and take care of the association with the object endpoint manually.

2023-07-21 14:42 UTC, giubacc commented
> For the current POC implementation I've been playing around with different settings that may or may not be useful in the `ObjectEndpoint` CRD. This led me to the conclusion that for the features described in this LEP, the following form of a CRD would be best suited:
> 
> ```
> ---
> apiVersion: longhorn.io/v1beta2
> kind: ObjectEndpoint
> metadata:
>   name: test-endpoint
>   namespace: longhorn-system
> spec:
>   storageClass: longhorn
>   credentials:
>     accessKey: foo
>     secretKey: bar
>   size: 5Gi
> ```
> 
> The differences to the proposed CRD are:
> 
> * The `Image` field is missing. This field is unnecessary as the Longhorn manager already knows which image it should use to deploy the s3gw, as that is given as command line option.
> * `PublicDomain` and `SSLCertificate` are missing because I haven't implemented the features making use of these settings yet.
> * `Volume` field has been replaced by the optional `storageClass` and `size` fields. These two fields describe the desired properties of the backing volume sufficiently. The controller can then automatically deploy the resources necessary to realize this. This makes it easier on a user to deploy an object endpoint, since they don't have to deploy a volume first and take care of the association with the object endpoint manually.

This sounds nicely. :+1: 

Some random questions:

Could it make sense to add Longhorn specific settings for controlling the volume properties?
Or here are we saying that we rely completely on the properties defined in the storage-class?
The use case here seems to suggest that is responsibility of the user to define his storage classes. Could this be automated someway when s3gw is used with LH (that is the privileged scenario)? Or is this the intended design?

2023-07-24 07:14 UTC, m-ildefons commented
> Could it make sense to add Longhorn specific settings for controlling the volume properties? Or here are we saying that we rely completely on the properties defined in the storage-class? The use case here seems to suggest that is responsibility of the user to define his storage classes. Could this be automated someway when s3gw is used with LH (that is the privileged scenario)? Or is this the intended design?

Both variants, expecting a user to pre-create storage classes or offering all settings, have their pros and cons. Expecting the user to create storage classes certainly is much simpler.
One noteworthy thing here is, that when creating a volume through the Longhorn UI, the users is asked for various settings directly, which completely circumvents the storage classes.
I'm not sure if we want to copy this behavior, but it would be a reasonable choice to be consistent with the volume creation dialogue.

We're also not necessarily confined to either/or exclusively. We could create an abstraction that can handle both, it would just be more work, e.g.:
```golang
longhorn.ObjectEndpoint{
  ObjectMeta metav1.ObjectMeta {
    Name: <string>
  },
  Spec: longhorn.ObjectEndpointSpec{
    Storage: <longhorn.StorageSettings>
  },
}

longhorn.StorageSettings{
  Size: <resource.Quantity>
  
  //+optional
  StorageClass: <string>
  
  //+optional
  VolumeSettings: <longhorn.VolumeSettings>
},

longhorn.VolumeSettings{
  numberOfReplicas: <string>
  staleReplicaTimeout: <string>
  fsType: <string>
  allowVolumeExpansion: <bool>
  [...]
},
```
This way both a storage class or volume settings could be specified directly. It's then the task of the controller to ensure that a) no conflicting settings are given (i.e. either the storage class _or_ the volume settings) and b) to provision the correct resources and connect them up.
This mechanism is certainly the most involved on the controller side, but it's within the realm of technical possibilities.

A strong argument for supporting volume settings directly instead of through a storage class is, that as far as I can tell the Longhonr UI does not have a dialogue for creating storage classes. It's up to the user to create them through the use of YAML files and `kubectl`, which is a bit of an ugly spot on the user experience IMO, especially when we expect the user to do that to make use of all the settings for the object endpoint. But a dialogue for creating storage classes from the Longhorn UI isn't in the scope of this LEP.

2023-07-24 10:41 UTC, jecluis commented
Why would we need to have the user defining the storage class? Can't we create one if there isn't one ourselves? Wouldn't that also give us more control over how the data is kept?

2023-07-25 14:13 UTC, m-ildefons commented
> Why would we need to have the user defining the storage class? Can't we create one if there isn't one ourselves? Wouldn't that also give us more control over how the data is kept?

There's a default storage class that we can fall back onto, in case the user hasn't deleted it.

Unrelated to that, another question: Should the ObjectEndpoint resource be namespace or cluster scoped?
The argument for being cluster scoped would be that this would allow us to keep the deployments, services, PVCs confined to the `longhorn-system` namespace, hiding them from the user.
Making it namespace scoped has advantages for users who utilize (cluster-)roles to limit permissions of actors on the cluster. I'm not sure how important that is.

2023-07-25 14:56 UTC, giubacc commented
> The argument for being cluster scoped would be that this would allow us to keep the deployments, services, PVCs confined to the `longhorn-system` namespace, hiding them from the user.

I haven't a strong opinion pro or cons one approach.
I would prefer technical s3gw resources to not pollute the user's namespace ... but being more pro or cons one way could become more obvious in practice.

2023-07-25 15:08 UTC, votdev commented on enhancements/20230430-object-endpoint.md
> +`s3gw` execution, and calling on `VolumeManager.Create()` for volume creation.
> After thinking about this, and from feedback from several parties, IMO the best approach might actually be
> 
>     1. Have the volumes being used by the individual object endpoints be shown in the volumes, so, as @PhanLe1010 mentioned, we could technically perform any operations on it as with any other volume;
> 
>     2. Have an "object endpoints" page/section/whatever specific for the various object endpoints, where we can then show object endpoint-specific metrics, data, whatever.
> 
> 
> As I see it, these two live on different layers of abstraction: Volumes are the lower level bits the user should not care about when deploying an object endpoint, but that they may still care about for snapshotting or whatever. On the upper layer, we have the object endpoint, which doesn't particularly care which volume it has as long as a volume claim is associated with its deployment, and for which we can provide specific metrics that are relevant in an object world.
> 

I like this proposal because it makes everything transparent for the users. They see the volumes that are created and used by s3gw normally in the LH UI and can perform all actions that can be done with a volume.

2023-07-25 15:23 UTC, votdev commented on enhancements/20230430-object-endpoint.md
> +happen. We expect to be able to simply restart existing pods using new images.
Assuming the on-disk format for the metadata store has not been changed.

2023-07-25 15:30 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +happen. We expect to be able to simply restart existing pods using new images.
We can easily do in-place metadata upgrades now. That is no longer an issue.

2023-08-16 00:24 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +  addressed in a specific LEP.
While these are non-goal for this LEP. I feel that we should keep this one in mind while designing this PR to make it easier for future work

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +`Persitent Volume` that will be bound to the `Persistent Volume Claim` mentioned
We will also need to create the Longhorn volume explicitly.

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +    StorageClass    string
The `StorageClass` property is ignored[1], since we manage the volume explicitly ourselves in the controller. Perhaps it should be removed or replaced by other properties that are more meaningful in this context.

[1]: 
When explicitly creating a PV and PVC together, the storage class property must match or be an empty string, but all other aspects of the storage class are ignored.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +before being able to move the endpoint to state `running`.
Is this a requirement or is this documenting what the current iteration of the controller is doing?

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +with multiple Object Endpoints, but that should be considered as future work.
This LEP now _includes_ the UI integration as well?

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +appreciated.
There is an integration test suite in longhorn/longhorn-tests which we can utilize to test the controller's behavior from a K8s client point of view.
There are also unit tests in the controller it self, which can be used to test individual functions against a mocked/faked K8s API.

2023-08-29 08:58 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +  used
Is being cluster-externally accessible a requirement for this LEP?

2023-08-29 13:09 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +with multiple Object Endpoints, but that should be considered as future work.
Integration, no. That presumes the administration and management UI becomes part of the Longhorn UI. That has been stated from the beginning that is not part of this LEP.

`s3gw-ui` support on the other hand has always been part of this LEP.

2023-08-30 01:58 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +state. Insights are greatly appreciated.
I am working on designing this part

2023-08-30 03:22 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +a volume; and 3) deploy an `s3gw-ui` pod for management and administration. For
I believe this has been discussed previously. There are on-going efforts to make the `s3gw-ui` not depend on a specific ingress to handle CORS. This LEP accounts for those efforts.

2023-08-30 03:25 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +* The user must provide SSL certificates to be used by the endpoint
In-cluster deployments may also require SSL -- we know of at least such a user. We can drop this requirement and have the user deploy SSL themselves, but natively supporting this seems the path of least resistance. Is there anything you are worried about?

2023-08-30 03:27 UTC, jecluis commented on enhancements/20230430-object-endpoint.md
> +  used
Potentially. I don't see why not. It shouldn't be adding a lot more complexity, I think, and requiring another LEP to make stuff externally accessible seems a bit of overkill to me.

2023-08-30 08:48 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +  used
It needs to be - otherwise we can't support the backup-from-another-LH-cluster-to-s3 use case.

2023-08-30 08:49 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +* The user must provide SSL certificates to be used by the endpoint
Can't we document / automate a `cert-manager` integration? We need SSL for the UIs anyway too.

2023-08-30 08:51 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +type ObjectEndpoint struct {
Amazon calls theirs "S3 endpoints". And, well, they are the API endpoints associated with the S3 API too, and we can have multiple ones of them. I think either phrasing works and we shouldn't get too invested in this argument :-)

2023-08-30 15:08 UTC, l-mb commented on enhancements/20230430-object-endpoint.md
> +this case, XFS, which `s3gw` requires for performance reasons.
(As a note, we need the reflink support so we can effectively merge multipart uploads etc, which ext4 can't do.)

2023-09-04 10:43 UTC, m-ildefons commented on enhancements/20230430-object-endpoint.md
> +type ObjectEndpoint struct {
I agree with Phan here. Using _ObjectStore_ would leave _endpoint_ free to describe TLS and ingress/domain configuration, allowing perhaps the use of multiple endpoints for one store, e.g. like so:
```
kind: ObjectStore
apiVersion: longhorn.io/v1beta2
metadata:
[...]
spec:
  credentials:
    accessKey: ...
    secretKey: ...
  storage:
    size: 100Gi
    numberOfReplicas: 3
    diskSelector:
      - ssd
  endpoints:
    - name: public
      domainName: foobar.example.com
      tls: ...
    - name: private
      domainName: foobar.longhorn-system.svc.cluster.local
```

2023-09-07 02:14 UTC, PhanLe1010 commented on enhancements/20230430-object-endpoint.md
> +    StorageClass    string
Agree to remove the `StorageClass` property. We still need to hardcode a fixed storageclass like `longhorn-objectstore` (without any parameter) so that features like PVC expansion can work. This is important because user will need to be able to resize the PVC. Ref the POC PR https://github.com/longhorn/longhorn-manager/pull/2135/files#diff-713be8c3744f9bf701a213640c0c1d0d302c1231aa21b291f7d35bdcdbd30068R433-R434

2023-10-04 11:28 UTC, votdev requested changes

2023-10-04 11:28 UTC, votdev commented on enhancements/20230430-object-endpoint.md
> +We thus propose the creation of a `/v1/endpoint/object` API endpoint. This route
This section does not match the reality of the PR https://github.com/longhorn/longhorn-manager/pull/2136/files#diff-cb740c237beef9090d8b3a15ca8b76aac83a3af2d52deadc382b4309916a715c and needs to be adapted.

2023-10-06 07:50 UTC, votdev commented on enhancements/20230430-object-endpoint.md
> +* A modal dialog is shown, with the various Object Endpoint related fields:
These fields are taken from https://github.com/longhorn/longhorn-manager/pull/2136/files#diff-c75a796f2c69c35ee5ab6293f23db5c8d5af9a241f4f2345e96b1fc41d72ddceR55

Is it necessary to request all that fields from the user or can we hardcode some of them?

2023-12-12 04:54 UTC, innobead commented
Closing first, and this will be revisited in 1.7.

2023-12-12 04:54 UTC, closed without merging