feat(lep): add SPDK volume support
longhorn/longhorn pull request #5987
Opened 2023-05-23 08:09 UTC by derekbit

Longhorn/longhorn#5778
Longhorn/longhorn#5711
Longhorn/longhorn#5744

2023-06-19 07:20 UTC, innobead requested changes
In general, LGTM. Just one comment. 

Suggest adding some test cases here, so they can be a reference for later e2e coverage.

2023-06-30 05:44 UTC, derekbit commented on enhancements/20230523-support-spdk-volumes.md
> +    - `spdk`: a newly introduced data path based on SPDK
Updated. Thank you.

2023-06-30 08:57 UTC, shuo-wu reviewed
In general LGTM

2023-06-30 08:57 UTC, shuo-wu commented on enhancements/20230523-support-spdk-volumes.md
> +- Environment Setup
NIT: The `uio` module installation & load is missed

2023-06-30 08:57 UTC, shuo-wu commented on enhancements/20230523-support-spdk-volumes.md
> +    - Introduce `backendStoreDriver` in `volume.Spec`, `engine.Spec` and `replica.Spec`.
NIT: and for Proxy gRPC service APIs.

2023-06-30 08:57 UTC, shuo-wu commented on enhancements/20230523-support-spdk-volumes.md
> +    - `Instance` gRPC service: It is tasked with managing various operations related to instance management, including creation, deletion, retrieval, listing, and watching. An instance, either an eng
NIT: a v2 engine typically means not only a raid bdev, but also the frontend nvme target & initiator & the bind mount device

2023-06-30 08:57 UTC, shuo-wu commented on enhancements/20230523-support-spdk-volumes.md
> +     ![gRPC Services](image/spdk_services.png)
BTW, one SPDK service can directly talk with other SPDK services.

2023-07-03 09:13 UTC, DamiaSan commented on enhancements/image/spdk_disks.png
From this diagram it seems that a `spdk-engine` communicates with many `spdk_tgt`, but I understood that every engine talks only with one spdk instance.

2023-07-17 03:11 UTC, derekbit commented on enhancements/20230523-support-spdk-volumes.md
> +     ![gRPC Services](image/spdk_services.png)
Updated. Thank you.

2023-07-17 03:11 UTC, derekbit commented on enhancements/image/spdk_disks.png
Updated. Thank you.

2023-07-17 03:11 UTC, derekbit commented on enhancements/20230523-support-spdk-volumes.md
> +    - `Instance` gRPC service: It is tasked with managing various operations related to instance management, including creation, deletion, retrieval, listing, and watching. An instance, either an eng
Revised. Thank you.

2023-07-17 03:11 UTC, derekbit commented on enhancements/20230523-support-spdk-volumes.md
> +    - Introduce `backendStoreDriver` in `volume.Spec`, `engine.Spec` and `replica.Spec`.
Added. Thank you.

2023-07-17 03:12 UTC, derekbit commented on enhancements/20230523-support-spdk-volumes.md
> +- Environment Setup
Added. Thank you.

2023-08-11 15:48 UTC, innobead approved these changes
LGTM. This has been implemented in 1.5.

2023-08-11 15:48 UTC, innobead commented on enhancements/20230523-support-spdk-volumes.md
> +          tags: []
`storageReserved` should be invalid in block disk mode? If yes, we should make a note in the doc.

2023-08-11 15:48 UTC, merged

2023-08-11 16:35 UTC, innobead commented on enhancements/20230523-support-spdk-volumes.md
> +          tags: []
Probably no need if it will not be taken effect. 

However, it's better to mention it's ineffective in this case to prevent unnecessary confusion.