feat(backupstore): add azurite emulator
longhorn/longhorn pull request #6006
Opened 2023-05-26 02:32 UTC by mantissahz

Add the Azurite manifest to start Azurite server for local testing

Ref: longhorn/longhorn#1309, https://github.com/longhorn/longhorn-tests/pull/1382

2023-05-28 16:27 UTC, innobead requested changes

2023-05-28 16:27 UTC, innobead commented on deploy/backupstores/azurite-backupstore.yaml
> +kind: Pod
Let's make this as deployment, change minio & nfs example as well.

2023-05-28 16:27 UTC, innobead commented on deploy/backupstores/azurite-backupstore.yaml
> +  name: azblob-secret
Duplicated, should only have one `azblob-secret`

2023-05-28 16:27 UTC, innobead commented on deploy/backupstores/azurite-backupstore.yaml
> +  name: azblob-secret
Should have this mounted to `longhorn-test-azblob` pod right?

2023-05-29 11:25 UTC, mantissahz commented on deploy/backupstores/azurite-backupstore.yaml
> +kind: Pod
Changed three backupstores `nfs`, `minio` and `azurite` as deployments

2023-05-29 11:25 UTC, mantissahz commented on deploy/backupstores/azurite-backupstore.yaml
> +  name: azblob-secret
Removed and left the secret in `longhorn-system` namespace

2023-05-29 11:28 UTC, mantissahz commented on deploy/backupstores/azurite-backupstore.yaml
> +  name: azblob-secret
It will have the default account and key when azurite server starts and we don't need to mount a volume that contains the secret but a default container (as s3 bucket) needs to be created when the backupstore is initialized

2023-05-29 11:52 UTC, innobead approved these changes

2023-05-29 11:52 UTC, merged

2023-05-29 11:52 UTC, innobead commented
cc @longhorn/qa