SPDK charts and examples
longhorn/longhorn pull request #6032
Opened 2023-05-31 15:00 UTC by derekbit

2023-06-01 03:23 UTC, innobead requested changes
In general, LGTM. Some comments needed to resolve.

2023-06-01 03:23 UTC, innobead commented on examples/spdk/storageclass.yaml
> +  fromBackup: ""
If not supported yet, we can comment out. Also, add a comment next to `parameters` to mention those parameters not supported yet.

2023-06-01 03:23 UTC, innobead commented on chart/templates/crds.yaml
> +                        backendStoreDriver:
Do we need this for deprecated `instances`?

2023-06-01 13:53 UTC, derekbit commented on chart/templates/crds.yaml
> +                        backendStoreDriver:
Yes, instances in old IMs need the field as well.

2023-06-01 13:54 UTC, derekbit commented on examples/spdk/storageclass.yaml
> +  fromBackup: ""
Addressed, thank you.

2023-06-01 14:02 UTC, innobead commented
Pending until manager PRs merged

2023-06-01 15:48 UTC, merged

2023-06-02 03:38 UTC, shuo-wu commented on chart/templates/crds.yaml
> +                        backendStoreDriver:
Why do not some `backendStoreDriver` fields include `enum`?

2023-06-02 03:44 UTC, derekbit commented on chart/templates/crds.yaml
> +                        backendStoreDriver:
Not sure if we need to include `enum` for the `backendStoreDriver` are in status.

2023-06-02 03:50 UTC, shuo-wu commented on chart/templates/crds.yaml
> +                        backendStoreDriver:
If it's allowed and there is compatibility issue, I think it's better to have