Add reserve storage percentage in helm chart
longhorn/longhorn pull request #6258
Opened 2023-07-07 20:37 UTC by aheyne

#5958 

- Add the StorageReservedPercentageForDefaultDisk configuration to the helm chart.

2023-07-11 07:01 UTC, innobead submitted a review, later dismissed
LGTM. 

@mantissahz @c3y1huang Please help review this as well.

2023-07-11 07:05 UTC, mantissahz approved these changes
LGTM

2023-07-11 07:08 UTC, c3y1huang requested changes

2023-07-11 07:08 UTC, c3y1huang commented on dev/upgrade-responder/install.sh
> +        "longhornSettingStorageReservedPercentageForDefaultDisk": {
Already exists in https://github.com/longhorn/longhorn/pull/6258/files#diff-5a0da96ff63d171316630a8bb3a731c3287ba8db343a47c2076c0d3e75824509R314.

2023-07-12 00:40 UTC, c3y1huang approved these changes
Suggest consolidating to a single commit.

2023-07-13 18:20 UTC, aheyne commented
Rebased and squashed

2023-07-14 00:58 UTC, mantissahz approved these changes

2023-07-15 12:00 UTC, innobead approved these changes

2023-07-15 12:00 UTC, merged

2023-07-15 12:00 UTC, innobead commented
@mergify backport v1.5.x