feat(lep): Talos Linux support design
longhorn/longhorn pull request #6325
Opened 2023-07-14 08:26 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/3161

2023-07-14 14:26 UTC, shuo-wu approved these changes
LGTM

2023-07-14 16:07 UTC, derekbit commented on enhancements/20230714-talos-linux-support.md
> +- Develop a common thread namespace switch package that can be utilized by projects requiring interaction with the host.
Can you elaborate more on why we need a thread namespace switch rather than use the existing `nsenter`? I remember you explained it before, but I forgot the details.

2023-07-14 16:09 UTC, derekbit commented on enhancements/20230714-talos-linux-support.md
> +# Talos Linux Support
If possible, can you add a short section or paragraph for introducing the difference between Talos and OS and why we need to do some changes.

2023-08-11 11:27 UTC, innobead requested changes
What's happening if the iscsid extention pod unexpectedly restarted? Would it cause the unexpected volume detached?

2023-08-11 11:27 UTC, innobead commented on enhancements/20230714-talos-linux-support.md
> +- The targeting function execute within a goroutine and utilize the `unix.Setns` to switch to different namespaces.
This is interesting to use `setns` at runtime.

2023-08-11 11:27 UTC, innobead commented on enhancements/20230714-talos-linux-support.md
> +Longhorn currently assumes that `iscsid` is running on the host. However, in Talos Linux, `iscsid` runs as a Talos extension service in a different namespace.
v2 data engine is relying on nvmecli on host, so we will have same need here. How about NFS, CIFS client here? do we need to have another Talos extension?

2023-08-11 11:27 UTC, innobead commented on enhancements/20230714-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
or we don't need to be that intelligent, but rather rely on the info provided by users like specify this setup is talos, so we will run it differently. 

This could be helpful if we need to support other specific purpose OS.

2023-08-14 01:42 UTC, c3y1huang commented on enhancements/20230714-talos-linux-support.md
> +Longhorn currently assumes that `iscsid` is running on the host. However, in Talos Linux, `iscsid` runs as a Talos extension service in a different namespace.
> v2 data engine is relying on nvmecli on host, so we will have same need here.
Yes, I assume we will have the same need for the v2 data engine. However, I think the support for v2 data engine should be evaluated later since the feature is still in preview phase.

> How about NFS, CIFS client here? do we need to have another Talos extension?
In regards to the NFS client and CIFS client, [they are preinstalled in the kubelet image](https://github.com/siderolabs/kubelet/blob/v1.27.4/Dockerfile#L33-L52).

2023-08-14 02:03 UTC, c3y1huang commented on enhancements/20230714-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
As there is only one OS required for this kind of handling, I prefer not to add a new setting for user to manually indicate the OS distro. Given that we already gather OS distribution information for Longhorn's usage data collection, my preferred approach would be to cache the OS distro and reuse it for the necessary dependency binaries.

2023-08-31 15:39 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
from Team talos, just saw this, fstrim could be included in the host as an extension though, if that makes things easier rather than switching to the kubelet container namespace

2023-08-31 18:21 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
yes, sure, I can put an example tomorrow, basically something based of this in the talos extensions repo https://github.com/siderolabs/pkgs/blob/main/util-linux/pkg.yaml, just have to enable the binaries

2023-08-31 18:27 UTC, innobead commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Thanks @frezbo :+1:

2023-09-01 04:16 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
@frezbo sounds good to me.

@innobead Having the fstrim execute on the host rather than within the kubelet namespace is a small change on the feature PRs. This shouldn't be a blocker for the PR reviews.

2023-09-01 12:06 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
I've created a draft PR here: https://github.com/siderolabs/extensions/pull/216

Also pushed the extensions here: `ghcr.io/frezbo/util-linux:2.39.1`, this provides `fstrim` at `/usr/local/sbin/fstrim`

2023-09-04 02:29 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
The extension image works for me.
```
> talosctl --talosconfig talosconfig -e 54.169.155.201 -n 10.0.28.181 get extensions
NODE          NAMESPACE   TYPE              ID                                          VERSION   NAME          VERSION
10.0.28.181   runtime     ExtensionStatus   000.ghcr.io-siderolabs-iscsi-tools-v0.1.4   1         iscsi-tools   v0.1.4
10.0.28.181   runtime     ExtensionStatus   001.ghcr.io-frezbo-util-linux-2.39.1        1         util-linux    $VERSION
> k exec -it longhorn-test -- ./run.sh -k test_filesystem_trim
Defaulted container "longhorn-test" out of: longhorn-test, longhorn-test-report
================================================ test session starts =================================================
platform linux -- Python 3.9.17, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: order-1.0.1, repeat-0.9.1
collected 349 items / 347 deselected / 2 selected                                                                    

test_basic.py::test_filesystem_trim[ext4] PASSED                                                               [ 50%]
test_basic.py::test_filesystem_trim[xfs] PASSED                                                                [100%]

================================================== warnings summary ==================================================
/usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323
  /usr/local/lib/python3.9/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.volume_backup_restore - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    warnings.warn(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================== 2 passed, 347 deselected, 1 warning in 149.90s (0:02:29) ==============================
```

@frezbo When can we expect this to be released?

2023-09-04 02:49 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
LEP updated.

2023-09-04 06:25 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
This would be part of Talos 1.6, I guess Dec, after k8s 1.29 release

2023-09-04 07:24 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Thanks @frezbo !

@innobead , here are the 2 options before Talos 1.6:
1. Stick with the previous kubelet proc for now and later change to use the host namespace once Talos 1.6 is released.
1. Implement directly with the host namespace. In the interim period before Talos v1.6 becomes available, we can test using ghcr.io/frezbo/util-linux:2.39.1.

2023-09-04 07:27 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
since `ghcr.io/frezbo/util-linux:2.39.1` is not talos version dependent, once I get this merged, that image could be used with older talos too. 

Since util-linux is not talos version dependent (unlike kernel modules, it can be used after merging. I'll get this merged in today.

2023-09-04 07:29 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Sorry for the confusion

2023-09-04 18:20 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
`ghcr.io/siderolabs/util-linux-tools:v1.6.0-alpha.0-4-gd9145f9` this is published and can be used

2023-11-14 05:54 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Experimenting with the latest Talos version (v1.5.5), I've encountered challenges. The approach of utilizing `.machine.install` for patching node system extensions no longer seems effective.

And, utilizing the [image factory](https://www.talos.dev/v1.5/talos-guides/install/boot-assets/#image-factory) is not possible due to the absence of the `util-linux-tool`. 

So my last option is to use the [imager](https://www.talos.dev/v1.5/talos-guides/install/boot-assets/#imager), and it leading errors while generating the AWS disk image with extensions:
```
error validating extension "iscsi-tools": path "/usr/include/libopeniscsiusr.h" is not allowed in extensions
Error: error validating extension "iscsi-tools": path "/usr/include/libopeniscsiusr.h" is not allowed in extensions
```

2023-11-14 06:18 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
https://github.com/siderolabs/extensions/pull/265 sorry, already a fix is underway

2023-11-14 06:47 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
@frezbo is there a way for v1.5.x to achieve `.machine.install` like v1.4.x so we don't need a customized Talos AWS disk image with the extensions?

2023-11-14 07:17 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
There's [factory.talos.dev](https://factory.talos.dev/), that would be the official way going forward, also the aws image downloaded from factory with iscsi-tools is not a broken one

2023-11-14 07:20 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Is there a plan to include `util-linux-tool` in the factory?

2023-11-14 07:23 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
> There's [factory.talos.dev](https://factory.talos.dev/), that would be the official way going forward, also the aws image downloaded from factory with iscsi-tools is not a broken one

To my knowledge, to use the AWS disk image in the factory, we need to upload it to AMI, is there are way to avoid that?

2023-11-14 08:02 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
Wipe my previous comment, I see v1.5.x now have `@sha256:<digest>` included.

2023-11-14 08:35 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
> Is there a plan to include util-linux-tool in the factory?

should be with Talos 1.6, you can replace the version in the link with `1.6.0-alpha.0`

> To my knowledge, to use the AWS disk image in the factory, we need to upload it to AMI

yes, no way around for now

2023-11-14 08:35 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
>  I see v1.5.x now have @sha256:<digest> included

yes, the `extensions` oci image has the list of all extension images and their sha's

2023-11-14 08:40 UTC, c3y1huang commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
@frezbo I see. Is there a plan to have the extensions hot-pluggable, without the need to rebuild the image every time we add or remove an extension?

2023-11-14 08:42 UTC, frezbo commented on enhancements/20230814-talos-linux-support.md
> +Instead of rewriting the `fstrim` binary dependency, leverage the existing `fstrim` binary within the `kubelet` namespace. However, considering that the `kubelet` namespace might not be present in ot
it's part of initramfs, so it needs to be rebuild

2023-12-18 09:57 UTC, innobead approved these changes
In general, LGTM. A few comments to think through, and see if anything we need to adjust/improve later.

2023-12-18 09:57 UTC, innobead commented on enhancements/20230814-talos-linux-support.md
> +- Once the targeting function completes its execution, the thread will switch back to the original namespace and unlock the thread to allow other goroutines to execute.
This should mean each namespace-based operation should be atomic instead of wrongly switching to another namespace during an operation.

2023-12-18 09:57 UTC, innobead commented on enhancements/20230814-talos-linux-support.md
> +
Would this cause performance issues if the function runs for a long time? Using a lock should occur soon to prevent any blocking operations? Are there any calls we need to worry about?

2023-12-18 09:57 UTC, innobead commented on enhancements/20230814-talos-linux-support.md
> +
This is cool. We probably require more system CLIs in the future, especially v2.

2023-12-18 09:57 UTC, innobead commented on enhancements/20230814-talos-linux-support.md
> +
As mentioned above, need to see if longer-locking would impact any performance.

2023-12-18 09:58 UTC, merged