Add LEP for disk anti-affinity
longhorn/longhorn pull request #6431
Opened 2023-07-31 20:41 UTC by ejweber

#3823

2023-08-03 15:57 UTC, james-munson approved these changes
A good step forward.

2023-08-03 15:57 UTC, james-munson commented on enhancements/20230718-disk-anti-affinity.md
> +  do not schedule to the same disk.
Kudos to you for this.

2023-08-03 15:57 UTC, james-munson commented on enhancements/20230718-disk-anti-affinity.md
> +to refuse to schedule replicas when different disks are not available.
I personally think this should default to "false", but I understand the arguments for leaving it as is.  At least the chances are reduced of falling into it accidentally.

2023-08-07 11:36 UTC, innobead requested changes
In general, LGTM. Just one comment needs to clarify.

2023-08-07 11:36 UTC, innobead commented on enhancements/20230718-disk-anti-affinity.md
> +
`spec.replicaSoftAntiAffinity = false` means each replica should be scheduled to a different node, so `multiple replicas would have scheduled to the same disk and no error would have occurred` is not right, correct?

What you want to test should be `spec.replicaSoftAntiAffinity = true, spec.replicaDiskSoftAntiAffinity = false`?

2023-08-07 14:23 UTC, ejweber commented on enhancements/20230718-disk-anti-affinity.md
> +
You are correct. Good catch. Fixed in an amend.

2023-08-07 14:43 UTC, innobead approved these changes

2023-08-07 14:43 UTC, merged