lep(backingimage): backingimage backup support
longhorn/longhorn pull request #6467
Opened 2023-08-07 10:04 UTC by ChanYiLin

ref: [longhorn/longhorn#4165](https://github.com/longhorn/longhorn/issues/4165)

2023-08-07 11:14 UTC, innobead requested changes
In general, look good, but have some comments needed to resolve.

Also, we need to make the BI backup & restore respect https://longhorn.io/docs/1.5.1/references/settings/#concurrent-volume-backup-restore-per-node-limit as well.

2023-08-07 11:14 UTC, innobead commented on enhancements/20230807-backingimage-backup-support.md
> +7. In `BackingImageDataSourceController`
How about when restore failed, how we will handle it? will do the cleanup with the `BackingImageDataSourcePod` lifecycle? or just Backup is failed, so when user deleted the backup, the related failed restore data will be cleaned up accordingly?

2023-08-07 11:14 UTC, innobead commented on enhancements/20230807-backingimage-backup-support.md
> +    - Restore when user create `Volume` through `CSI`
so the volume restore and BI restore will happen concurrently, but the restoring volume will become ready until the BI is ready, correct?

2023-08-09 07:57 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +        - if the block is already in the backup store, skip it.
This part will be the same as original volume backup

2023-08-09 07:59 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +    - Setup
so this test is not to test the functionality but to test the space efficiency, should we measure the metrics in the test or just provide the backingimage of backingimage as test case ?

2023-08-09 08:03 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +    - Workflow
will change to directly read/backup qcow2 block by block to avoid conversion

2023-08-09 08:06 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +7. In `BackingImageDataSourceController`
BackupBackingImage and BackingImage don't related to each other
When user restore a BackupBackingImage, It means creating a BackingImage with `type=restore`
so if the BackingImage creation failed, it will follow the original BackingImage failure handler which will delete the datasourcepod and cleanup the tmp file.
For `type=restore` we can also do retry like `type=download`

2023-08-09 08:07 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +7. In `BackingImageDataSourceController`
BackupBackingImage won't failed in this case, it only represents the backup in the backup store

2023-08-09 08:08 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +    - Restore when user create `Volume` through `CSI`
Yes, replica will wait until its node has BackingImage then create the replica instance

2023-08-09 08:34 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +
Added

2023-08-11 10:09 UTC, innobead submitted a review, later dismissed
In general, LGTM.

Just a note, we will only get benefits when backing up images because of prevent duplicated blocks to upload, but restoring backing is full restore instead.

2023-08-11 10:09 UTC, innobead commented on enhancements/20230807-backingimage-backup-support.md
> +    - If it failed to restore the `BackingImage`, the status of the `BackingImage` will be failed and  `BackingImageDataSourcePod` will be cleaned up and retry with backoff limit like `type=download`
Is there any timeout for the backoff in the current download? We should prevent an infinite download eventually and just make the backing image creation failed. (let it fail)

2023-08-11 10:20 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> +    - If it failed to restore the `BackingImage`, the status of the `BackingImage` will be failed and  `BackingImageDataSourcePod` will be cleaned up and retry with backoff limit like `type=download`
Will create another improvement issue for this

2023-08-11 10:23 UTC, innobead approved these changes

2023-08-11 10:25 UTC, merged