feat(lep): multiple backup stores support
longhorn/longhorn pull request #6630
Opened 2023-09-04 06:37 UTC by mantissahz

Ref: longhorn/longhorn#5411

2023-09-05 04:27 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +The current Longhorn only support a single backup store for all volumes. The feature aims to provide multiple backup stores with tiering.
Actually, we don't support tiering in the implementation. `The feature aims to provide multiple backup stores` is good enough.

2023-09-05 04:34 UTC, innobead commented on enhancements/20230828-multiple-backup-stores-support.md
> +The current Longhorn only support a single backup store for all volumes. The feature aims to provide multiple backup stores with tiering.
@derekbit what tiering (use cases) you think we could/should support in the future?

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +- Backups can be synchronized from difference remote backup targets.
```suggestion
- Backups can be synchronized from different remote backup targets.
```

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +- Backups can be backed up to difference remote backup targets.
```suggestion
- Snapshots can be backed up to different remote backup targets.
```

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +- A backup can be restored from difference remote backup targets to be a new volume.
```suggestion
- A backup can be restored from its remote backup targets to be a new volume.
```

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +1. User can find the link `Backup Target` in drop down menu of `Setting`.
We probably can remove the `backup-target` and `backup-target-credential-secret` from the settings. One of the backup targets is set to the default one.

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +  default: true
Can user delete the default backup target?

2023-09-05 04:45 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetName: the backup target Name. (string)
What's the purpose of the `status.backupTargetName`?

2023-09-05 05:59 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +The current Longhorn only support a single backup store for all volumes. The feature aims to provide multiple backup stores with tiering.
Removed `with tiering`

2023-09-05 05:59 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +  default: true
I think it would be like clean up the backup target URL of default backup target we implement now, so default backup target can be deleted: 

1. if it is the only one backup target.
2. if there are other backup targets, and then we choose another one as default randomly.

WDYT?

2023-09-05 06:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +- Backups can be synchronized from difference remote backup targets.
Modified. Thanks

2023-09-05 06:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +- Backups can be backed up to difference remote backup targets.
Modified. Thanks

2023-09-05 06:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +- A backup can be restored from difference remote backup targets to be a new volume.
Modified. Thanks

2023-09-05 06:01 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +1. User can find the link `Backup Target` in drop down menu of `Setting`.
Added in `Implementation Overview`>`CRD` to mention that we will remove these two settings.

2023-09-05 06:02 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetName: the backup target Name. (string)
It is used to get the BackupTarget CR conveniently

2023-09-05 20:46 UTC, james-munson requested changes

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +     - backup target controller needs to synchronize the data from the extra backup target created.
What data are synchronized, and to where?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +     - backup target controller needs to delete the data in the cluster related the extra backup target deleted.
What does this mean?  When a backup target is deleted, all the backups on it are implicitly deleted?  That seems extreme.  Shouldn't we require that there be no backups stored there before we delete a backup target?

Another question:  does it make sense to have a "read-only" status on a backup target such that one can restore existing backups, but not use it to make new ones?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +```txt
```yaml

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +User can setup the default backup target as usual on the page `Setting/General` and create extra backup targets on the page `Settings/Backup Target` or create/modify backup targets by the manifest. A
When backing up to multiple targets, is each backup independent (duplicating the process of calculating diffs and so on?)  Or is there one actual backup operation, and each write is "mirrored" to the set of targets as we go?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetName: the backup target Name. (string)
This has backupTargetName twice.

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +   - Create a pulling backup volume from the backup target by the backup volume name `volumeName` + `-` + `backupTarget.Name` and adding a label `backup-target` with the backup target URL.
What is a "pulling" backup volume?  What is it pulling, and from where?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +3. Setup an extra old backup target.
What makes it "old"?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +
How is the migration from a global setting to a new CRD done during upgrade?

2023-09-05 20:46 UTC, james-munson commented on enhancements/20230828-multiple-backup-stores-support.md
> +    | Update | backupTargetURL, credentialSecret string, pollInterval time.Duration, default boolean | err error | Update the backup targets information | **PUT** `/v1/backuptargets/{backupTargetName
If one modifies a backup target to be the default one, is the attribute automatically removed from the previous default in a single transaction?  If not, does it validate that there is not currently a default?

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetName: the backup target Name. (string)
Removed. Thanks

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +     - backup target controller needs to delete the data in the cluster related the extra backup target deleted.
> What does this mean? When a backup target is deleted, all the backups on it are implicitly deleted?

Only Backup/BackupVolume CR objects related to the deleted backup target in the cluster will be deleted and data on remote backup target will not be deleted as now we do for `BackupTargets.Spec.BackupTargetURL` is empty.

Modified the description to be more clear.

> does it make sense to have a "read-only" status on a backup target such that one can restore existing backups, but not use it to make new ones?

Yes, it is a good idea. 
Thanks.

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +```txt
Modified. Thanks

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +User can setup the default backup target as usual on the page `Setting/General` and create extra backup targets on the page `Settings/Backup Target` or create/modify backup targets by the manifest. A
>When backing up to multiple targets, is each backup independent (duplicating the process of calculating diffs and so on?)

Yes, it is independent.

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +   - Create a pulling backup volume from the backup target by the backup volume name `volumeName` + `-` + `backupTarget.Name` and adding a label `backup-target` with the backup target URL.
Modified the description. A `pulling` backup volume is a backup volume existing on the remote backup target and we prepare to create a BackupVolume CR object for it when we synchronize the backup information from the remote backup target.

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +
We have the `default` backup target created now when the setting controller is running.
We just need to fill in the values of `default` backup target during upgrade.

2023-09-06 02:06 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +    | Update | backupTargetURL, credentialSecret string, pollInterval time.Duration, default boolean | err error | Update the backup targets information | **PUT** `/v1/backuptargets/{backupTargetName
>If one modifies a backup target to be the default one, is the attribute automatically removed from the previous default in a single transaction?

Yes, it is.
Added more descriptions for this in `User Experience In Detail` and `Implementation Overview`
Thanks

2023-09-06 02:07 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +     - backup target controller needs to synchronize the data from the extra backup target created.
Modified. The backups information will be synchronized from remote backup target and controller will create Backup/BackupVolume CR objects that exists on remote backup target.

2023-09-06 19:29 UTC, james-munson submitted a review, later dismissed
Thanks for the changes.  LGTM

2023-09-07 15:02 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +## Proposal
What will happen when two backup targets have the same backup volumes?

2023-09-07 15:07 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +3. User can create a new backup target on the page `Backup Target` by clicking the button `Create` and first backup target created will be the default backup target.
Can we create secrets on the UI for better UX?

2023-09-07 15:09 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +kind: BackupTarget
Can we add `labels` in BackupTarget spec? Then, users can add some custom information.

2023-09-07 15:12 UTC, derekbit commented on enhancements/20230828-multiple-backup-stores-support.md
> +status:
Can we introduce `status.conditions` indicating the status of the backup targets such as `connection status`?
For example, node resources' conditions are
```
    conditions:
    - lastProbeTime: ""
      lastTransitionTime: "2023-09-06T15:40:50Z"
      message: Node rancher70-worker1 is ready
      reason: ""
      status: "True"
      type: Ready
    - lastProbeTime: ""
      lastTransitionTime: "2023-09-06T15:40:50Z"
      message: ""
      reason: ""
      status: "True"
      type: Schedulable
    - lastProbeTime: ""
      lastTransitionTime: "2023-09-06T15:40:50Z"
      message: ""
      reason: ""
      status: "True"
      type: MountPropagation
``

2023-09-08 02:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +## Proposal
The backup volume CR object name will be `volume name + backup target name as a postfix concatenated`, so we add fields `backupTargetName`, `backupTargetURL` and `volumeName` to tell which backup volume is belong to which volume in the cluster and which remote backup target.

2023-09-08 02:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +kind: BackupTarget
Modified to add labels in BackupTarget spec. Thanks

2023-09-08 02:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +status:
We have had the `status.conditions` in `BackupTargetStatus` of BackupTarget CRD.

2023-09-08 02:01 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +1. Modify the Backup CRD `backups.longhorn.io` to add new fields `BackupTargetURL` in `Spec` and `BackupTargetName` in `Status`.
Yes, both added when creating Backup and BackupVolume CR objects. Thanks

2023-10-17 18:54 UTC, PhanLe1010 commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetURL: the backup target URL. (string)
I am wondering how do we handle the case user change the backup target's URL to a new URL. How do we handle the situation that the backup.Spec.backupTargetURL still pointing to old URL?

2023-10-18 01:35 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetURL: the backup target URL. (string)
It would be like the old way we handle the backup target URL changed, the old backups (CR objects) that do not exist on the new remote backup target would be removed from the cluster.

2023-10-18 02:00 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +8. User can create a new backup target on the page `Backup Target` by clicking the button `Create` and first backup target created will be the default backup target. User have to fill out the necessa
>Is it legal to create another target with a different name but exactly the same URL and credentials?

I believe that it is not legal to create another target with a different name but exactly the same URL and credentials even though it might work well on the data engine side, it might be confused on the control plane side for handling backup volume and its backups on the same URL path.

>Is it legal to create another target with a different name but exactly the same URL host+path (although perhaps different mount options or other query tags)?

If it had exactly the same URL host+path w/wo different mount options, it is not legal as below.

@james-munson Thanks a lot, it is what I did not consider and handle.

2023-10-18 02:11 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +9. User can modify a backup target information by clicking the button `Edit`.
>Is it legal to modify the name? (probably not, since existing backups have that name as a reference).

Yeah, the name should not be modified.

>Is it legal to modify the URL, keeping the same name?

It is legal as what we are doing now, we could modify the `SettingNameBackupTarget` `backup-target` and old backups would be removed then pull new backups on the new URL backup target.

>Is it legal to modify the URL to be the same as another existing target?

No, I believe it is not legal now for different backup targets with the same URL as mentioned in https://github.com/longhorn/longhorn/pull/6630#discussion_r1363013849.

2023-11-15 08:40 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +    backupTargetURL: the backup target URL. (string)
Add a description of this behavior of the backup target controller.

2023-11-15 08:41 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +8. User can create a new backup target on the page `Backup Target` by clicking the button `Create` and first backup target created will be the default backup target. User have to fill out the necessa
Added a description of this discussion.

2023-11-15 08:41 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +9. User can modify a backup target information by clicking the button `Edit`.
Added a description of this discussion.

2023-12-05 01:10 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +1. Modify the Backup CRD `backups.longhorn.io` to add new fields `BackupTargetURL` in `Spec` and `BackupTargetName` in `Status`. And add a label LonghornLabelBackupTarget `backup-target` for resource
Yes, you are right. `BackupTargetName` should be in `Spec`.
Modified. Thanks.

2023-12-05 01:10 UTC, mantissahz commented on enhancements/20230828-multiple-backup-stores-support.md
> +2. Modify the Backup Volume CRD `backupvolumes.longhorn.io` to add new fields `BackupTargetURL` and `VolumeName` in `Spec` and `BackupTargetName` in `Status`. And add a label LonghornLabelBackupTarge
Modified. Thanks.

2023-12-07 00:37 UTC, james-munson submitted a review, later dismissed

2024-05-20 09:07 UTC, innobead requested changes
There are some comments needed to clarify and resolve first.

2024-05-20 09:07 UTC, innobead commented on enhancements/20240520-multiple-backup-stores-support.md
> +  labels: {}
What's purpose of `labels`?

2024-05-20 09:07 UTC, innobead commented on enhancements/20240520-multiple-backup-stores-support.md
> +After users click the button `Create Backup` on the `Volume Details` page, they can choose multiple backup targets by checkboxes to create backups on backup targets.
Does this mean multiple backups at the same time? Or we should only support backup store tiering only? Still, one time one backup for each volume but can be to different backup stores.

P.S. I am concerned about the performance and stability. 

Or. if this can be managed by our concurrent backup setting, then it's fine but needs to be noticeable for users.

2024-05-20 09:07 UTC, innobead commented on enhancements/20240520-multiple-backup-stores-support.md
> +    backupTargetURL: the backup target URL. (string)
Why need target? target name is able to reference the backup url instead?

2024-05-20 09:07 UTC, innobead commented on enhancements/20240520-multiple-backup-stores-support.md
> +      backup-target: the backup target name (string)
For labels, please follow the label convention which should start longhorn prefix or something similar.

2024-05-20 09:07 UTC, innobead commented on enhancements/20240520-multiple-backup-stores-support.md
> +  readOnly: it is able to create a backup on this remote backup target or not. (boolean)
Why we need `readOnly`? which use case?

2024-05-20 11:55 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +Users can choose backup stores to that they want to back up volumes.
Yes, the default one.
Updated as item 5 in `Proposal`.

2024-05-20 11:59 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +     - backup target controller needs to synchronize the backups information from the remote backup target and create Backup CR objects and BackupVolume CR objects in the cluster when the backup targ
The backup volume CR object name will be volume name + backup target name as a postfix concatenated, so we add fields backupTargetName, backupTargetURL and volumeName to tell which backup volume is belong to which volume in the cluster and which remote backup target.
Ex.: volumes `pvc-9bad2abe-8a13-466d-8373-cb35a813e6f6-nfs-001` = `volumeName` + `BackupTargetName`

2024-05-20 12:01 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +2. Introduce new fields `Labels` in `Spec` and `Default` and `ReadOnly` in `Status` of BackupTarget CRD.
Removed `Labels` first as mentioned in https://github.com/longhorn/longhorn/pull/6630#discussion_r1318757875.
Updated to add more descriptions for the new fields.

2024-05-20 12:04 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +3. Introduce new fields `BackupTargetURL` and `BackupTargetName` in `Spec` of both BackupVolume, Backup and BackupBackingImage CRDs to keep backup target information.
Added more descriptions about the new fields below the statement.
`BackupTargetURL` is used to identify the remote backup target for synchronizing the backup volumes and backups because users might modify the URL of a backup target.

2024-05-20 12:05 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +User need to create/modify backup targets on the page `Settings/Backup Target` or by the manifest. After backup targets are created and synchronized, users can start to create a backup on these remot
Modified the statement. Yes, what I meant is like `Setting/Backing Image` on the UI.

2024-05-20 12:07 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +7. The page `Backup Target` would show backup target name, backup target url, secret name for this backup target (credential), poll interval, default and availability status.
Removed the parts of the page `Backup Target Credential`.
Updated all `backup store` to `backup target`.

2024-05-20 12:07 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +  labels: {}
Removed the `labels` used for users' customization.

2024-05-20 12:15 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +After users click the button `Create Backup` on the `Volume Details` page, they can choose multiple backup targets by checkboxes to create backups on backup targets.
It should still be managed by our concurrent backup setting.

2024-05-20 12:21 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +    backupTargetURL: the backup target URL. (string)
It is necessary when creating a backup to know which backup target is chosen or it will become the default backup target name by the mutator.

The backup URL in `Status` is set when the backup is completed.

2024-05-20 12:22 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +      backup-target: the backup target name (string)
Modified to `longhorn.io/backup-target`.

2024-05-20 12:31 UTC, mantissahz commented on enhancements/20240520-multiple-backup-stores-support.md
> +  readOnly: it is able to create a backup on this remote backup target or not. (boolean)
Added the use case. @james-munson recommended it in https://github.com/longhorn/longhorn/pull/6630#discussion_r1316370624.
Users can only read data from the backup target and can not store the data on the backup target.

2024-06-07 07:36 UTC, a110605 commented on enhancements/20240520-multiple-backup-targets-support.md
> +After users click the button `Create Backup` on the `Volume Details` page, they can choose multiple backup targets by checkboxes to create backups on backup targets.
Prefer giving dropdown for user to select ONE of backup targets to do volume backup.

2024-06-11 02:45 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +After users click the button `Create Backup` on the `Volume Details` page, they can choose multiple backup targets by checkboxes to create backups on backup targets.
Modified. Thanks

2024-06-12 09:54 UTC, a110605 commented on enhancements/20240520-multiple-backup-targets-support.md
> +- Modify the API `BackupBackingImageCreate`, `BackupBackingImageGet` and `BackupBackingImageList`:
We may consider modify `/v1/settings` API to rename 
- Backup Target -> Default Backup Target 
- Backup Target Credential Secret -> Default Backup Target Credential Secret

Since we won't remove those settings in setting page, right ?

2024-06-12 10:41 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +- Modify the API `BackupBackingImageCreate`, `BackupBackingImageGet` and `BackupBackingImageList`:
The settings `backup-target`(Backup Target), `backup-target-credential-secret`(Backup Targtet Credential Secret), and `backupstore-poll-interval`(Backupstore Pull Interval) will be removed from the settings. And they will not be shown on the Settings page.

2024-06-12 22:11 UTC, james-munson commented on enhancements/20240520-multiple-backup-targets-support.md
> +
Old and obsolete backup-related settings will be deleted during upgrade?

2024-06-13 01:42 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +
Yes, `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval` will be removed from the global settings.
The original `default` backup target will be preserved.

2024-06-13 03:36 UTC, a110605 commented on enhancements/20240520-multiple-backup-targets-support.md
> +- Modify the API `BackupBackingImageCreate`, `BackupBackingImageGet` and `BackupBackingImageList`:
yeah, I saw them removed in setting page.

2024-06-14 05:19 UTC, a110605 commented on enhancements/20240520-multiple-backup-targets-support.md
> +    | Update | backupTargetURL, credentialSecret string, pollInterval time.Duration, default, readOnly boolean | err error | Update the backup targets information | **PUT** `/v1/backuptargets/{backup
The real implementation doesn't use PUT method. Instead use POST

```
/v1/backuptargets/${backupTargetName}?action=backupTargetUpdate
```

2024-06-17 08:30 UTC, a110605 commented on enhancements/20240520-multiple-backup-targets-support.md
> +      BackupTargetIRL  string `json:"backupTargetURL"`
typo `BackupTargetIRL`

2024-06-19 09:33 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +      BackupTargetIRL  string `json:"backupTargetURL"`
Removed. Thanks

2024-06-22 04:31 UTC, shuo-wu commented on enhancements/20240520-multiple-backup-targets-support.md
> +3. Modify backup volume controller to tell which backup volume belongs to which backup target and synchronize the backups of the backup volume from remote backup target.
One important issue you haven't considered is that, in each reconciliation, which remote backup target the BackupVolume needs to sync up with. 
Changing `BackupVolume.Spec.BackupTargetNames []string` to something like `BackupVolume.Spec.BackupTargetSyncRequestedTime map[string]metav1.Time` may help.

2024-06-24 01:06 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +     1. The first backup target created will become the default backup target.
Yes, and now the backup target controller will pick the first it gets to be the default one.

2024-06-24 01:12 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +3. Modify backup volume controller to tell which backup volume belongs to which backup target and synchronize the backups of the backup volume from remote backup target.
Yes, this would be more clear.
What I considered is to use `BackupVolume.Spec.BackupTargetNames []string` and `orginal SyncRequestedTime metav1.Time` to trigger the synchronization.
But yes, what you suggested is a better way.

2024-06-24 01:17 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +     3. It is not allowed to delete or disable a default backup target directly.
I would agree that we don't need a default backup target.
And all kinds of backup operations should start with a valid backup target.

2024-06-24 01:45 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +   - Remove a backup volume or backup backing image CR object if the field `Spec.BackupTargetNames` is empty.
>Will there be a race?

It seems like it. (maybe I could do a quick test)

> I knew this field mainly decides when a BackupVolume CR can be deleted. Due to this race case, I suspect one BackupVolume CR only for one Volume is really a good idea.

Do you mean that we create a BackupVolume CR for each volume from the remote backup target like what I proposed last time?

2024-06-25 07:45 UTC, mantissahz commented on enhancements/20240520-multiple-backup-targets-support.md
> +   - Remove a backup volume or backup backing image CR object if the field `Spec.BackupTargetNames` is empty.
I think it is simpler to make one BackupVolume CR only for one backup Volume on the remote backup targets to simplify the backup target, backup volume and backup synchronization, and the DR volume sync procedure.

| Backup Target btA | Backup Target btB |
| -------- | ------- |
| URL: nfs://192.168.121.20:/opt/nfs01/ | URL: nfs://192.168.121.30:/opt/nfs02/ |
| Volume volA | Volume volA |
| Volume volB | Volume volB |

After the backup target controller pulls the backup volume information, the backup volume custom resource objects will be like:

```yaml
---
kind: BackupVolume
metadata:
  ...
  finalizers:
  - longhorn.io
  labels:
    backup-target: "btA"
    backup-volume: "volA"
  name: bv-1234-abcd-5678-efgh # bv-<Random UUID>
spec:
  syncRequestedAt: "2010-01-10T01:01:01Z"
  backupTargetName: "btA"
  backupVolumeName: "volA"
status:
  ...
  lastBackupName: backup-123456abcd
  ...
---
kind: BackupVolume
metadata:
  ...
  finalizers:
  - longhorn.io
  labels:
    backup-target: "btB"
    backup-volume: "volA"
  name: bv-5678-abcd-1234-efgh # bv-<Random UUID>
spec:
  syncRequestedAt: "2010-01-10T01:01:01Z"
  backupTargetName: "btB"
  backupVolumeName: "volA"
status:
  ...
  lastBackupName: backup-abcd123456
  ...
```

And then the backup volume controller will pull the backups with each backup volume.

```yaml
---
kind: Backup
metadata:
  ...
   finalizers:
  - longhorn.io
  labels:
    backup-volume: bv-1234-abcd-5678-efgh
  name: backup-1234567890
spec:
  ...
  backupTargetName: "btA"
  snapshotName: ""
  syncRequestedAt: null
status:
  ...
---
kind: Backup
metadata:
  ...
   finalizers:
  - longhorn.io
  labels:
    backup-volume: bv-5678-abcd-1234-efgh
   name: backup-0123456789
spec:
  ...
  backupTargetName: "btB"
  snapshotName: ""
  syncRequestedAt: null
status:
  ...
```
When listing the Backup Volume resource objects by the RESTFul API, it should only return

```json
{"volA":{"btA": {"backup volume info on btA"}, "btB": {"backup volume info on btB"}}, "volB": ...}
```

When getting the Backup resource objects of backup volume "volA", by the RESTFul API, it will send the backup target name with the requesting URL like the original one 

```bash
curl -X GET http://192.168.121.100:10000/v1/backupvolumes/volA?action=BackupGet -d {"backupTagetName": "btA"}
```
and it will return the `backup-1234567890` information.

For creating a DR volume, it still creates the volume by setting the field `fromBackup` as 

```yaml
fromBackup: nfs://192.168.121.20:/opt/nfs01/?backup=backup-1234567890&volume=volA
```

We can get the backup information by parsing the field `fromBackup` and then we can get the backup target and backup volume information from the backup information.
The volume controller can update the `Status.LastBackup` of the DR volume by these backup related information to trigger the restoration.

cc @longhorn/dev

2024-09-12 21:42 UTC, james-munson requested changes

2024-09-12 21:42 UTC, james-munson commented on enhancements/20240910-multiple-backup-targets-support.md
> +4. Introduce new fields `BackupTargetName` and `VolumeName` in `Spec` to keep information of the remote backup target and volume name.
In `Spec` of which CR?

2024-09-12 21:42 UTC, james-munson commented on enhancements/20240910-multiple-backup-targets-support.md
> +5. Introduce new fields `BackupTargetName` and `BackingImage` in `Spec` to keep information of the remote backup target and backing image name.
In `Spec` of which CR?

2024-09-13 00:23 UTC, mantissahz commented on enhancements/20240910-multiple-backup-targets-support.md
> +4. Introduce new fields `BackupTargetName` and `VolumeName` in `Spec` to keep information of the remote backup target and volume name.
`BackupVolume` CRD.
Added. Thanks.

2024-09-13 00:23 UTC, mantissahz commented on enhancements/20240910-multiple-backup-targets-support.md
> +5. Introduce new fields `BackupTargetName` and `BackingImage` in `Spec` to keep information of the remote backup target and backing image name.
`BackupBackingImage` CRD.
Added. Thanks.

2024-09-26 04:54 UTC, mantissahz commented
Updated the LEP:
- The `default` backup target will not be removed, and it will always be the default one.
- The settings `backup-target`, `backup-target-credential-secret`, `backupstore-poll-interval` will not be removed, and these settings still control the backup target URL, poll interval and secret name of the `default` backup target. 
- A volume can only be backed up to a backup target at the same time.

2024-10-17 03:41 UTC, mantissahz commented
Hi team @longhorn/dev, 

The LEP is ready for review (updated parts as above). Please review it if you are available. Thanks.

cc @innobead, @derekbit, @james-munson, @shuo-wu, @c3y1huang, @ChanYiLin.

2024-11-04 05:53 UTC, innobead requested changes
The idea should be straightforward; however, I still have some questions, possibly because the LEP isn't up-to-date.

cc: @derekbit, @ChanYiLin, @shuo-wu. Please help review this, as @mantissahz might be wrapping it up. Let’s aim to finalize this soon and include it in version 1.8.0.

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
Why do we need `readonly`? is it part of the multiple backup target story?

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +  readOnly: false
What does `readOnly` in status mean? I thought it's in the spec if we want to have it.

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +3. There will be an empty default backup target created by Longhorn.
There seems no user story about setting the default backup target mentioned here. Users should be able to set the default backup target from the available backup targets.

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Create backups to store the snapshot by the manifest as below:
```suggestion
2. Create a backup referring to the snapshot by the manifest as below:
```

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +3. If the field `spec.backupTargetName` is empty, it will be replaced by the field `spec.backupTargetName` in the volume of the snapshot.
It may be helpful to clarify how `backupTargetname` is prioritized. For instance, a backup takes precedence over a volume, while the lowest priority is assigned to the backup target set globally.

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +4. If the `spec.backupTargetName` field will be assigned, it should be the same to the `spec.backupTargetName` field in the volume of the snapshot.
If a snapshot’s `backupTargetName` should always match its volume, why do we need this specific field in Backup CRD instead of using the value directly from the volume?

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Disaster Recovery Volume From A Remote Backup Target By UI
Is DR available for multiple backup targets? or just for the default global backup target?

2024-11-04 05:53 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
Suggest adding test coverage for DR and updating the global backup target.

2024-11-05 04:03 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
Added the user story. @james-munson recommended it in https://github.com/longhorn/longhorn/pull/6630#discussion_r1316370624.
Users can only read data from the backup target and can not store the data on the backup target for certain reasons (such as the remote backup target server is running out of storage).

2024-11-05 04:04 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +  readOnly: false
Yes, it is sufficient in the `spec`, and removed it from the `status`. Thanks.

2024-11-05 04:07 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +3. There will be an empty default backup target created by Longhorn.
Added the user story for the default backup target.
The LEP does not allow users to set the default backup target, and the default backup target will always be the backup target `default` that Longhorn will create.

2024-11-05 04:08 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Create backups to store the snapshot by the manifest as below:
Modified. Thanks.

2024-11-05 04:09 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +3. If the field `spec.backupTargetName` is empty, it will be replaced by the field `spec.backupTargetName` in the volume of the snapshot.
The field. `Spec.BackupTargetName` of the `Backup` is removed.
Added the description for the priority in the section `Default Backup Target` of the user stories.

2024-11-05 04:11 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +4. If the `spec.backupTargetName` field will be assigned, it should be the same to the `spec.backupTargetName` field in the volume of the snapshot.
Yes, you are right. I removed the filed `Spec.BackupTargetName` of the `Backup` and moved it to the `Status` to specify the backup target of the `Backup`. Thanks

2024-11-05 04:12 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Disaster Recovery Volume From A Remote Backup Target By UI
It should be available for multiple backup targets, do you think we should limit it to the default global backup target?

2024-11-05 04:13 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
Added test cases for updating the default global backup tarter and creating a DR volume. Thanks.

2024-11-05 04:33 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
This might be over-consideration.  We can add this to No-Goals first.

2024-11-05 04:34 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Disaster Recovery Volume From A Remote Backup Target By UI
No. If it's feasible, it's good to have. We don't need to do any differentiation here.

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +- A backup can be restored from its remote backup targets to be a new volume.
Single backup target for each volume

```suggestion
- A backup can be restored from its remote backup target to be a new volume.
```

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
Let's remove `ReadOnly` which is out of scope of the feature.
```suggestion
2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
```

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +    - Different backup targets might have volumes with the same names.
Only show one backupvolume?

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +When users attempt to restore existing backups from a remote backup target that is read-only or cannot create a new backup for certain reasons (such as insufficient storage), they can set the `Spec.R
Suggest removing the read-only feature. It is out of scope.

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +1. There will be an empty default backup target created by Longhorn and users should activate the default backup target before creating a new backup target.
What does `activate` mean?

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. Users can set the backup target `Spec.ReadOnly` true and then users can not create any backups on it.
Suggest removing it.

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
Will you introduce `backupTarget.status.conditions` to help understand the status and troubleshoot?

2024-11-05 06:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
Another question: 
If volume `abc`''s backups are both in `default`, `backupTarget A` and `backupTarget B`, what will Longhorn show in the two cases

- `volume.spec.backupTargetName` is `""`
- `volume.spec.backupTargetName` is `"default"`
- `volume.spec.backupTargetName` is `"backupTarget A"`

2024-11-05 07:45 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +- A backup can be restored from its remote backup targets to be a new volume.
Modified. Thanks.

2024-11-05 07:45 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce new fields `ReadOnly` in `Spec` of `BackupTarget` CRD.
Removed. Thanks

2024-11-05 07:51 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +    - Different backup targets might have volumes with the same names.
Removed the confusing statement.

>Only show one backupvolume?

No. It will be one-to-one

- volume A on backup target A
```yaml
 metadata:
   name: the backup volume name. (random string)
 spec:
   backupTargetName: backupTargetA
   volumeName: volumeA
   ...
```
- volume A on backup target B
```yaml
 metadata:
   name: the backup volume name. (random string)
 spec:
   backupTargetName: backupTargetB
   volumeName: volumeA
   ...
```

2024-11-05 07:51 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +When users attempt to restore existing backups from a remote backup target that is read-only or cannot create a new backup for certain reasons (such as insufficient storage), they can set the `Spec.R
Removed. Thanks

2024-11-05 07:51 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. Users can set the backup target `Spec.ReadOnly` true and then users can not create any backups on it.
Removed. Thanks

2024-11-05 08:04 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
>Will you introduce backupTarget.status.conditions to help understand the status and troubleshoot?

Added a section in user stories for backup target conditions.

>Another question:
If volume abc''s backups are both in default, backupTarget A and backupTarget B, what will Longhorn show in the two cases

Three backup CR objects will be created corresponding to the backup targets

- backup target "default"
```yaml
metadata:
  labels:
    longhorn.io/backup-target: defaultBackupTagetName
  name: the backup name. (random string)
status:
  backupTarget: defaultBackupTagetName
  volumeName: abc
  ...
```
- backup target A
```yaml
metadata:
  labels:
    longhorn.io/backup-target: backupTagetAName
  name: the backup name. (random string)
status:
  backupTarget: backupTagetAName
  volumeName: abc
  ...
```
- backup target B
```yaml
metadata:
  labels:
    longhorn.io/backup-target: backupTagetBName
  name: the backup name. (random string)
status:
  backupTarget: backupTagetBName
  volumeName: abc
  ...
```

The differences are the `Status.BackupTarget` field and `longhorn.io/backup-target` label.

>- volume.spec.backupTargetName is ""

It will be not be empty, and it would be populated with the default backup target name by the volume mutator when creating.

>- volume.spec.backupTargetName is "default"
>- volume.spec.backupTargetName is "backupTarget A"

The `volume.spec.backupTargetName` is irrelated to the backup after the backup is created.

2024-11-05 08:05 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. Users can set the backup target `Spec.ReadOnly` true and then users can not create any backups on it.
Removed. Thanks

2024-11-05 08:06 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +1. There will be an empty default backup target created by Longhorn and users should activate the default backup target before creating a new backup target.
It means `set up` and the backup target is available.
Modified it to be `set up`. Thanks.

2024-11-05 08:14 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
`defaultBackupTagetName` => what's this? `default`?

> It will be not be empty, and it would be populated with the default backup target name by the volume mutator when creating.


How to handle the existing backups?

2024-11-05 08:30 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
>defaultBackupTagetName => what's this? `default`?

Yes, the default backup target name is `default`.

>How to handle the existing backups?

In the section `Upgrade strategy`, it will fill in the labels `longhorn.io/backup-target` and field `BackupTarget` in `Status` for existing Backup CR objects with  the `default` backup target name.

2024-11-05 09:26 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
One question: why do we need `status.BackupTarget`?

2024-11-05 11:26 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
The field `status.BackupTarget` is used to point out this backup is stored on (synced from) this backup target.

2024-11-05 13:24 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
I see. Why not replace ` longhorn.io/backup-target` with `spec.BackupTarget`

2024-11-06 00:29 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
>I see. Why not replace  longhorn.io/backup-target with spec.BackupTarget

Yes, we could use the label `longhorn.io/backup-target` instead of the field `Status.BackupTarget`, but users can easily modify the label `longhorn.io/backup-target` and it will be complex when we get the backup target name for the information shown on CLI columns or returned by RESTFul APIs.

2024-11-06 00:59 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
No, I mean `Spec.BackupTarget`. What's the purpose of the label? Why not use spec field?

2024-11-06 01:18 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
>No, I mean `Spec.BackupTarget`.

Not sure which filed you mentioned, do you mean the field `Volume.Spec.BackupTargetName` or `Backup.Spec.BackupTarget`?

If you meant the field `backup.Spec.BackupTarget`, I removed it from the `Spec` in the LEP and moved it to the field `Backup.Status.BackupTarget`.

>What's the purpose of the label? Why not use spec field?

The label is used to get the backups of the backup target and volume quickly.

2024-11-06 01:45 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +
> Not sure which filed you mentioned, do you mean the field Volume.Spec.BackupTargetName or Backup.Spec.BackupTarget?

I mean why not remove the label and use Spec.BackupTarget instead.

> The label is used to get the backups of the backup target and volume quickly.

OK. Got it. 

Do we really need `Status.BackupTargetName`? We already have the label. Isn't it?

2024-11-06 02:34 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +
Added some descriptions for the field `Status.BackupTarget`. Thanks.

2024-11-11 00:30 UTC, derekbit commented
cc @c3y1huang Can you help review again? Thank you.

2024-11-15 04:56 UTC, c3y1huang requested changes

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Default Backup Target
I believe we are removing the backup target-related settings on the Setting page, right? Could you include this info in the LEP?

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +4. Modify the Volume CRD `volumes.longhorn.io` to add a new field `BackupTargetName` in `Spec` for a default backup target.
Can the volume's `BackupTargetName` be updated? If so, how will Longhorn handle it?

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Backup To Remote Backup Targets By UI
How will the Backup page display backups from different targets?

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
We should add test coverage for the backup and restore of volumes in the system backup and restore process.

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +The `default` backup target will be created by Longhorn after installing Longhorn, and it will be the default backup target when creating a volume and a system backup. Users need to set up the `defau
Consider clarify on what happens if a user attempts to delete the `default` backup target.

2024-11-15 04:56 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +When creating a volume with an empty `BackupTagetName` filed, this filed will be populated with the default backup target name `default`.
```suggestion
When creating a volume with an empty `BackupTargetName` field, this field will be populated with the default backup target name `default`.
```

2024-11-25 02:57 UTC, derekbit commented
@mantissahz Please address @c3y1huang's comments. Thank you.

2024-11-26 01:18 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Default Backup Target
No, we are not removing the backup target-related setting.
The default backup target will be able to be modified by the backup target-related settings.

2024-11-26 01:36 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +4. Modify the Volume CRD `volumes.longhorn.io` to add a new field `BackupTargetName` in `Spec` for a default backup target.
Yes, it could be updated. If it is updated by another backup target name, the next backups to be created will be stored on the new backup target.

2024-11-26 01:50 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Backup To Remote Backup Targets By UI
Added a description for displaying the different backup targets on the `Backup` page.

```txt
On the `Backup` page, the backup targets are displayed first if one or more backup volumes exist. Clicking a backup target will expand or collapse the list to show the associated backup volumes.
```

2024-11-26 01:50 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
Added. Thanks.

2024-11-26 01:50 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +When creating a volume with an empty `BackupTagetName` filed, this filed will be populated with the default backup target name `default`.
Modified. Thanks

2024-11-26 01:52 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +The `default` backup target will be created by Longhorn after installing Longhorn, and it will be the default backup target when creating a volume and a system backup. Users need to set up the `defau
Added a description prohibiting the deletion of the `default` backup target.

2024-12-03 07:41 UTC, ChanYiLin commented on enhancements/20240926-multiple-backup-targets-support.md
> +- Backups can be synchronized from different remote backup targets.
Are we addressing this goal in this LEP?
I don't see the implementation design for this one in the following docs

2024-12-03 07:44 UTC, ChanYiLin commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Modify the Backup Volume CRD `backupvolumes.longhorn.io` to add new fields `BackupTargetName` and `VolumeName` in `Spec`, and add labels `LonghornLabelBackupTarget` and `LonghornLabelBackupVolume`
Does that means we will have >= 1 BackupVolumes for 1 Volume ?
But I thought the BackupVolume's name is the same as the Volume without any random string or UUID
So how do we create multiple BackupVolume CR with the same name in the cluster?

2024-12-03 07:47 UTC, ChanYiLin commented on enhancements/20240926-multiple-backup-targets-support.md
> +3. Modify the Backup Backing Image CRD `backupbackingimages.longhorn.io` to add new fields `BackingImage` and `BackupTargetName` in `Spec`, and add labels `LonghornLabelBackupTarget = "backup-target"
Same as the Volume, since the BackupBackingImage is using the same name as the BackingImage
If users creates two BackupBackingImage from the same BackingImage with different backup targets
How to avoid the name conflict?

2024-12-03 07:49 UTC, ChanYiLin reviewed
Maybe I just misunderstood something, but I have some questions.

2024-12-03 07:55 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +- Backups can be synchronized from different remote backup targets.
When a new backup target is created and available, the backups on this remote backup target will be synchronized immediately by the backup target, backup volume, and backup controllers.

2024-12-03 07:59 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Modify the Backup Volume CRD `backupvolumes.longhorn.io` to add new fields `BackupTargetName` and `VolumeName` in `Spec`, and add labels `LonghornLabelBackupTarget` and `LonghornLabelBackupVolume`
>Does that means we will have >= 1 BackupVolumes for 1 Volume ?

Yes, identifying the backup volume depends on the combination of the backup target name and volume name.

The backup volume pulled from the remote backup target will have a [random backup volume name](https://github.com/longhorn/longhorn/pull/6630/files#diff-f66bf27d07bfda116e6936671071bf1ef0ce469653a32bdb0c1c3571f8a6c1b5R273).

2024-12-03 08:08 UTC, ChanYiLin commented on enhancements/20240926-multiple-backup-targets-support.md
> +- Backups can be synchronized from different remote backup targets.
Got it.

2024-12-03 08:09 UTC, ChanYiLin commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Modify the Backup Volume CRD `backupvolumes.longhorn.io` to add new fields `BackupTargetName` and `VolumeName` in `Spec`, and add labels `LonghornLabelBackupTarget` and `LonghornLabelBackupVolume`
Oh I see the implementation in the code.
Got it, thanks

2024-12-03 08:09 UTC, ChanYiLin approved these changes

2024-12-05 02:48 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +The current Longhorn only support a single backup target for all volumes. The feature aims to provide multiple backup targets.
```suggestion
The current Longhorn only supports a single backup target for all volumes. The feature aims to provide multiple backup targets.
```

2024-12-05 02:48 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +    - Different backup targets might have volumes with the same names.
This is important. Please add the information to the LEP. Thank you.

2024-12-06 01:51 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +The current Longhorn only support a single backup target for all volumes. The feature aims to provide multiple backup targets.
Modified. Thanks

2024-12-06 01:52 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +    - Different backup targets might have volumes with the same names.
Added it back. Thanks

2024-12-14 00:22 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +### User Stories
Add some cases
- Case1
	- Create a storageClass without backupTargetName
	- Create a volume that volume.spec.backupTargetName will be assigned
- Case2
	- Create a storageClass with backupTargetName
	- Create a volume that volume.spec.backupTargetName will be assigned
- Case3
	- Delete backupTarget when DR volumes are existing

2024-12-14 00:26 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Custom Resource Definitions
Need to add the ownerReference Design

2024-12-14 00:52 UTC, derekbit commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Implementation Overview
Add
1. How to handle backupTarget CR deletion
  - backup CRs handling
  - backupVolume CRs handling
  - volume CRs handling
  - DR volumes handling

2. How to handle the the backupTarget CRs while uninstalling Longhorn system

2024-12-16 04:54 UTC, innobead requested changes
In general, the design is quite straigthforward. 

However, I still have some feedback and some points need to be clarified and explained briefly well.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +### User Stories
>Delete backupTarget when DR volumes are existing

Is this a valid case? I thought DR volumes only from the default backup target which should not be deleted.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +Users need to create/modify backup targets on the page `Setting/Backup Target` as `Setting/Backing Image` via the Longhorn UI or by the manifest. After backup targets are created and synchronized, us
When deleting a backup target which is not default, suggest considering the following checks. 
- For existing volumes (runtime), if it's referenced by volumes, they can't be deleted until the volumes don't use it.
- If it has been used by existing storage classes, a warning notification (log, event) should be created. Also, users should be warned when deleting from UI. 
- When creating new volumes (creation time), as the backup target is deleted, so the volumes should not be created and the corresponding error education should be clear for users.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. Users can delete a backup target by clicking the button `Delete`.
A webhook validation is needed to check the conditions that prevent deletion. This is also applied to creation/modification cases.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +The condition `BackupTargetConditionTypeUnavailable` will be set to true if the backup target URL is empty or if retrieving backup information from the remote backup target fails due to issues such a
Suggest adding more reasoning to the condition message, so users can better understand the cause of the unavailability.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Disaster Recovery Volume From A Remote Backup Target By UI
If we create DR volumes for volumes that are using multiple backup targets, how does DR work in the remote cluster?

I assume the remote cluster uses only the default backup target for DR volumes. In this case, will the above DR volumes incrementally restore to the remote backup target? Or will users need to configure all backup targets in the remote cluster to ensure all DR volumes are incrementally restored?

Suggest explaining this clear.

2024-12-16 04:54 UTC, innobead commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
Miss backup image test cases if you want to add this functionality.

2024-12-16 10:52 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Test plan
Added. Thanks.

2024-12-16 10:54 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +- Snapshots of a volume can not be backed up to different remote backup targets concurrently.
Yes, as you mentioned. Modified. Thanks.

2024-12-16 10:56 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +### User Stories
>Add some cases
>- Case1
>-- Create a storageClass without backupTargetName
>-- Create a volume that volume.spec.backupTargetName will be assigned
>- Case2
>-- Create a storageClass with backupTargetName
>-- Create a volume that volume.spec.backupTargetName will be assigned
>- Case3
>-- Delete backupTarget when DR volumes are existing

@derekbit Added. Thanks.

>Is this a valid case? I thought DR volumes only from the default backup target which should not be deleted.

Yes, we can create DR volumes from all backup targets.

2024-12-16 10:57 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Custom Resource Definitions
Added Thanks.

2024-12-16 10:57 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +### Implementation Overview
Added. Thanks.

2024-12-16 10:57 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Introduce a new field `BackupTarget` in `Status` of the `Backup` CRD to keep backup target information.
Modified. Thanks and I will remember next time.

2024-12-16 10:58 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +4. Introduce new fields `BackupTargetName` and `BackingImage` in `Spec` of `BackupBackingImage` CRD to keep information of the remote backup target and backing image name.
>If the implementation is straightforward, feel free to proceed, but it's nice to have.

Yes, it is implemented.

2024-12-16 10:58 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. The system backup will be handled by the default backup target.
Modified. Thanks

2024-12-16 10:59 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Default Backup Target
Modified. Thanks.

>Additionally, DR volumes will only function as expected when using the default backup target.

We can use all backup targets created in the cluster.

2024-12-16 11:00 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +#### Create A Disaster Recovery Volume From A Remote Backup Target By UI
Added some explanations. Thanks.

2024-12-16 11:09 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +Users need to create/modify backup targets on the page `Setting/Backup Target` as `Setting/Backing Image` via the Longhorn UI or by the manifest. After backup targets are created and synchronized, us
>For existing volumes (runtime), if it's referenced by volumes, they can't be deleted until the volumes don't use it.

We left the update operation (the filed `Volume.Spec.BackupTargetName`) to users if they try to delete the backup target referenced by volumes.

>If it has been used by existing storage classes, a warning notification (log, event) should be created. Also, users should be warned when deleting from UI.

Yes, a warning/event will be helpful. Added in the `Create/Delete Backup Target` section.

>When creating new volumes (creation time), as the backup target is deleted, so the volumes should not be created and the corresponding error education should be clear for users.

Now the implementation only check if the backup target exists, and yes, we should check if the backup target is deleting.

2024-12-16 11:18 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +The condition `BackupTargetConditionTypeUnavailable` will be set to true if the backup target URL is empty or if retrieving backup information from the remote backup target fails due to issues such a
Added some error reasons we encountered.

2024-12-16 11:20 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +6. Users can delete a backup target by clicking the button `Delete`.
It only prevents deleting the backup target when DR volumes exist now

2024-12-17 01:36 UTC, c3y1huang commented on enhancements/20240926-multiple-backup-targets-support.md
> +    BackupTargetName int64 `json:"backupTargetName"`
Should we handle this field during the upgrade for existing volumes? We might have overlooked this scenario in the implementation.

2024-12-17 01:57 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +    BackupTargetName int64 `json:"backupTargetName"`
We will handle it and we have the implementation to handle this scenario. Thanks

2024-12-24 09:37 UTC, roger-ryao commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Existing backups on the extra backup target B can be synchronized back to the cluster.
```suggestion
2. Existing backups on the extra backup target A can be synchronized back to the cluster.
```
I think they meant to say `Default backup` and `backup target-a` here.

2024-12-30 10:22 UTC, mantissahz commented on enhancements/20240926-multiple-backup-targets-support.md
> +2. Existing backups on the extra backup target B can be synchronized back to the cluster.
Modified. Thanks.

2025-01-13 03:53 UTC, derekbit approved these changes

2025-01-13 03:54 UTC, merged