doc(chart): add table of helm values
longhorn/longhorn pull request #6639
Opened 2023-09-06 07:43 UTC by ChanYiLin

ref: [longhorn/longhorn#5455](https://github.com/longhorn/longhorn/issues/5455)

- use `helm-doc` to generate table of values in readme
- for `default settings`, modify the description in `questions.yaml` of each setting to one sentence.
    - make the descriptions in `values.yaml`  same as those  in `questinos.yaml`
    - for details, user can check the website

2023-09-07 03:53 UTC, ChanYiLin commented
conflicts fixed

2023-09-07 19:28 UTC, ejweber submitted a review, later dismissed
LGTM in general.

I brought up some minor formatting NITs that it might be nice to resolve while making large changes to `values.yaml`.

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
> +    # -- system default registry
Nit: start this with a capital letter.

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
> +  # -- `imagePullPolicy` to apply to all containers
Nit: May want to make the difference between this and systemManagedPodsImagePullPolicy clear.

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
> +    # If the backing image does not exists, Longhorn will use this field to create a backing image. Otherwise, Longhorn will use it to verify the selected backing image.
Nit: This appears to be the only use of `#` (instead of `# --`) in this PR. Is it intended?

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
> +  # -- tolerations for longhorn manager
Nit: We moved away from capital letters to start comments in this section and beyond. I suggest we maintain the standard as much as possible.

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
> +  # Can replace the kubernetes.io/ingress.class annotation on v1.18+
Nit: Here (and a few lines below) is another location where we used a bare `#`.

2023-09-07 19:28 UTC, ejweber commented on chart/values.yaml
Nit: I prefer to adhere to a line length in files like this instead of letting long sentences wrap. Since we're adding a bunch of long sentence comments now, it is a good time to consider breaking them up onto separate lines.

2023-09-12 07:56 UTC, ChanYiLin commented on chart/values.yaml
> +    # -- system default registry
Fixed, thanks

2023-09-12 07:57 UTC, ChanYiLin commented on chart/values.yaml
> +  # -- `imagePullPolicy` to apply to all containers
Fixed, thanks!

2023-09-12 08:04 UTC, ChanYiLin commented on chart/values.yaml
> +    # If the backing image does not exists, Longhorn will use this field to create a backing image. Otherwise, Longhorn will use it to verify the selected backing image.
We use this tool to generate value table in readme: https://github.com/norwoodj/helm-docs
It requires adding comments on top of each value so it can retrieve those comments as descriptions.

The format requires starting with `#--` as below example
```
config:
  databasesToCreate:
    # -- Default database for storage of database metadata
    - postgres

    # -- Database for the [hashbash](https://github.com/norwoodj/hashbash-backend-go) project
    - hashbash
```

The second line doesn't have `--` because the line would be too long if I put it in the first line. It will be concatenated to the first line in the same description.

2023-09-12 08:04 UTC, ChanYiLin commented on chart/values.yaml
> +  # -- tolerations for longhorn manager
Fixed, thanks!

2023-09-12 08:04 UTC, ChanYiLin commented on chart/values.yaml
> +  # Can replace the kubernetes.io/ingress.class annotation on v1.18+
Explained above, thanks!

2023-09-12 08:05 UTC, ChanYiLin commented on chart/values.yaml
I agree with you, I will try to keep the comment short or break it into multiple line.

2023-09-19 13:27 UTC, innobead requested changes
In general, LGTM. Just one comment needs to resolve. 

We should make questions.yaml automatically generated as well in the future. Please help create an issue for that and add to 1.7.

2023-09-19 13:27 UTC, innobead commented on chart/values.yaml
>    tolerations: []
The same issue is as the doc PR. Just need to make the description consistent with others.

2023-09-26 03:19 UTC, ChanYiLin commented on chart/values.yaml
>    tolerations: []
Fixed.

2023-09-26 03:33 UTC, ChanYiLin commented
> In general, LGTM. Just one comment needs to resolve.
> 
> We should make questions.yaml automatically generated as well in the future. Please help create an issue for that and add to 1.7.

Issue created: https://github.com/longhorn/longhorn/issues/6788

2023-10-04 15:42 UTC, innobead approved these changes

2023-10-04 15:47 UTC, innobead approved these changes

2023-10-04 15:47 UTC, merged