Automatically evict replicas while draining LEP
longhorn/longhorn pull request #6643
Opened 2023-09-06 16:14 UTC by ejweber

#2238

2023-09-11 23:40 UTC, james-munson requested changes
A couple of questions.

2023-09-11 23:40 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- The volume controller uses `replica.status.evictionRequested == true` to influence replica scheduling/deletion
This is a repeat of above, but presumably you wanted to talk about replica.status.evictionRequested == false.

2023-09-11 23:40 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  hosting a replica, it may set `status.evictionRequested = false` on that replica.
What happens to a rebuild in progress?  Does it finish, and then we decide which replica is the best candidate to discard?  (Might not be the one we just built...)

2023-09-11 23:40 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- Verify the drain never completes.
How is it made clear to the user what the holdup is, and that it won't change without some action to make it possible?

2023-09-12 14:28 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- The volume controller uses `replica.status.evictionRequested == true` to influence replica scheduling/deletion
Yes, this is an unfortunately copy/paste error. Cleaning it up.

2023-09-12 14:33 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  hosting a replica, it may set `status.evictionRequested = false` on that replica.
We currently don't do anything if an extra replica is rebuilt during a canceled eviction. The rebuild finishes and the user simply has extra replicas until they decide to delete one. (This is something we were discussing the other day offline, as I found the behavior a bit surprising.) It may be desirable to add the auto-deletion of a replica when eviction is cancelled, but we should probably do that in another ticket, as I don't think we want auto-eviction behavior to be different than `evictionRequested` behavior in that regard.

2023-09-13 15:50 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  hosting a replica, it may set `status.evictionRequested = false` on that replica.
It would be sufficient (and helpful) to put a sentence in the LEP to that effect - that it is by design, and can be remedied manually.  (I suspect that if auto-balance is enabled, it might find the extra and conclude that it should pare the most constrained replica of the set.)
I use the LEPs as the best documentation of design decisions, so it's valuable to put this kind of thing in there.  Thanks!

2023-09-13 16:33 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- Verify the drain never completes.
Reading up on node drain, I gather that it will be considered timed out if the evictions have not completed within some budget (an hour, maybe?  I think it is built into Kubernetes.)  But the non-progressing status won't just hang forever, if I understand it.  So we don't have to debug why it is hung, but rather why it failed.

That's a good thing, but it is hard to link that in a causal way with the blocking item, because the decisions are made at totally different layers.  We can use as a guide the behavior when the pod disruption budget is violated, perhaps.  Is that more than a logging message or an Event?

At the very least, I suppose we can add a knowledge base item about "how to figure out why your eviction failed" with a direct node attachment as one possibility.  I know, I'm not being much help here.

I like the idea of adding the yellow "auto-evicting" status for a node.

2023-09-15 20:59 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  hosting a replica, it may set `status.evictionRequested = false` on that replica.
Added.

2023-10-12 16:04 UTC, ejweber commented
@james-munson has provided some helpful feedback on this already. @longhorn/dev-control-plane, can we get some other eyes on it so I can progress?

2023-10-13 04:26 UTC, shuo-wu reviewed
In general LGTM

2023-10-13 04:26 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - The drain operation is significantly slower than for other behaviors. Every replica must be rebuilt on another node
I am thinking if we can do rebuilding for the last healthy replicas on the cordon node only. I mean, we can make this the 5th option. Rebuilding is really time and resource consuming. If unnecessary, I prefer not to rebuild a new replica from zero.

2023-10-13 04:26 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +Add a `status.autoEvicting` to the `node.longhorn.io/v1beta2` custom resource. This is not a field users can/should
It seems that this field is unnecessary in the controller reconciliation either. All controllers can directly check setting  `node-drain-policy` during the eviction handling.

2023-10-13 16:06 UTC, james-munson reviewed
Clearing the request-changes flag, but I'm interested in Shuo's questions.

2023-10-13 16:06 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +Add a `status.autoEvicting` to the `node.longhorn.io/v1beta2` custom resource. This is not a field users can/should
It sure would be nice to be able to see that status directly on the node when debugging, though.  Is the concern that a possibly redundant status has the chance that it might be wrong if we hit a failure window before it is updated?

2023-10-13 16:20 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +Add a `status.autoEvicting` to the `node.longhorn.io/v1beta2` custom resource. This is not a field users can/should
I see your point. I can just move the the logic about whether auto eviction should occur to a utility function and call it wherever we would otherwise check `node.status.autoEvicting`.

A downside is if we want to show auto eviction status in the UI, we must offload the logic for deciding whether auto eviction is occurring to it too. Additionally, there will be nowhere for a user to check whether auto eviction is occurring with kubectl. (They could look at individual replica statuses for `evictionRequested`, but not the node itself.) WDYT?

2023-10-13 16:35 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - The drain operation is significantly slower than for other behaviors. Every replica must be rebuilt on another node
Yes, I think this is valuable. "Block For Eviction If Contains Last Replica" could be another behavior. We'll have to introduce some additional logic in the replica controller that doesn't currently exist. Today, it decides whether to evict a replica solely based on the `spec.evictionRequested` of its node or disk (and with my current changes, based on the `status.autoEvicting` of its node). It'll now need to selectively decide whether a replica should be evicted based on the status of the other replicas.

2023-10-13 16:36 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +Add a `status.autoEvicting` to the `node.longhorn.io/v1beta2` custom resource. This is not a field users can/should
Looks like my comment was a bit redundant with @james-munson's! We must have been responding in parallel.

2023-10-17 21:19 UTC, PhanLe1010 submitted a review, later dismissed
In general, LGTM

2023-10-17 21:19 UTC, PhanLe1010 commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  Drawbacks:
Maybe another drawback is that there will be a lot of data movement. Brand new replicas are being rebuilt on new nodes. Then possibly, the replica rebalancing feature will move them back.

2023-10-17 21:37 UTC, PhanLe1010 commented
Btw, looks like the checking for healthy/failed replicas to decide whether draining should be allowed may be vulnerable to a race condition: sometimes replica CRs were not up-to-date thus we may kill the last healthy replica because we incorrectly think that there are healthy replicas on other nodes. However, looks like I cannot think of a way to prevent this race. Maybe users have to rely on the auto-salvage feature for this case.

2023-10-20 09:10 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - The drain operation is significantly slower than for other behaviors. Every replica must be rebuilt on another node
> It'll now need to selectively decide whether a replica should be evicted based on the status of the other replicas. How do we feel about this approach? Is it an overstep of the replica controller's responsibility?

OK. I understand your concern. Yes, that would be an overstep in the current design. Then what I am thinking is, if we can add a spec field `replica.spec.evictionRequested` rather than `replica.status.autoEvicting` to control it. This new spec field is updated by the node controller. WDYT?

2023-10-23 15:43 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - The drain operation is significantly slower than for other behaviors. Every replica must be rebuilt on another node
Ok, so in general, move the logic of deciding which replicas should be evicted to the node controller without touching the logic of HOW the replicas are actually evicted. I think this works. I'll prove it today and see if there are any problems.

2023-10-24 14:13 UTC, ejweber commented
I made significant changes to the LEP, mostly based on a POC I implemented in response to @shuo-wu's comment: https://github.com/longhorn/longhorn/pull/6643#pullrequestreview-1675673151. The spirit is largely the same, but the `block-for-eviction-if-contains-last-replica` behavior required some reworking. The changes are all in the latest commit, so feel free to look just at that one for an understanding of the differences.

Highlights:

- There is a new, additional `block-for-eviction-if-contains-last-replica` behavior.
- The `replica.status.evictionRequested` field is deprecated in favor of `replica.spec.evictionRequested`.
- The logic for kicking off a replica eviction is moved to the node controller (from the replica controller).

2023-10-24 21:43 UTC, james-munson approved these changes
Still LGTM.  A couple of observations from me.

2023-10-24 21:43 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- Verify the drain never completes.
It occurs to me that if an eviction requires a full rebuild, we are capped at what we can rebuild in an hour, which is on the order of 150 GB, if I recall.  So any configuration with full-rebuild policy AND replicas larger than that is almost certain to fail, right?  Something to mention, perhaps in the docs or KB  that will accompany this setting.

2023-10-24 21:43 UTC, james-munson commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +
At some point, perhaps also in a KB or best-practices doc, we might consider ranking this on a scale of speed vs safety.  WDYT?

2023-10-25 08:44 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - `spec.evictionRequested == false` on the replica's disk, AND
For most of the evicting replicas, there is no need to unset `replica.spec.evictionRequested` since they will be cleaned up after eviction complete (IIRC).
The only exception is the eviction cancellation. I am wondering if these 2 conditions are enough for the canceling. And that's the current implementation. If a kube node is still in state `cordon`, the controller always updates the corresponding node/disk `spec.evictionRequested` to the correct state. the replica field just needs to rely on node/disk `spec.evictionRequested` without duplicatedly considering the kube node.

2023-10-25 08:44 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- The node controller sets `status.autoEvicting = true` when a node has evicting replicas because of the new drain
Is `node.status.autoEvicting = true` determined by `kubenode.status.Unschedulable == true && (policy == block-for-eviction || policy == block-for-eviction-if-contains-last-replica)`, or by if containiing evicting replicas?

2023-10-26 16:41 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- The node controller sets `status.autoEvicting = true` when a node has evicting replicas because of the new drain
In my current POC code, it is determined by "containing evicting replicas". My thinking is that we would like to transition `autoEvicting` to `false` after all replicas that require a drain are gone, even if the drain itself isn't complete (potentially for some completely unrelated reason, like some non-Longhorn-consuming pod that can't finish evicting).

2023-10-26 17:10 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - `spec.evictionRequested == false` on the replica's disk, AND
> And that's the current implementation. If a kube node is still in state cordon, the controller always updates the corresponding node/disk spec.evictionRequested to the correct state

I am not able to find this behavior. We set the Longhorn node's `Schedulable` condition based on the Kubernetes node's status, but not its `spec.evictionRequested`.

In general, I think we do not want to automatically set `spec.evictionRequested = true` on nodes or disks because this is a user-specified field, and we do not want to lose track of the fact that they set it. I am treating those user specifications separately from any auto-eviction logic, so we need to check both ` `spec.evictionRequested` fields AND the node condition to determine whether to evict replicas. 

- If the user has specified eviction, we do so no matter what.
- If the user has not specified eviction, we may still evict replicas based on the new node drain policies. We need to check if the node is schedulable to activate this behavior.
- When the user is not specifying eviction AND the conditions aren't right for auto-eviction, we cancel evictions.

It does look like we may be able to use the Longhorn node's `Scheduling` condition here instead of the Kubernetes node's field, since the node controller is updating that automatically, but this is a minor optimization.

2023-10-26 17:11 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +
I agree. Adding that to the main issue.

2023-10-30 04:41 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - `spec.evictionRequested == false` on the replica's disk, AND
> I think we do not want to automatically set spec.evictionRequested = true on nodes or disks because this is a user-specified field

OK, I got your point. In other words, we will set `replica.spec.evictionRequested` when node/disk `spec.evictionRequested == true`, or the auto eviction policy is correct with a cordoned kube node. Otherwise, we can unset `replica.spec.evictionRequested`.

NIT: The comment you explained here is more easy-to-understand comparing with the final condition checks listed in the LEP.

2023-10-30 04:44 UTC, shuo-wu commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- The node controller sets `status.autoEvicting = true` when a node has evicting replicas because of the new drain
Got it. I am fine with the case you mentioned since `autoEvicting` only cares about Longhorn replicas

2023-10-30 04:44 UTC, shuo-wu submitted a review, later dismissed
In general LGTM

2023-11-01 21:04 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  - `spec.evictionRequested == false` on the replica's disk, AND
Got it. I wrote these lines after I wrote the code. I probably focused too much on making them mirror the code exactly and not enough on making them readable. I simplified them while cleaning up a couple of other things.

2023-11-02 18:00 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +Add a `status.autoEvicting` to the `node.longhorn.io/v1beta2` custom resource. This is not a field users can/should
Closing this conversation, since `status.autoEvicting` is remaining in the feature as a "true status" now (set true or false depending on whether auto evicting is occuring).

2023-11-02 18:00 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +  Drawbacks:
Closing this conversation, since `status.autoEvicting` is remaining in the feature as a "true status" now (set true or false depending on whether auto evicting is occuring).

2023-11-02 18:04 UTC, ejweber commented on enhancements/20230905-automatically-evict-replicas-while-draining.md
> +- Verify the drain never completes.
Please check https://github.com/longhorn/website/pull/794. I did not mention 150 GB specifically (not sure exactly where that number is documented), but tried to highlight the need to adjust drain timeouts accordingly.

2023-11-13 19:22 UTC, PhanLe1010 approved these changes
LGTM. Thanks for the great work!

2023-11-13 19:27 UTC, PhanLe1010 approved these changes

2023-11-13 19:28 UTC, merged

2023-11-14 08:56 UTC, innobead commented
LGTM. This is good.

cc @derekbit @shuo-wu