example: add an example for encrypted volume in block mode
longhorn/longhorn pull request #6731
Opened 2023-09-19 11:27 UTC by derekbit

Longhorn/longhorn#4883

2023-09-19 12:10 UTC, innobead requested changes
Some comments need to resolve first.

2023-09-19 12:10 UTC, innobead commented on examples/block/crypto/storageclass-crypto-global.yaml
> +  migratable: "true"
Why using `migratable: "true""`?

2023-09-19 12:10 UTC, innobead commented on examples/block/crypto/deployment_with_pvc.yaml
> +  volumeMode: Block
RWX + block volume, it seems a unsupported combination, even though the current implementation would just treat it as RWX no matter what type of volume mode.

2023-10-19 13:58 UTC, innobead commented
@derekbit Please help update this, then we can merge it.

2023-10-19 14:13 UTC, derekbit commented on examples/block/crypto/storageclass-crypto-global.yaml
> +  migratable: "true"
Just an example. Will

It can be
`migratable: "true""` + `accessMode: ReadWriteMany` (a block device for vm) or
`migratable: "false""` + `accessMode: ReadWriteOnce` (a generic block device).
I think both cases are fine. Will update the example to the second one.

2023-10-19 14:14 UTC, derekbit commented on examples/block/crypto/deployment_with_pvc.yaml
> +  volumeMode: Block
> RWX + block volume, it seems a unsupported combination

Harvester uses RWX + migratable: "true"" + block volume, right?

2023-10-19 14:21 UTC, derekbit commented
> @derekbit Please help update this, then we can merge it.

Updated. Thank you.

2023-10-19 14:57 UTC, innobead approved these changes

2023-10-19 14:57 UTC, merged

2023-10-19 14:58 UTC, innobead commented on examples/block/crypto/deployment_with_pvc.yaml
> +  volumeMode: Block
Right! I thought it was RWO + migratable.

2023-10-19 14:59 UTC, innobead commented on examples/block/crypto/storageclass-crypto-global.yaml
> +  migratable: "true"
Since `migratble` is a specific case for volume migration used in Harvester, it would be more helpful to have a general case instead.