7102 - Add checks for kubectl failure to query nodes.
longhorn/longhorn pull request #7184
Opened 2023-11-22 18:14 UTC by james-munson

This addresses the issue #7102 - if we fail to get nodes from kubectl, the environment checking script is satisfied that every node in the empty list meets the criteria, and does not fail.

2023-11-22 20:08 UTC, ejweber commented on scripts/environment_check.sh
> +    warn "kubectl get nodes returned empty list - check KUBECONFIG setup"
NIT: I feel like this should be an error (like the one above) since we are crashing out of the script with it.

2023-11-22 20:11 UTC, ejweber requested changes
I tried both new failure methods and they worked as expected.

```
eweber@laptop:~/longhorn> scripts/environment_check.sh 
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[WARN]  kubectl get nodes returned empty list - check KUBECONFIG setup

eweber@laptop:~/longhorn> export KUBECONFIG=broke
eweber@laptop:~/longhorn> scripts/environment_check.sh 
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
W1122 14:06:05.513260   26649 loader.go:222] Config not found: broke
E1122 14:06:05.513903   26649 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1122 14:06:05.514054   26649 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1122 14:06:05.515413   26649 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1122 14:06:05.516563   26649 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1122 14:06:05.517915   26649 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[ERROR] kubectl get nodes failed - check KUBECONFIG setup
```

One NIT to answer or resolve.

2023-11-27 16:50 UTC, james-munson commented on scripts/environment_check.sh
> +    warn "kubectl get nodes returned empty list - check KUBECONFIG setup"
Okay, done.

2023-11-27 17:13 UTC, ejweber approved these changes
LGTM

2023-11-28 01:42 UTC, PhanLe1010 approved these changes
LGTM.

Could you rebase and repush? @james-munson 

Should we also backport it to older versions?

2023-11-28 01:45 UTC, innobead approved these changes

2023-11-28 01:47 UTC, merged

2023-11-28 01:48 UTC, innobead commented
We need to backport this to 1.5.x and 1.4.x if needed. @james-munson I just added backport labels to the source ticket, so please fix them as well. Thanks.

2023-11-28 18:39 UTC, james-munson commented
@mergify backport v1.4.x v1.5.x