Release v1.5.3 and bump memmory request/limit for upgrade responder
longhorn/longhorn pull request #7189
Opened 2023-11-23 02:20 UTC by PhanLe1010

longhorn/longhorn#7082
longhorn/longhorn#7105

2023-11-29 13:44 UTC, innobead requested changes

2023-11-29 13:44 UTC, innobead commented on deploy/upgrade_responder_server/chart-values.yaml
> +          "name": "v1.5.3",
1.5.3 has been marked as stable.

2023-12-12 14:51 UTC, innobead commented on deploy/upgrade_responder_server/chart-values.yaml
> +          "name": "v1.5.3",
@PhanLe1010 Fix this, and then we can merge this PR.

2023-12-14 04:17 UTC, PhanLe1010 commented on deploy/upgrade_responder_server/chart-values.yaml
> +          "name": "v1.5.3",
Fixed. Thanks @innobead

2023-12-14 04:42 UTC, innobead approved these changes

2023-12-14 04:42 UTC, merged