feat(lep): default priority class
longhorn/longhorn pull request #7252
Opened 2023-12-04 14:24 UTC by mantissahz

Add a default priority class with the highest value to the setting `priority-class`.

Ref: longhorn/longhorn#6528

2023-12-11 06:23 UTC, innobead commented
_*User cases:*_
- For fresh install, the default priority class will be set if there is no priority class set by users. The setting of the priority class will be updated. 
- For upgrade, if volumes are attached, the setting should be applied except for user-managed components. The setting of the priority class will not be updated. 
- For upgrade, if all volumes are detached, the setting should be applied including user-managed components. The setting of the priority class will be updated because the source of truth of settings is the config map (`longhorn-default-setting`). 

_*Notes for users:*_

- Because the setting of priority class will be overridden no matter if it has been set or not in the above item 3, we need to add this to the important note. 
- For item 2, because the setting will not be updated, need to notify users about this. If they want to make it take effect, need to update on their own. 

Anything missing? @mantissahz

2023-12-11 09:10 UTC, mantissahz commented
> User cases:

Add another case:
For upgrade, if all volumes are detached but the setting `priority-class` is set to a priority class, the setting should be applied except for user-managed components. The setting of the priority class will not be updated.

And add Test plans for user cases

2023-12-12 11:08 UTC, innobead requested changes

2023-12-12 11:08 UTC, innobead commented on enhancements/20231204-default-priority-class.md
> +NOTE: Before modifying the setting `priority-class`, all Longhorn volumes must be detached.\
`\` removed. Please review this PR again to fix some minor doc issues.

2023-12-12 11:08 UTC, innobead commented on enhancements/20231204-default-priority-class.md
> +priorityClassName: longhorn-critical
Suggest `defaultPriorityClass` to align with the existing variables in values.yaml. 

This is important to make things consistent for UX.

2023-12-12 11:08 UTC, innobead commented on enhancements/20231204-default-priority-class.md
> +2. Add a test case which the setting `priority-class` will be updated without a value that the user set or a volume attached after the upgrade.
Add a test case `where` the ....

2023-12-12 11:08 UTC, innobead commented on enhancements/20231204-default-priority-class.md
> +### Test plan
Please update the test cases accordingly as per my other comments.

2023-12-12 12:04 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +
Modified. Thanks.

2023-12-12 12:05 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +2. Change the priority class by modifying the setting `priority-class` as mentioned in section [Priority Class](https://longhorn.io/docs/1.6.0/advanced-resources/deploy/priority-class).
Modified. Thanks.

2023-12-12 12:05 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +2. For upgrade, if all volumes are detached, the setting should be applied including user-managed components. The setting of the priority class will be updated because the source of truth of settings
Modified. Thanks.

2023-12-12 12:05 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +3. For upgrade, if all volumes are detached and the setting of the priority class is set to a priority class name, the setting should be applied except for user-managed components. The setting of the
Yes, it is what you describe.
Modified. Thanks.

2023-12-12 12:06 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +priorityClassName: longhorn-critical
Modified. Thanks.

2023-12-12 12:06 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +### Test plan
Updated. Thanks.

2023-12-12 12:06 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +NOTE: Before modifying the setting `priority-class`, all Longhorn volumes must be detached.\
Removed and reviewed the PR again. Thanks

2023-12-12 12:06 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +2. Add a test case which the setting `priority-class` will be updated without a value that the user set or a volume attached after the upgrade.
Modified. Thanks.

2023-12-12 12:31 UTC, innobead requested changes

2023-12-12 12:31 UTC, innobead commented on enhancements/20231204-default-priority-class.md
> +4. For an upgrade, if volumes are attached, the setting should be applied except for user-managed components. The setting of the priority class will not be updated.
This one is still confusing. 

Why if volumes are attached, the setting should be applied except for user-managed components? so the setting will be applied to the `priority-class` global setting? If yes, this will cause the system managed pods restarted, right?

Should be:
> For an upgrade, if volumes are attached, the setting should be applied to the user-managed components only if they haven't been set. The setting of the priority class will not be updated.

There are two places to update priority class:
- Each priority class of the user managed components
- Global settings for system managed components

2023-12-12 13:07 UTC, mantissahz commented on enhancements/20231204-default-priority-class.md
> +4. For an upgrade, if volumes are attached, the setting should be applied except for user-managed components. The setting of the priority class will not be updated.
Modified. Yes, it should be what you described.
>For an upgrade, if volumes are attached, the setting should be applied to the user-managed components only if they haven't been set. The setting of the priority class will not be updated.

Thanks

2023-12-12 13:20 UTC, innobead approved these changes
In general, LGTM. 

Here's a corrected version:

In summary, updating the global setting of the priority class will be a best effort, as it will depend on whether there are any running volumes during the upgrade.

2023-12-12 13:20 UTC, merged