feat: default priority class
longhorn/longhorn pull request #7262
Opened 2023-12-05 13:57 UTC by mantissahz

Add a priority class template YAML file to create a default priority class.
Add a new field `defaultPriorityClassName` in value.yaml.
Update the deploy YAML file - longhorn.yaml

Ref: longhorn/longhorn#6528

2023-12-05 15:20 UTC, innobead requested changes
In general, LGTM. Some feedback needs to resolve.

Also, need to have a test coverage to ensure don't break user envs if they already configure priorityClass.

2023-12-05 15:20 UTC, innobead commented on chart/templates/priority-class.yaml
> +kind: PriorityClass
let's change the file name to `priorityclass.yaml` to be consistent with `storageclass.yaml`.

P.S. We should review file name convention later and make names consistent if needed.

2023-12-05 15:20 UTC, innobead commented on chart/templates/priority-class.yaml
> +value: 1000000000
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass

2023-12-05 15:20 UTC, innobead commented on chart/templates/priority-class.yaml
> +description: "Used for Longhorn pods to ensure pods have not been evicted when low system resources by the Kube scheduler."
`Ensure Longhorn pods have the highest priority to prevent any unexpected eviction by the Kubernetes scheduler under node pressure.`

2023-12-05 15:20 UTC, innobead commented on chart/questions.yaml
> +  - variable: defaultSettings.priorityClass
This was missed?! Good catch.

2023-12-05 15:20 UTC, innobead commented on chart/values.yaml
> +defaultPriorityClassName: &defaultPriorityClassNameRef "longhorn-critical"
Suggest setting `defaultSettings.priorityClass` to this value as well, so you don't need to hard-code it in longhorn-manager.

2023-12-06 15:12 UTC, mantissahz commented on chart/templates/priority-class.yaml
> +kind: PriorityClass
Renamed. Thanks.

2023-12-06 15:12 UTC, mantissahz commented on chart/templates/priority-class.yaml
> +description: "Used for Longhorn pods to ensure pods have not been evicted when low system resources by the Kube scheduler."
Modified. Thanks.

2023-12-06 15:14 UTC, mantissahz commented on chart/values.yaml
> +defaultPriorityClassName: &defaultPriorityClassNameRef "longhorn-critical"
Removed `defaultPriorityClassName` and the longhorn-manager upgrade process will handle the default priority class.
Thanks.

2023-12-06 15:15 UTC, mantissahz commented on chart/templates/priority-class.yaml
> +value: 1000000000
Added into the YAML file `priorityclass.yaml`

2023-12-07 15:08 UTC, mantissahz commented on chart/templates/deployment-ui.yaml
> +      priorityClassName: {{ .Values.longhornUI.priorityClass | default "longhorn-critical" .Values.defaultSettings.priorityClass | quote }}
Modified. Made a default value of `defaultSettings.priorityClass` to values.yaml.
And this part will revert to the original.

2023-12-13 08:19 UTC, innobead commented
@mantissahz as we discussed, review the change I made and also fix `questions.yaml` for the change of `values.yaml`. Of course, fix the conflict with the master. 

Do some tests, then we can merge this PR.

2023-12-13 17:11 UTC, mantissahz commented
Hi @innobead,
Tested 4 cases (fresh install, upgrade with a volume attached, upgrade with no volume attached, and upgrade with no volume attached and the setting `priority-class` has been customized by users) in the LEP with the [longhorn-manager PR](https://github.com/longhorn/longhorn-manager/pull/2332) and it looks working as we mentioned.

2023-12-18 10:28 UTC, innobead approved these changes
LGTM

2023-12-18 10:28 UTC, merged