chart: introduce v1-data-engine setting
longhorn/longhorn pull request #7403
Opened 2023-12-21 02:27 UTC by derekbit

longhorn/longhorn#7095

2023-12-25 13:35 UTC, innobead approved these changes
LGTM

2023-12-25 13:35 UTC, innobead commented
@jillian-maroket Please help review the description of the new settings. After that, we can merge this PR.

2023-12-26 03:20 UTC, jillian-maroket reviewed
Let me know if you have concerns about the changes.

2023-12-26 03:20 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: "This integer value indicates how many millicpus on each node will be reserved for each instance manager Pod for v2 data engine. By default, the SPDK target daemon within an instance
```suggestion
    description: "Number of millicpus on each node to be reserved for each instance manager pod for the V2 Data Engine. By default, the Storage Performance Development Kit (SPDK) target daemon within each instance manager pod uses 1 CPU core. Configuring a minimum CPU usage value is essential for maintaining engine and replica stability, especially during periods of high node workload. The default value is 1250 millicpus."
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
> +  # -- This integer value indicates how many percent of the total allocatable CPU on each node will be reserved for each instance manager Pod for v1 data engine.
```suggestion
  # -- Percentage of the total allocatable CPU resources on each node to be reserved for each instance manager pod for the V1 Data Engine.
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
> +  # -- This allows users to activate v1 data engine.
```suggestion
  # -- Setting that allows you to enable the V1 Data Engine.
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
>    # You can leave it with the default value, which is 12%.
```suggestion
  # The default value is 12%.
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
> +  # -- This integer value indicates how many millicpus of CPU on each node will be reserved for each instance manager Pod for v2 data engine.
```suggestion
  # -- Number of millicpus on each node to be reserved for each instance manager pod for the V2 Data Engine.
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
> +  # You can leave it with the default value, which is 1250 millicpus.
```suggestion
  # The default value is 1250 millicpus.
```

2023-12-26 03:20 UTC, jillian-maroket commented on chart/values.yaml
> +  # -- Enabling this setting will notify Longhorn that the cluster is using Kubernetes Cluster Autoscaler.
```suggestion
  # -- Setting that notifies Longhorn that the cluster is using the Kubernetes Cluster Autoscaler.
```

2023-12-26 04:47 UTC, innobead commented
@derekbit Let's update/correct the description of the settings in other places (doc, longhorn-manager?) after merging.

2023-12-26 05:09 UTC, derekbit commented
> @derekbit Let's update/correct the description of the settings in other places (doc, longhorn-manager?) after merging.

@jillian-maroket @innobead 
All are updated. Thank you.

2023-12-26 05:35 UTC, innobead requested changes
LGTM, just one comment.

2023-12-26 05:35 UTC, innobead commented on chart/values.yaml
> +  # -- Setting that notifies Longhorn that the cluster is using the Kubernetes Cluster Autoscaler.
Why do we have this comment next here? It should be for the cluster autoscaler setting.

2023-12-26 06:30 UTC, derekbit commented on chart/values.yaml
> +  # -- Setting that notifies Longhorn that the cluster is using the Kubernetes Cluster Autoscaler.
@jillian-maroket updated the description as well, so update it together.

2023-12-26 06:36 UTC, innobead approved these changes

2023-12-26 06:36 UTC, merged