doc(backupbackingimage): add example yaml of backingimage backup and restore
longhorn/longhorn pull request #7510
Opened 2024-01-02 06:41 UTC by ChanYiLin

ref: longhorn/longhorn 4165

2024-01-02 15:48 UTC, innobead requested changes

2024-01-02 15:48 UTC, innobead commented on enhancements/20230807-backingimage-backup-support.md
> -        BackingImageName string            `json:"backingImageName"`
`BackingImageName` is not required? how to know which backing image is being backed up?

2024-01-03 02:20 UTC, ChanYiLin commented on enhancements/20230807-backingimage-backup-support.md
> -        BackingImageName string            `json:"backingImageName"`
BackingImage is global unique
so its backup should also be global unique
I simply make them the same name.

2024-01-03 06:25 UTC, innobead approved these changes

2024-01-03 06:25 UTC, merged