fix(namespace): add the field namespaceOverride back.
longhorn/longhorn pull request #7747
Opened 2024-01-22 09:57 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#6527

#### What this PR does / why we need it:

This field is used to override the Longhorn namespace when Longhorn is a sub-chart such as a sub-chart of the Harvester.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-01-22 15:04 UTC, innobead requested changes
LGTM, just one feedback.

2024-01-22 15:04 UTC, innobead commented on chart/README.md
> +| namespaceOverride | `""` | Specify override namespace, specifically this is useful for using longhorn as sub-chart and its release namespace is not the `longhorn-system` such as Harvester. |
No need to specially mention Harvester.

2024-01-22 15:04 UTC, innobead commented
@mergify backport v1.6.x

2024-01-23 00:52 UTC, mantissahz commented on chart/README.md
> +| namespaceOverride | `""` | Specify override namespace, specifically this is useful for using longhorn as sub-chart and its release namespace is not the `longhorn-system` such as Harvester. |
Modified. Thanks.

2024-01-23 03:02 UTC, innobead approved these changes
Please update the website doc.

2024-01-23 03:02 UTC, merged