fix(environment_check): add check for globalDefault priority class.
longhorn/longhorn pull request #7807
Opened 2024-01-29 20:25 UTC by james-munson

#### Which issue(s) this PR fixes:

Issue https://jira.suse.com/browse/SURE-7492

#### What this PR does / why we need it:

Make the environment_check script look for an existing priority class with globalDefault=true to head off this issue and https://github.com/longhorn/longhorn/issues/2820.

#### Special notes for your reviewer:

This is really only for backport to v1.4.x and v1.5.x. 
In 1.6.0 and later, Longhorn defines its own `longhorn-critical` priority class and ensures that system pods are set to that.

That's why I opened this PR directly into `v1.5.x` to take the place of https://github.com/longhorn/longhorn/pull/7796, because it really doesn't need to go into master.

#### Additional documentation or context

2024-01-30 01:28 UTC, PhanLe1010 commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class."
Can we link the recommended action into the log for user to see it? 
```suggestion
      warn "Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason"
```

2024-01-30 01:28 UTC, PhanLe1010 commented on scripts/environment_check.sh
> +  info "Cluster has no global default priority class."
Should we remove this log because it may sound like something negative when user see it while it is actually a good thing? If the check pass, maybe just silently move on as other checks?

2024-01-30 15:04 UTC, ejweber reviewed
LGTM in general.

I agree with @Phan's suggestions.

2024-01-30 17:31 UTC, james-munson commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class."
Done.

2024-01-31 14:35 UTC, ejweber approved these changes

2024-02-01 07:56 UTC, innobead requested changes

2024-02-01 07:56 UTC, innobead commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason"
Do we not need to check whether the priority class of Longhorn components is set or not? If there is a global priority, it does not imply that Longhorn doesn't have a configured priority class.

2024-02-01 14:13 UTC, ejweber commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason"
I think we generally expect the user to run the environment check before they install Longhorn: https://longhorn.io/docs/1.5.3/deploy/install/#using-the-environment-check-script. (Though certainly we ask some users to run it after the fact.)

2024-02-01 14:17 UTC, innobead commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason"
That's fair. Probably just make it a warning instead of returning an error.

2024-02-01 16:27 UTC, james-munson commented on scripts/environment_check.sh
> +      warn "Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason"
Right, it is just a warning and a reference article.

2024-02-02 03:12 UTC, shuo-wu approved these changes

2024-02-05 11:37 UTC, innobead approved these changes

2024-02-05 11:37 UTC, merged

2024-02-07 17:00 UTC, james-munson commented
@mergify backport v1.4.x