feat(lep): support a ReadOnlyMany behavior.
longhorn/longhorn pull request #7853
Opened 2024-02-05 20:47 UTC by james-munson

#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/5041

#### What this PR does / why we need it:

Make an LEP with a proposal for how to implement `ReadOnlyMany` behavior in Longhorn code.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-02-06 09:33 UTC, innobead requested changes

2024-02-06 09:33 UTC, innobead commented on enhancements/20240202-read-only-many.md
> +Add a parameter to storageclass and thus to volume spec named `mountReadOnly` with default value of `false`.
We should just leverage the access mode of a PVC to determine if the volume is ROM. The mount ro option should supersede the customized options provided by users.

2024-02-06 09:33 UTC, innobead commented on enhancements/20240202-read-only-many.md
> +#### 2. New `ReadOnlyMany` access mode enum value:
As an official support, we should go with option 2 to provide a better user experience via a standard interface (access mode: ROM).

2024-02-06 09:33 UTC, innobead commented
Would like to hear thoughts from @derekbit and @shuo-wu

2024-02-06 09:55 UTC, derekbit commented on enhancements/20240202-read-only-many.md
> +Add a parameter to storageclass and thus to volume spec named `mountReadOnly` with default value of `false`.
Agree with @innobead's suggestion.
If the PVC is ROM, we automatically append `ro` option.

2024-02-06 19:50 UTC, ejweber reviewed
I agree with the comments so far: we should leverage the Kubernetes `AccessMode = ReadOnlyMany` (set in PVC and PV) instead of adding a new field to a StorageClass and Longhorn volume.

We should consider the possibility that we will be asked to create a volume with multiple capabilities / access modes simultaneously. For example:

- ReadOnlyMany, and
- ReadWriteMany.

Then, we may be asked to publish the volume with either of these access modes.

What should we do in this case?

I think we should probably create a Longhorn volume with `AccessMode == rwx` when responding to the `CreateVolume` request. Then, we should modify behavior appropriately in `ControllerPublishVolume` (if we want to enforce read-only on the export) and `NodeStageVolume`/`NodePublishVolume` (where we will modify mount options).

2024-02-06 20:00 UTC, ejweber commented
> Instead of "only" doing this on the mount side though I believe we'll want to change the actual export to be read-only (or rather, not rw), so that the NFS server side enforces this too.

I am not sure this is strictly necessary, but it may be the "right" thing to do. It looks like we already template the Ganesha configuration, so it might not be too difficult to change the access type on the export if we can get the right information to the share manager pod (https://github.com/longhorn/longhorn-share-manager/blob/3168f43cad72c25cec704494064f3f58e28b7210/pkg/server/nfs/nfs_server.go#L148-L169). That may mean an additional API change though, since I don't think there's an existing ShareManager field to drop the read-only information into.

2024-02-08 19:42 UTC, PhanLe1010 commented
As discussed with @james-munson, currently Kubernetes has 4 access modes in total:
1. RWO - ReadWriteOnce
1. ROX - ReadOnlyMany
1. RWX - ReadWriteMany
1. RWOP - ReadWriteOncePod

We are missing `ReadOnlyMany` and `ReadWriteOncePod`. Maybe `ReadWriteOncePod` can be on a different ticket but it would be great if we keep it in mind while developing this `ReadOnlyMany` mode.

2024-02-08 20:07 UTC, PhanLe1010 commented
> simultaneously. For example:
> 
> ReadOnlyMany, and
> ReadWriteMany.
> Then, we may be asked to publish the volume with either of these access modes.
> 
> What should we do in this case?
> 
> I think we should probably create a Longhorn volume with AccessMode == rwx when responding to the CreateVolume request. Then, we should modify behavior appropriately in ControllerPublishVolume (if we want to enforce read-only on the export) and NodeStageVolume/NodePublishVolume (where we will modify mount options).

This is a good point. I think we can take a look at how CSI sidecar is handling the selection when there are multiple modes specified. Some combinations should be blocked in CreateVolume:  https://github.com/kubernetes-csi/csi-lib-utils/blob/f82f9de5b8aeb3c3b236d7f58fc5eeab34438078/accessmodes/access_modes.go#L36-L78

2024-02-08 22:47 UTC, PhanLe1010 commented
> Instead of "only" doing this on the mount side though I believe we'll want to change the actual export to be read-only (or rather, not rw), so that the NFS server side enforces this too.

Agree with @ejweber that  this might not be strictly necessary. When PVC requests ReadOnlyMany, it is not mandatory that we have to force the underlying storage layer to be read-only https://kubernetes.io/docs/concepts/storage/persistent-volumes/#:~:text=For%20example%2C%20even%20if%20a%20PersistentVolume%20is%20created%20as%20ReadOnlyMany%2C%20it%20is%20no%20guarantee%20that%20it%20will%20be%20read%2Donly

2024-02-16 21:02 UTC, james-munson commented
Converting this to draft while I incorporate the feedback and renew with the recommended approach.  I'll either re-open or close and replace with another PR.

2024-05-21 08:17 UTC, innobead commented
@james-munson This PR has been pending for a while. Let's resume this and try to get it for 1.7.0 still.

2024-07-25 05:07 UTC, derekbit commented
ping @james-munson

2025-09-02 09:47 UTC, derekbit commented
Revisit while working on this feature.
cc @COLDTURNIP

2025-09-02 09:47 UTC, closed without merging