chart: Add Snapshot Maximum Count to the Settings
longhorn/longhorn pull request #7896
Opened 2024-02-08 20:26 UTC by yardenshoham

It was missing

2024-02-08 20:55 UTC, PhanLe1010 reviewed
Thanks for the PR. There is a small naming issue.

Can we also verify the question.yaml is a valid yaml file or not by https://www.yamllint.com/? 
We will add this functionality in Longhorn in the future https://github.com/longhorn/longhorn/issues/7897

2024-02-08 20:57 UTC, yardenshoham commented on chart/templates/default-setting.yaml
> +    max-snapshotum: {{ .Values.defaultSettings.maxSnapshotNum }}
Oops I will fix

2024-02-08 22:31 UTC, PhanLe1010 commented on chart/templates/default-setting.yaml
> +    max-snapshotum: {{ .Values.defaultSettings.maxSnapshotNum }}
Can you create a Github bug ticket @yardenshoham https://github.com/longhorn/longhorn/issues/new/choose

The ticket is used to move this fix through our development pipeline which including QA testing

2024-02-09 07:27 UTC, yardenshoham commented on chart/templates/default-setting.yaml
> +    max-snapshotum: {{ .Values.defaultSettings.maxSnapshotNum }}
Done https://github.com/longhorn/longhorn/issues/7906

2024-02-20 06:02 UTC, innobead commented on chart/templates/default-setting.yaml
> +    max-snapshotum: {{ .Values.defaultSettings.maxSnapshotNum }}
Please fix this to `snapshot-max-count` as Phan mentioned. Thanks.

2024-02-20 06:04 UTC, innobead requested changes

2024-02-20 06:04 UTC, innobead commented on chart/values.yaml
> +  maxSnapshotNum: ~
`snapshotMaxCount` instead

2024-02-20 08:56 UTC, FrankYang0529 requested changes
Overall LGTM. Thanks for the contribution.

2024-02-20 08:56 UTC, FrankYang0529 commented on chart/README.md
> +| defaultSettings.snapshotMaxCount | Maximum snapshot count for a volume. The value should be between 2 to 250 |
Hi @yardenshoham, may you run `./scripts/helm-docs.sh` to update `README.md` file? Thanks.

Ref: https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update

2024-02-20 09:34 UTC, yardenshoham commented on chart/templates/default-setting.yaml
> +    max-snapshotum: {{ .Values.defaultSettings.maxSnapshotNum }}
Done https://github.com/longhorn/longhorn/pull/7896/commits/9ab25c13ecb67dac3590bf92d52522e19b35c1df

2024-02-20 09:34 UTC, yardenshoham commented on chart/values.yaml
> +  maxSnapshotNum: ~
Done https://github.com/longhorn/longhorn/pull/7896/commits/9ab25c13ecb67dac3590bf92d52522e19b35c1df

2024-02-20 09:37 UTC, yardenshoham commented on chart/README.md
> +| defaultSettings.snapshotMaxCount | Maximum snapshot count for a volume. The value should be between 2 to 250 |
Done https://github.com/longhorn/longhorn/pull/7896/commits/ba17bf90fe38f5409fd13068e15679a22c9af236

2024-02-20 09:39 UTC, FrankYang0529 approved these changes

2024-02-20 10:00 UTC, innobead approved these changes

2024-02-20 10:00 UTC, merged

2024-02-20 10:00 UTC, innobead commented
Thanks @yardenshoham !

2024-02-20 10:01 UTC, innobead commented
@mergify backport v1.6.x