Feat(serviceMonitor): Add multiple settings for ServiceMonitor resource.
longhorn/longhorn pull request #8120
Opened 2024-03-06 20:07 UTC by kejrak

#### What this PR does / why we need it:

This PR introduces additional settings for ServiceMonitor, primarily focusing on the incorporation of additionalLabels for custom use and annotations. I added another ServiceMonitor settings, that helps to better configure monitoring of Loghorn.

2024-03-08 20:32 UTC, shuo-wu approved these changes

2024-03-21 11:45 UTC, innobead commented
> Can you please [create an issue](https://github.com/longhorn/longhorn/issues/new/choose) using one of the templates and link this PR to it @kejrak?

@ejweber @kejrak seems not creating the issue yet. Can you help with that and finish the QA process (ready-for-testing)? Thanks.

2024-03-22 21:21 UTC, ejweber requested changes
I'm not super familiar with some of these fields. Can you provide an example values.yaml so we can verify these changes work as expected? It can help us produce a manual test of the behavior for QA verification.

2024-03-22 21:21 UTC, ejweber commented on chart/README.md
> +| metrics.serviceMonitor.tlsConfig | `{}` | Settings to change Prometheus ServiceMonitor tlsConfig. |
I think we should not add `tlsConfig` and `scheme`. If I understand correctly what they do, they cannot be meaningfully changed modified for Longhorn currently. This is because the Longhorn metrics endpoint serves on an unencrypted HTTP endpoint and the behavior is not configurable.

2024-03-24 11:05 UTC, kejrak commented
Hi @ejweber, you are right. I will look at it asap a fix it.

2024-04-09 14:37 UTC, ejweber requested changes

2024-04-11 19:15 UTC, kejrak commented on chart/templates/servicemonitor.yaml
> +    scheme: {{ . }}
Coming right up!

2024-07-05 09:42 UTC, christiaan-bronkhorst commented
@ejweber @kejrak  is there still something missing before we can get this merged?

2024-07-09 21:58 UTC, ejweber commented
Sorry, somehow this one dropped off my radar. I will check it out again tomorrow.

2024-07-10 16:16 UTC, kejrak commented
Please let me know if there's anything I can do.

2024-07-11 20:11 UTC, ejweber commented
Hello again @kejrak. I'd like to make the following changes:

- https://github.com/longhorn/longhorn/pull/8120/commits/79b2f0483c4cbcd4248d2b30be12d8d4303e53f2
  Adjust some field descriptions to exactly match https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint. (This isn't particularly important to me, but I think it's a good idea.)
- https://github.com/longhorn/longhorn/pull/8120/commits/43da2733467b63f9b331678543c315a30f98a2ba
  Default `interval` to empty instead of `30s`. This is because the docs say: "If empty, Prometheus uses the global scrape interval." I think it is best to let this Prometheus default take affect (and users will not expect it to change to 30s in the Longhorn ServiceMonitor, since it is empty now.)

Also, you'll notice https://github.com/longhorn/longhorn/pull/8120/commits/79b2f0483c4cbcd4248d2b30be12d8d4303e53f2 reordered `chart/README.md`. It is because we generate that document with `scripts/helm-docs.sh` and commit it using whatever canonical ordering the script provides.

If you agree with the changes, please review and approve. If not please feel free to make further adjustments.

2024-07-11 20:13 UTC, ejweber commented
- [ ] There is one step left. Usually @jillian-maroket reviews Helm field descriptions for clarity, as they end up in the online documentation. Can you take a look at these @jillian-maroket?

2024-07-11 20:15 UTC, ejweber approved these changes
LGTM with my changes. Need to wait for approval from @kejrak and @jillian-maroket (if she has time). If @jillian-maroket doesn't have time soon, we can merge and adjust the descriptions in a followup as necessary.

I guess @kejrak can't officially review with the way the project is setup, so we'll just wait for them to agree or not.

2024-07-11 20:17 UTC, kejrak reviewed
LGMT. Thank you @ejweber.

2024-07-11 20:27 UTC, merged

2024-07-11 20:28 UTC, ejweber commented
Merged to get this into v1.7.0-rc1. Can follow up on any description wording issues before release.

2024-07-12 14:46 UTC, christiaan-bronkhorst commented
Fantastic! Thanks @ejweber

2024-07-12 14:51 UTC, ejweber commented
@mergify backport v1.6.x v1.5.x