doc(enhancement): add recurring and manual full backup support
longhorn/longhorn pull request #8186
Opened 2024-03-14 08:00 UTC by ChanYiLin

ref: https://github.com/longhorn/longhorn/issues/7070

Add a proposal of **recurring and manual full backup support**

2024-03-14 10:49 UTC, innobead requested changes
In general, LG. Just a few comments. 

BTW, we should consider adding some cases to ensure our existing use cases around back, restore and DR should work as expected.

2024-03-14 10:49 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
Have you considered adding this as a new field into Backup CRD?

2024-03-14 10:49 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +    - Using label so we can filter Backup by the label to distinguish the full backup and normal backup easily.
Can we still leverage the field selector to achieve the same purpose if using a field?

https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

2024-03-14 10:49 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +    - Since we already pass `Label` through the grpc call chain from `longhorn-manager`->`longhorn-instance-manager`->`longhorn-engine/replica`->`backupstore`. So we don't need to do much modificatio
This is a sweet extension point.

2024-03-14 10:49 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Test plan
Suggest adding a regression test to ensure incremental backup of concurrent recurring jobs should still work, the same as DR volume, the incremental restore should work correctly.

2024-03-15 05:03 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
@shuo-wu @c3y1huang @ejweber @mantissahz any idea? 

We should better determine when it's appropriate to use CR fields or labels.

2024-03-15 05:10 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
This is kind of like passing parameters or options to the Backup execution

If considering the future extension
I don't think adding **fields** to the CRD is a proper way, cause we already pass a lot of request parameters down the grpc call chain, we then need to change the grpc interface every time we want to pass new options.
And that will introduce grpc interface breaking change.
https://github.com/longhorn/longhorn-manager/blob/v1.6.0/engineapi/backup_monitor.go#L85-L87
```
		_, replicaAddress, err := engineClientProxy.SnapshotBackup(engine, backup.Spec.SnapshotName, backup.Name,
			backupTargetClient.URL, volume.Spec.BackingImage, biChecksum, string(compressionMethod), concurrentLimit, storageClassName,
			backup.Spec.Labels, backupTargetClient.Credential)
```

If we really don't want to add this kind of Backup options to the label 
We at least should add a general `Options map[string]string` or `Parameters map[string]string` for all this kind of Backup Options.

2024-03-15 05:36 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
In addition, when adding parameters
We will have to update the UI in 
1. `Create Backup` in Volume Page
2. `Create Backup Task Recurring Job`
to add place for user to add parameters.

2024-03-15 05:40 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
This is more like a general question. 

If adding a field would cause breaking changes, then we need to think about how we design the current gRPC interface, because they should be compatible always if could. gRPC or protobuf can be compatibly designed.

The code you shared is about our `wrapper client` instead of the gRPC client, the real client should be below and the payload will be wrapped in `ProxyEngineRequest` which should be backward compatible even if adding any new field there. That said, for a new Longhorn manager with a full backup support client, when it calls an older version IM, the full backup will not take effect but delta backup as usual.

[/pkg/client/proxy_backup.go#L42-L62](https://github.com/longhorn/longhorn-instance-manager/blob/d670b03db8d2445296a19f6e737c283f1ed7798d/pkg/client/proxy_backup.go#L42-L62)
```go
	req := &rpc.EngineSnapshotBackupRequest{
		ProxyEngineRequest: &rpc.ProxyEngineRequest{
			Address:    serviceAddress,
			EngineName: engineName,
			// nolint:all replaced with DataEngine
			BackendStoreDriver: rpc.BackendStoreDriver(driver),
			DataEngine:         rpc.DataEngine(driver),
			VolumeName:         volumeName,
		},
		Envs:                 envs,
		BackupName:           backupName,
		SnapshotName:         snapshotName,
		BackupTarget:         backupTarget,
		BackingImageName:     backingImageName,
		BackingImageChecksum: backingImageChecksum,
		CompressionMethod:    compressionMethod,
		ConcurrentLimit:      int32(concurrentLimit),
		StorageClassName:     storageClassName,
		Labels:               labels,
	}
	recv, err := c.service.SnapshotBackup(getContextWithGRPCTimeout(c.ctx), req)
```

2024-03-15 07:36 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
Discussed with @innobead , here is the summarize

1. If this setting is used for local cluster to reconcile the CR, we should just add the field to the CRD Spec. In this case, we don't even have to store this field as metadata in the backupstore for another cluster to pull, because it is useless in new cluster.
2. If we want this setting to be preserved in the backupstore and be pulled to another cluster because it will be used in another cluster, e.g. `longhorn.io/volume-access-mode: rwo`, we can just use `Label`.
3. To conclude, for execution options, it might only used for backup execution. But since it is useful for user to reference the options in the new cluster. We may still use `Label` to store the execution options.

Note:
- But use key/value map like `Labels` or `Parameters` is not a good practice cause that will confuse the user what is the correct **"key"** of each setting and need to look up the doc. Need to keep in mind.

2024-03-15 07:39 UTC, innobead approved these changes
LGTM

2024-03-15 08:14 UTC, c3y1huang commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
Pros:
- Labeling provides a quick way of resource search and batch operation.

Cons:
- The user needs to be cautious when specifying the label, as a minor typo could lead to incorrect configurations. For instance, a small mistake might cause a recurring job to run incremental backups instead of full backups, potentially resulting in data loss without the user realizing it.

Is there any way to make this obvious for the user to know that a full backup has been taken? Perhaps through the status?

2024-03-15 14:36 UTC, ejweber commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
> The user needs to be cautious when specifying the label, as a minor typo could lead to incorrect configurations.

It looks like we do not currently validate labels (e.g. in the webhook). Perhaps we can add label validation? Probably we cannot attempt to validate all labels, since the user may add arbitrary labels to objects. But, if we detect a label with the prefix `longhorn.io`, we can ensure the key is known. For many (like the one we are discussing), we can also ensure the value it known.

2024-03-18 01:53 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
Sure I can add a status to indicate if this is a full backup
If `longhron.io/backup-mode: full` exists in the label, we then mark the `status.full = True`

2024-03-19 08:24 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +2. **Backup**: add a new reserved Longhorn label `longhorn-backup-mode: full`
Conclusion:

1. Use label instead of spec.XXX to store options
    - We still want to store these options as future metadata and show them in another cluster when restoring.
2. Since we use label to store options and these options are all with prefix `longhorn.io`. We should add validation to check those label with `longhron.io` are the options we know.
    - In this case, we don't need to add status, because we ensure the options is correct in the begining.

2024-03-27 02:46 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
The main purpose of the labels is to reduce the number of parameters. Is it correct?

2024-03-27 02:52 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Goals
Collect the metrics such as number of new blocks and number of overridden blocks in a full backup. 
The purpose is to help users evaluatee the cost growth and adjust the interval.

2024-03-27 02:54 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +3. Maybe adjust the UI to make the process more simple
Make the full and incremental backup visualized.
For example, add `full` or `incremental` tag in the backup chain.

2024-03-27 03:03 UTC, derekbit reviewed
Will the full backup introduce impacts to DR volumes?

2024-03-27 06:29 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
But RecurringJob is shared with different job type, e.g. Backup, Snapshot and Trim
`full-backup-interval` will only be used in Backup

I think the concept here is more like BackingImage or StorageClass parameters (`map[string]string`)
With different type of BackingImage, it accept different set of Options.
```
sourceType: export-from-volume
sourceParameters:
  volume-name: vol-export-src
  export-type: qcow2
```

2024-03-27 06:32 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
I prefer the `spec.parameters` as wll.

2024-03-27 06:45 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Goals
Discussed with @derekbit 
Since "new blocks and number of overridden blocks in a full backup" is actually the whole volume size
user can simply check the volume size for this case

2024-03-27 07:04 UTC, ChanYiLin commented
> Will the full backup introduce impacts to DR volumes?

No, I don't think so
Full Backup is just like Incremental Backup
The difference is only when doing Backup, Full Backup will pretend there is no lastBackup to collect all the blocks of the Volume.
From the metadata perspective, it is still a Backup and it will become the lastBackup after completion. 
So the DR Volume will pull the lastBackup and do incremental restore in the new cluster

2024-03-27 07:27 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
Yeah
But last time I discussed with @innobead ,we got the conclusion that both `Label` and `Parameters` is `map[string]string` so there is no much differences.

2024-03-27 07:45 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +3. Maybe adjust the UI to make the process more simple
Added

2024-03-27 07:46 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Goals
Added.

I found we need to store the information in new fields in Backup CRD
because the backup is a async call, so we can't get the number in the grpc call but can only get it by syncing the Backup metadata.

2024-03-27 08:10 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
I see. Tried to clarify the purposes of labels and spec.parameters.
According to the [kubernetes document](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

```
Labels are intended to be used to specify identifying attributes of objects that are meaningful and relevant to
users, but do not directly imply semantics to the core system. Labels can be used to organize and to select 
subsets of objects.
```

Labels in Kubernetes are designed for recording attributes and metadata that describe resources. They're not intended for controlling the behavior of a resource, which is the role of the spec.

`full-backup-interval` is a parameter that controls the behavior of a backup recurring job, so it'd better to store in the spec.parameters.

@innobead WDYT?

2024-03-28 00:05 UTC, derekbit approved these changes
LGTM

2024-03-28 01:30 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +    full-backup-interval: 0
Following our discussion with @shuo-wu, we recommend replacing `parameters map[string]string` with `parameters map[JobType]map[string]string`.
`JobType` could include values like `Backup`, `Snapshot` and so on. This modification ensures that parameters for different types are clearly classified.

2024-03-28 04:17 UTC, shuo-wu commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
As discussed with @derekbit, I think it's better to have a spec field like this:
```
type Parameters struct {
	Backup *BackupParameters `json:"backup,omitempty"`

	Snapshot *SnapshotParameters `json:"snapshot,omitempty"`

	Trim *TrimParameters `json:"trim,omitempty"`
}
```

I prefer not to rely on the labeling too much for the decision-making. As mentioned in the k8s doc, the label is mainly for identifying or filtering objects. Besides, there is no restrictive convention against the Longhorn reserved label key format and usage. Even developers like me, need to check the reference doc before using labels to operate something. It's unfriendly for users.

BTW, the idea is from [SPDK Bdev](https://github.com/longhorn/go-spdk-helper/blob/d05637da59788eeeb8927c663f0eec7c958d3f97/pkg/spdk/types/bdev.go#L124).

2024-03-28 05:14 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- When doing full backup, Longhorn will backup **all the current blocks** of the volume and **overwrite them** on the backupstore even if those blocks already exists on the backupstore.
LGTM @shuo-wu @derekbit above comments.

2024-03-28 06:20 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +    full-backup-interval: 0
We have `spec.task = backup` in RecurringJob CR
So we don't need to change the parameters structure.

2024-05-20 15:23 UTC, innobead reviewed
In general, LGTM. Just a few feedback.

2024-05-20 15:23 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. **BackupVolume**: add a new status `.Status.BackupCount` to record how many backups have been created.
What's the purpose of this new status field?

2024-05-20 15:23 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +4. store the `new upload data size`, `reupload data size` to the Backup Status.
Does `new upload data size` mean delta uploaded data? `reupload ata size` means full backup?

If yes, suggest the following naming. WDYT?
- `incrementa-backup/data-size`
- `full-backup/data-size`

2024-05-20 15:23 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Test plan
Need to add a test case for DR. 

Recurring backup with a full backup period, then see if DR volume can be activated with correct data.

2024-05-24 08:24 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +4. store the `new upload data size`, `reupload data size` to the Backup Status.
not exactly
one can keep doing full-backup but each time with new data block
the block is not exactly from `incrementa-backup/data-size`

2024-05-24 08:25 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Test plan
sure

2024-05-24 08:28 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. **BackupVolume**: add a new status `.Status.BackupCount` to record how many backups have been created.
Does backup time mean the number of `full backup`? When will it be reset?

2024-05-24 09:20 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. **BackupVolume**: add a new status `.Status.BackupCount` to record how many backups have been created.
It starts when the BackupVolume is created and is stored on the backupstore
it meas how many times this Volume has backed up no matter if it is full or incremental

The parameter is `full-backup-interval: 5` in recurring backup job.
So every 5 times backup, it will do full backup
It used the backupCount in BackupVolume to check.

2024-05-28 19:52 UTC, shuo-wu approved these changes
In general LGTM

2024-05-28 19:52 UTC, shuo-wu commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +  - `full-backup-interval`: used in `RecurringJob - Backup Type` to execute full backup every N incremental backups (default to 0 for always incremental)
NIT: It's better to provide an example in the description: If N is 5, it means that after 5 regular incremental backups, the 6th backup will be the full one.

2024-05-28 19:52 UTC, shuo-wu commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- Collect metrics of `newly upload data size` and `overwritten data size` for user to better understand the cost.
Can Longhorn collect this info if it's not recorded in Backup CR?

2024-05-29 04:52 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +4. store the `new upload data size`, `reupload data size` to the Backup Status.
the request is from @derekbit 
it is to help user understand the real data transfer amount in this backup
it count when we actually "upload" the block

so even for `incremental backup` => if the block already on the backupstore, we won't upload it, thus it is not in `new upload data size`
so for `full backup` => if there is new block needs to upload, it is in `new upload data size`

2024-05-29 05:02 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +  parameters:
you agree on @derekbit and @shuo-wu above and now change again?
Should we discussed with @derekbit and @shuo-wu agiain

2024-05-29 05:29 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +5. Restore the last backup of the BackupVolume.
The purpose of this test is that you wonder if concurrent backup restore work (lock issue)
But I found we actually have test for that: https://github.com/longhorn/longhorn-tests/blob/v1.5.1/manager/integration/tests/test_basic.py#L3186

And we also already have incremenatal  backup and restore e2e tests
So I don't quite understand what you want to achieve in this test?

2024-05-29 05:30 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +  parameters:
I have discussed with @derekbit 
He will provide conclusion we have.

2024-05-29 05:30 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. Need to pass `parameters` through the grpc function call chain.
I have discussed with @derekbit 
He will provide conclusion we have.

2024-05-29 05:33 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. **BackupVolume**: add a new status `.Status.BackupCount` to record how many backups have been created.
it is not for the metrics.
it is for recurring job to check how many backup has been executed 
so it will perform full backup next time.

for example
```
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: recurring-full-backup-per-min
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '* * * * *'
  groups: []
  labels: {}
  parameters:
    full-backup-interval: 5
  name: recurring-full-backup-per-min
  retain: 0
  task: backup
```
`full-backup-interval: 5` meaning every 5 incremental backup, we execute 1 full backup
then how do we know how many backup we executed (since backup might be deleted by users.)
we have to record the number in backupvolume 
so the job can get the value and see if it needs to perform full backup.

2024-05-29 05:33 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +### Test plan
added

2024-05-29 05:36 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +  - `full-backup-interval`: used in `RecurringJob - Backup Type` to execute full backup every N incremental backups (default to 0 for always incremental)
added the example, thanks

2024-05-29 05:38 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- Collect metrics of `newly upload data size` and `overwritten data size` for user to better understand the cost.
we can only know if this is newly upload data or overwritten data
when it checks if the block on the backupstore or not during upload process (and it is concurrent process) in backupstore library.

I think it is quite hard for Longhorn to collect the information in real time.

2024-05-29 05:39 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +  parameters:
After discussing with @ChanYiLin, we both agree with

- Using `spec.parameters` is better for passing them to the longhorn-engine via gRPC without additional changes to the gRPC interface, but it makes the attributes in CRD implicit.

- If we adopt `spec.mode`, we need to update the gRPC interface and append parameters. This extra effort is inevitable.

To avoid the drawbacks of both methods, we propose the following solution:

- Use `spec.mode` in the backup CRD.
- Convert the spec fields to a `parameters` map and pass them to the longhorn-engine via gRPC. For example:
   ```
  parameters := getBackupParameters(spec, ...)
  err := SnapshotBackup(..., parameters)
   ```

This approach requires updating only the CRD and the `getBackupParameters` function. The gRPC interface remains unchanged when introducing a new parameter.


WDYT? @innobead @ChanYiLin

2024-05-29 05:39 UTC, derekbit commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. Need to pass `parameters` through the grpc function call chain.
After discussing with @ChanYiLin, we both agree with

- Using `spec.parameters` is better for passing them to the longhorn-engine via gRPC without additional changes to the gRPC interface, but it makes the attributes in CRD implicit.

- If we adopt `spec.mode`, we need to update the gRPC interface and append parameters. This extra effort is inevitable.

To avoid the drawbacks of both methods, we propose the following solution:

- Use `spec.mode` in the backup CRD.
- Convert the spec fields to a `parameters` map and pass them to the longhorn-engine via gRPC. For example:
   ```
  parameters := getBackupParameters(spec, ...)
  err := SnapshotBackup(..., parameters)
   ```

This approach requires updating only the CRD and the `getBackupParameters` function. The gRPC interface remains unchanged when introducing a new parameter.


WDYT? @innobead @ChanYiLin

2024-05-29 06:37 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +5. Restore the last backup of the BackupVolume.
Discussed,concurrent backup restored already covered here: https://github.com/longhorn/longhorn-tests/blob/v1.5.1/manager/integration/tests/test_basic.py#L3186
If need to imvprove can create another ticket for it

2024-05-29 06:58 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +1. Need to pass `parameters` through the grpc function call chain.
Disscuess @innobead , we are good with the proposal

2024-05-29 07:11 UTC, innobead commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- Collect metrics of `newly upload data size` and `overwritten data size` for user to better understand the cost.
`newly upload data size`: new data upload size for delta backup
`overwritten data size`: overwritten data size for full backup.

2024-05-29 07:11 UTC, innobead approved these changes

2024-05-29 07:11 UTC, merged

2024-05-29 07:13 UTC, ChanYiLin commented on enhancements/20240314-recurring-and-manual-full-backup-support.md
> +- Collect metrics of `newly upload data size` and `overwritten data size` for user to better understand the cost.
- `newly upload data size`: the data size uploaded to the backupstore in this backup (skip data due to already exists on the backupstore won't count)
  - `overwritten data size`: the data size uploaded to the backupstore and overwritten the exists block on the backupstore.