feat(LEP): storage network for RWX volumes
longhorn/longhorn pull request #8616
Opened 2024-05-22 06:17 UTC by c3y1huang

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#8184

#### What this PR does / why we need it:

This LEP proposes to extend Longhorn's storage network feature to support RWX volumes.

#### Special notes for your reviewer:

None.

#### Additional documentation or context

None.

2024-05-24 10:50 UTC, innobead requested changes
I have a few feedback and questions that need to be clarified first. 

BTW, the idea of using headless service for share manager pods is impressive.

2024-05-24 10:50 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- Before: Data network segregation was unavailable for RWX volumes.
This is not clear. In fact, it works for RWO volume inside the share manager. It's better to clarify this.

`Data network segregation only works in the underlying RWO volume, but the data traffic between the mount point (client) and the share manager pod still goes through the cluster network.`

2024-05-24 10:50 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **CSI Annotations:** Share manager pods and CSI plugin pods will be annotated with the storage network for NFS client mounting.
CSI Plugin is not system managed but a daemonset. When will we add the annotation? We will not wait for all volumes detached first?

2024-05-24 10:50 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, Longhorn will delete the associated workload pod when it is using the storage-network. If the pod is managed by a controller, the kubelet w
Will this interrupt user running workloads? If yes, should we get the confirmation from users before doing this?

2024-05-24 10:53 UTC, innobead commented
Added @mantissahz to the review, as this is involved in danger zone settings, which we are allowing to take effect asynchronously.

2024-05-27 01:14 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, Longhorn will delete the associated workload pod when it is using the storage-network. If the pod is managed by a controller, the kubelet w
> Will this interrupt user running workloads?

This will interrupt the user's running workloads.

> If yes, should we get the confirmation from users before doing this?

We can leverage on `auto-delete-pod-when-volume-detached-unexpectedly` setting for handling this.

2024-05-27 01:19 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **CSI Annotations:** Share manager pods and CSI plugin pods will be annotated with the storage network for NFS client mounting.
We will apply the annotation in the same way as the RWO volume using the setting controller, once all volumes have been detached.

2024-05-27 14:15 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **CSI Annotations:** Share manager pods and CSI plugin pods will be annotated with the storage network for NFS client mounting.
So that means we will not apply the setting immediately but will eventually do so once all volumes are detached.

2024-05-27 14:18 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, Longhorn will delete the associated workload pod when it is using the storage-network. If the pod is managed by a controller, the kubelet w
If we can ensure the behavior when setting the storage network is the same as other danger zone settings, then we don't need to leverage this setting or create a new one.

2024-05-27 14:26 UTC, innobead reviewed
In general, LGTM. 

Just one last question about if `workload pod restart` behavior is  necessary or not.

2024-05-27 14:26 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, the NFS share mountpoint becomes unavailable, rendering any attempt to access it unresponsive. User can manually restart the workload pod,
I assume the annotation will only be applied once all volumes are detached, meaning there are no workloads using any active volumes. Do we still need this `workload pod restart` behavior?

2024-05-27 16:26 UTC, Vicente-Cheng reviewed
General is very clear about the current status. Thanks for it!
There is only one corner point: restart the workload pod. (with the above comment)

I checked some other solutions that might be facing the same situation.
Found an interesting article below: https://github.com/rook/rook/blob/master/design/ceph/multus-network.md#new-holder-daemonset

I am still checking what is the final solution with the multus-network on their implementation because this design says `not finalized`.

I will update again after I dig deeper into their code.

2024-05-27 16:26 UTC, Vicente-Cheng commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, the NFS share mountpoint becomes unavailable, rendering any attempt to access it unresponsive. User can manually restart the workload pod,
I know we need extra operations with workload pod if the csi-plugin (with multus) respawns.
The reason is described in the following section, `Share Manager Process Namespaces`, which is very clear.

But it still impacts the user. The workload pod restart means the application failed. Even the csi-plugin pod restart might be a corner case.

2024-05-28 00:20 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, the NFS share mountpoint becomes unavailable, rendering any attempt to access it unresponsive. User can manually restart the workload pod,
During the storage-network setting application, there will be no associated workload pod to restart because all the volumes should be detached.

A workload pod will only restart if all the following conditions are met:
1. The pod is using RWX volumes + the cluster has storage networking configured.
1. The `auto-delete-pod-when-volume-detached-unexpectedly` setting is enabled. [This setting doesn't apply to the workload pods that don't have a controller. Longhorn never deletes them.](https://github.com/longhorn/longhorn-manager/blob/aebb5a8a1c5d5b9463c0c39b7ad4ae0766795477/types/setting.go#L691)
1. The workload pod is located on the same node as the restarted CSI plugin pod.

2024-05-28 01:41 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Workload Pod Restart:** When a CSI plugin pod restarts, Longhorn will delete the associated workload pod when it is using the storage-network. If the pod is managed by a controller, the kubelet w
When configuring the storage network, it is necessary to detach the volume, ensuring that no workload pods are using it.

However, Longhorn should handle the situation when the CSI plugin pod restarts unexpectedly to resolve dangling mount issues of already RWX volume attached workload pods.

Since Longhorn cannot control how users configure the NAD (maybe providing with own CNI plugin) and the host environment, this setting provides an option for users who managed to use the host network namespace with the storage network. In this scenario, the user does not need to restart the workload pods if the CSI plugin pod restarts unexpectedly.

2024-05-28 01:42 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **CSI Annotations:** Share manager pods and CSI plugin pods will be annotated with the storage network for NFS client mounting.
This behavior remains the same as for the other dangerous zone settings.

2024-05-28 01:57 UTC, c3y1huang commented
> I checked some other solutions that might be facing the same situation. Found an interesting article below: https://github.com/rook/rook/blob/master/design/ceph/multus-network.md#new-holder-daemonset
> 
> I am still checking what is the final solution with the multus-network on their implementation because this design says `not finalized`.

The holder pod idea seems quite similar what @ejweber had in mind. However, there is a downside: we cannot guarantee that the holder pod won't be restarted, and managing this just adds extra complexity.

It looks like Rook Ceph decided to leave this responsibility to the user when using Multus.
- [Multus-enabled clusters to begin "holder" pod deprecation.](https://github.com/rook/rook/blob/53be5ce1e928674a5e1866dcb68370cdfba17d61/ROADMAP.md?plain=1#L23)
- [Multus Prerequisites](https://rook.io/docs/rook/latest/CRDs/Cluster/network-providers/#multus-prerequisites)

2024-05-28 06:17 UTC, innobead commented
Discussed with @c3y1huang. Need to update the test cases for the upgrade. The rule is that we should not interrupt users' workloads during the upgrade if the storage network has been set up before the upgrade.

2024-05-30 07:28 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Existing RWX Volumes:** Upgrading from previous version with existing volumes will be unaffected since the NFS client mount was established in the host network namespace that is not affected by t
If the existing RWX volumes restart, will it be restarted with the new storage network applied? If yes, the original consumer workloads will retry to connect with an invalid connection, correct?

What's the expected behavior here? I assumed the workloads would be somehow killed (by respecting `SettingNameAutoDeletePodWhenVolumeDetachedUnexpectedly`) to restart so that they could connect the new share manager through the storage network. However, the connection resuming of the existing client connection will not work in this special case.

2024-05-30 07:28 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Future Version Upgrades:** The Longhorn Kubernetes pod controller will trigger the deletion of workload pods, causing Kubelet to restart the workload pod. This process will remount NFS entries wh
Can you explain when `Future Version Upgrades` will happen? If the storage network is enabled before upgrade, after upgrade, the workloads should continue working w/o interruption.

2024-05-30 07:46 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Existing RWX Volumes:** Upgrading from previous version with existing volumes will be unaffected since the NFS client mount was established in the host network namespace that is not affected by t
Here is the current behavior: https://github.com/longhorn/longhorn-tests/blob/114b39b9a607ad6058687b70ccdf3d07b145eb80/docs/content/manual/release-specific/v1.7.0/test-storage-network-support-for-rwx-volume.md

2024-05-30 07:52 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Future Version Upgrades:** The Longhorn Kubernetes pod controller will trigger the deletion of workload pods, causing Kubelet to restart the workload pod. This process will remount NFS entries wh
For the upgrade after v1.7.0 (1.7.1, 1.7.2 ...), when an upgrade involves change to the CSI plugin DaemonSet, existing RWX volume workload pods that that using NFS share mounts on the storage-network will be restarted as the CSI plugin pods are restarted.

2024-05-30 07:59 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Future Version Upgrades:** The Longhorn Kubernetes pod controller will trigger the deletion of workload pods, causing Kubelet to restart the workload pod. This process will remount NFS entries wh
Clear. Thanks.

2024-05-30 08:00 UTC, innobead approved these changes

2024-05-30 08:00 UTC, merged

2024-05-30 08:31 UTC, innobead commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Existing RWX Volumes:** Upgrading from previous version with existing volumes will be unaffected since the NFS client mount was established in the host network namespace that is not affected by t
@c3y1huang needs to double check the behavior. If needed, we need to update this LEP.

2024-05-31 09:19 UTC, c3y1huang commented on enhancements/20240522-storage-network-for-rwx-volumes.md
> +- **Existing RWX Volumes:** Upgrading from previous version with existing volumes will be unaffected since the NFS client mount was established in the host network namespace that is not affected by t
https://github.com/longhorn/longhorn/pull/8679/files