feat(LEP): pre-pull share-manager, instance-manager images
longhorn/longhorn pull request #8648
Opened 2024-05-27 09:01 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#8376

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-05-28 05:34 UTC, innobead reviewed
There are a few questions below.

- If the image is deleted manually on a node, what's the status of the image? how will this be handled? I assume users need to delete the pod on the node to make it repull. Also, how can we ensure NodeDeploymentMap up to date if the downloaded image is deleted on one node and the status can be updated accordingly to NodeDeploymentMap?
- Can we delete the daemonset if all images are ready? This can save unnecessary pods running but users can still check the image readyness status.
- I feel this is almost the same as the current engine image. Can we just migrate the engine image to this new CR if this is a minor feature.

2024-05-29 20:20 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +  ImageConditionTypeReadyReasonBinary    = "binary"
How does Longhorn utilize this condition?

2024-05-29 20:20 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    Incompatible bool `json:"incompatible"`
I am not sure if the image pre-pull feature needs to understand this... 
Could you talk more about the goal and non-goal in the LEP?

2024-05-30 12:55 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +  type ImageStatus struct {
As the discussion in today's sync-up meeting, we can add all `EngineImage`'s status fields here.

2024-05-30 13:00 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +  type ImageStatus struct {
`status.refCount` might be useful for automatically deleting old share-manager and instance-manager images. That means, we need a auto-deletion mechanism as well.

2024-05-30 13:05 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +1. Fresh install or upgrade Longhorn
Will new `Image` resources for share-manager image and so on be automatically while upgrading longhorn-system?

2024-05-30 13:08 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +
Need to handle the outdated images. For example, an `Image` resource for an old share-manager image is not referenced by any share-manager pods, the resource should be automatically deleted.

2024-05-30 23:42 UTC, ejweber commented on enhancements/20240516-pre-pull-images.md
> +3. Image Daemonsets of share and instance manager are created.
TBH, this seems like a lot of overhead in the cluster for the somewhat small benefit of having the images pre-pulled and ready to go. What if we need multiple instance-manager and engine-images simultaneously? That's quite a few DaemonSets (and pods).

Would it be possible to maintain only a single DaemonSet with multiple containers? There could be one container for each image we still want deployed on the cluster. When a new Image resource is created, we could just modify the spec of the one DaemonSet, causing a rolling restart. It is fine if the DaemonSet restarts, since it won't really do anything but exist.

2024-05-31 00:26 UTC, PhanLe1010 commented on enhancements/20240516-pre-pull-images.md
> +
Agree. This will be very similar to the engine-image CR.

2024-06-03 04:22 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    Type ImageType `json:"type"`
blindly pull the image for everything worker node via a DaemonSet

2024-06-03 04:23 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +  ImageConditionTypeReadyReasonBinary    = "binary"
Add the descriptions for the condition. Thanks.

2024-06-03 04:23 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    Incompatible bool `json:"incompatible"`
Removed the field. Thanks.

2024-06-03 04:24 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +  type ImageStatus struct {
Do we still need `refCount`?

2024-06-03 04:27 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +1. Fresh install or upgrade Longhorn
Separate the test case:
For upgrade, it will create new images according to the system provides and update the corresponding DaemonSets. And delete the old image reosurces.

2024-06-03 04:30 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +
Separated the test case. Thanks
Yes, old image resources should be deleted automatically.

2024-06-03 04:32 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +3. Image Daemonsets of share and instance manager are created.
Modified the part of the image controller to update the DaemonSet when the share/instance images are changed.

2024-06-03 14:45 UTC, innobead requested changes
Can we just delete the daemsonset after all nodes already have pulled the image at the first time? 

After pulling images, the DS is still around like the current engine image. I feel we should change the behavior to make the pulling task dynamically instead of still occupying the system resources after the goal is achieved.

2024-06-03 15:13 UTC, ejweber commented
> Can we just delete the daemsonset after all nodes already have pulled the image at the first time?
>
> After pulling images, the DS is still around like the current engine image. I feel we should change the behavior to make the pulling task dynamically instead of still occupying the system resources after the goal is achieved.

This was discussed on Thursday before you were able to join. If we do as you suggest, there are two possibilities:

1. Our controller watches for the images to eventually be garbage collected by Kubernetes or the container-runtime on any cluster node (or for new nodes in the cluster that don't have the images). When it detects this condition, it recreates the DaemonSet. We can either reconcile on all `nodes.kubernetes.io` changes or reconcile `nodes.kubernetes.io` periodically to see what images are available on what nodes. The LEP as it is currently written has the following:

```
- Add `KubeNodeInformer.AddEventHandlerWithResyncPeriod` in the image controller to handle cases where share/instance manager images deleted on nodes.
```

2. Our controller doesn't do that. When our images are garbage collected or new nodes join the cluster, some nodes don't have the images we want.

I preferred maintaining the DaemonSet to offload all "thinking" to the Kubernetes DaemonSet controller (and probably not monitoring `nodes.kubernetes.io` at all). For users that didn't like the extra DaemonSet, they could just disable the setting. IIRC, that was the consensus at the end of the meeting, but I don't think opinions were strong either way.

2024-06-03 15:14 UTC, ejweber commented on enhancements/20240516-pre-pull-images.md
> +  - `NodeDeploymentMap` only synchronizes the containers status of the DaemonSet pod of the image; therefore, it can not detect if the share/instance manager images are deleted for some reason.
I don't think it is possible to delete an image if it is in use by a running container. Can you check it?

2024-06-03 15:15 UTC, ejweber commented on enhancements/20240516-pre-pull-images.md
> +   2. Image Daemonsets of share and instance manager are created.
Are we still planning on having a DaemonSet for each type of image? Wouldn't one that covers both suffice?

2024-06-04 00:40 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +   2. Image Daemonsets of share and instance manager are created.
Yes, we could have containers for images in a DaemonSet. I will test it and update the LEP. Thanks.

2024-06-04 01:31 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +  - `NodeDeploymentMap` only synchronizes the containers status of the DaemonSet pod of the image; therefore, it can not detect if the share/instance manager images are deleted for some reason.
Yes, I could delete the share-manager image manually when the pod is running.

```bash
master:~# root@rancher60-master:~# kl get no rancher60-worker1 -oyaml|grep share
    - docker.io/longhornio/longhorn-share-manager@sha256:ca0956077ab9a83e93704d3bc28ea664d2b154064e45d0145cee2bd58857ead6
    - docker.io/longhornio/longhorn-share-manager:master-head

master:~# # A couple of minutes after deleting the share-manager image.
master:~# root@rancher60-master:~# kl get no rancher60-worker1 -oyaml|grep share
master:~# kl get pod|grep mi
image-smi-5ceacedd-jl9q2                            1/1     Running   0          4m50s
image-smi-5ceacedd-5ndgs                            1/1     Running   0          4m50s
image-smi-5ceacedd-8mnb9                            1/1     Running   0          4m50s
image-imi-2ef43be6-58d7d                            1/1     Running   0          4m50s
image-imi-2ef43be6-njdcm                            1/1     Running   0          4m50s
image-imi-2ef43be6-8j98v                            1/1     Running   0          4m50s
master:~# kl get pod image-smi-5ceacedd-5ndgs -oyaml
apiVersion: v1
kind: Pod
metadata:
  ...
spec:
  ...
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - rancher60-worker1
  ...
status:
  ...
  containerStatuses:
  - containerID: containerd://bd2feadb18eae93ae22e9049a5c4bcd3c77fa1984e3c59d84443fbe6279ad84b
    image: docker.io/longhornio/longhorn-share-manager:master-head
    imageID: docker.io/longhornio/longhorn-share-manager@sha256:ca0956077ab9a83e93704d3bc28ea664d2b154064e45d0145cee2bd58857ead6
    lastState: {}
    name: image-smi-5ceacedd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-04T01:14:25Z"
  ...

worker1:~# # delete the share image on the worker node
worker1:~# k3s crictl rmi docker.io/longhornio/longhorn-share-manager:master-head
Deleted: docker.io/longhornio/longhorn-share-manager:master-head
worker1:~#
worker1:~# k3s crictl images |grep  longhorn-share-manager:master-head
```

2024-06-04 07:41 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    Type ImageType `json:"type"`
There is no need to know the image type as Longhorn is blindly pulling all required images and periodically checking them if necessary.

2024-06-04 07:41 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    NeedCreateDaemonSet bool `json:"needCreateDaemonSet"`
As we discussed, shouldn't Longhorn pull images by creating the corresponding daemonset? Is there an exception?

2024-06-04 07:41 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    Conditions []Condition `json:"conditions"`
Seems redundant.

2024-06-04 07:41 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +  - `NodeDeploymentMap` only synchronizes the containers status of the DaemonSet pod of the image; therefore, it can not detect if the share/instance manager images are deleted for some reason.
Then keeping the DaemonSet running seems meaningless. Longhorn has to periodically verify if an image exists on a node by checking the corresponding `kubernetesNode.status`

2024-06-05 07:38 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    Type ImageType `json:"type"`
Removed the `Type`. Thanks

2024-06-05 07:40 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +  - `NodeDeploymentMap` only synchronizes the containers status of the DaemonSet pod of the image; therefore, it can not detect if the share/instance manager images are deleted for some reason.
The controller will delete the DaemonSet after the image state is `deployed`.
Thanks for all the comments.

2024-06-05 07:41 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    Conditions []Condition `json:"conditions"`
Yes, removed the `Conditions`. Thanks.

2024-06-05 17:46 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    ShareManagerImage string `json:"shareManagerImage"`
Can we blindly use one field `ImageURL` instead?

2024-06-06 01:38 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    NeedCreateDaemonSet bool `json:"needCreateDaemonSet"`
Removed this field. Thanks

2024-06-06 01:45 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    ShareManagerImage string `json:"shareManagerImage"`
Could you give an example? Would it be like this?

```golang
ImageURL := "longhornio/longhorn-instance-manager:master-head,longhornio/longhorn-share-manager:master-head"
```

2024-06-06 03:22 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +   2. Image Daemonsets of share and instance manager are created.
Updated. Thanks

2024-06-06 04:17 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +    ShareManagerImage string `json:"shareManagerImage"`
I am fine with using either multiple CRs or a `ImageURLMap` with a single CR.

2024-06-06 08:10 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    ShareManagerImage string `json:"shareManagerImage"`
Choose a DaemonSet with multiple CRs. Thanks

2024-06-07 00:38 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +- Not delete the DaemonSet after images are deployed.
This statement is confusing... Is this what we plan to do but not for now?  I prefer to directly remove this line

2024-06-07 00:38 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +- Keep the DaemonSet around with the global setting `start-pre-pull-manager-images` enabled to prevent the DamonSet from toggling on and off by detecting images deleted on worker nodes.
> Keep the DaemonSet around ......

This statement is a little bit mieleading as well.

2024-06-07 01:09 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +- Not delete the DaemonSet after images are deployed.
You are right. Removed. Thanks.

2024-06-07 01:10 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +- Keep the DaemonSet around with the global setting `start-pre-pull-manager-images` enabled to prevent the DamonSet from toggling on and off by detecting images deleted on worker nodes.
Modified to describe why we should keep the DaemonSet because of the garbage collection of unused container images. Thanks.

2024-06-08 16:07 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +- A global setting `start-pre-pull-manager-images`. Users can determine whether or not pre-pulling images. Default is `true`.
Can we use `pre-pull-manager-images` for the simplicity?

2024-06-08 16:07 UTC, derekbit commented on enhancements/20240516-pre-pull-images.md
> +There is the [garbage collection of unused containers and images feature](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images) of kubernetes. The `kubelet` performs
The kubelet's garbage collection period is set to just two minutes. Does this cause the engine image deployed on each node to be repeatedly pulled and deleted?

If not, can we prevent the unnecessary garbage collection for share-manager images and pin the images?

2024-06-08 16:44 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +- A global setting `start-pre-pull-manager-images`. Users can determine whether or not pre-pulling images. Default is `true`.
How about pre-pull-images?

2024-06-09 08:58 UTC, derekbit commented
After rethinking the whole picture of the feature, the objectives of the feature include
- Reduce Startup Time: Decrease the startup time for instance-manager and share-manager pods.
- Image Management: Pin the instance-manager and share-manager images on worker nodes. If disk usage reaches `HighThresholdPercent`, kubelet's image garbage collection will remove unused images. When the pre-pull feature is enabled, the image controller will repull the image. This cleanup and repull cycle will repeat continuously. Then, the potential issues are
  - Resource Waste: Unnecessary cleanup and repulling consume computing and networking resources.
  - Failover Delays: If a share-manager pod fails over to a node where the share-manager image has just been cleaned up, the failover time may increase significantly.

Therefore, it might be better to pin the share-manager and instance-manager images for the current Longhorn version, similar to the engine image.

2024-06-12 03:49 UTC, mantissahz commented
As discussed with @derekbit, we would use a simple way to pre-pull the share-manager image.

1. Pull the share-manager image in the `initContainer` of the longhorn-manger DaemonSet.
2. Use the command `ctr -n k8s.io images label [share-manager-image-url] io.cri-containerd.pinned=pinned` or APIs(if it has) to set the attribute `pinned` of the image true.
3. Unpin the old share-manager image by the command or APIs.
4. When uninstallation, unpin all share-manager images.

Are there any concerns if we use this way to pre-pull the images?
cc @longhorn/dev

2024-06-13 15:48 UTC, ejweber commented
> As discussed with @derekbit, we would use a simple way to pre-pull the share-manager image.
> 
> 1. Pull the share-manager image in the `initContainer` of the longhorn-manger DaemonSet.
> 2. Use the command `ctr -n k8s.io images label [share-manager-image-url] io.cri-containerd.pinned=pinned longhornio=true` or APIs(if it has) to set the attribute `pinned` of the image true.
> 3. Unpin the old share-manager image with the label `longhornio=true` by the command or APIs.
> 4. When uninstallation, unpin all share-manager images with the label `longhornio=true`.
> 
> Therefore we don't need to add a new CRD and a new controller to handle it.
> 
> Are there any concerns if we follow this way to pre-pull the images? cc @longhorn/dev

In general, it sounds like pinning is exactly the behavior we want. However, I'm not 100% sure I understand how this would work in practice:

1. Do we expect to be able to run `ctr ...` commands that take effect on the host from the longhorn-manager (or its init) container? Will we need some special configuration on the container to do this? Will we need to be able to handle `containerd` sockets in arbitrary locations? (IIRC, RKE2 uses `/run/k3s/containerd/containerd.sock` and it's generally required to [pass that address](https://gist.github.com/superseb/3b78f47989e0dbc1295486c186e944bf#ctr) when using `ctr` commands.
2. Is this approach container runtime agnostic? (I'm really not sure here, but [many different runtimes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) are supported for use with Kubernetes, and it seems this approach might only work with containerd.)

2024-06-14 00:45 UTC, PhanLe1010 commented
Adding to the feedback from @ejweber , is there any downside if we just create 1 container for share-manager image and 1 container for instance-manager image inside longhorn-manager pod and let them go to eternally sleep instead of the init container ? That way we will automatically achieve pin and unpin effect without having doing anything, won't we?

2024-06-14 00:58 UTC, ejweber commented
> Adding to the feedback from @ejweber , is there any downside if we just create 1 container for share-manager image and 1 container for instance-manager image inside longhorn-manager pod and let them go to eternally sleep instead of the init container ? That way we will automatically achieve pin and unpin effect without having doing anything, won't we?

Interesting! This wouldn't have been possible with the original design (which folded in EngineImage), but with the current direction of this LEP, it might be a good solution.

Do the extra containers use resources?

Probably no. Their image layers have to be on the node anyway (that's the point of the LEP), and we can theoretically run them with a different entry point (e.g. `sleep infinity`) so we don't have to load the processes we would otherwise run into memory.

2024-06-14 02:01 UTC, james-munson commented
The snags with container and pod lifetime are in this blog post describing the "native sidecar" feature:  https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/#how-did-users-get-sidecar-behavior-before-1-28

2024-06-18 02:51 UTC, mantissahz commented
Track on this PR https://github.com/longhorn/longhorn/pull/8775.

2024-06-18 02:51 UTC, closed without merging