feat(lep): pre-pull share-manager/instance-manager images
longhorn/longhorn pull request #8775
Opened 2024-06-18 02:48 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#8376

2024-06-19 13:23 UTC, innobead requested changes

2024-06-19 13:23 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
This example is not really sidecar but a traditional init container instead, which will start and stop before the application container(s) starts. That means they could be garbage collected as usual. 

Please check https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#pod-sidecar-containers to use `restartPolicy: Always` to ensure they run as sidecar.

2024-06-20 02:55 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
This field `restartPolicy` in `initContainers` is only implemented from v1.28 (native sidecar container alpha).
Moved the initial containers to containers and use the `sleep infinity` command.

2024-06-20 05:05 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +      command: ["sh", "-c", "echo longhorn-instance-manager image pulled && sleep infinity"]
Don't we need `ImagePullPolicy: IfNotPresent`? BTW, why do we need longhorn instance manager? I thought IM pods should be immediately run when Longhorn starts running.

2024-06-20 05:09 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
I am curious if this only takes effect in newer versions, but can still be applied in older Kubernetes versions without taking effect. This question is about the backward compatibility of Kubernetes.

2024-06-20 05:25 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +      command: ["sh", "-c", "echo longhorn-instance-manager image pulled && sleep infinity"]
Added for clarity. If it is omitted, the default of ImagePullPolicy will be IfNotPresent.
And Removed the pre-pulling instance-manager container.

2024-06-20 05:27 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
>but can still be applied in older Kubernetes versions without taking effect.

No, it can not be applied in the older Kubernetes versions (I tested it in the v1.26.3+k3s1). There is no `restartPolicy` field in the `initContainer`.

2024-06-20 05:34 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
Then Kubernetes resource API is not backward compatible.

2024-06-20 05:34 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +- Pre-pull the instance-manager image on all worker nodes.
Remove this as we don't need.

2024-06-20 05:37 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +- Pre-pull the instance-manager image on all worker nodes.
Removed the instance manager part. Thanks

2024-06-20 07:18 UTC, derekbit commented
cc @james-munson  for review

2024-06-20 09:56 UTC, mantissahz commented
The resource usage of the pre-pull image container `pre-pull-share-manager-image`:
```txt
root@rancher60-worker1:~# crictl stats
CONTAINER           NAME                           CPU %               MEM                 DISK                INODES
...
4493f3cdca904       longhorn-manager               0.25                48.65MB             77.82kB             18
4ba3c011b587e       csi-provisioner                0.07                12.3MB              36.86kB             11
5d6a790970abe       instance-manager               0.04                14.57MB             69.63kB             20
6a4a1c8533f36       longhorn-csi-plugin            0.00                15.89MB             77.82kB             19
73268e5ee9882       pre-pull-share-manager-image   0.00                1.61MB              36.86kB             9
...
```

It remains at 1.6MB for memory usage.
And it will not start the nfs-ganesha server.

2024-06-20 15:44 UTC, ejweber commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
Can we create an issue to move to the native sidecar pattern when we raise the minimum Kubernetes version to at least `v1.29` (when it is enabled by default), or potentially whatever version it goes GA in? It looks like this approach will work in the interim, but the native approach will likely be more "correct".

2024-06-20 15:51 UTC, ejweber approved these changes
I tried running a longhorn-manager like the latest PR describes looking for the issues described in https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/#how-did-users-get-sidecar-behavior-before-1-28. We don't really care about startup order, but it will be bad if the pre-pull container somehow blocks deletion. Neither of the following seemed to be problematic:

- `kubectl delete longhorn-manager...` - Maybe it took longer than usual? However, the longhorn-manager pod was eventually deleted and recreated.
- `ssh <node> kill -9 <longhorn-manager PID>` - Looks like the readiness probe failed and the longhorn-manager container restarted. No effect from the pre-pull container.

I'll be curious to hear from @james-munson if he thinks there are other scenarios we should worry about, but LGTM.

2024-06-20 16:11 UTC, innobead approved these changes

2024-06-21 22:46 UTC, shuo-wu commented on enhancements/20240516-pre-pull-images.md
> +- Add containers in the `longhorn-manager` DaemonSet:
Which one is responsible for adding this container? And how?

2024-06-22 15:02 UTC, innobead commented on enhancements/20240516-pre-pull-images.md
> +- Add containers in the `longhorn-manager` DaemonSet:
Is it pre-defined in the longhorn manger daemonset manifest?

2024-06-24 00:59 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +    initContainers:
Sure, here is the improvement ticket https://github.com/longhorn/longhorn/issues/8811

2024-06-24 01:00 UTC, mantissahz commented on enhancements/20240516-pre-pull-images.md
> +- Add containers in the `longhorn-manager` DaemonSet:
Yes, it is pre-defined in the manifest as this PR https://github.com/longhorn/longhorn/pull/8778

2024-06-24 02:36 UTC, merged

2024-06-25 17:02 UTC, derekbit commented
> I tried running a longhorn-manager like the latest PR describes looking for the issues described in https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/#how-did-users-get-sidecar-behavior-before-1-28. We don't really care about startup order, but it will be bad if the pre-pull container somehow blocks deletion. Neither of the following seemed to be problematic:
> 
> * `kubectl delete longhorn-manager...` - Maybe it took longer than usual? However, the longhorn-manager pod was eventually deleted and recreated.

@mantissahz Have you measured how long will a longhorn-manager pod be deleted? Will 

> * `ssh <node> kill -9 <longhorn-manager PID>` - Looks like the readiness probe failed and the longhorn-manager container restarted. No effect from the pre-pull container.
> 
> I'll be curious to hear from @james-munson if he thinks there are other scenarios we should worry about, but LGTM.