Use special labels for node selection by admission and conversion web…
longhorn/longhorn pull request #8804
Opened 2024-06-21 21:17 UTC by james-munson

…hooks.

#### Which issue(s) this PR fixes:

Issue #8803 

#### What this PR does / why we need it:

This customizes the node selector used by the two webhooks to allow individual control of which nodes might be assigned the service.  See #6205, for instance.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-06-24 21:29 UTC, ejweber requested changes
I am thinking we need to add these labels dynamically during longhorn-manager startup if we want to achieve the behavior described in https://github.com/longhorn/longhorn/issues/8803#issuecomment-2187398322.

2024-06-27 00:52 UTC, derekbit approved these changes
LGTM for the newly added labels, but we need more inputs for the design https://github.com/longhorn/longhorn/issues/8803#issuecomment-2192856444.

2024-07-19 21:26 UTC, ejweber requested changes
Can we rename the PR, since it also includes the RWX fast failover setting.

LGTM in principle. IIUC though, it needs changes to the recovery backend service too now.

2024-07-22 00:36 UTC, derekbit commented on chart/README.md
> +| defaultSettings.enableShareManagerFastFailover | Turn on logic to detect and move RWX volumes quickly on node failure. |
How about renaming it to `RWXVolumeFastFailover`?

```suggestion
| defaultSettings.enableShareManagerFastFailover | Turn on logic to detect and move RWX volumes quickly on node failure. |
```

2024-07-22 00:39 UTC, derekbit commented
longhorn-okd.yaml is not regerneated. Could you execute `scripts/generate-longhorn-yaml.sh`?

2024-07-22 17:46 UTC, ejweber commented on chart/questions.yaml
> +  default: false
I still think `false` per the discussion in https://github.com/longhorn/longhorn-manager/pull/2811#discussion_r1680585760.

2024-07-22 18:01 UTC, james-munson commented on chart/questions.yaml
> +  default: false
Agreed.  This experimental feature is not well enough tested for stability to turn it on by default.

2024-07-22 18:49 UTC, ejweber reviewed
LGTM except for two issues raised by @derekbit.

- Variable name.
- .yaml regeneration.

2024-07-22 21:10 UTC, james-munson commented on chart/README.md
> +| defaultSettings.enableShareManagerFastFailover | Turn on logic to detect and move RWX volumes quickly on node failure. |
Done, thank you.

2024-07-22 21:38 UTC, ejweber approved these changes
LGTM. Thanks!

2024-07-23 00:28 UTC, derekbit approved these changes
LGTM

2024-07-23 03:10 UTC, merged

2024-07-23 04:24 UTC, derekbit commented
@mergify backport v1.7.x