fix(spdk): enable uio_pci_generic and vfio_pci kernel modules
longhorn/longhorn pull request #9193
Opened 2024-08-06 04:39 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9182

#### What this PR does / why we need it:

According to the [SPDK System Configuration User Guide](https://spdk.io/doc/system_configuration.html), neither uio_pci_generic nor vfio_pci is universally suitable for all devices and environments. Therefore, the preflight installation enables both uio_pci_generic and vfio_pci kernel modules, allowing spdk/setup.sh to automatically select the appropriate module.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-06 06:45 UTC, derekbit commented
@mergify backport v1.7.x

2024-08-06 13:00 UTC, innobead requested changes
LGTM except for one comment.

2024-08-06 13:06 UTC, derekbit commented on deploy/prerequisite/longhorn-spdk-setup.yaml
> +
Fixed. Thank you.

2024-08-07 07:23 UTC, innobead approved these changes

2024-08-07 07:23 UTC, merged