feat(ci): automatically scan and notify testing items every Sunday
longhorn/longhorn pull request #9249
Opened 2024-08-18 04:44 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9237

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-18 15:23 UTC, innobead requested changes
In general, LGTM. Just one feedback.

2024-08-18 15:23 UTC, innobead commented on .github/workflows/scan_and_notify_testing_items.py
> +    issues = list_issues_in_project(github_token,
Can we filter the issues belonging to the current sprint only? For other non-current sprints, QA should track them on another tab of the project or use a different workflow if need an automatic notification.

This workflow is for letting the team know how many issues are ready for testing by the end of the current sprint.

2024-08-18 15:26 UTC, innobead commented on .github/workflows/scan_and_notify_testing_items.yml
> +    - cron: '0 12 * * 0'
Ideally, we should trigger this every two weeks before the end of the sprint. However, since the cron syntax may not support that frequency, a weekly trigger works for me

2024-08-18 15:30 UTC, derekbit commented on .github/workflows/scan_and_notify_testing_items.py
> +    issues = list_issues_in_project(github_token,
> Can we filter the issues belonging to the current sprint only? For other non-current sprints, QA should track them on another tab of the project or use a different workflow if need an automatic notification.
> 
> This workflow is for letting the team know how many issues are ready for testing by the end of the current sprint.

Can we show two lists at the same time? One is for current sprint and the other one is for non-current sprints.

```
List of current sprints:
1.
2.
3.
...

List of non-current sprints:
1.
2.
3.
...
```

2024-08-18 15:34 UTC, derekbit commented on .github/workflows/scan_and_notify_testing_items.yml
> +    - cron: '0 12 * * 0'
Just figured out a better method. We can run the workflow every Sunday and compare the date with the Project's current print. Then, scan and notify only when it is the end of the sprint. I will improve the PR.

2024-08-18 16:05 UTC, innobead commented on .github/workflows/scan_and_notify_testing_items.py
> +    issues = list_issues_in_project(github_token,
What's the reason for showing non current sprint issues?

BTW, can we add the issue owners next to each issue? I think this is helpful for members quickly know their status.

2024-08-18 16:12 UTC, derekbit commented on .github/workflows/scan_and_notify_testing_items.py
> +    issues = list_issues_in_project(github_token,
> What's the reason for showing non current sprint issues?

To avoid missing the non-current sprint issues that should be tested before.

> BTW, can we add the issue owners next to each issue? I think this is helpful for members quickly know their status.

Sure.

2024-08-18 16:31 UTC, innobead commented on .github/workflows/scan_and_notify_testing_items.py
> +    issues = list_issues_in_project(github_token,
Yeah. That was why I said we can have a separate workflow for this purpose. But, let's make it simple  to have both in this workflow fine for me!

2024-08-23 06:03 UTC, derekbit commented
The colleague of IT team for slack app is on vacation. Waiting for his approval for incoming webook.
https://suse.slack.com/archives/C02CWABQMEX/p1723887838447749

2024-08-29 11:08 UTC, derekbit commented
Ready for review.

2024-08-30 08:18 UTC, yangchiu approved these changes
LGTM

2024-08-31 01:51 UTC, merged