feat(v2 volume/configurable cpu mask): updata crds.yaml and longhorn.yaml
longhorn/longhorn pull request #9321
Opened 2024-08-27 06:15 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#8835

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-31 16:30 UTC, innobead requested changes
Don't we need to add the new setting `v2-data-engine-cpu-mask` to the chart?

2024-09-01 14:39 UTC, derekbit commented
> Don't we need to add the new setting v2-data-engine-cpu-mask to the chart?

Yes, I forgot it. Added, thank you.

2024-09-01 15:27 UTC, innobead commented
> > Don't we need to add the new setting v2-data-engine-cpu-mask to the chart?
> 
> Yes, I forgot it. Added, thank you.

Let's remember to go through the items in https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update, as we need to update the Chart readme and questions.yaml. It's a bit lengthy, but we can potentially streamline it using automation later.. 

@longhorn/doc needs to review the description of the new setting as usual.

2024-09-02 05:14 UTC, jillian-maroket reviewed
I split up the first sentence in the description to make it easier to read.

2024-09-02 05:14 UTC, jillian-maroket commented on chart/values.yaml
> +  # --The setting is used to specify which CPU cores the Storage Performance Development Kit (SPDK) target daemon within each instance manager pod should run on. The default value is "0x1".
```suggestion
  # --CPU cores on which the Storage Performance Development Kit (SPDK) target daemon should run. The SPDK target daemon is located in each Instance Manager pod. The default value is "0x1".
```

2024-09-02 09:20 UTC, derekbit commented on chart/values.yaml
> +  # --The setting is used to specify which CPU cores the Storage Performance Development Kit (SPDK) target daemon within each instance manager pod should run on. The default value is "0x1".
@jillian-maroket Can you review it again? Thank you.

2024-09-02 09:34 UTC, jillian-maroket reviewed
I made a few changes to the new sentence.

2024-09-02 09:34 UTC, jillian-maroket commented on chart/values.yaml
> +  # -- CPU cores on which the Storage Performance Development Kit (SPDK) target daemon should run. The SPDK target daemon is located in each Instance Manager pod. The default value is "0x1". The numb
```suggestion
  # -- CPU cores on which the Storage Performance Development Kit (SPDK) target daemon should run. The SPDK target daemon is located in each Instance Manager pod. Ensure that the number of cores is less than or equal to the guaranteed Instance Manager CPUs for the V2 Data Engine. The default value is "0x1".
```

2024-09-02 13:51 UTC, innobead commented
@derekbit it seems you haven't updated the questions.yaml and chart readme yet?

> Let's remember to go through the items in [Wiki: Longhorn Setting Update](https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update), as we need to update the Chart readme and questions.yaml. It's a bit lengthy, but we can potentially streamline it using automation later..

2024-09-02 13:58 UTC, derekbit commented
> @derekbit it seems you haven't updated the questions.yaml and chart readme yet?
> 
> > Let's remember to go through the items in [Wiki: Longhorn Setting Update](https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update), as we need to update the Chart readme and questions.yaml. It's a bit lengthy, but we can potentially streamline it using automation later..

Oh, yes, forgot it. I probably need a workflow to check it.

2024-09-03 06:49 UTC, derekbit commented
cc @jillian-maroket ready for review. Thank you.

2024-09-03 15:10 UTC, jillian-maroket reviewed
Let me know if you have concerns about the changes.

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: 'Data source type of a backing image used in a Longhorn StorageClass. If the backing image exists in the cluster, Longhorn uses this setting to verify the image. If the backing image
```suggestion
    description: 'Data source type of a backing image used in a Longhorn StorageClass. If the backing image exists in the cluster, Longhorn uses this setting to verify the image. If the backing image does not exist, Longhorn creates one using the specified data source type. **Caution** [1] This field is useful only if the backing image name is specified. [2] Backing images with data source type \"upload\" are best created using the Longhorn UI. Uploading requires sending file data to Longhorn after object creation, which can be complicated when performed manually.'
```

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: "Data source parameters of a backing image used in a Longhorn StorageClass. You can specify a JSON string of a map. (Example: `'{\"url\":\"https://backing-image-example.s3-region.ama
```suggestion
    description: "Data source parameters of a backing image used in a Longhorn StorageClass. You can specify a JSON string of a map. (Example: `'{\"url\":\"https://backing-image-example.s3-region.amazonaws.com/test-backing-image\"}'`) **Caution** [1] This field is useful only if the backing image name is specified. [2] Ensure that quotes are used correctly when specifying parameters."
```

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +  description: "Setting that allows you to enable network policies that control access to Longhorn pods. Warning: The Rancher Proxy will not work if this feature is enabled and a custom NetworkPolicy
```suggestion
  description: "Setting that allows you to enable network policies that control access to Longhorn pods. **Caution** The Rancher Proxy will work only if this feature is enabled and a custom NetworkPolicy is added."
```

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: 'Number of millicpus on each node to be reserved for each Instance Manager pod when the V2 Data Engine is enabled. The default value is "1250". WARNING: - Specifying a value of 0 dis
```suggestion
    description: 'Number of millicpu on each node to be reserved for each Instance Manager pod when the V2 Data Engine is enabled. The default value is \"1250\". **Caution** [1] Specifying a value of \"0\" disables CPU requests for Instance Manager pods. You must specify an integer between \"1000\" and \"8000\". [2] This is a global setting. Modifying the value triggers an automatic restart of the Instance Manager pods. Do not modify the value while volumes are still attached.'
```

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: 'CPU cores on which the Storage Performance Development Kit (SPDK) target daemon should run. The SPDK target daemon is located in each Instance Manager pod. Ensure that the number of
```suggestion
    description: 'CPU cores on which the Storage Performance Development Kit (SPDK) target daemon should run. The SPDK target daemon is located in each Instance Manager pod. Ensure that the number of cores is less than or equal to the guaranteed Instance Manager CPUs for the V2 Data Engine. The default value is \"0x1\".'
```

2024-09-03 15:10 UTC, jillian-maroket commented on chart/questions.yaml
> +    description: 'Number of millicpus on each node to be reserved for each Instance Manager pod when the V2 Data Engine is enabled. The default value is "1250". WARNING: - Specifying a value of 0 dis
> group: "Longhorn Default Settings'

This should not be part of the description.

2024-09-04 01:57 UTC, jillian-maroket approved these changes
LGTM. Thanks!

2024-09-04 02:18 UTC, merged