lep: V2 Volume Live Migration
longhorn/longhorn pull request #9925
Opened 2024-12-07 07:15 UTC by PhanLe1010

longhorn/longhorn#6361

2024-12-11 22:35 UTC, james-munson requested changes
Some small spelling items and a couple of questions.

2024-12-11 22:35 UTC, james-munson commented on enhancements/20241206-v2-volume-live-migration.md
> +   The volume become sorely attached to node-2.
"sorely" -> "solely"

2024-12-11 22:35 UTC, james-munson commented on enhancements/20241206-v2-volume-live-migration.md
> +   The volume become sorely attached to node-1.
ditto.

2024-12-11 22:35 UTC, james-munson commented on enhancements/20241206-v2-volume-live-migration.md
> +// TODO: describe the state transition by sudo code
"sudo" should be "pseudo".  Is there a plan to fill in this part?

2024-12-11 22:35 UTC, james-munson commented on enhancements/20241206-v2-volume-live-migration.md
> +    1. Delete r1' and r2'
I gather that only zero or one engine can be active at a time, so an attempt to activate e2 before e1 is deleted will be rejected?  That's how we protect against simultaneous writes from both?

2024-12-12 23:29 UTC, james-munson reviewed
Taking off the "request changes" tag in case I don't get a chance to later.

2024-12-14 00:50 UTC, PhanLe1010 commented on enhancements/20241206-v2-volume-live-migration.md
> +   The volume become sorely attached to node-2.
Thank you. Fixed

2024-12-14 00:51 UTC, PhanLe1010 commented on enhancements/20241206-v2-volume-live-migration.md
> +   The volume become sorely attached to node-1.
Thank you. Fixed

2024-12-14 00:52 UTC, PhanLe1010 commented on enhancements/20241206-v2-volume-live-migration.md
> +    1. Delete r1' and r2'
No, we don't stop user from writing to 2 engine at the same time. It is the responsibility of user to coordinate the write

But you are correct that there at most on active engine at a time

2024-12-14 09:38 UTC, innobead commented on enhancements/20241206-v2-volume-live-migration.md
> +    1. Delete r1' and r2'
Have we explained users should manage exclusive IO operation during the migration in the current doc? If no, it might be helpful to improve the doc to  prevent users from having any wrong expectation.

2024-12-14 09:45 UTC, innobead approved these changes
LGTM.

2024-12-14 09:46 UTC, merged

2024-12-21 00:33 UTC, PhanLe1010 commented on enhancements/20241206-v2-volume-live-migration.md
> +    1. Delete r1' and r2'
Hi @innobead 
I think only Harvester uses this live migration feature and they are aware of this. 
I just looked up and see that we don't mention this live migration feature at all in our document. 
Maybe we don't need to document it?

2024-12-22 14:30 UTC, innobead commented on enhancements/20241206-v2-volume-live-migration.md
> +    1. Delete r1' and r2'
Okay, that's fine.